return {
  version = "1.2",
  luaversion = "5.1",
  tiledversion = "1.2.0",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 40,
  height = 40,
  tilewidth = 64,
  tileheight = 64,
  nextlayerid = 25,
  nextobjectid = 2531,
  properties = {},
  tilesets = {
    {
      name = "ground",
      firstgid = 1,
      filename = "../../../../../../../../../../Desctop/Новая папка/ground.tsx",
      tilewidth = 64,
      tileheight = 64,
      spacing = 0,
      margin = 0,
      columns = 8,
      image = "../../../../../../../../../../Desctop/Новая папка/tiles.png",
      imagewidth = 512,
      imageheight = 128,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 64,
        height = 64
      },
      properties = {},
      terrains = {},
      tilecount = 16,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      id = 23,
      name = "BG_TILES",
      x = 0,
      y = 0,
      width = 40,
      height = 40,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 6, 6, 4, 4, 4, 4, 4, 4, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 6, 6, 4, 4, 4, 4, 4, 4, 4, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 6, 6, 4, 4, 4, 4, 4, 4, 4, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 0, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0,
        0, 0, 0, 0, 0, 0, 4, 4, 4, 4, 4, 4, 4, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4,
        0, 0, 0, 0, 0, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4,
        0, 0, 0, 0, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4,
        0, 0, 0, 0, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 0,
        0, 0, 4, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 0,
        0, 0, 4, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 4, 4, 4, 4, 4, 4, 2, 0,
        0, 4, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 0,
        0, 4, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4,
        0, 4, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 2, 4, 6, 6, 6, 4, 2, 4, 4, 4, 4, 4, 4, 4, 6, 6, 4, 4, 2, 4,
        0, 0, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 2, 4, 6, 6, 6, 4, 2, 4, 4, 4, 4, 4, 4, 4, 6, 6, 4, 4, 2, 4,
        0, 4, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 2, 4, 6, 6, 6, 4, 2, 4, 4, 4, 4, 4, 4, 4, 6, 6, 4, 4, 2, 4,
        0, 4, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4,
        0, 4, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4,
        4, 4, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 2, 0,
        4, 4, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4, 4, 6, 6, 6, 4, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 2, 0,
        0, 4, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4, 4, 6, 6, 6, 4, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 2, 0,
        4, 4, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4, 4, 6, 6, 6, 4, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 2, 4,
        0, 4, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 2, 4,
        4, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4,
        4, 4, 2, 6, 6, 6, 6, 6, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4,
        0, 4, 2, 6, 6, 6, 6, 6, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4, 4, 6, 6, 6, 4, 2, 0,
        0, 4, 2, 6, 6, 6, 6, 6, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4, 4, 6, 6, 6, 4, 2, 0,
        0, 4, 2, 6, 6, 6, 6, 6, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4, 4, 6, 6, 6, 4, 2, 0,
        0, 4, 2, 6, 6, 6, 6, 6, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4,
        0, 4, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 0, 0, 4, 4, 4, 4, 4, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4,
        0, 4, 2, 4, 4, 4, 4, 4, 2, 6, 6, 6, 6, 6, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
        0, 4, 2, 4, 4, 4, 4, 4, 2, 6, 6, 6, 6, 6, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
        4, 4, 2, 4, 4, 4, 4, 4, 2, 6, 6, 6, 6, 6, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0,
        4, 4, 2, 4, 4, 4, 4, 4, 2, 6, 6, 6, 6, 6, 2, 4, 4, 4, 0, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 4, 0, 4, 4, 4, 0, 4, 0, 4, 4, 0,
        4, 4, 2, 4, 4, 4, 4, 4, 2, 6, 6, 6, 6, 6, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 0,
        4, 4, 2, 4, 4, 4, 4, 4, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 0,
        0, 4, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 0, 0, 0, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 0, 0,
        0, 0, 2, 4, 0, 0, 0, 0, 0, 4, 4, 4, 0, 4, 4, 4, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 4, 0, 0, 0, 0, 0, 0,
        0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 4, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "objectgroup",
      id = 17,
      name = "FG_OBJECTS",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 492,
          name = "",
          type = "city_lamp",
          shape = "rectangle",
          x = 1728,
          y = 832,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 493,
          name = "",
          type = "city_lamp",
          shape = "rectangle",
          x = 1664,
          y = 832,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 519,
          name = "",
          type = "city_lamp",
          shape = "rectangle",
          x = 1664,
          y = 1152,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 520,
          name = "",
          type = "city_lamp",
          shape = "rectangle",
          x = 1728,
          y = 1152,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 522,
          name = "",
          type = "city_lamp",
          shape = "rectangle",
          x = 1728,
          y = 1216,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 524,
          name = "",
          type = "city_lamp",
          shape = "rectangle",
          x = 1280,
          y = 1152,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 525,
          name = "",
          type = "city_lamp",
          shape = "rectangle",
          x = 1344,
          y = 1152,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 588,
          name = "",
          type = "city_lamp",
          shape = "rectangle",
          x = 128,
          y = 1920,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 838,
          name = "",
          type = "city_lamp",
          shape = "rectangle",
          x = 2432,
          y = 1152,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 839,
          name = "",
          type = "city_lamp",
          shape = "rectangle",
          x = 2432,
          y = 1216,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 840,
          name = "",
          type = "city_lamp",
          shape = "rectangle",
          x = 1728,
          y = 384,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 841,
          name = "",
          type = "city_lamp",
          shape = "rectangle",
          x = 1664,
          y = 384,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 842,
          name = "",
          type = "city_lamp",
          shape = "rectangle",
          x = 2432,
          y = 384,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 843,
          name = "",
          type = "city_lamp",
          shape = "rectangle",
          x = 2432,
          y = 448,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 846,
          name = "",
          type = "city_lamp",
          shape = "rectangle",
          x = 1728,
          y = 1920,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 847,
          name = "",
          type = "city_lamp",
          shape = "rectangle",
          x = 1728,
          y = 1984,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 848,
          name = "",
          type = "city_lamp",
          shape = "rectangle",
          x = 2496,
          y = 1920,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 849,
          name = "",
          type = "city_lamp",
          shape = "rectangle",
          x = 2432,
          y = 1920,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 850,
          name = "",
          type = "city_lamp",
          shape = "rectangle",
          x = 1344,
          y = 1536,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 851,
          name = "",
          type = "city_lamp",
          shape = "rectangle",
          x = 1280,
          y = 1536,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 852,
          name = "",
          type = "city_lamp",
          shape = "rectangle",
          x = 896,
          y = 2304,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 853,
          name = "",
          type = "city_lamp",
          shape = "rectangle",
          x = 896,
          y = 2368,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 854,
          name = "",
          type = "city_lamp",
          shape = "rectangle",
          x = 512,
          y = 1536,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 855,
          name = "",
          type = "city_lamp",
          shape = "rectangle",
          x = 512,
          y = 1600,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 857,
          name = "",
          type = "city_lamp",
          shape = "rectangle",
          x = 512,
          y = 832,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 858,
          name = "",
          type = "city_lamp",
          shape = "rectangle",
          x = 576,
          y = 832,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 859,
          name = "",
          type = "city_lamp",
          shape = "rectangle",
          x = 512,
          y = 2304,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 860,
          name = "",
          type = "city_lamp",
          shape = "rectangle",
          x = 576,
          y = 2304,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 862,
          name = "",
          type = "city_lamp",
          shape = "rectangle",
          x = 192,
          y = 1920,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 863,
          name = "",
          type = "city_lamp",
          shape = "rectangle",
          x = 192,
          y = 1216,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 864,
          name = "",
          type = "city_lamp",
          shape = "rectangle",
          x = 128,
          y = 1216,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 865,
          name = "",
          type = "city_lamp",
          shape = "rectangle",
          x = 960,
          y = 384,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 866,
          name = "",
          type = "city_lamp",
          shape = "rectangle",
          x = 960,
          y = 448,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 867,
          name = "",
          type = "city_lamp",
          shape = "rectangle",
          x = 1344,
          y = 768,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 868,
          name = "",
          type = "city_lamp",
          shape = "rectangle",
          x = 1344,
          y = 832,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 958,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 1400,
          y = 904,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 959,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 1608,
          y = 889,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 960,
          name = "",
          type = "lawnornament_4",
          shape = "rectangle",
          x = 1505,
          y = 992,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 961,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 1592,
          y = 888,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 962,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 1400,
          y = 1064,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 963,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 1400,
          y = 889,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 964,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 1400,
          y = 1048,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 965,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 1400,
          y = 1080,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 966,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 1400,
          y = 936,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 967,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 1449,
          y = 889,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 968,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 1576,
          y = 889,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 969,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 1431,
          y = 1097,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 970,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 1432,
          y = 890,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 971,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 1559,
          y = 888,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 972,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 1417,
          y = 889,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 973,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 1400,
          y = 920,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 974,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 1591,
          y = 1095,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 975,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 1416,
          y = 1096,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 976,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 1607,
          y = 1096,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 977,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 1448,
          y = 1096,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 978,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 1558,
          y = 1095,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 979,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 1399,
          y = 1096,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 980,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 1608,
          y = 936,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 981,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 1608,
          y = 920,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 982,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 1608,
          y = 1080,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 983,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 1608,
          y = 904,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 984,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 1575,
          y = 1096,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 985,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 1608,
          y = 1048,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 986,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 1608,
          y = 1064,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 987,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 1016,
          y = 1288,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 988,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 1224,
          y = 1273,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 989,
          name = "",
          type = "lawnornament_4",
          shape = "rectangle",
          x = 1121,
          y = 1376,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 990,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 1208,
          y = 1272,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 991,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 1016,
          y = 1448,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 992,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 1016,
          y = 1273,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 993,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 1016,
          y = 1432,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 994,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 1016,
          y = 1464,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 995,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 1016,
          y = 1320,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 996,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 1065,
          y = 1273,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 997,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 1192,
          y = 1273,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 998,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 1047,
          y = 1481,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 999,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 1048,
          y = 1274,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1000,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 1175,
          y = 1272,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1001,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 1033,
          y = 1273,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1002,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 1016,
          y = 1304,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1003,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 1207,
          y = 1479,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1004,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 1032,
          y = 1480,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1005,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 1223,
          y = 1480,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1006,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 1064,
          y = 1480,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1007,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 1174,
          y = 1479,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1008,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 1015,
          y = 1480,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1009,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 1224,
          y = 1320,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1010,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 1224,
          y = 1304,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1011,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 1224,
          y = 1464,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1012,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 1224,
          y = 1288,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1013,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 1191,
          y = 1480,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1014,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 1224,
          y = 1432,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1015,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 1224,
          y = 1448,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1016,
          name = "",
          type = "city_lamp",
          shape = "rectangle",
          x = 960,
          y = 1152,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1017,
          name = "",
          type = "city_lamp",
          shape = "rectangle",
          x = 896,
          y = 1152,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1059,
          name = "",
          type = "pighouse_city2",
          shape = "rectangle",
          x = 1796,
          y = 1760,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1064,
          name = "",
          type = "pighouse_city2",
          shape = "rectangle",
          x = 1796,
          y = 1668,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1070,
          name = "",
          type = "pighouse_city2",
          shape = "rectangle",
          x = 1596,
          y = 1852,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1074,
          name = "",
          type = "pighouse_city2",
          shape = "rectangle",
          x = 1412,
          y = 1468,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1079,
          name = "",
          type = "pighouse_city2",
          shape = "rectangle",
          x = 1504,
          y = 1284,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1080,
          name = "",
          type = "pighouse_city2",
          shape = "rectangle",
          x = 1412,
          y = 1284,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 198,
          name = "",
          type = "pighouse_city2",
          shape = "rectangle",
          x = 1796,
          y = 1468,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 200,
          name = "",
          type = "pighouse_city2",
          shape = "rectangle",
          x = 1796,
          y = 1376,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 206,
          name = "",
          type = "pighouse_city2",
          shape = "rectangle",
          x = 1888,
          y = 1284,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1081,
          name = "",
          type = "pighouse_city2",
          shape = "rectangle",
          x = 1596,
          y = 1284,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1181,
          name = "",
          type = "pighouse_city2",
          shape = "rectangle",
          x = 2364,
          y = 608,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1183,
          name = "",
          type = "pighouse_city2",
          shape = "rectangle",
          x = 2272,
          y = 516,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1279,
          name = "",
          type = "pighouse_city2",
          shape = "rectangle",
          x = 1120,
          y = 516,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1281,
          name = "",
          type = "pig_shop_arcane_entrance",
          shape = "rectangle",
          x = 1212,
          y = 516,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1298,
          name = "",
          type = "pighouse_city2",
          shape = "rectangle",
          x = 644,
          y = 700,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1304,
          name = "",
          type = "pig_shop_weapons_entrance",
          shape = "rectangle",
          x = 644,
          y = 516,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1311,
          name = "",
          type = "pighouse_city2",
          shape = "rectangle",
          x = 736,
          y = 1668,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1312,
          name = "",
          type = "pighouse_city2",
          shape = "rectangle",
          x = 644,
          y = 1668,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1323,
          name = "",
          type = "pighouse_city2",
          shape = "rectangle",
          x = 260,
          y = 2144,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1325,
          name = "",
          type = "pighouse_city2",
          shape = "rectangle",
          x = 444,
          y = 2144,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1347,
          name = "",
          type = "pighouse_city2",
          shape = "rectangle",
          x = 260,
          y = 1376,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1348,
          name = "",
          type = "pighouse_city2",
          shape = "rectangle",
          x = 352,
          y = 1468,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1391,
          name = "",
          type = "pighouse_city2",
          shape = "rectangle",
          x = 2272,
          y = 2052,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1392,
          name = "",
          type = "pighouse_city2",
          shape = "rectangle",
          x = 2180,
          y = 2052,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1393,
          name = "",
          type = "pighouse_city2",
          shape = "rectangle",
          x = 2364,
          y = 2052,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1394,
          name = "",
          type = "pighouse_city2",
          shape = "rectangle",
          x = 1796,
          y = 2236,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1395,
          name = "",
          type = "pighouse_city2",
          shape = "rectangle",
          x = 1796,
          y = 2144,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1399,
          name = "",
          type = "pighouse_city2",
          shape = "rectangle",
          x = 1888,
          y = 2052,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1400,
          name = "",
          type = "pighouse_city2",
          shape = "rectangle",
          x = 1796,
          y = 2052,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1401,
          name = "",
          type = "pighouse_city2",
          shape = "rectangle",
          x = 1980,
          y = 2052,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1427,
          name = "",
          type = "pighouse_city2",
          shape = "rectangle",
          x = 1028,
          y = 2144,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1432,
          name = "",
          type = "pig_antiquities_entrance",
          shape = "rectangle",
          x = 1028,
          y = 2052,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1449,
          name = "",
          type = "pighouse_city2",
          shape = "rectangle",
          x = 1596,
          y = 516,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1453,
          name = "",
          type = "pighouse_city2",
          shape = "rectangle",
          x = 1120,
          y = 1668,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1480,
          name = "",
          type = "pighouse_city2",
          shape = "rectangle",
          x = 1412,
          y = 316,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1499,
          name = "",
          type = "pighouse_city2",
          shape = "rectangle",
          x = 444,
          y = 608,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1503,
          name = "",
          type = "pighouse_city2",
          shape = "rectangle",
          x = 444,
          y = 900,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1504,
          name = "",
          type = "pighouse_city2",
          shape = "rectangle",
          x = 252,
          y = 900,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1507,
          name = "",
          type = "pig_shop_tinker_entrance",
          shape = "rectangle",
          x = 260,
          y = 992,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1454,
          name = "",
          type = "pig_guard_tower2",
          shape = "rectangle",
          x = 1028,
          y = 1668,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1455,
          name = "",
          type = "pig_guard_tower2",
          shape = "rectangle",
          x = 1212,
          y = 1668,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1502,
          name = "",
          type = "pig_guard_tower2",
          shape = "rectangle",
          x = 444,
          y = 516,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1280,
          name = "",
          type = "pig_guard_tower2",
          shape = "rectangle",
          x = 1028,
          y = 516,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1285,
          name = "",
          type = "pig_guard_tower2",
          shape = "rectangle",
          x = 1212,
          y = 992,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1286,
          name = "",
          type = "pig_guard_tower2",
          shape = "rectangle",
          x = 1212,
          y = 1084,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1338,
          name = "",
          type = "pig_guard_tower2",
          shape = "rectangle",
          x = 644,
          y = 1468,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1342,
          name = "",
          type = "pig_guard_tower2",
          shape = "rectangle",
          x = 828,
          y = 1468,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1512,
          name = "",
          type = "pig_antiquities_entrance",
          shape = "rectangle",
          x = 1028,
          y = 316,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1513,
          name = "",
          type = "hatshop_entrance",
          shape = "rectangle",
          x = 828,
          y = 1668,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1541,
          name = "",
          type = "pig_guard_tower_palace2",
          shape = "rectangle",
          x = 473,
          y = 1631,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1542,
          name = "",
          type = "lawnornament_1",
          shape = "rectangle",
          x = 224,
          y = 1759,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1543,
          name = "",
          type = "pig_guard_tower_palace2",
          shape = "rectangle",
          x = 223,
          y = 1632,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1544,
          name = "",
          type = "lawnornament_1",
          shape = "rectangle",
          x = 353,
          y = 1631,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1545,
          name = "",
          type = "pig_guard_tower_palace2",
          shape = "rectangle",
          x = 224,
          y = 1889,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1546,
          name = "",
          type = "lawnornament_1",
          shape = "rectangle",
          x = 480,
          y = 1760,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1547,
          name = "",
          type = "pig_guard_tower_palace2",
          shape = "rectangle",
          x = 481,
          y = 1889,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1548,
          name = "",
          type = "lawnornament_1",
          shape = "rectangle",
          x = 352,
          y = 1888,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1549,
          name = "",
          type = "pig_palace_entrance",
          shape = "rectangle",
          x = 352,
          y = 1759,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1550,
          name = "",
          type = "lawnornament_7",
          shape = "rectangle",
          x = 406,
          y = 1704,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1551,
          name = "",
          type = "lawnornament_7",
          shape = "rectangle",
          x = 295,
          y = 1704,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1552,
          name = "",
          type = "lawnornament_7",
          shape = "rectangle",
          x = 407,
          y = 1816,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1553,
          name = "",
          type = "lawnornament_7",
          shape = "rectangle",
          x = 295,
          y = 1815,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1916,
          name = "",
          type = "deciduoustree_tall",
          shape = "rectangle",
          x = 2160,
          y = 1264,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1917,
          name = "",
          type = "deciduoustree_tall",
          shape = "rectangle",
          x = 2160,
          y = 1488,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1918,
          name = "",
          type = "deciduoustree_tall",
          shape = "rectangle",
          x = 2160,
          y = 1432,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1919,
          name = "",
          type = "deciduoustree_tall",
          shape = "rectangle",
          x = 2160,
          y = 1320,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1920,
          name = "",
          type = "deciduoustree_tall",
          shape = "rectangle",
          x = 2160,
          y = 1377,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1921,
          name = "",
          type = "pighouse_city2",
          shape = "rectangle",
          x = 2366,
          y = 1377,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1922,
          name = "",
          type = "pighouse_city2",
          shape = "rectangle",
          x = 2368,
          y = 1472,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2128,
          name = "",
          type = "topiary_3",
          shape = "rectangle",
          x = 736,
          y = 2143,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2129,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 632,
          y = 2041,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2130,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 632,
          y = 2056,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2131,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 632,
          y = 2071,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2132,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 632,
          y = 2088,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2133,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 648,
          y = 2040,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2134,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 663,
          y = 2040,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2135,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 679,
          y = 2040,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2136,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 839,
          y = 2040,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2137,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 792,
          y = 2040,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2138,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 807,
          y = 2040,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2139,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 823,
          y = 2040,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2140,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 632,
          y = 2248,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2141,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 648,
          y = 2247,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2142,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 663,
          y = 2247,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2143,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 679,
          y = 2247,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2144,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 838,
          y = 2249,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2145,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 791,
          y = 2249,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2146,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 806,
          y = 2249,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2147,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 822,
          y = 2249,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2148,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 840,
          y = 2088,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2149,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 840,
          y = 2056,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2150,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 840,
          y = 2071,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2151,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 632,
          y = 2233,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2152,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 631,
          y = 2216,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2153,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 631,
          y = 2199,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2154,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 839,
          y = 2233,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2155,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 838,
          y = 2216,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2156,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 838,
          y = 2199,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2157,
          name = "",
          type = "lawnornament_1",
          shape = "rectangle",
          x = 815,
          y = 2064,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2158,
          name = "",
          type = "lawnornament_1",
          shape = "rectangle",
          x = 657,
          y = 2223,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2159,
          name = "",
          type = "lawnornament_1",
          shape = "rectangle",
          x = 655,
          y = 2066,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2160,
          name = "",
          type = "lawnornament_7",
          shape = "rectangle",
          x = 784,
          y = 2288,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2161,
          name = "",
          type = "lawnornament_1",
          shape = "rectangle",
          x = 815,
          y = 2223,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2162,
          name = "",
          type = "lawnornament_7",
          shape = "rectangle",
          x = 695,
          y = 2288,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2163,
          name = "",
          type = "lawnornament_7",
          shape = "rectangle",
          x = 592,
          y = 2186,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2164,
          name = "",
          type = "lawnornament_7",
          shape = "rectangle",
          x = 592,
          y = 2096,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2165,
          name = "",
          type = "lawnornament_7",
          shape = "rectangle",
          x = 695,
          y = 2000,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2166,
          name = "",
          type = "lawnornament_7",
          shape = "rectangle",
          x = 784,
          y = 2000,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2167,
          name = "",
          type = "lawnornament_7",
          shape = "rectangle",
          x = 880,
          y = 2096,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2168,
          name = "",
          type = "lawnornament_7",
          shape = "rectangle",
          x = 880,
          y = 2185,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2214,
          name = "",
          type = "pig_guard_tower2",
          shape = "rectangle",
          x = 736,
          y = 992,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2215,
          name = "",
          type = "lawnornament_7",
          shape = "rectangle",
          x = 672,
          y = 927,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2216,
          name = "",
          type = "lawnornament_7",
          shape = "rectangle",
          x = 800,
          y = 929,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2217,
          name = "",
          type = "lawnornament_7",
          shape = "rectangle",
          x = 672,
          y = 1055,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2218,
          name = "",
          type = "lawnornament_7",
          shape = "rectangle",
          x = 800,
          y = 1056,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2219,
          name = "",
          type = "lawnornament_3",
          shape = "rectangle",
          x = 857,
          y = 1105,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2220,
          name = "",
          type = "lawnornament_3",
          shape = "rectangle",
          x = 856,
          y = 880,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2221,
          name = "",
          type = "lawnornament_3",
          shape = "rectangle",
          x = 856,
          y = 935,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2222,
          name = "",
          type = "lawnornament_3",
          shape = "rectangle",
          x = 857,
          y = 1049,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2223,
          name = "",
          type = "lawnornament_3",
          shape = "rectangle",
          x = 856,
          y = 993,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2224,
          name = "",
          type = "lawnornament_3",
          shape = "rectangle",
          x = 617,
          y = 1050,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2225,
          name = "",
          type = "lawnornament_3",
          shape = "rectangle",
          x = 617,
          y = 1106,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2226,
          name = "",
          type = "lawnornament_3",
          shape = "rectangle",
          x = 616,
          y = 881,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2227,
          name = "",
          type = "lawnornament_3",
          shape = "rectangle",
          x = 616,
          y = 936,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2228,
          name = "",
          type = "lawnornament_3",
          shape = "rectangle",
          x = 616,
          y = 994,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2277,
          name = "",
          type = "hedge_layered",
          shape = "rectangle",
          x = 1850,
          y = 328,
          width = 0,
          height = 0,
          rotation = -180,
          visible = true,
          properties = {}
        },
        {
          id = 2278,
          name = "",
          type = "hedge_layered",
          shape = "rectangle",
          x = 1993,
          y = 328,
          width = 0,
          height = 0,
          rotation = -180,
          visible = true,
          properties = {}
        },
        {
          id = 2279,
          name = "",
          type = "hedge_layered",
          shape = "rectangle",
          x = 1993,
          y = 120,
          width = 0,
          height = 0,
          rotation = -180,
          visible = true,
          properties = {}
        },
        {
          id = 2280,
          name = "",
          type = "hedge_layered",
          shape = "rectangle",
          x = 1849,
          y = 120,
          width = 0,
          height = 0,
          rotation = -180,
          visible = true,
          properties = {}
        },
        {
          id = 2281,
          name = "",
          type = "pighouse_city2",
          shape = "rectangle",
          x = 1793,
          y = 319,
          width = 0,
          height = 0,
          rotation = -180,
          visible = true,
          properties = {}
        },
        {
          id = 2282,
          name = "",
          type = "pighouse_city2",
          shape = "rectangle",
          x = 1793,
          y = 127,
          width = 0,
          height = 0,
          rotation = -180,
          visible = true,
          properties = {}
        },
        {
          id = 2283,
          name = "",
          type = "pig_guard_tower2",
          shape = "rectangle",
          x = 1793,
          y = 223,
          width = 0,
          height = 0,
          rotation = -180,
          visible = true,
          properties = {}
        },
        {
          id = 2284,
          name = "",
          type = "lawnornament_6",
          shape = "rectangle",
          x = 1921,
          y = 288,
          width = 0,
          height = 0,
          rotation = -180,
          visible = true,
          properties = {}
        },
        {
          id = 2285,
          name = "",
          type = "lawnornament_6",
          shape = "rectangle",
          x = 1921,
          y = 256,
          width = 0,
          height = 0,
          rotation = -180,
          visible = true,
          properties = {}
        },
        {
          id = 2286,
          name = "",
          type = "lawnornament_6",
          shape = "rectangle",
          x = 1921,
          y = 224,
          width = 0,
          height = 0,
          rotation = -180,
          visible = true,
          properties = {}
        },
        {
          id = 2287,
          name = "",
          type = "lawnornament_6",
          shape = "rectangle",
          x = 1920,
          y = 192,
          width = 0,
          height = 0,
          rotation = -180,
          visible = true,
          properties = {}
        },
        {
          id = 2288,
          name = "",
          type = "lawnornament_6",
          shape = "rectangle",
          x = 1921,
          y = 160,
          width = 0,
          height = 0,
          rotation = -180,
          visible = true,
          properties = {}
        },
        {
          id = 2395,
          name = "",
          type = "pig_guard_tower2",
          shape = "rectangle",
          x = 1888,
          y = 992,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2396,
          name = "",
          type = "wall_stone",
          shape = "rectangle",
          x = 1765,
          y = 866,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2397,
          name = "",
          type = "pighouse_city2",
          shape = "rectangle",
          x = 1888,
          y = 912,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2398,
          name = "",
          type = "pighouse_city2",
          shape = "rectangle",
          x = 1888,
          y = 1072,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2399,
          name = "",
          type = "wall_stone",
          shape = "rectangle",
          x = 1765,
          y = 898,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2400,
          name = "",
          type = "wall_stone",
          shape = "rectangle",
          x = 1765,
          y = 883,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2401,
          name = "",
          type = "wall_stone",
          shape = "rectangle",
          x = 1765,
          y = 915,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2402,
          name = "",
          type = "wall_stone",
          shape = "rectangle",
          x = 1765,
          y = 962,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2403,
          name = "",
          type = "wall_stone",
          shape = "rectangle",
          x = 1765,
          y = 947,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2404,
          name = "",
          type = "wall_stone",
          shape = "rectangle",
          x = 1765,
          y = 930,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2405,
          name = "",
          type = "wall_stone",
          shape = "rectangle",
          x = 1765,
          y = 979,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2406,
          name = "",
          type = "wall_stone",
          shape = "rectangle",
          x = 1765,
          y = 1058,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2407,
          name = "",
          type = "wall_stone",
          shape = "rectangle",
          x = 1765,
          y = 1090,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2408,
          name = "",
          type = "wall_stone",
          shape = "rectangle",
          x = 1765,
          y = 1026,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2409,
          name = "",
          type = "wall_stone",
          shape = "rectangle",
          x = 1765,
          y = 1011,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2410,
          name = "",
          type = "wall_stone",
          shape = "rectangle",
          x = 1765,
          y = 994,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2411,
          name = "",
          type = "wall_stone",
          shape = "rectangle",
          x = 1765,
          y = 1075,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2412,
          name = "",
          type = "wall_stone",
          shape = "rectangle",
          x = 1765,
          y = 1107,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2413,
          name = "",
          type = "wall_stone",
          shape = "rectangle",
          x = 1765,
          y = 1043,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2414,
          name = "",
          type = "wall_stone",
          shape = "rectangle",
          x = 1765,
          y = 1122,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2415,
          name = "",
          type = "wall_stone",
          shape = "rectangle",
          x = 2013,
          y = 914,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2416,
          name = "",
          type = "wall_stone",
          shape = "rectangle",
          x = 2013,
          y = 929,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2417,
          name = "",
          type = "wall_stone",
          shape = "rectangle",
          x = 2013,
          y = 1074,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2418,
          name = "",
          type = "wall_stone",
          shape = "rectangle",
          x = 2013,
          y = 978,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2419,
          name = "",
          type = "wall_stone",
          shape = "rectangle",
          x = 2013,
          y = 1089,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2420,
          name = "",
          type = "wall_stone",
          shape = "rectangle",
          x = 2013,
          y = 897,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2421,
          name = "",
          type = "wall_stone",
          shape = "rectangle",
          x = 2013,
          y = 1042,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2422,
          name = "",
          type = "wall_stone",
          shape = "rectangle",
          x = 2013,
          y = 1010,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2423,
          name = "",
          type = "wall_stone",
          shape = "rectangle",
          x = 2013,
          y = 1025,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2424,
          name = "",
          type = "wall_stone",
          shape = "rectangle",
          x = 2013,
          y = 882,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2425,
          name = "",
          type = "wall_stone",
          shape = "rectangle",
          x = 2013,
          y = 1121,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2426,
          name = "",
          type = "wall_stone",
          shape = "rectangle",
          x = 2013,
          y = 993,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2427,
          name = "",
          type = "wall_stone",
          shape = "rectangle",
          x = 2013,
          y = 865,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2428,
          name = "",
          type = "wall_stone",
          shape = "rectangle",
          x = 2013,
          y = 1106,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2429,
          name = "",
          type = "wall_stone",
          shape = "rectangle",
          x = 2013,
          y = 961,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2430,
          name = "",
          type = "wall_stone",
          shape = "rectangle",
          x = 2013,
          y = 946,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2431,
          name = "",
          type = "wall_stone",
          shape = "rectangle",
          x = 2013,
          y = 1057,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2432,
          name = "",
          type = "lawnornament_6",
          shape = "rectangle",
          x = 1805,
          y = 896,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2433,
          name = "",
          type = "lawnornament_6",
          shape = "rectangle",
          x = 1805,
          y = 943,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2434,
          name = "",
          type = "lawnornament_6",
          shape = "rectangle",
          x = 1805,
          y = 991,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2435,
          name = "",
          type = "lawnornament_6",
          shape = "rectangle",
          x = 1805,
          y = 1039,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2436,
          name = "",
          type = "lawnornament_6",
          shape = "rectangle",
          x = 1805,
          y = 1088,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2437,
          name = "",
          type = "lawnornament_6",
          shape = "rectangle",
          x = 1975,
          y = 894,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2438,
          name = "",
          type = "lawnornament_6",
          shape = "rectangle",
          x = 1975,
          y = 1037,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2439,
          name = "",
          type = "lawnornament_6",
          shape = "rectangle",
          x = 1975,
          y = 989,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2440,
          name = "",
          type = "lawnornament_6",
          shape = "rectangle",
          x = 1975,
          y = 1086,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2441,
          name = "",
          type = "lawnornament_6",
          shape = "rectangle",
          x = 1975,
          y = 941,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2454,
          name = "",
          type = "hedge_layered",
          shape = "rectangle",
          x = 2311,
          y = 888,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2455,
          name = "",
          type = "hedge_layered",
          shape = "rectangle",
          x = 2168,
          y = 888,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2456,
          name = "",
          type = "hedge_layered",
          shape = "rectangle",
          x = 2168,
          y = 1096,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2457,
          name = "",
          type = "hedge_layered",
          shape = "rectangle",
          x = 2312,
          y = 1096,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2458,
          name = "",
          type = "pighouse_city2",
          shape = "rectangle",
          x = 2368,
          y = 897,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2459,
          name = "",
          type = "pighouse_city2",
          shape = "rectangle",
          x = 2368,
          y = 1089,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2460,
          name = "",
          type = "pighouse_city2",
          shape = "rectangle",
          x = 2368,
          y = 993,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2461,
          name = "",
          type = "lawnornament_6",
          shape = "rectangle",
          x = 2240,
          y = 928,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2462,
          name = "",
          type = "lawnornament_6",
          shape = "rectangle",
          x = 2240,
          y = 960,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2463,
          name = "",
          type = "lawnornament_6",
          shape = "rectangle",
          x = 2240,
          y = 992,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2464,
          name = "",
          type = "lawnornament_6",
          shape = "rectangle",
          x = 2241,
          y = 1024,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2465,
          name = "",
          type = "lawnornament_6",
          shape = "rectangle",
          x = 2240,
          y = 1056,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2495,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 2168,
          y = 1672,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2496,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 2376,
          y = 1657,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2497,
          name = "",
          type = "city_lamp",
          shape = "rectangle",
          x = 2273,
          y = 1760,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2498,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 2360,
          y = 1656,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2499,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 2168,
          y = 1832,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2500,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 2168,
          y = 1657,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2501,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 2168,
          y = 1816,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2502,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 2168,
          y = 1848,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2503,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 2168,
          y = 1704,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2504,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 2217,
          y = 1657,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2505,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 2344,
          y = 1657,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2506,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 2199,
          y = 1865,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2507,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 2200,
          y = 1658,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2508,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 2327,
          y = 1656,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2509,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 2185,
          y = 1657,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2510,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 2168,
          y = 1688,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2511,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 2359,
          y = 1863,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2512,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 2184,
          y = 1864,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2513,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 2375,
          y = 1864,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2514,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 2216,
          y = 1864,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2515,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 2326,
          y = 1863,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2516,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 2167,
          y = 1864,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2517,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 2376,
          y = 1704,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2518,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 2376,
          y = 1688,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2519,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 2376,
          y = 1848,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2520,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 2376,
          y = 1672,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2521,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 2343,
          y = 1864,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2522,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 2376,
          y = 1816,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2523,
          name = "",
          type = "hedge_cone",
          shape = "rectangle",
          x = 2376,
          y = 1832,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2525,
          name = "",
          type = "pighouse_city2",
          shape = "rectangle",
          x = 1888,
          y = 516,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2526,
          name = "",
          type = "pighouse_city2",
          shape = "rectangle",
          x = 1980,
          y = 516,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2529,
          name = "",
          type = "pighouse_city2",
          shape = "rectangle",
          x = 1504,
          y = 132,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2530,
          name = "",
          type = "pighouse_city2",
          shape = "rectangle",
          x = 1596,
          y = 132,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
