return {
  version = "1.1",
  luaversion = "5.1",
  orientation = "orthogonal",
  width = 13,
  height = 13,
  tilewidth = 64,
  tileheight = 64,
  properties = {},
  tilesets = {
    {
      name = "tiles",
      firstgid = 1,
      tilewidth = 64,
      tileheight = 64,
      spacing = 0,
      margin = 0,
      image = "setpiecemod/tiles.png",
      imagewidth = 512,
      imageheight = 128,
      properties = {},
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      name = "BG_TILES",
      x = 0,
      y = 0,
      width = 13,
      height = 13,
      visible = true,
      opacity = 1,
      properties = {},
      encoding = "lua",
      data = {
        4, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4,
        4, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4,
        4, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4,
        4, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4,
        4, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4,
        4, 4, 4, 4, 4, 2, 2, 2, 4, 4, 4, 4, 4,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        4, 4, 4, 4, 4, 2, 2, 2, 4, 4, 4, 4, 4,
        4, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4,
        4, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4,
        4, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4,
        4, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4,
        4, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4
      }
    },
    {
      type = "objectgroup",
      name = "FG_OBJECTS",
      visible = true,
      opacity = 1,
      properties = {},
      objects = {
        {
          name = "spawnpoint_master",
          type = "spawnpoint_master",
          shape = "rectangle",
          x = 388,
          y = 388,
          width = 56,
          height = 57,
          visible = true,
          properties = {}
        },
        {
          name = "lobby_to_dst",
          type = "lobby_to_dst",
          shape = "rectangle",
          x = 131,
          y = 133,
          width = 56,
          height = 57,
          visible = true,
          properties = {}
        },
        {
          name = "dst_to_sw",
          type = "dst_to_sw",
          shape = "rectangle",
          x = 645,
          y = 132,
          width = 56,
          height = 57,
          visible = true,
          properties = {}
        },
        {
          name = "dst_to_hamlet",
          type = "dst_to_hamlet",
          shape = "rectangle",
          x = 132,
          y = 643,
          width = 56,
          height = 57,
          visible = true,
          properties = {}
        },
        {
          name = "underwater_entrance",
          type = "underwater_entrance",
          shape = "rectangle",
          x = 646,
          y = 643,
          width = 56,
          height = 57,
          visible = true,
          properties = {}
        },
        {
          name = "multiplayer_portal",
          type = "multiplayer_portal",
          shape = "rectangle",
          x = 388,
          y = 388,
          width = 56,
          height = 57,
          visible = true,
          properties = {}
        },
        {
          name = "berrybush",
          type = "berrybush",
          shape = "ellipse",
          x = 127,
          y = 318,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "berrybush",
          type = "berrybush",
          shape = "ellipse",
          x = 319,
          y = 66,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "berrybush",
          type = "berrybush",
          shape = "ellipse",
          x = 61,
          y = 62,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "grass",
          type = "grass",
          shape = "ellipse",
          x = 44,
          y = 279,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "grass",
          type = "grass",
          shape = "ellipse",
          x = 61,
          y = 321,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "grass",
          type = "grass",
          shape = "ellipse",
          x = 294,
          y = 173,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "grass",
          type = "grass",
          shape = "ellipse",
          x = 306,
          y = 200,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "grass",
          type = "grass",
          shape = "ellipse",
          x = 151,
          y = 44,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "grass",
          type = "grass",
          shape = "ellipse",
          x = 187,
          y = 59,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "sapling",
          type = "sapling",
          shape = "ellipse",
          x = 46,
          y = 171,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "sapling",
          type = "sapling",
          shape = "ellipse",
          x = 202,
          y = 348,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "sapling",
          type = "sapling",
          shape = "ellipse",
          x = 209,
          y = 246,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "sapling",
          type = "sapling",
          shape = "ellipse",
          x = 247,
          y = 108,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "evergreen",
          type = "evergreen",
          shape = "ellipse",
          x = 112,
          y = 247,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "evergreen",
          type = "evergreen",
          shape = "ellipse",
          x = 250,
          y = 40,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "evergreen",
          type = "evergreen",
          shape = "ellipse",
          x = 95,
          y = 95,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "evergreen",
          type = "evergreen",
          shape = "ellipse",
          x = 318,
          y = 269,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "evergreen",
          type = "evergreen",
          shape = "ellipse",
          x = 95,
          y = 351,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "evergreen",
          type = "evergreen",
          shape = "ellipse",
          x = 272,
          y = 340,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "seashell_beached",
          type = "seashell_beached",
          shape = "ellipse",
          x = 515,
          y = 73,
          width = 12,
          height = 12,
          visible = true,
          properties = {}
        },
        {
          name = "seashell_beached",
          type = "seashell_beached",
          shape = "ellipse",
          x = 489,
          y = 173,
          width = 12,
          height = 12,
          visible = true,
          properties = {}
        },
        {
          name = "seashell_beached",
          type = "seashell_beached",
          shape = "ellipse",
          x = 589,
          y = 88,
          width = 12,
          height = 12,
          visible = true,
          properties = {}
        },
        {
          name = "seashell_beached",
          type = "seashell_beached",
          shape = "ellipse",
          x = 552,
          y = 243,
          width = 12,
          height = 12,
          visible = true,
          properties = {}
        },
        {
          name = "seashell_beached",
          type = "seashell_beached",
          shape = "ellipse",
          x = 612,
          y = 313,
          width = 12,
          height = 12,
          visible = true,
          properties = {}
        },
        {
          name = "seashell_beached",
          type = "seashell_beached",
          shape = "ellipse",
          x = 735,
          y = 272,
          width = 12,
          height = 12,
          visible = true,
          properties = {}
        },
        {
          name = "seashell_beached",
          type = "seashell_beached",
          shape = "ellipse",
          x = 765,
          y = 97,
          width = 12,
          height = 12,
          visible = true,
          properties = {}
        },
        {
          name = "seashell_beached",
          type = "seashell_beached",
          shape = "ellipse",
          x = 672,
          y = 62,
          width = 12,
          height = 12,
          visible = true,
          properties = {}
        },
        {
          name = "bambootree",
          type = "bambootree",
          shape = "ellipse",
          x = 549,
          y = 297,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "bambootree",
          type = "bambootree",
          shape = "ellipse",
          x = 680,
          y = 262,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "bambootree",
          type = "bambootree",
          shape = "ellipse",
          x = 551,
          y = 142,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "bambootree",
          type = "bambootree",
          shape = "ellipse",
          x = 591,
          y = 34,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "bambootree",
          type = "bambootree",
          shape = "ellipse",
          x = 789,
          y = 53,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "bush_vine",
          type = "bush_vine",
          shape = "ellipse",
          x = 730,
          y = 76,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "bush_vine",
          type = "bush_vine",
          shape = "ellipse",
          x = 490,
          y = 45,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "bush_vine",
          type = "bush_vine",
          shape = "ellipse",
          x = 559,
          y = 353,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "bush_vine",
          type = "bush_vine",
          shape = "ellipse",
          x = 793,
          y = 355,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "bush_vine",
          type = "bush_vine",
          shape = "ellipse",
          x = 491,
          y = 245,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "palmtree",
          type = "palmtree",
          shape = "ellipse",
          x = 671,
          y = 348,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "palmtree",
          type = "palmtree",
          shape = "ellipse",
          x = 576,
          y = 198,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "palmtree",
          type = "palmtree",
          shape = "ellipse",
          x = 475,
          y = 113,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "palmtree",
          type = "palmtree",
          shape = "ellipse",
          x = 767,
          y = 160,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "palmtree",
          type = "palmtree",
          shape = "ellipse",
          x = 789,
          y = 212,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "city_lamp",
          type = "city_lamp",
          shape = "ellipse",
          x = 512,
          y = 320,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "city_lamp",
          type = "city_lamp",
          shape = "ellipse",
          x = 512,
          y = 512,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "city_lamp",
          type = "city_lamp",
          shape = "ellipse",
          x = 320,
          y = 512,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "city_lamp",
          type = "city_lamp",
          shape = "ellipse",
          x = 320,
          y = 320,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "lawornament_6",
          type = "lawnornament_6",
          shape = "ellipse",
          x = 64,
          y = 576,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "lawornament_6",
          type = "lawnornament_6",
          shape = "ellipse",
          x = 249,
          y = 552,
          width = 22,
          height = 18,
          visible = true,
          properties = {}
        },
        {
          name = "lawornament_6",
          type = "lawnornament_6",
          shape = "ellipse",
          x = 256,
          y = 768,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "lawornament_6",
          type = "lawnornament_6",
          shape = "ellipse",
          x = 64,
          y = 768,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "city_lamp",
          type = "city_lamp",
          shape = "ellipse",
          x = 126,
          y = 731,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "lawornament_5",
          type = "lawnornament_5",
          shape = "ellipse",
          x = 46,
          y = 623,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "lawornament_1",
          type = "lawnornament_1",
          shape = "ellipse",
          x = 167,
          y = 553,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "flower_cave",
          type = "flower_cave",
          shape = "ellipse",
          x = 596,
          y = 504,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "flower_cave",
          type = "flower_cave",
          shape = "ellipse",
          x = 738,
          y = 544,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "flower_cave",
          type = "flower_cave",
          shape = "ellipse",
          x = 527,
          y = 663,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "flower_cave",
          type = "flower_cave",
          shape = "ellipse",
          x = 598,
          y = 795,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "flower_cave",
          type = "flower_cave",
          shape = "ellipse",
          x = 764,
          y = 762,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_small",
          shape = "ellipse",
          x = 521,
          y = 576,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_medium",
          shape = "ellipse",
          x = 518,
          y = 739,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "ellipse",
          x = 663,
          y = 569,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "ellipse",
          x = 499,
          y = 790,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_small",
          shape = "ellipse",
          x = 755,
          y = 604,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_medium",
          shape = "ellipse",
          x = 794,
          y = 711,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_small",
          shape = "ellipse",
          x = 677,
          y = 788,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_small",
          shape = "ellipse",
          x = 599,
          y = 713,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "ellipse",
          x = 797,
          y = 801,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "topiary_3",
          shape = "ellipse",
          x = 128,
          y = 740,
          width = 85,
          height = 77,
          visible = true,
          properties = {}
        },
        {
          name = "city_lamp",
          type = "city_lamp",
          shape = "ellipse",
          x = 703,
          y = 724,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "city_lamp",
          type = "city_lamp",
          shape = "ellipse",
          x = 702,
          y = 97,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "city_lamp",
          type = "city_lamp",
          shape = "ellipse",
          x = 702,
          y = 97,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "topiary_4",
          shape = "ellipse",
          x = 267,
          y = 627,
          width = 85,
          height = 77,
          visible = true,
          properties = {}
        },
        {
          name = "lawornament_5",
          type = "lawnornament_5",
          shape = "ellipse",
          x = 334,
          y = 775,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "lawornament_5",
          type = "lawnornament_3",
          shape = "ellipse",
          x = 51,
          y = 689,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "lawornament_5",
          type = "lawnornament_3",
          shape = "ellipse",
          x = 96,
          y = 480,
          width = 25,
          height = 29,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
