return {
  version = "1.1",
  luaversion = "5.1",
  orientation = "orthogonal",
  width = 20,
  height = 20,
  tilewidth = 64,
  tileheight = 64,
  properties = {},
  tilesets = {
    {
      name = "ground",
      firstgid = 1,
      filename = "../dont_starve/ground.tsx",
      tilewidth = 64,
      tileheight = 64,
      spacing = 0,
      margin = 0,
      image = "../dont_starve/tiles.png",
      imagewidth = 512,
      imageheight = 384,
      properties = {},
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      name = "BG_TILES",
      x = 0,
      y = 0,
      width = 20,
      height = 20,
      visible = true,
      opacity = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "objectgroup",
      name = "FG_OBJECTS",
      visible = true,
      opacity = 1,
      properties = {},
      objects = {
        {
          name = "",
          type = "underseamoonglass_rock",
          shape = "rectangle",
          x = 340,
          y = 152,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "grotto_pool_big",
          shape = "rectangle",
          x = 476,
          y = 126,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "underseamoonglass_rock",
          shape = "rectangle",
          x = 626,
          y = 170,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "grotto_pool_big",
          shape = "rectangle",
          x = 844,
          y = 130,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "grotto_pool_big",
          shape = "rectangle",
          x = 898,
          y = 208,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "underseamoonglass_rock",
          shape = "rectangle",
          x = 1008,
          y = 270,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "underseamoonglass_rock",
          shape = "rectangle",
          x = 1036,
          y = 358,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "grotto_pool_big",
          shape = "rectangle",
          x = 996,
          y = 480,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "grotto_pool_big",
          shape = "rectangle",
          x = 1048,
          y = 636,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "underseamoonglass_rock",
          shape = "rectangle",
          x = 998,
          y = 756,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "grotto_pool_big",
          shape = "rectangle",
          x = 1038,
          y = 852,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "grotto_pool_big",
          shape = "rectangle",
          x = 1000,
          y = 1042,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "underseamoonglass_rock",
          shape = "rectangle",
          x = 834,
          y = 1106,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "underseamoonglass_rock",
          shape = "rectangle",
          x = 618,
          y = 1060,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "grotto_pool_big",
          shape = "rectangle",
          x = 446,
          y = 1088,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "underseamoonglass_rock",
          shape = "rectangle",
          x = 260,
          y = 1052,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "grotto_pool_big",
          shape = "rectangle",
          x = 166,
          y = 898,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "grotto_pool_big",
          shape = "rectangle",
          x = 188,
          y = 742,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "underseamoonglass_rock",
          shape = "rectangle",
          x = 150,
          y = 526,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "grotto_pool_big",
          shape = "rectangle",
          x = 196,
          y = 350,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "underseamoonglass_rock",
          shape = "rectangle",
          x = 230,
          y = 182,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "grotto_pool_big",
          shape = "rectangle",
          x = 582,
          y = 380,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "grotto_pool_big",
          shape = "rectangle",
          x = 836,
          y = 790,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "grotto_pool_big",
          shape = "rectangle",
          x = 406,
          y = 796,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "underseamoonglass_rock",
          shape = "rectangle",
          x = 388,
          y = 262,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "underseamoonglass_rock",
          shape = "rectangle",
          x = 448,
          y = 254,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "underseamoonglass_rock",
          shape = "rectangle",
          x = 538,
          y = 282,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "underseamoonglass_rock",
          shape = "rectangle",
          x = 302,
          y = 364,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "underseamoonglass_rock",
          shape = "rectangle",
          x = 456,
          y = 414,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "underseamoonglass_rock",
          shape = "rectangle",
          x = 322,
          y = 482,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "underseamoonglass_rock",
          shape = "rectangle",
          x = 524,
          y = 640,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "underseamoonglass_rock",
          shape = "rectangle",
          x = 512,
          y = 748,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "underseamoonglass_rock",
          shape = "rectangle",
          x = 286,
          y = 628,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "underseamoonglass_rock",
          shape = "rectangle",
          x = 688,
          y = 772,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "underseamoonglass_rock",
          shape = "rectangle",
          x = 568,
          y = 878,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "underseamoonglass_rock",
          shape = "rectangle",
          x = 784,
          y = 952,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "underseamoonglass_rock",
          shape = "rectangle",
          x = 822,
          y = 708,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "underseamoonglass_rock",
          shape = "rectangle",
          x = 918,
          y = 542,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "underseamoonglass_rock",
          shape = "rectangle",
          x = 794,
          y = 298,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "underseamoonglass_rock",
          shape = "rectangle",
          x = 708,
          y = 390,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "underseamoonglass_rock",
          shape = "rectangle",
          x = 958,
          y = 430,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "underseamoonglass_rock",
          shape = "rectangle",
          x = 710,
          y = 518,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "underseamoonglass_rock",
          shape = "rectangle",
          x = 492,
          y = 586,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "underseamoonglass_rock",
          shape = "rectangle",
          x = 398,
          y = 918,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "underseamoonglass_rock",
          shape = "rectangle",
          x = 880,
          y = 948,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "underseamoonglass_rock",
          shape = "rectangle",
          x = 768,
          y = 632,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "underseamoonglass_rock",
          shape = "rectangle",
          x = 528,
          y = 456,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "grotto_pool_small",
          shape = "rectangle",
          x = 684,
          y = 276,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "grotto_pool_small",
          shape = "rectangle",
          x = 804,
          y = 446,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "undersearock_moon",
          shape = "rectangle",
          x = 364,
          y = 472,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "grotto_pool_small",
          shape = "rectangle",
          x = 356,
          y = 678,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "underseamoonglass_rock",
          shape = "rectangle",
          x = 298,
          y = 794,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "undersearock_moon",
          shape = "rectangle",
          x = 384,
          y = 1060,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "grotto_pool_small",
          shape = "rectangle",
          x = 530,
          y = 1062,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "underseamoonglass_rock",
          shape = "rectangle",
          x = 702,
          y = 992,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "underseamoonglass_rock",
          shape = "rectangle",
          x = 1018,
          y = 896,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "underseamoonglass_rock",
          shape = "rectangle",
          x = 1048,
          y = 704,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "grotto_pool_small",
          shape = "rectangle",
          x = 388,
          y = 540,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
		
        {
          name = "",
          type = "undersearock_moon_shell",
          shape = "rectangle",
          x = 632,
          y = 618,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },

        {
          name = "",
          type = "undersearock_moon",
          shape = "rectangle",
          x = 682,
          y = 568,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },

        {
          name = "",
          type = "underseamoonglass_rock",
          shape = "rectangle",
          x = 582,
          y = 668,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },		
		
        {
          name = "",
          type = "undersearock_moon",
          shape = "rectangle",
          x = 582,
          y = 568,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
		
        {
          name = "",
          type = "undersearock_moon",
          shape = "rectangle",
          x = 682,
          y = 668,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },

        {
          name = "",
          type = "underseamoonglass_rock",
          shape = "rectangle",
          x = 602,
          y = 568,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },

        {
          name = "",
          type = "undersearock_moon",
          shape = "rectangle",
          x = 632,
          y = 668,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },

        {
          name = "",
          type = "undersearock_moon",
          shape = "rectangle",
          x = 582,
          y = 618,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },	

        {
          name = "",
          type = "underseamoonglass_rock",
          shape = "rectangle",
          x = 692,
          y = 618,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        }				
		
      }
    }
  }
}