return {
  version = "1.1",
  luaversion = "5.1",
  orientation = "orthogonal",
  width = 3,
  height = 3,
  tilewidth = 64,
  tileheight = 64,
  properties = {},
  tilesets = {
    {
      name = "tiles",
      firstgid = 1,
      tilewidth = 64,
      tileheight = 64,
      spacing = 0,
      margin = 0,
      image = "tileset/tiles.png",
      imagewidth = 512,
      imageheight = 128,
      properties = {},
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      name = "BG_TILES",
      x = 0,
      y = 0,
      width = 3,
      height = 3,
      visible = true,
      opacity = 1,
      properties = {},
      encoding = "lua",
      data = {
        6, 6, 6,
        6, 6, 6,
        6, 6, 6
      }
    },
    {
      type = "objectgroup",
      name = "FG_OBJECTS",
      visible = true,
      opacity = 1,
      properties = {},
      objects = {
      {
          id = 1,
          name = "Reed",
          type = "reeds",
          shape = "ellipse",
          x = 96.3859,
          y = 48.3669,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "Reed",
          type = "reeds",
          shape = "ellipse",
          x = 72.9185,
          y = 28.5543,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "Reed",
          type = "reeds",
          shape = "ellipse",
          x = 91.2283,
          y = 24,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "Reed",
          type = "reeds",
          shape = "ellipse",
          x = 92.2989,
          y = 93.2935,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "Reed",
          type = "reeds",
          shape = "ellipse",
          x = 82.4592,
          y = 42.4592,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "Reed",
          type = "reeds",
          shape = "ellipse",
          x = 67.6114,
          y = 53.1765,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "Reed",
          type = "reeds",
          shape = "ellipse",
          x = 86.3642,
          y = 9.04632,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "Reed",
          type = "reeds",
          shape = "ellipse",
          x = 105.918,
          y = 36.0409,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "Reed",
          type = "reeds",
          shape = "ellipse",
          x = 77,
          y = 80,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "Reed",
          type = "reeds",
          shape = "ellipse",
          x = 78,
          y = 102,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "Reed",
          type = "reeds",
          shape = "ellipse",
          x = 111,
          y = 13,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "mangrove tree",
          type = "tree_mangrove",
          shape = "ellipse",
          x = 105.242,
          y = 76.6848,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "mangrove tree",
          type = "tree_mangrove",
          shape = "ellipse",
          x = 94.0842,
          y = 34.6226,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "mangrove tree",
          type = "tree_mangrove",
          shape = "ellipse",
          x = 71.375,
          y = 17.2989,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "mangrove tree",
          type = "tree_mangrove",
          shape = "ellipse",
          x = 70.3642,
          y = 114.334,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "Reed",
          type = "reeds",
          shape = "ellipse",
          x = 115.804,
          y = 70.7609,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "Reed",
          type = "reeds",
          shape = "ellipse",
          x = 114.649,
          y = 89.2391,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "Reed",
          type = "reeds",
          shape = "ellipse",
          x = 85.5462,
          y = 111.875,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "Reed",
          type = "reeds",
          shape = "ellipse",
          x = 106.158,
          y = 109.231,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
--water
        },
        {
          name = "",
          type = "fishinholewaterspawner",
          shape = "rectangle",
          x = 100,
          y = 90,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },	
        {
          name = "",
          type = "fishinholewaterspawner",
          shape = "rectangle",
          x = 100,
          y = 90,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },	
        {
          name = "",
          type = "oxwaterspawner",
          shape = "rectangle",
          x = 100,
          y = 90,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },	
        {
          name = "",
          type = "oxwaterspawner",
          shape = "rectangle",
          x = 100,
          y = 90,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },	
        {
          name = "",
          type = "Grasswaterspawner",
          shape = "rectangle",
          x = 100,
          y = 90,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },	
        {
          name = "",
          type = "Grasswaterspawner",
          shape = "rectangle",
          x = 100,
          y = 90,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },		
        {
          name = "",
          type = "Grasswaterspawner",
          shape = "rectangle",
          x = 100,
          y = 90,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },		
        {
          name = "",
          type = "Grasswaterspawner",
          shape = "rectangle",
          x = 100,
          y = 90,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },		
        {
          name = "",
          type = "Grasswaterspawner",
          shape = "rectangle",
          x = 100,
          y = 90,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },		
        {
          name = "",
          type = "Grasswaterspawner",
          shape = "rectangle",
          x = 100,
          y = 90,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },		
        {
          name = "",
          type = "Grasswaterspawner",
          shape = "rectangle",
          x = 100,
          y = 90,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },		
        {
          name = "",
          type = "Grasswaterspawner",
          shape = "rectangle",
          x = 100,
          y = 90,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },		
        {
          name = "",
          type = "Grasswaterspawner",
          shape = "rectangle",
          x = 100,
          y = 90,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },		
        {
          name = "",
          type = "Grasswaterspawner",
          shape = "rectangle",
          x = 100,
          y = 90,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },		
        {
          name = "",
          type = "Grasswaterspawner",
          shape = "rectangle",
          x = 100,
          y = 90,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },		
        {
          name = "",
          type = "Grasswaterspawner",
          shape = "rectangle",
          x = 100,
          y = 90,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },		
        {
          name = "",
          type = "Grasswaterspawner",
          shape = "rectangle",
          x = 100,
          y = 90,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },		
        {
          name = "",
          type = "Grasswaterspawner",
          shape = "rectangle",
          x = 100,
          y = 90,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },		
        {
          name = "",
          type = "Grasswaterspawner",
          shape = "rectangle",
          x = 100,
          y = 90,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },		
        {
          name = "",
          type = "Grasswaterspawner",
          shape = "rectangle",
          x = 100,
          y = 90,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },				
--quinas		
        {
          name = "",
          type = "Grasswaterspawner",
          shape = "rectangle",
          x = 100,
          y = 90,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "Grasswaterspawner",
          shape = "rectangle",
          x = 100,
          y = 90,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },	
        {
          name = "",
          type = "mangrovespawner",
          shape = "rectangle",
          x = 100,
          y = 90,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },			
        {
          name = "",
          type = "mangrovespawner",
          shape = "rectangle",
          x = 100,
          y = 90,
          width = 0,
          height = 0,
          isible = true,
          properties = {}
        },
        {
          name = "",
          type = "mangrovespawner",
          shape = "rectangle",
          x = 100,
          y = 90,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mangrovespawner",
          shape = "rectangle",
          x = 100,
          y = 90,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mangrovespawner",
          shape = "rectangle",
          x = 100,
          y = 90,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mangrovespawner",
          shape = "rectangle",
          x = 100,
          y = 90,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mangrovespawner",
          shape = "rectangle",
          x = 100,
          y = 90,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mangrovespawner",
          shape = "rectangle",
          x = 100,
          y = 90,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mangrovespawner",
          shape = "rectangle",
          x = 100,
          y = 90,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mangrovespawner",
          shape = "rectangle",
          x = 100,
          y = 90,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mangrovespawner",
          shape = "rectangle",
          x = 100,
          y = 90,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mangrovespawner",
          shape = "rectangle",
          x = 100,
          y = 90,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mangrovespawner",
          shape = "rectangle",
          x = 100,
          y = 90,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mangrovespawner",
          shape = "rectangle",
          x = 100,
          y = 90,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
		        {
          name = "",
          type = "mangrovespawner",
          shape = "rectangle",
          x = 100,
          y = 90,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mangrovespawner",
          shape = "rectangle",
          x = 100,
          y = 90,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mangrovespawner",
          shape = "rectangle",
          x = 100,
          y = 90,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mangrovespawner",
          shape = "rectangle",
          x = 100,
          y = 90,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mangrovespawner",
          shape = "rectangle",
          x = 100,
          y = 90,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mangrovespawner",
          shape = "rectangle",
          x = 100,
          y = 90,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
		
		
      }
    }
  }
}
