return {
  version = "1.1",
  luaversion = "5.1",
  tiledversion = "0.15.1",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 10,
  height = 10,
  tilewidth = 64,
  tileheight = 64,
  nextobjectid = 49,
  properties = {},
  tilesets = {
    {
      name = "ground",
      firstgid = 1,
      filename = "Modding/DS/tileset/ground.tsx",
      tilewidth = 64,
      tileheight = 64,
      spacing = 0,
      margin = 0,
      image = "Modding/DS/tileset/tiles.png",
      imagewidth = 512,
      imageheight = 128,
      tileoffset = {
        x = 0,
        y = 0
      },
      properties = {},
      terrains = {},
      tilecount = 16,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      name = "BG_TILES",
      x = 0,
      y = 0,
      width = 10,
      height = 10,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 9, 9, 9, 9, 9, 9, 0, 0,
        0, 9, 9, 9, 9, 9, 9, 9, 9, 0,
        9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
        9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
        9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
        9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
        9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
        9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
        0, 9, 9, 9, 9, 9, 9, 9, 9, 0, 
        0, 0, 9, 9, 9, 9, 9, 9, 0, 0, 	
      }
    },
    {
      type = "objectgroup",
      name = "FG_OBJECTS",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 4,
          name = "",
          type = "teepee",
          shape = "rectangle",
          x = 256,
          y = 192,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "",
          type = "teepee",
          shape = "rectangle",
          x = 320,
          y = 448,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "tikihead",
          shape = "rectangle",
          x = 320,
          y = 320,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 37,
          name = "",
          type = "teepee",
          shape = "rectangle",
          x = 448,
          y = 256,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "",
          type = "teepee",
          shape = "rectangle",
          x = 192,
          y = 448,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "",
          type = "cave_banana_tree",
          shape = "rectangle",
          x = 448,
          y = 448,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 42,
          name = "",
          type = "cave_banana_tree",
          shape = "rectangle",
          x = 576,
          y = 448,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 43,
          name = "",
          type = "cave_banana_tree",
          shape = "rectangle",
          x = 576,
          y = 320,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "",
          type = "cave_banana_tree",
          shape = "rectangle",
          x = 576,
          y = 192,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "",
          type = "cave_banana_tree",
          shape = "rectangle",
          x = 64,
          y = 448,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "",
          type = "cave_banana_tree",
          shape = "rectangle",
          x = 64,
          y = 320,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
		
        {
          name = "",
          type = "cave_banana_tree",
          shape = "rectangle",
          x = 64,
          y = 192,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_banana_tree",
          shape = "rectangle",
          x = 384,
          y = 576,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_banana_tree",
          shape = "rectangle",
          x = 320,
          y = 576,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_banana_tree",
          shape = "rectangle",
          x = 256,
          y = 576,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_banana_tree",
          shape = "rectangle",
          x = 384,
          y = 64,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_banana_tree",
          shape = "rectangle",
          x = 320,
          y = 64,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_banana_tree",
          shape = "rectangle",
          x =256,
          y = 64,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tikifire",
          shape = "rectangle",
          x = 512,
          y = 512,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tikifire",
          shape = "rectangle",
          x = 512,
          y = 128,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tikifire",
          shape = "rectangle",
          x = 128,
          y = 512,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tikifire",
          shape = "rectangle",
          x = 128,
          y = 128,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }		
		
      }
    }
  }
}
