return {
    CoinsPrefab =
    {
        [001] = "quagmire_coin1",
        [002] = "quagmire_coin2",
        [003] = "quagmire_coin3",
        [004] = "quagmire_coin4",
        [005] = "goldnugget",		
    },
    GoodsPrefab =
    {
--------------------------lavaarena_boarlord----------------------------------------------------		
		[001] = "spiderbattle",
        [002] = "houndbattle",
        [003] = "mermbattle",
		[004] = "knightbattle",	
        [005] = "boarbattle",		
        [006] = "lizardbattle",
-----------------------------lavaarena_spectator2---------------------------------		
		[007] = "meat",
        [008] = "fish",
        [009] = "carrot",
        [010] = "tfwp_fire_bomb",
		[011] = "quagmire_coin1",		
        [012] = "quagmire_coin2",
--------------------------lavaarena_spectator4---------------------------------------		
		[013] = "spidergland",
        [014] = "healingsalve",
        [015] = "bandage",
        [016] = "antidote",
		[017] = "reviver",		
        [018] = "goatmilk",
--------------------------lavaarena_spectator1---------------------------------------
		[019] = "lavaarena_armorlight",		
		[020] = "lavaarena_rechargerhat",
		[021] = "tfwp_healing_staff",
		[022] = "tfwp_lava_hammer",
		[023] = "lavaarena_healingflowerhat",
        [024] = "lavaarena_armorextraheavy",		
		
		[025] = "lavaarena_armorlightspeed",
		[026] = "lavaarena_feathercrownhat",
		[027] = "tfwp_infernal_staff",
		[028] = "tfwp_dragon_dart",
		[029] = "lavaarena_tiaraflowerpetalshat",
		[030] = "lavaarena_armor_hpextraheavy",
		
		[031] = "lavaarena_armormedium",
		[032] = "lavaarena_strongdamagerhat",
		[033] = "tfwp_control_book",
		[034] = "tfwp_spear_lance",
        [035] = "lavaarena_eyecirclethat",		
		[036] = "lavaarena_armor_hpdamager",
			
		[037] = "lavaarena_armormediumdamager",
		[038] = "lavaarena_lightdamagerhat",		
		[039] = "tfwp_lava_dart",
		[040] = "tfwp_spear_gung",	
		[041] = "lavaarena_crowndamagerhat",
		[042] = "lavaarena_armor_hprecharger",		

-----------------------------lavaarena_spectator3---------------------------------

		[043] = "bedroll_straw",
		[044] = "cutgrass",		
		[045] = "minerhat",
		[046] = "log",	
		[047] = "twigs",
		[048] = "rocks",	

-----------------------------lavaarena_spectator1--------------------------------

		[049] = "lavaarena_armormediumrecharger",
		[050] = "lavaarena_armorheavy",		
		[051] = "tfwp_summon_book",
		[052] = "tfwp_heavy_sword",	
		[053] = "lavaarena_healinggarlandhat",
		[054] = "lavaarena_armor_hppetmastery",	

-----------------------------goatkid forge--------------------------------

		[055] = "knightbattle",
		[056] = "boarbattle",		
		[057] = "lizardbattle",
		[058] = "bossboarbattle",	
		[059] = "rhinocebrosbattle",
		[060] = "swineclopsbattle",	
--------------------------gorge mum----------------------------------------
		[061] = "quagmire_crate_pot_hanger",
		[062] = "quagmire_crate_oven",		
		[063] = "quagmire_crate_grill_small",
		[064] = "plate_silver",	
		[065] = "bowl_silver",
		[066] = "quagmire_goatmilk",	
--------------------------trade 1--------------------------------------

		[067] = "quagmire_seedpacket_1",
		[068] = "quagmire_seedpacket_2",		
		[069] = "quagmire_seedpacket_4",
		[070] = "quagmire_seedpacket_5",	
		[071] = "quagmire_seedpacket_6",
		[072] = "quagmire_seedpacket_mix",	
--------------------------trade 2------------------------------------
		[073] = "quagmire_seedpacket_7",
		[074] = "quagmire_sapbucket",		
		[075] = "pot_syrup",
		[076] = "pot",	
		[077] = "casseroledish",
		[078] = "quagmire_crate_grill",		
		
----------------------pig elder----------------------------
		[079] = "wateringcan",
		[080] = "axe",		
		[081] = "shovel",
		[082] = "farm_hoe",	
		[083] = "fertilizer",
		[084] = "farm_plow_item",	
----------------------goatkid gorge-------------------
		[085] = "quagmire_key_park",
		[086] = "quagmire_salt_rack_item",		
		[087] = "fishingrod",
		[088] = "trap",	
		[089] = "birdtrap",
		[090] = "quagmire_slaughtertool",
		
----------------------merm trade 3-------------------
		[091] = "quagmire_seedpacket_3",
		[092] = "quagmire_coin1",		
		[093] = "quagmire_coin2",
		[094] = "quagmire_coin1",	
		[095] = "dubloon",
		[096] = "oinc",		
		
--"quagmire_seedpacket_3" 1
--"quagmire_pigeon" 3
--"quagmire_salt_rack_item" 8
--"fishingrod" 3
--"trap" 4
--"birdtrap" 5
--"quagmire_crabtrap"  1 moeda 3
--"quagmire_slaughtertool"  1 moeda 3





	
		
    }
}

--[[
    GoodsPrefab =
    {
		[001] = "livinglog",
        [002] = "nightmarefuel",
        [003] = "wathgrithrhat",
        [004] = "spear_wathgrithr",
		[005] = "honeycomb",		
        [006] = "firestaff",
        [007] = "transistor",
        [008] = "silk",
        [009] = "goldnugget",
        [010] = "cutreeds",
        [011] = "flint",
        [012] = "rocks",	
        [013] = "footballhat",
        [014] = "charcoal",
        [015] = "nitre",
        [016] = "dug_grass",
        [017] = "sapling",
        [018] = "houndstooth",
        [019] = "jellybean",
        [020] = "icestaff",		
        [021] = "royal_jelly",
        [022] = "honey",
        [023] = "trunk_summer",
        [024] = "trunk_winter",
        [025] = "trunk_cooked",
        [026] = "wetgoop",
        [027] = "butter",
        [028] = "goatmilk",
        [029] = "wormlight",
        [030] = "seeds",
        [031] = "seeds_cooked",
        [032] = "bonestew",
        [033] = "butterflymuffin",
        [034] = "carrot_seeds",
        [035] = "corn_seeds",
        [036] = "dragonfruit_seeds",
        [037] = "perogies",
        [038] = "powcake",
        [039] = "butterflywings",
        [040] = "batwing",
        [041] = "turkeydinner",
        [042] = "unagi",
        [043] = "glommerfuel",
        [044] = "wormlight_lesser",
        [045] = "tallbirdegg_cooked",
        [046] = "acorn_cooked",
        [047] = "petals",
        [048] = "rottenegg",
        [049] = "meatballs",
        [050] = "frogglebunwich",
        [051] = "pomegranate_seeds",
        [052] = "jammypreserves",
        [053] = "fruitmedley",
        [054] = "honeynuggets",
        [055] = "kabobs",
        [056] = "monsterlasagna",
        [057] = "lightbulb",
        [058] = "ratatouille",
        [059] = "stuffedeggplant",
        [060] = "taffy",
        [061] = "flowersalad",
        [062] = "eggplant_seeds",
        [063] = "watermelonicle",
        [064] = "pumpkin_seeds",
        [065] = "trailmix",
        [066] = "cutlichen",
        [067] = "petals_evil",
        [068] = "batwing_cooked",
        [069] = "plantmeat",
        [070] = "plantmeat_cooked",
        [071] = "foliage",
        [072] = "phlegm",
        [073] = "ice",
        [074] = "gunpowder",
        [075] = "featherhat",
        [076] = "trap_teeth",
        [077] = "beemine",
        [078] = "blowdart_fire",
        [079] = "blowdart_pipe",
        [080] = "blowdart_sleep",
        [081] = "blowdart_yellow",
        [082] = "boomerang",
        [083] = "manrabbit_tail",
		[084] = "spoiled_food",
        [085] = "durian_seeds",
        [086] = "pigskin",
        [087] = "watermelon_seeds",
        [088] = "eel",
        [089] = "eel_cooked",
        [090] = "dragonfruit",
        [091] = "mole",
        [092] = "dragonfruit_cooked",
        [093] = "meat",
        [094] = "cookedmeat",
        [095] = "meat_dried",
        [096] = "monstermeat",
        [097] = "cookedmonstermeat",
        [098] = "monstermeat_dried",
        [099] = "smallmeat",
        [100] = "cookedsmallmeat",
        [101] = "smallmeat_dried",
        [102] = "drumstick",
        [103] = "drumstick_cooked",
        [104] = "froglegs",
        [105] = "froglegs_cooked",
        [106] = "fish",
        [107] = "fish_cooked",
        [108] = "blue_cap",
        [109] = "blue_cap_cooked",
        [110] = "green_cap",
        [111] = "green_cap_cooked",
        [112] = "red_cap",
        [113] = "red_cap_cooked",
        [114] = "eggplant",
        [115] = "eggplant_cooked",
        [116] = "carrot",
        [117] = "carrot_cooked",
        [118] = "corn",
        [119] = "corn_cooked",
        [120] = "pumpkin",
        [121] = "pumpkin_cooked",
        [122] = "cactus_meat",
        [123] = "cactus_meat_cooked",
        [124] = "cactus_flower",
        [125] = "berries_juicy",
        [126] = "berries_juicy_cooked",
        [127] = "berries",
        [128] = "berries_cooked",
        [129] = "cave_banana",
        [130] = "cave_banana_cooked",
        [131] = "durian",
        [132] = "durian_cooked",
        [133] = "pomegranate",
        [134] = "pomegranate_cooked",
        [135] = "watermelon",
        [136] = "watermelon_cooked",
        [137] = "bird_egg",
        [138] = "bird_egg_cooked",
        [139] = "tallbirdegg",
 
    }
]]