local STRINGS = GLOBAL.STRINGS

-----------------------------Biome Jungle -----------------------------





-----------------------------Biome Tidal Mash---------------------------

GLOBAL.STRINGS.NAMES.TIGERSHARKPOOL = "Lago do Tubarão Tigre"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TIGERSHARKPOOL = "Há um tubarão estranho nesta lagoa."


GLOBAL.STRINGS.NAMES.LAVAPONDBIG = "Piscina de lava"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LAVAPONDBIG = "Um pouco quente para o meu gosto."

GLOBAL.STRINGS.NAMES.HARPOON = "Arpão"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.HARPOON = "Um arpão para jogar."



-----------------------------Biome Volcano------------------------------
GLOBAL.STRINGS.NAMES.DRAGOON = "Dragão"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DRAGOON = "Você é um cara rápido, não é??"

GLOBAL.STRINGS.NAMES.DRAGOONHEART = "Coração do dragão."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DRAGOONHEART = "Onde o dragão uma vez guardou seus sentimentos."

GLOBAL.STRINGS.NAMES.DRAGOONDEN = "Cabana do dragão"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DRAGOONDEN = "Até mesmo os tontos têm que dormir."

GLOBAL.STRINGS.NAMES.DRAGOONSPIT = "Saliva de dragão"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DRAGOONSPIT = "É essencialmente repugnante.!"

GLOBAL.STRINGS.NAMES.DRAGOONEGG = "Ovo de dragão"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DRAGOONEGG = "Eu ouço rachaduras?"

GLOBAL.STRINGS.NAMES.OBSIDIAN = "Obsidian"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OBSIDIAN = "É uma rocha de fogo."

GLOBAL.STRINGS.NAMES.BOOK_METEOR1 = "Alegria de Vulcanologia"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOOK_METEOR1 = "O prefácio apenas diz 'Espero que gostem de dragões.'"

GLOBAL.STRINGS.NAMES.OBSIDIAN_WORKBENCH = "Mesa de trabalho de obsidian"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OBSIDIAN_WORKBENCH = "Eu sinto-me inspirado."

GLOBAL.STRINGS.NAMES.OBSIDIANFIREPIT = "Fogueira de obsidian"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OBSIDIANFIREPIT = "Esta fogueira é um bom condutor de fogo."


GLOBAL.STRINGS.NAMES.ARMOROBSIDIAN = "Armadura de obsidian"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.ARMOROBSIDIAN = "Eu sou um gênio."

GLOBAL.STRINGS.NAMES.SPEAR_OBSIDIAN = "Lança de obsidian"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPEAR_OBSIDIAN = "Isso vai deixar uma marca."

--GLOBAL.STRINGS.NAMES.OBSIDIANMACHETE = "Obsidian Machete"
--GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OBSIDIANMACHETE = "It's hot to the touch."

GLOBAL.STRINGS.NAMES.AXEOBSIDIAN = "Machado de obsidian"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.AXEOBSIDIAN = "Uma combinação vencedora!"

GLOBAL.STRINGS.NAMES.ROCK_OBSIDIAN = "Rocha de Obsidian"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.ROCK_OBSIDIAN = "Exploda! Será quebrada!"

GLOBAL.STRINGS.NAMES.OBSIDIANBOMB = "Bomba de obsidian"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OBSIDIANBOMB = "É até bombardeiro!"

GLOBAL.STRINGS.NAMES.ROCK_CHARCOAL = "Rocha de carvão"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.ROCK_CHARCOAL = "Precisaria de uma meia muito grande ..."

GLOBAL.STRINGS.NAMES.MAGMAROCK = "Magma Pile"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MAGMAROCK_FULL = "Eu consigo cavar isso."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MAGMAROCK = "Eu consigo cavar isso."

GLOBAL.STRINGS.NAMES.MAGMAROCK_GOLD = "Rocha de magma"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MAGMAROCK_GOLD_FULL = "Eu vejo uma oportunidade dourada."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MAGMAROCK_GOLD = "Eu vejo uma oportunidade dourada."

GLOBAL.STRINGS.NAMES.FLAMEGEYSER = "Geiser de fogo"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FLAMEGEYSER = "Talvez eu devesse ficar para longe."

GLOBAL.STRINGS.NAMES.VOLCANO_SHRUB = "Árvore de cinzas queimada"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.VOLCANO_SHRUB = "Você parece pálida."

GLOBAL.STRINGS.NAMES.VOLCANO_EXIT = "Vulcão"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.VOLCANO_EXIT = "Eu posso sentir uma brisa fresca lá fora."

GLOBAL.STRINGS.NAMES.VULCANO_ENTRANCE = "Entrada do vulcão"
GLOBAL.STRINGS.NAMES.ESCADADOVULCAO = "Saida do vulcão"

GLOBAL.STRINGS.NAMES.VOLCANO = "Vulcão"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.VOLCANO = "Me parece seguro, bem..."

GLOBAL.STRINGS.NAMES.VOLCANOSTAFF = "Cajado do vulcão"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.VOLCANOSTAFF = "O rótulo diz: 'Mantenha-se fora ofreach de crianças'."

STRINGS.NAMES.LAVAPOOL = "Piscina de lava"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LAVAPOOL = "Um pouco quente para o meu gosto."

STRINGS.NAMES.DUG_ELEPHANTCACTUS = "Muda de Cacto Elefante"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_ELEPHANTCACTUS = "Uma usina de picada transplantada."
STRINGS.NAMES.ELEPHANTCACTUS = "Cacto Elefante"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ELEPHANTCACTUS = "Oh, eu posso usar isso para furar meus olhos!"
STRINGS.NAMES.ELEPHANTCACTUS_ACTIVE = "Cacto Elefante ativo"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ELEPHANTCACTUS_ACTIVE = "Os espinhos deste cacto são muito mais incomuns."
STRINGS.NAMES.ELEPHANTCACTUS_STUMP = "Toco do cacto do elefante"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ELEPHANTCACTUS_STUMP = "É muito antes que o Presidente vai estar fora."


STRINGS.TABS.OBSIDIANTAB = "Volcanic"
GLOBAL.STRINGS.RECIPE_DESC.DRAGOONDEN = "Entre no covil do dragão."
GLOBAL.STRINGS.RECIPE_DESC.OBSIDIANBOMB = "KA-BLAMMIER!"
GLOBAL.STRINGS.RECIPE_DESC.ARMOROBSIDIAN = "Quente quando toca."
GLOBAL.STRINGS.RECIPE_DESC.SPEAR_OBSIDIAN = "Como vou segurar isso com as mãos??"
GLOBAL.STRINGS.RECIPE_DESC.OBSIDIANFIREPIT = "A mais forte de todos as fogueiras!"
GLOBAL.STRINGS.RECIPE_DESC.OBSIDIANMACHETE = "Cortando, queimado!"
GLOBAL.STRINGS.RECIPE_DESC.AXEOBSIDIAN = "Como um machado regular só que mais quente."
--GLOBAL.STRINGS.RECIPE_DESC.COFFEE = "Hot Coffee!"
GLOBAL.STRINGS.RECIPE_DESC.BOOK_METEOR1 = "Meteoro do céu!"
GLOBAL.STRINGS.RECIPE_DESC.VOLCANOSTAFF = "O céu está caindo!"



--GLOBAL.STRINGS.UI.WORLDGEN.VOLCANOTITLE = "BOILING MAGMA"
--GLOBAL.STRINGS.NAMES.VOLCANO_ALTAR = "Volcano Altar of Snackrifice"
--GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.VOLCANO_ALTAR.GENERIC = "It appears to be closed."
--GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.VOLCANO_ALTAR.OPEN = "The altar is open and ready to accept offerings!"
--GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.VOLCANO_ALTAR_BROKEN = "Darn it!"
--GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.VOLCANO_ALTAR_TOWER = "How scary!"
--GLOBAL.STRINGS.CHARACTERS.GENERIC.ANNOUNCE_VOLCANO_ERUPT = "That can't be good."

GLOBAL.STRINGS.NAMES.COFFEEBUSH = "Arbusto de café"
GLOBAL.STRINGS.NAMES.DUG_COFFEEBUSH = "Planta de café"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_COFFEEBUSH = "Isto pertence à terra!"


GLOBAL.STRINGS.NAMES.COFFEEBEANS = "Sementes de café"
GLOBAL.STRINGS.NAMES.COFFEEBEANS_COOKED = "Sementes de café torradas"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.COFFEEBEANS = "Podem estar torradas."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.COFFEEBEANS_COOKED = "Calor definitivamente melhorou eles."

GLOBAL.STRINGS.NAMES.COFFEE = "Café"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.COFFEEBOT = "É uma cafeteira."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.COFFEE = "Simplesmente delicioso e energizante!"


--GLOBAL.STRINGS.SIGA = "Me siga"
GLOBAL.STRINGS.NAMES.WOODLEGS1 = "Woodlegs"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOODLEGS1 = "Este é o Woodlegs."

GLOBAL.STRINGS.NAMES.WOODLEGSGHOST = "Fantasma do Woodlegs"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOODLEGSGHOST = "Ele foi meu amigo."

GLOBAL.STRINGS.NAMES.WOODLEGS_KEY1 = "Chave de osso"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOODLEGS_KEY1 = "Algo em algum lugar deve estar trancado."

GLOBAL.STRINGS.NAMES.WOODLEGS_KEY2 = "Chave de ouro"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOODLEGS_KEY2 = "Essa chave deve servir para alguma coisa."

GLOBAL.STRINGS.NAMES.WOODLEGS_KEY3 = "Chave de osso"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOODLEGS_KEY3 = "Isso é uma chave."

GLOBAL.STRINGS.NAMES.WOODLEGS_CAGE = "Gaiola do Woodlegs"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOODLEGS_CAGE = "Isso parece ter uma quantidade excessiva de fechaduras."


GLOBAL.STRINGS.NAMES.SLIP = "Slip"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SLIP = "Um pequeno monstro peludo."

GLOBAL.STRINGS.NAMES.SLIPSTOR = "Slipstor"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SLIPSTOR = "É grande, peludo como um monstro."

GLOBAL.STRINGS.NAMES.SLIPSTOR_SPAWNER = "Slipstor Spawner"



GLOBAL.STRINGS.NAMES.TWISTER = "Sealnado"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TWISTER = "Eu pensei que era estranhamente ventilado por aqui."

GLOBAL.STRINGS.NAMES.TWISTER_SEAL = "Seal"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TWISTER_SEAL = "D'awww."

GLOBAL.STRINGS.NAMES.TWISTER_TORNADO = "Tornado"


GLOBAL.STRINGS.NAMES.MERMFISHER = "Merm Fisher"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MERMFISHER = "Parece-me uma boa pessoa, que dizer, peixe?."

GLOBAL.STRINGS.NAMES.FLUP = "Flup"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FLUP = "Deixe-me sozinho!"

GLOBAL.STRINGS.NAMES.TIDALPOOL = "Piscina das marés"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TIDALPOOL = "Uma piscina deixada pelas marés."

GLOBAL.STRINGS.NAMES.MERMFISHHOUSE = "Casa do Merm pescador"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MERMFISHHOUSE = "Hm... deve feder ai dentro"

GLOBAL.STRINGS.NAMES.POISONHOLE = "Buraco venenoso"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.POISONHOLE = "Eu acho que vou ficar longe disso."

GLOBAL.STRINGS.NAMES.TIGERSHARK = "Turbarão Tigre"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TIGERSHARK = "Bem que é aterrorizante, é..."

GLOBAL.STRINGS.NAMES.TIGERSHARKSHADOW = "Sombra do Turbarão Tigre"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TIGERSHARKSHADOW = "A sombra da besta!"

GLOBAL.STRINGS.NAMES.SNAKESKINFLOOR = "Chão de cobra"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SNAKESKINFLOOR = "Realmente amarra a sala."

GLOBAL.STRINGS.NAMES.TURF_MAGMAFIELD = "Chão de magma"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_MAGMAFIELD = "Chão de magma."

GLOBAL.STRINGS.NAMES.TURF_JUNGLE = "Chão da selva"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_JUNGLE = "Terreno muito retorcido."

GLOBAL.STRINGS.NAMES.TURF_ASH = "Chão de cinzas"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_ASH = "Chão de cinzas."

GLOBAL.STRINGS.NAMES.TURF_VOLCANO = "Chão de vulcão"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_VOLCANO = "Chão de vulcão."

GLOBAL.STRINGS.NAMES.TURF_TIDALMARSH = "Chão de pântano tropical"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_TIDALMARSH = "Chão de pântano."

GLOBAL.STRINGS.NAMES.TURF_LAVAROCK = "Chão de lava"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_LAVAROCK = "Chão de lava."

GLOBAL.STRINGS.NAMES.TURF_MEADOW = "Chão de Pradaria"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_MEADOW = "Chão de Pradaria."

GLOBAL.STRINGS.NAMES.SNAKE = "Snake"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SNAKE = "Eu me pergunto se ele vai me vender um pouco de óleo?"

GLOBAL.STRINGS.NAMES.SNAKE_POISON = "Cobra venenosa"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SNAKE_POISON = "Ainda pior do que uma cobra comum!"

GLOBAL.STRINGS.NAMES.SNAKESKIN = "Pele de cobra"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SNAKESKIN = "Estou intrigado e arrepiado."

GLOBAL.STRINGS.NAMES.SNAKE_HOLE = "Ninho de cobra"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SNAKE_HOLE = "Não deve ser tão bom lá dentro.."

GLOBAL.STRINGS.NAMES.SNAKEOIL = "Oléo de cobra"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SNAKEOIL = "No rótulo dizia'Jay's, oléo maravilhoso de cobra!"


GLOBAL.STRINGS.NAMES.LIVINGJUNGLETREE = "Arvore da selva viva."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LIVINGJUNGLETREE = "Assim como qualquer outra árvore."

--jungle tree
GLOBAL.STRINGS.NAMES.JUNGLETREE = "Árvore da selva"
GLOBAL.STRINGS.NAMES.TREE_JUNGLE = "Árvore da selva"

GLOBAL.STRINGS.NAMES.JUNGLETREESEED = "Semente de árvore da selva."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.JUNGLETREESEED = "Eu posso ouvir o assobio de pequenas serpentes."

GLOBAL.STRINGS.NAMES.JUNGLE_TREE_SAPLING = "Um pé de árvore da selva."

--bamboo
GLOBAL.STRINGS.NAMES.BAMBOO = "Bambu"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BAMBOO = "Talvez eu possa enganar meus inimigos com isso?"

GLOBAL.STRINGS.NAMES.BAMBOOTREE = "Bamboo Patch"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BAMBOOTREE = {
	GENERIC = "Parece muito robusto.",
	BURNING = "Adeus, bambu.",
	BURNT = "Eu sinto como se eu pudesse ter evitado isso.",
	CHOPPED = "Toma essa natureza!"
}

GLOBAL.STRINGS.NAMES.DUG_BAMBOOTREE = "Bamboo Raiz"
GLOBAL.STRINGS.RECIPE_DESC.DUG_BAMBOOTREE = "Cresça árvore de bambu"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_BAMBOOTREE = "Eu preciso plantar isso."

GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DEPLETED_BAMBOOTREE = "Será que vai crescer novamente?"



GLOBAL.STRINGS.NAMES.DOYDOYBABY = "Bebê Doydoy"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOYDOYBABY = "Que coisinha fofa...."

GLOBAL.STRINGS.NAMES.DOYDOYTEEN = "Teen Doydoy"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOYDOYTEEN = "Cresça! !"

GLOBAL.STRINGS.NAMES.DOYDOY = "Doydoy"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOYDOY = "Eu me sinto estranhamente protetora deste pássaro."

GLOBAL.STRINGS.NAMES.DOYDOYEGG = "Ovo de Doydoy."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOYDOYEGG = "Talvez eu devesse ter deixado ele chocar."

GLOBAL.STRINGS.NAMES.DOYDOYEGG_COOKED = "Ovo Doydoy frito"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOYDOYEGG_COOKED = "Uma reação química controlada tornou esta matéria de ovo mais nutritiva."

GLOBAL.STRINGS.NAMES.DOYDOYEGG_CRACKED = "Ovo rachado do Doydoy."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOYDOYEGG_CRACKED = "Oh, bem. Tenho certeza que há muito mais!"

GLOBAL.STRINGS.NAMES.DOYDOYFEATHER = "Doydoy Feather"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOYDOYFEATHER = "Macia e ameaçada!"

GLOBAL.STRINGS.NAMES.DOYDOYNEST = "Doydoy Nest"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOYDOYNEST = "Isto é para ovos de doydoy, idiota."

GLOBAL.STRINGS.RECIPE_DESC.DOYDOYNEST = "Apenas faça."
GLOBAL.STRINGS.RECIPE_DESC.DOYDOYEGG = "Você pode chocar seu próprio doydoy!"

--wildborehouse
GLOBAL.STRINGS.NAMES.WILDBOREHOUSE = "Wildbore House"
GLOBAL.STRINGS.RECIPE_DESC.WILDBOREHOUSE = "Pig out!"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WILDBOREHOUSE = "Que casa chata."

--wildbore head
GLOBAL.STRINGS.NAMES.WILDBOREHEAD = "Wildbore Head"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WILDBOREHEAD = "Cheira tão mal quanto parece."
--wildbore 

GLOBAL.STRINGS.NAMES.WILDBORE = "Wildbore"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WILDBORE = "Eu não sou louco por isso."

--wildbore guard
GLOBAL.STRINGS.NAMES.WILDBOREGUARD = "Wildbore Guard"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WILDBOREGUARD = "O que ele está protegendo??"






GLOBAL.STRINGS.NAMES.BEAVERKING_SPAWNER = "Beaverking Spawner"

GLOBAL.STRINGS.NAMES.WILDBEAVERGUARD = "Wildbeaver Guard"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WILDBEAVERGUARD = "He looks serious"

GLOBAL.STRINGS.NAMES.BEAVER_HEAD = "Beaver head"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BEAVER_HEAD = "Someone should tell his family."

GLOBAL.STRINGS.NAMES.BEAVERTORCH = "Beaver Torch"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BEAVERTORCH = "Sure looks cozy."

GLOBAL.STRINGS.NAMES.BEAVERSKIN = "Beaver Skin"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BEAVERSKIN = "The hide of a beaver creature"

GLOBAL.STRINGS.WILDBEAVER_NAMES = {
	"Castor",
}

GLOBAL.STRINGS.NAMES.BEAVER_KING = "Rei Castor"

GLOBAL.STRINGS.WILDBEAVER_TALK_FIGHT = {
	"VOU TE MORDER!",
	"VA EMBORA!",
	"VOLTEI PARA LUTAR!",
}
GLOBAL.STRINGS.WILDBEAVER_TALK_FOLLOW = {
	"VOCÊ ME ENTENDE",
	"VAMOS CONSTRUIR UMA BARRAGEM",
	"NÓS PRECISAMOS DE MAIS MADEIRA",
}
GLOBAL.STRINGS.WILDBEAVER_TALK_GOHOME = {
	"VOU TERMINAR A BARRAGEM AMANHÃ",
	"HORA DE DORMIR",
	"VEJO VOCÊ MAIS TARDE",
}

GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WILDBEAVER = "Qual o nome disso...?!"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WILDBEAVER_HOUSE = "Onde o Castor mora."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BEAVER_KING = "Este deve governar todos eles."


GLOBAL.STRINGS.CHARACTERS.WILLOW.DESCRIBE.WILDBEAVER = "Você pega madeira, eu queimo: parece bom?"
GLOBAL.STRINGS.CHARACTERS.WILLOW.DESCRIBE.WILDBEAVER_HOUSE = "Ttodo mundo tem um lugar melhor que o meu..."
GLOBAL.STRINGS.CHARACTERS.WILLOW.DESCRIBE.BEAVER_KING = "Um grande para governar todos eles, suponho."

GLOBAL.STRINGS.CHARACTERS.WENDY.DESCRIBE.WILDBEAVER = "Posso montar em suas costas? Por favor, por favor"
GLOBAL.STRINGS.CHARACTERS.WENDY.DESCRIBE.WILDBEAVER_HOUSE = "Quando a represa se rompe, a inundação consome tudo."
GLOBAL.STRINGS.CHARACTERS.WENDY.DESCRIBE.BEAVER_KING = "Rei das represas."

GLOBAL.STRINGS.CHARACTERS.WX78.DESCRIBE.WILDBEAVER = "ELE COME MADEIRA."
GLOBAL.STRINGS.CHARACTERS.WX78.DESCRIBE.WILDBEAVER_HOUSE = "A MORADA DE UM COMEDOR DE MADEIRA."
GLOBAL.STRINGS.CHARACTERS.WX78.DESCRIBE.BEAVER_KING = "O REI DOS COMEDORES DE MADEIRA."

GLOBAL.STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WILDBEAVER = "Um primo perdido dO Castor canadense?"
GLOBAL.STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WILDBEAVER_HOUSE = "Deve ser para eles o equivalente a uma represa."
GLOBAL.STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BEAVER_KING = "Um rei para governar todos eles e para coordená-los na construção de barragens..."

GLOBAL.STRINGS.CHARACTERS.WOODIE.DESCRIBE.WILDBEAVER = "Ho, bonito. Não somos parentes?"
GLOBAL.STRINGS.CHARACTERS.WOODIE.DESCRIBE.WILDBEAVER_HOUSE = "O único imóvel em que investiria."
GLOBAL.STRINGS.CHARACTERS.WOODIE.DESCRIBE.BEAVER_KING = "Indo bem, né?"

GLOBAL.STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.WILDBEAVER = "Grandes dentuços?"
GLOBAL.STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.WILDBEAVER_HOUSE = "Os dentuços vivem aqui."
GLOBAL.STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.BEAVER_KING = "O maior de todos os dentuços!"

GLOBAL.STRINGS.CHARACTERS.WEBBER.DESCRIBE.WILDBEAVER = "WOODIE é você?"
GLOBAL.STRINGS.CHARACTERS.WEBBER.DESCRIBE.WILDBEAVER_HOUSE = "É aqui que esses criaturas vivem."
GLOBAL.STRINGS.CHARACTERS.WEBBER.DESCRIBE.BEAVER_KING = "Todos saudam o rei madeira primeiro!"

GLOBAL.STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.WILDBEAVER = "Vamos fazer uma batalha?"
GLOBAL.STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.WILDBEAVER_HOUSE = "A morada daqueles Castores selvagens."
GLOBAL.STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.BEAVER_KING = "Como você pode suportar esta ociosidade?"
GLOBAL.STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WILDBEAVER = "Outro tipo de idiotas da aldeia."
GLOBAL.STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WILDBEAVER_HOUSE = "Então eles vivem aqui."
GLOBAL.STRINGS.CHARACTERS.WAXWELL.DESCRIBE.BEAVER_KING = "Você é o supervisor deles ou o quê?"
GLOBAL.STRINGS.RECIPE_DESC.WILDBEAVER_HOUSE = "Beaver out!"
GLOBAL.STRINGS.NAMES.DOUBLE_UMBRELLAHAT = "Dumbrella"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOUBLE_UMBRELLAHAT = "Função definitivamente sobre a forma."
GLOBAL.STRINGS.NAMES.WILDBEAVER_HOUSE = "Beaver House"
STRINGS.NAMES.VENOMGLAND = "Glândula de veneno"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.VENOMGLAND = "Somente veneno, cura veneno."

STRINGS.NAMES.BERRYBUSH2_SNAKE = "Arbusto de berries"

STRINGS.NAMES.OCTOPUSKING = "Yaarctopus"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.OCTOPUSKING = "Sou um palerma para este tipo de ser."

STRINGS.NAMES.SWEET_POTATO_PLANTED = "Batata doçe"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SWEET_POTATO_PLANTED = "Que cenoura estranha."

STRINGS.NAMES.SWEET_POTATO = "Batata doçe"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SWEET_POTATO = "Parece Inhame!"

STRINGS.NAMES.SWEET_POTATO_COOKED = "Batata doçe"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SWEET_POTATO_COOKED = "Parece até Inhame!!"

STRINGS.NAMES.PARROT_PIRATE = "Papagaio Pirata"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PARROT_PIRATE = "Tento não comer nada com um nome."

STRINGS.NAMES.PARROT = "Papagaio"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PARROT = "Tento não comer nada com um nome."

STRINGS.NAMES.DUBLOON = "Moedas"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUBLOON = "Estou rico!"

STRINGS.NAMES.DOYDOYFAN = "Pena Tropical"
STRINGS.RECIPE_DESC.DOYDOYFAN = "Luxuosamente macia, luxuosamente tropical"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOYDOYFAN = "De alguma forma a brisa sai pelas costas duas vezes mais rápido."

STRINGS.NAMES.FABRIC = "Pano"
STRINGS.RECIPE_DESC.FABRIC = "O bambu é tão versátil!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FABRIC = "Pano macio feito de raízes duras!"

STRINGS.NAMES.SNAKESKINHAT = "Chapéu de pele de cobra"
STRINGS.RECIPE_DESC.SNAKESKINHAT = "Mantenha a chuva fora, e olhar fresco." 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SNAKESKINHAT = "Deve repelir a chuva do meu cabelo."

STRINGS.NAMES.ARMOR_SNAKESKIN = "Jaqueta de cobra"
STRINGS.RECIPE_DESC.ARMOR_SNAKESKIN = "Fique seco e de couro."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ARMOR_SNAKESKIN = "Muito elegante!"

STRINGS.NAMES.TURF_SNAKESKINFLOOR = "Chão de pele de cobra"
STRINGS.RECIPE_DESC.TURF_SNAKESKINFLOOR = "Realmente amarra toda a sala."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_SNAKESKINFLOOR = "Dddddddeclaração Eddddelegante."

--STRINGS.NAMES.TURF_WATER_MANGROVE = "红树林地皮"
--STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_WATER_MANGROVE = "红树林地皮"

STRINGS.NAMES.TURF_BEACH = "Chão de praia"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_BEACH = "Chão arenoso."

STRINGS.NAMES.COCONUT = "Coco"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.COCONUT = "Requer um bom machete."

STRINGS.NAMES.COCONUT_HALVED = "Coco partido"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.COCONUT_HALVED = "Quando eu bato osdois, eles fazem sons de cavalo."

STRINGS.NAMES.COCONUT_COOKED = "Coco assado"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.COCONUT_COOKED = "Agora só preciso de um bolo."

STRINGS.NAMES.PALMTREE = "Coqueiro"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PALMTREE = "Que tropical."

STRINGS.NAMES.PALMLEAF = "Folha de coqueiro"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PALMLEAF = "Meu cabelo parece bem molhado... é quando seca esse é o problema."

STRINGS.NAMES.ROCK_LIMPET = "Rocha lapa"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ROCK_LIMPET = "Eu poderia encher um balde com todos aqueles caracóis!"

STRINGS.NAMES.LIMPETS = "Lapa"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LIMPETS = "Talvez morrer de fome não seja tão ruim."

STRINGS.NAMES.LIMPETS_COOKED = "Lapa assada"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LIMPETS_COOKED = "Escargot!"

STRINGS.NAMES.PALMLEAF_HUT = "Cabana de folha de coqueiro"
STRINGS.RECIPE_DESC.PALMLEAF_HUT = "Escapar da chuva. Principalmente."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PALMLEAF_HUT = "Sombra, doce sombra."

STRINGS.NAMES.SAND_CASTLE = "Castelo de areia"
STRINGS.RECIPE_DESC.SAND_CASTLE = "Terapêutico e relaxante."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SAND_CASTLE = "Olha o que eu fiz!"

STRINGS.NAMES.SANDHILL = "Monte de areia"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SANDHILL = "É melhor ficar longe dos meus sapatos."

STRINGS.NAMES.SAND = "Areia"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SAND = "Uma pilha acessível da areia de bolso."

STRINGS.NAMES.SEASHELL_BEACHED = "Conchas"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEASHELL_BEACHED = "Lixo marinho."

STRINGS.NAMES.SEASHELL = "Conchas"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEASHELL = "Talvez eu possa vendê-los."

STRINGS.NAMES.CRATE = "Caixa"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CRATE = "Deve haver uma maneira de abri-lo."

STRINGS.NAMES.CRAB = "Siri"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CRAB = "Não fique mal-humorado comigo, senhor."

STRINGS.NAMES.CRABHOLE = "Buraco de Siri"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CRABHOLE = "Eles chamam um buraco na areia de sua casa."

STRINGS.NAMES.CRAB_HIDDEN = "Siri camuflado"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CRAB_HIDDEN = "Onde será que siri foi?"

STRINGS.NAMES.SEAGULL = "Gaivota"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEAGULL = "Shoo! Encontrem outra terra!"

STRINGS.NAMES.SEAGULLWATER = "Gaivota"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEAGULLWATER = "Shoo! Encontrem outra terra!"

STRINGS.NAMES.FISH_MEAT_SMALL = "Petisco de peixe"

STRINGS.NAMES.TROPICAL_FISH = "Peixe tropical"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TROPICAL_FISH = "Que peixe mais tropical."

STRINGS.NAMES.TUNACAN = "Lata de sardinha"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TUNACAN = "De onde é que isto está vindo?"

STRINGS.NAMES.TOUCAN = "Tucano"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TOUCAN = "Não consigo pegá-lo."

STRINGS.NAMES.RAFT = "Barco de bambu"
STRINGS.RECIPE_DESC.RAFT = "Totalmente tipo de embarcação"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAFT = "Isto parece adequado."

STRINGS.NAMES.SLOTMACHINE = "Máquina de caça-níqueis"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SLOTMACHINE = "Acho que posso ficar por um momento ou dois."

STRINGS.NAMES.VINE = "Vinhas"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.VINE = "Talvez eu possa amarrar as coisas com isso."

STRINGS.NAMES.BUSH_VINE = "Arbusto de vinhas."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BUSH_VINE = "É tudo videira!!"

STRINGS.NAMES.DUG_BUSH_VINE = "Arbusto de vinha cortado"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_BUSH_VINE = "Acho que devo ir buscá-lo."

STRINGS.NAMES.MACHETE = "Machete"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MACHETE = "Gosto do corte desta lâmina."
STRINGS.RECIPE_DESC.MACHETE = "Cortador de coisas!"

STRINGS.NAMES.GOLDENMACHETE = "Machete de ouro"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GOLDENMACHETE = "Cortando com estilo."
STRINGS.RECIPE_DESC.GOLDENMACHETE = "Cortador de coisas com ESTILO!"

STRINGS.NAMES.OBSIDIANMACHETE = "Machete de obsidian"
STRINGS.RECIPE_DESC.OBSIDIANMACHETE = "Cortador quente!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.OBSIDIANMACHETE = "Está quente para cortar."

STRINGS.PULAFORA = "Muito raso para navegar!"
STRINGS.SEMBARCO = "Vou morrer sem um barco!"

STRINGS.NAMES.CORMORANT = "Cormorão"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CORMORANT = "Aposto que comeu muitos peixes."

STRINGS.NAMES.SEAWEED = "Algas"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEAWEED = "Uma erva daninha. Do mar..."

STRINGS.NAMES.SEAWEED_COOKED = "Algas assada"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.COOKED = "Char grelhado à perfeição."

STRINGS.NAMES.SEAWEED_DRIED = "Algas seca"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEAWEED_DRIED = "Salgado!"

STRINGS.NAMES.SEAWEED_PLANTED = "Algas"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEAWEED_PLANTED = "É isso que é comida por aqui?"

STRINGS.NAMES.CORAL = "Coral"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CORAL = "Material de construção vivo!"

STRINGS.NAMES.CORALREEF = "Recife de corais"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CORALREEF = "O coral formou um recife!"

STRINGS.NAMES.FISHINHOLE = "Cardume"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISHINHOLE = "Esta área parece muito boa para pescar."

GLOBAL.STRINGS.NAMES.GRASS_WATER = "Grama aquática"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.GRASS_WATER = "Até aqui elas aparecem?!"

GLOBAL.STRINGS.NAMES.TREE_MANGROVE = "Árvore do mangue"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TREE_MANGROVE = "Bem adaptadas."

GLOBAL.STRINGS.NAMES.ANTIDOTE = "Anti veneno"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.ANTIDOTE = "Isso vai me ajudar."
GLOBAL.STRINGS.RECIPE_DESC.ANTIDOTE = "Cura para o veneno"

GLOBAL.STRINGS.NAMES.QUAGMIRE_SALMON = "Salmão"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.QUAGMIRE_SALMON = "Hm... deve ser bom"

GLOBAL.STRINGS.NAMES.QUAGMIRE_POND_SALT = "Lagoa de sal"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.QUAGMIRE_POND_SALT = "Agora vou poder salgar minhas comidas."

GLOBAL.STRINGS.NAMES.QUAGMIRE_SWAMPIG = "Porco do Pântano"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.QUAGMIRE_SWAMPIG = "Porco do Pântano."

GLOBAL.STRINGS.NAMES.QUAGMIRE_SWAMPIG_HOUSE = "Casa de porco"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.QUAGMIRE_SWAMPIG_HOUSE = "Eles já foram melhores."

GLOBAL.STRINGS.NAMES.QUAGMIRE_SWAMPIG_HOUSE_RUBBLE = "Casa de porco"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.QUAGMIRE_SWAMPIG_HOUSE_RUBBLE = "Eles já foram melhores."

GLOBAL.STRINGS.NAMES.CROCODOG = "Crocodilo"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CROCODOG = "A mordida deve doer."

GLOBAL.STRINGS.NAMES.WATERCROCODOG = "Crocodilo aquático"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WATERCROCODOG = "Ele deve ser mais forte na água."

GLOBAL.STRINGS.NAMES.POISONCROCODOG = "Crocodilo venenoso."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.POISONCROCODOG = "Longe de mim, por favor!"

GLOBAL.STRINGS.NAMES.GRASSWATER = "Grama aquática."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.GRASSWATER = "Até aqui elas aparecem?!"

GLOBAL.STRINGS.NAMES.ARMOR_SEASHELL = "Armor Seashell"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.ARMOR_SEASHELL = "Sinto-me que pertenço ao mar."
GLOBAL.STRINGS.RECIPE_DESC.ARMOR_SEASHELL = "Proteção a mais."

GLOBAL.STRINGS.NAMES.OXHAT = "Chapéu de Ox"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OXHAT = "Bem estiloso."
GLOBAL.STRINGS.RECIPE_DESC.OXHAT = "Proteção extra."

GLOBAL.STRINGS.NAMES.CHIMINEA = "Chaminé"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CHIMINEA = "Chuva, adeus."
GLOBAL.STRINGS.RECIPE_DESC.CHIMINEA = "Protege da chuva."

GLOBAL.STRINGS.NAMES.OX_HORN = "Chifre de Ox"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OX_HORN = "Bem triste."

GLOBAL.STRINGS.NAMES.OX = "Beefalo aquático"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OX = "Eles gostam de água."

GLOBAL.STRINGS.NAMES.ROWBOAT = "Barco"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.ROWBOAT = "Agora minha aventura está completa."
GLOBAL.STRINGS.RECIPE_DESC.ROWBOAT = "Um barco mais resistente"

GLOBAL.STRINGS.NAMES.ENCRUSTEDBOAT = "Barco de coral"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.ENCRUSTEDBOAT = "Bem resistente."
GLOBAL.STRINGS.RECIPE_DESC.ENCRUSTEDBOAT = "Altamente resistente"

GLOBAL.STRINGS.NAMES.TURF_QUAGMIRE_PARKFIELD = "Chão rosado"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_QUAGMIRE_PARKFIELD = "Bem estiloso."

GLOBAL.STRINGS.NAMES.COTTONTREE = "Árvore de algodão"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.COTTONTREE = "Bem macio."

GLOBAL.STRINGS.NAMES.COTTONTREE_SAPLING = "Muda de Árvore de algodão"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.COTTONTREE_SAPLING = "Agora posso coloca-las em qualquer lugar."

GLOBAL.STRINGS.NAMES.COTTONTREE_CONE = "Semente da árvore de algodão"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.COTTONTREE_CONE = "Sementes?"

GLOBAL.STRINGS.NAMES.BALLPHINHOUSE = "Casa de golfinho"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BALLPHINHOUSE = "Deve ser bem divertido lá dentro."

GLOBAL.STRINGS.NAMES.BALLPHIN = "Golfinho"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BALLPHIN = "Como ele é bonitinho."

GLOBAL.STRINGS.NAMES.JELLYFISH = "Àgua viva"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.JELLYFISH = "Deve queimar."

GLOBAL.STRINGS.NAMES.JELLYFISH_DEAD = "Àgua viva morta"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.JELLYFISH_DEAD = "Ainda queima."

GLOBAL.STRINGS.NAMES.JELLYFISH_COOKED = "Àgua viva assada"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.JELLYFISH_COOKED = "E não é que elas são saborosas."

GLOBAL.STRINGS.NAMES.JELLYJERKY = "Àgua viva seca"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.JELLYJERKY = "Sem substâncias que queimam."

GLOBAL.STRINGS.NAMES.JELLYFISH_PLANTED = "Àgua viva plantada"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.JELLYFISH_PLANTED = "Como é que é?"

GLOBAL.STRINGS.NAMES.LOGRAFT = "Barco de Madeira"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LOGRAFT = "Barco de Madeira."
GLOBAL.STRINGS.RECIPE_DESC.LOGRAFT = "Isto parece... um tipo barco, como uma..."

GLOBAL.STRINGS.NAMES.FROG_POISON = "Sapo Venenoso"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FROG_POISON = "Parece pior do que o normal."

GLOBAL.STRINGS.NAMES.SHARKITTENSPAWNER = "Casa de Sharkitten"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHARKITTENSPAWNER = "Onde está a mãe deles?!"

GLOBAL.STRINGS.NAMES.WHALE_BLUE = "Baleia azul"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WHALE_BLUE = "Aquela baleia tem problemas emocionais."

GLOBAL.STRINGS.NAMES.WHALE_WHITE = "Baleia branca"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WHALE_WHITE = "Parece um lutador."

GLOBAL.STRINGS.NAMES.WHALE_CARCASS_WHITE = "Carcaça da baleia branca"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WHALE_CARCASS_WHITE = "Bruto. Acho que o inchaço começou."

GLOBAL.STRINGS.NAMES.WHALE_CARCASS_BLUE = "Carcaça da baleia azul"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WHALE_CARCASS_BLUE = "Bruto. Acho que o inchaço começou."

GLOBAL.STRINGS.NAMES.LOBSTER_DEAD_COOKED = "Lagosta morta cozida"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LOBSTER_DEAD_COOKED = "Uma delícia."

GLOBAL.STRINGS.NAMES.LOBSTER_DEAD = "Lagosta morta"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LOBSTER_DEAD = "Você deve cozinhar bem."

GLOBAL.STRINGS.NAMES.FISH_RAW_SMALL_COOKED = "Peixe cru cozido"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH_RAW_SMALL_COOKED = "Um pequeno pedaço de peixe cozido."

GLOBAL.STRINGS.NAMES.FISH_RAW_SMALL = "Peixe crus pequeno"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH_RAW_SMALL = "Um pequeno pedaço de peixe."

GLOBAL.STRINGS.NAMES.FISH_MED_COOKED = "Peixe médio cozido"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH_MED_COOKED = "Grelhado à perfeição."

GLOBAL.STRINGS.NAMES.FISH_MED = "Peixe cão"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH_MED = "Peixe cão morto, coitado."

GLOBAL.STRINGS.NAMES.SPOILED_FISH = "Pexei podre"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPOILED_FISH = "Não estou muito curioso(a) sobre o cheiro."

GLOBAL.STRINGS.NAMES.FISH_RAW = "Peixe cru"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH_RAW = "Um pedaço de carne de peixe."

GLOBAL.STRINGS.NAMES.DEAD_SWORDFISH = "Peixe espada morto"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DEAD_SWORDFISH = "É melhor eu não correr com isso."

GLOBAL.STRINGS.NAMES.BLUBBER = "Gordura"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BLUBBER = "Gelatinoso."

GLOBAL.STRINGS.NAMES.KNIGHTBOAT_CANNONSHOT = "Guerreiro aquático do canhão"

GLOBAL.STRINGS.NAMES.KNIGHTBOAT = "Cavaleiro flutuante do barco"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.KNIGHTBOAT = "Saia do canal, seu maníaco!"

GLOBAL.STRINGS.NAMES.OCTOPUSCHEST = "Baú do Octopus"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OCTOPUSCHEST = "Espero que essa coisa seja à prova de água."

GLOBAL.STRINGS.NAMES.KRAKEN = "Quacken"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.KRAKEN = "Agora não é o momento para eu ser um charlatão sábio!"

GLOBAL.STRINGS.NAMES.KRAKENCHEST = "Baú do Quacken"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.KRAKENCHEST = "Ao vencedor, os despojos."

GLOBAL.STRINGS.NAMES.KRAKEN_TENTACLE = "Tentáculo do Quacken"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.KRAKEN_TENTACLE = "Uma fera que nunca dorme."

GLOBAL.STRINGS.NAMES.SOLOFISH = "Peixe cão"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SOLOFISH = "Tem aquele cheiro de cachorro molhado."

GLOBAL.STRINGS.NAMES.SWORDFISH = "Peixe espada"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SWORDFISH = "Acho que este peixe evoluiu para me fazer passar."

GLOBAL.STRINGS.NAMES.LOBSTER_LAND= "Lagosta"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LOBSTER_LAND= "Aquela lagosta está dormindo."

GLOBAL.STRINGS.NAMES.SHARX = "Sharx"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHARX = "Estas coisas são mesmo persistentes."

GLOBAL.STRINGS.NAMES.STUNGRAY = "Arraia venenosa"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.STUNGRAY = "Acho que vou manter distância."

GLOBAL.STRINGS.NAMES.LUGGAGECHEST = "Mala flutuante"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LUGGAGECHEST = "Parece um baú de viajante."

GLOBAL.STRINGS.NAMES.REDBARREL = "Barril de pólvora"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.REDBARREL = "Tão original..."

GLOBAL.STRINGS.NAMES.LOBSTERHOLE = "Toca de lagosta"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LOBSTERHOLE = "Aquela lagosta está dormindo."

GLOBAL.STRINGS.NAMES.DEBRIS_1 = "Detritos"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DEBRIS_1 = "Havia alguém aqui antes de mim!"

GLOBAL.STRINGS.NAMES.DEBRIS_2 = "Detritos"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DEBRIS_2 = "Havia alguém aqui antes de mim!"

GLOBAL.STRINGS.NAMES.DEBRIS_3 = "Detritos"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DEBRIS_3 = "Havia alguém aqui antes de mim!"

GLOBAL.STRINGS.NAMES.DEBRIS_4 = "Detritos"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DEBRIS_4 = "Havia alguém aqui antes de mim!"

GLOBAL.STRINGS.NAMES.BOATREPAIRKIT = "Kit de reparo de barco"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOATREPAIRKIT = "Finalmente, vou poder arrumar meu barco."
GLOBAL.STRINGS.RECIPE_DESC.BOATREPAIRKIT = "Mantenha-se flutuando naquele barco!"

GLOBAL.STRINGS.NAMES.WRECK = "Barco naugragado"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WRECK = "Pobre pequeno barco."

GLOBAL.STRINGS.NAMES.PIRATEGHOST = "Pirata Fantasma"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PIRATEGHOST = "Ele encontrou um fim terrível. Eu também vou se eu não sair daqui."

GLOBAL.STRINGS.NAMES.GRAMANOVA = "Grama"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.GRASSWATER = "Multi usos!"

GLOBAL.STRINGS.NAMES.WRECKOF = "Naufrágio do %s"
GLOBAL.STRINGS.NAMES.SHIPNAMES =
{"Nautilus",
"Mackay-Bennett",
"Mary Celeste",
"Beagle",
"Santa Maria",
"Bluenose",
"Mauretania",
"Endeavour",
"Edmund Fitzgerald",
"Pequod",
"Mississinewa",
"African Queen",
"Mont-Blanc",
"Caine",
 "Pharaoh",
 "Minnow",
 "Syracusia",
 "Baron of Renfrew",
 "Ariel",
 "Hispaniola",}

GLOBAL.STRINGS.NAMES.MUSSEL_STICK = "Vara do mexilhão"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSSEL_STICK = "Vou mesmo ficar com os mexilhões."
GLOBAL.STRINGS.RECIPE_DESC.MUSSEL_STICK = "Vara do mexilhão."

GLOBAL.STRINGS.NAMES.MUSSEL_FARM = "Fazenda de mexilhão"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSSEL_FARM = "Pergunto-me se são de Bruxelas."

GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSSEL_FARM = "Pergunto-me se são de Bruxelas."
GLOBAL.STRINGS.NAMES.MUSSEL_FARM = "Fazenda de mexilhão"

GLOBAL.STRINGS.NAMES.MUSSEL_COOKED = "Mexilhão assado"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSSEL_COOKED = "Eu cozinho um mexilhão malvado."

GLOBAL.STRINGS.NAMES.MUSSEL = "Mexilhão"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSSEL = "Eu me pergunto se eles são de Bruxelas."

GLOBAL.STRINGS.NAMES.MOSQUITO_POISON = "Mosquito venenoso"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOSQUITO_POISON = "Estes malditos mosquitos carregam uma terrível doença."

GLOBAL.STRINGS.NAMES.WATERYGRAVE= "Sepultura aquosa"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WATERYGRAVE = "Claro, eu poderia pescá-lo de lá. Mas eu deveria?"

GLOBAL.STRINGS.NAMES.BIOLUMINESCENCE= "Bioluminescência"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BIOLUMINESCENCE = "Estes fazem um brilho calmante."

GLOBAL.STRINGS.NAMES.BOTTLELANTERN= "Lanterna de frasco"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOTTLELANTERN = "Uma garrafa cheia de seres."
GLOBAL.STRINGS.RECIPE_DESC.BOTTLELANTERN = "Seres oceânicos incandescente em uma garrafa."

GLOBAL.STRINGS.NAMES.MESSAGEBOTTLEEMPTY1= "Frasco vazio"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MESSAGEBOTTLEEMPTY1 = "Apenas uma garrafa vazia"
GLOBAL.STRINGS.RECIPE_DESC.MESSAGEBOTTLEEMPTY1 = "Não se esqueça de reciclar!"

GLOBAL.STRINGS.NAMES.ARMOUREDBOAT = "Barco reforçado"
GLOBAL.STRINGS.RECIPE_DESC.ARMOUREDBOAT = "Reforço direto do mar!"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.ARMOUREDBOAT = "Esse é um barco durável."

GLOBAL.STRINGS.NAMES.CARGOBOAT = "Barco cargueiro"
GLOBAL.STRINGS.RECIPE_DESC.CARGOBOAT = "Acumulando espaço no mar!"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CARGOBOAT = "Tem espaço para todas as minhas coisas!"

GLOBAL.STRINGS.NAMES.CORAL_BRAIN = "Coral cérebro "
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CORAL_BRAIN = "Motivo de reflexão."

GLOBAL.STRINGS.NAMES.CORAL_BRAIN_ROCK = "Coral cérebro"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CORAL_BRAIN_ROCK = "Eu me pergunto o que está tramando..."

GLOBAL.STRINGS.NAMES.SANDBAG = "Saco de areia"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SANDBAG = "Isto deve manter a água fora."

GLOBAL.STRINGS.NAMES.SANDBAG_ITEM = "Saco de areia"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SANDBAG_ITEM = "Tecnologia da areia, em fim."
GLOBAL.STRINGS.RECIPE_DESC.SANDBAG_ITEM = "Areia. O maior inimigo da água..."

GLOBAL.STRINGS.NAMES.LIMESTONE = "Pedra lima"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LIMESTONE = "Pode ser um material de construção útil."
GLOBAL.STRINGS.RECIPE_DESC.LIMESTONE = "Pedra, com uma pitada de Cal.."

GLOBAL.STRINGS.NAMES.CUTLASS = "Agulha suprema"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUTLASS = "Espero que esta espada não comece a cheirar..."
GLOBAL.STRINGS.RECIPE_DESC.CUTLASS = "Peixes foram prejudicados na tomada deste.."

GLOBAL.STRINGS.NAMES.AERODYNAMICHAT = "Chapéu aerodinâmico"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.AERODYNAMICHAT = "Ele realmente corta o ar!"
GLOBAL.STRINGS.RECIPE_DESC.AERODYNAMICHAT = "Design aerodinâmico para viagens eficientes."

GLOBAL.STRINGS.NAMES.SHARK_FIN = "Barbatana de tubarão"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHARK_FIN = "Uma barbatana elegante."

GLOBAL.STRINGS.NAMES.RAINBOWJELLYFISH = "Água-viva colorida"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAINBOWJELLYFISH = "Esta criatura é pura ciência!"

GLOBAL.STRINGS.NAMES.RAINBOWJELLYFISH_DEAD = "Água viva colorida morta"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAINBOWJELLYFISH_DEAD = "Ele viveu uma vida boa."

GLOBAL.STRINGS.NAMES.RAINBOWJELLYFISH_COOKED = "Água viva-colorida assada"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAINBOWJELLYFISH_COOKED = "É tudo comida."

GLOBAL.STRINGS.NAMES.RAINBOWJELLYJERKY = "Água-viva colorida seca"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAINBOWJELLYJERKY = "Seria um parvo se não comesse isto."

GLOBAL.STRINGS.NAMES.RAINBOWJELLYFISH_PLANTED = "Água-viva colorida"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAINBOWJELLYFISH_PLANTED = "A ciência trabalha de formas misteriosas."

GLOBAL.STRINGS.NAMES.PRIMEAPE = "Macaco"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PRIMEAPE = "Essas coisas vão ser o meu fim."

GLOBAL.STRINGS.NAMES.PRIMEAPEBARREL = "Cabana de macacos"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PRIMEAPEBARREL = "Aqui mora o mal."

GLOBAL.STRINGS.NAMES.MONKEYBALL = "Bola de bananas"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MONKEYBALL = "Eu tenho um estranho desejo de nomeá-la depois de mim."
GLOBAL.STRINGS.RECIPE_DESC.MONKEYBALL = "Vá para o negócio dos macacos."

GLOBAL.STRINGS.NAMES.NEEDLESPEAR = "Espinho de cactus"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.NEEDLESPEAR = "Ainda bem que não pisei nisto."
GLOBAL.STRINGS.RECIPE_DESC.NEEDLESPEAR = "needlespear"

GLOBAL.STRINGS.NAMES.PEG_LEG = "Pena e pau"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PEG_LEG = "Posso fazer reparos se alguém quiser usá-lo de verdade."
GLOBAL.STRINGS.RECIPE_DESC.PEG_LEG = "Peg Leg"

GLOBAL.STRINGS.NAMES.SPEAR_POISON = "Lança venenosa"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPEAR_POISON = "Agora é extremamente mortal."
GLOBAL.STRINGS.RECIPE_DESC.SPEAR_POISON = "Lento e doloroso."

GLOBAL.STRINGS.NAMES.MESSAGEBOTTLE1 = "Mensagem em um frasco"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MESSAGEBOTTLE1 = "Alguém me escreveu um bilhete!"

GLOBAL.STRINGS.NAMES.BURIEDTREASURE = "Aqui está a localização do alvo"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BURIEDTREASURE = "Por favor, seja um bom tesouro!"

GLOBAL.STRINGS.NAMES.SHARK_GILLS = "Brânquias de tubarão"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHARK_GILLS = "Eu gostaria de ter brânquias."

GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.COFFEEBUSH = "Acho que precisa ser fertilizado."

GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.JUNGLETREE = "Aquela árvore precisa de um corte de cabelo."

GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.JUNGLETREE_BURNT = "Que desperdício de madeira."

GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.JUNGLETREE_STUMP = "Toma essa, natureza!"

GLOBAL.STRINGS.NAMES.SAIL = "Vela"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SAIL = "Isso realmente deve transformar a minha experiência de barco.."
GLOBAL.STRINGS.RECIPE_DESC.SAIL = "Capturar o vento!"

GLOBAL.STRINGS.NAMES.CLOTHSAIL = "Vela de pano"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CLOTHSAIL = "O vento não está fugindo agora!"
GLOBAL.STRINGS.RECIPE_DESC.CLOTHSAIL = "Pegar ainda mais vento!"

GLOBAL.STRINGS.NAMES.SNAKESKINSAIL = "Vela de pele de cobra"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SNAKESKINSAIL = "Escale e navegue!"
GLOBAL.STRINGS.RECIPE_DESC.SNAKESKINSAIL = "Coletor de vento resistente."

GLOBAL.STRINGS.NAMES.FEATHERSAIL = "Vela da pena"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FEATHERSAIL = "É luz de penas!"
GLOBAL.STRINGS.RECIPE_DESC.FEATHERSAIL = "Como uma asa de pássaro, para seu barco!"

GLOBAL.STRINGS.NAMES.IRONWIND = "Vento de ferro"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.IRONWIND = "Isto é como um cientista deve viajar.."
GLOBAL.STRINGS.RECIPE_DESC.IRONWIND = "Diesel!"

GLOBAL.STRINGS.NAMES.WOODLEGSSAIL = "Vela pirata"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOODLEGSSAIL = "A vela pirata por excelência."
GLOBAL.STRINGS.RECIPE_DESC.WOODLEGSSAIL = "Eu vou me tornar um pirata!"

GLOBAL.STRINGS.NAMES.BOAT_LANTERN = "Lanterna do barco"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOAT_LANTERN = "Isso vai fazer maravilhas para a minha visão norturna!"
GLOBAL.STRINGS.RECIPE_DESC.BOAT_LANTERN = "Ilumine a situação."

GLOBAL.STRINGS.NAMES.BOAT_TORCH = "Tocha de barco"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOAT_TORCH = "Isto vai manter as minhas mãos livres."
GLOBAL.STRINGS.RECIPE_DESC.BOAT_TORCH = "Ver no mar."

GLOBAL.STRINGS.NAMES.BOATCANNON = "Canhão de barco"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOATCANNON = "A única coisa melhor do que um barco é um barco com um canhão."
GLOBAL.STRINGS.RECIPE_DESC.BOATCANNON = "Tem o seu barco de volta."

GLOBAL.STRINGS.NAMES.WOODLEGS_BOATCANNON = "Canhão do pirata"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOODLEGS_BOATCANNON = "Digno de um pirata"
GLOBAL.STRINGS.RECIPE_DESC.WOODLEGS_BOATCANNON = "Bem reforçado"

GLOBAL.STRINGS.NAMES.QUACKERINGRAM = "Quacken Destruidor"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.QUACKERINGRAM = "SMASH!"
GLOBAL.STRINGS.RECIPE_DESC.QUACKERINGRAM = "É melhor todos saírem do seu caminho."

GLOBAL.STRINGS.NAMES.QUACKENDRILL = "Broca de Quacken"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.QUACKENDRILL = "Um instrumento de perfuração em águas profundas"
GLOBAL.STRINGS.RECIPE_DESC.QUACKENDRILL = "Para grasnar no mar profundo"

GLOBAL.STRINGS.NAMES.QUACKENBEAK = "Bico de Quacken"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.QUACKENBEAK = "Se aquele bruto não consegue segurar a boca, então eu vou."

GLOBAL.STRINGS.NAMES.TRAWLNET = "Rede de arrasto"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TRAWLNET = "Definitivamente está afundando."
GLOBAL.STRINGS.RECIPE_DESC.TRAWLNET = "O pescador paciente é sempre recompensado."

STRINGS.NAMES.GLASS_SHARDS = "Cacos de vidro"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GLASS_SHARDS = "A alta temperatura transforma a areia em vidro imperfeito."
STRINGS.RECIPE_DESC.GLASS_SHARDS = "Fragmentos do seu coração."

STRINGS.NAMES.SHARD_SWORD = "Espada de fragmentos"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHARD_SWORD = "A caneta é mais poderosa."
STRINGS.RECIPE_DESC.SHARD_SWORD = "Para cortar seres das sombras."

STRINGS.NAMES.SHARD_BEAK = "Bico de Caco"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHARD_BEAK = "Um instrumento de desconstrução."
STRINGS.RECIPE_DESC.SHARD_BEAK = "Destrói ninhos redutores."

STRINGS.NAMES.PORTO_SURFBOARD = "Prancha"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTO_SURFBOARD = "Se eu estivesse na minha prancha eu poderia te pegar."
STRINGS.RECIPE_DESC.PORTO_SURFBOARD = "Pendurar dez!"

STRINGS.NAMES.SURFBOARD = "Prancha"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SURFBOARD = "Se eu estivesse na minha prancha eu poderia te pegar"
STRINGS.RECIPE_DESC.SURFBOARD = "Pendurar dez!"

STRINGS.NAMES.PORTO_WOODLEGSBOAT = "Barco do pirata"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTO_WOODLEGSBOAT = "Uma nave serve para um malandro."
STRINGS.RECIPE_DESC.PORTO_WOODLEGSBOAT = "Vai fazer umas coisas de pirata."

STRINGS.NAMES.WOODLEGSBOAT = "Barco do pirata"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOODLEGSBOAT = "Uma nave serve para um malandro."
STRINGS.RECIPE_DESC.WOODLEGSBOAT = "Vai fazer umas coisas de pirata."

STRINGS.NAMES.PORTO_PIRATEBOATAMIGO = "Barco do pirata"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTO_PIRATEBOATAMIGO = "Uma nave serve para um malandro."
STRINGS.RECIPE_DESC.PORTO_PIRATEBOATAMIGO = "Vai fazer umas coisas de pirata."

STRINGS.NAMES.PIRATEBOATAMIGO = "Barco do pirata"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PIRATEBOATAMIGO = "Uma nave serve para um malandro."
STRINGS.RECIPE_DESC.PIRATEBOATAMIGO = "Vai fazer umas coisas de pirata."

STRINGS.NAMES.TURBINE_BLADES = "Lâminas da turbina"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURBINE_BLADES = "Talvez isto tenha alimentado aquela tempestade bestial?"

STRINGS.NAMES.SHARKITTEN = "Filhote de tubarão tigre"

STRINGS.NAMES.TRAWLNETDROPPED = "Rede de arrasto"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TRAWLNETDROPPED = "Definitivamente está afundando."

STRINGS.NAMES.SAPLING1 = "Moita de gravetos"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SAPLING1 = "Poderia ser legal se fosse mais fresco."

GLOBAL.STRINGS.NAMES.BANANAPOP = "Banana Pop"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BANANAPOP = "Não, não o cérebro congelar! Preciso disso para a ciência!"

GLOBAL.STRINGS.NAMES.CEVICHE = "Ceviche"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CEVICHE = "Posso ter uma tigela maior? Este parece um pouco de camarão."

GLOBAL.STRINGS.NAMES.SWEETPOTATOSOUFFLE = "Suflê de batata-doce"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SWEETPOTATOSOUFFLE = "Suflês de batata-doce são uma tendência crescente."

GLOBAL.STRINGS.NAMES.SEAFOODGUMBO = "Marisco gumbo"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEAFOODGUMBO = "É uma sopa de marisco Jumbo."

GLOBAL.STRINGS.NAMES.SURFNTURF = "Surf 'n' Turf"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SURFNTURF = "É perfeito!"

GLOBAL.STRINGS.NAMES.SHARKFINSOUP = "Sopa de barbatana de tubarão"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHARKFINSOUP = "É barbatana de tubarão-punida!"

GLOBAL.STRINGS.NAMES.MUSSELBOUILLABAISE = "Bouillabaise do mexilhão"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSSELBOUILLABAISE = "Imagine as experiências que eu poderia correr sobre ele!"

GLOBAL.STRINGS.NAMES.MONSTERTARTARE = "Tartare monstro"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MONSTERTARTARE = "Deve haver algo melhor para comer por aqui."

GLOBAL.STRINGS.NAMES.LOBSTERDINNER = "Jantar de lagosta"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LOBSTERDINNER = "Se eu comê-lo de manhã sobrará ainda para a jantar?."

GLOBAL.STRINGS.NAMES.LOBSTERBISQUE = "Sopa de lagosta"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LOBSTERBISQUE = "Poderia usar mais sal, mas não na minha sopa."

GLOBAL.STRINGS.NAMES.FRESHFRUITCREPES = "Crepes frescos de fruta"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FRESHFRUITCREPES = "Fruta açucarada! Parte de um pequeno-almoço equilibrado."

GLOBAL.STRINGS.NAMES.BISQUE = "Bisque"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BISQUE = "Cozinhar que com certeza me manteve sopa boa."

GLOBAL.STRINGS.NAMES.CALIFORNIAROLL = "Rolo de Califórnia"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CALIFORNIAROLL = "Mas eu não tenho pauzinhos."

GLOBAL.STRINGS.NAMES.JELLYOPOP = "Jelly-O Pop"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.JELLYOPOP = "Geleia de água-viva bem na minha boca!"

STRINGS.NAMES.SAPLINGNOVA = "Muda de gravetos"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SAPLINGNOVA = "Poderia ser legal se fosse mais fresco."

STRINGS.NAMES.PORTAL_SHIPWRECKED = "Barco"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTAL_SHIPWRECKED = "Esta quebrado"

STRINGS.NAMES.BUOY = "Boia"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BUOY = "Ohhhh boia"
STRINGS.RECIPE_DESC.BUOY = "Marque seu lugar na água."

STRINGS.NAMES.ARMOR_LIFEJACKET = "Colete salva-vidas"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ARMOR_LIFEJACKET = "Mantém-me flutuando, sem o meu barco!"
STRINGS.RECIPE_DESC.ARMOR_LIFEJACKET = "Segurança em primeiro lugar!"

GLOBAL.STRINGS.NAMES.GRASSNOVA = "Grama"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.GRASSNOVA = "Grama."

STRINGS.WALLY1 = "Chump."
STRINGS.WALLY2 = "Bela Viagem"

STRINGS.NAMES.SURFBOARDITEM = "Prancha de Surf"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.LUCKYHAT = "Faz-me parecer escorbuto... Quero dizer assustador!?"
STRINGS.NAMES.LUCKYHAT = "Chapéu Lucky"
STRINGS.RECIPE_DESC.LUCKYHAT = "Traga tesouros."

STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPICEPACK = "Meu saco de truques de chef!"
STRINGS.NAMES.SPICEPACK = "Malote do cozinheiro chefe"
STRINGS.RECIPE_DESC.SPICEPACK = "Refrescar seus alimentos."

STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTABLECOOKPOT = "Que novas aventuras culinárias vamos empreender, velho amigo?"
STRINGS.NAMES.PORTABLECOOKPOT = "Panela portátil"
STRINGS.NAMES.PORTABLECOOKPOT_ITEM = "Panela portátil"
STRINGS.RECIPE_DESC.PORTABLECOOKPOT_ITEM = "Que novas aventuras culinárias vamos empreender, velho amigo?"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.PIRATEHAT = "Apto para um malandro implacável. Ou a mim."
STRINGS.NAMES.PIRATEHAT = "Chapéu Pirata"
STRINGS.RECIPE_DESC.PIRATEHAT = "É a vida de um pirata para vós!"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CAPTAINHAT = "O traje de barco apropriado!"
STRINGS.NAMES.CAPTAINHAT = "Chapéu de Capitão"
STRINGS.RECIPE_DESC.CAPTAINHAT = "Use um. Seu barco vai respeitá-lo mais."


GLOBAL.STRINGS.NAMES.PORTO_RAFT = "Jangada"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTO_RAFT = "Isto parece adequado."
STRINGS.RECIPE_DESC.PORTO_RAFT = "Totalmente tipo de navegação."

GLOBAL.STRINGS.NAMES.PORTO_ARMOUREDBOAT = "Barco blindado"
GLOBAL.STRINGS.RECIPE_DESC.PORTO_ARMOUREDBOAT = "Descascar para fora para este vaso saudável."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTO_ARMOUREDBOAT = "Esse é um barco durável."

GLOBAL.STRINGS.NAMES.PORTO_CARGOBOAT = "Barco de carga"
GLOBAL.STRINGS.RECIPE_DESC.PORTO_CARGOBOAT = "Acumulando no mar!"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTO_CARGOBOAT = "Tem espaço para todas as minhas coisas!"

GLOBAL.STRINGS.NAMES.PORTO_LOGRAFT = "Jagada de madeira"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTO_LOGRAFT = "Jagada de madeira...?"
GLOBAL.STRINGS.RECIPE_DESC.PORTO_LOGRAFT = "Este parece... tipo de barco..."

GLOBAL.STRINGS.NAMES.PORTO_ROWBOAT = "Barco"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTO_ROWBOAT = "Agora minha aventura está completa."
GLOBAL.STRINGS.RECIPE_DESC.PORTO_ROWBOAT = "Um barco mais resistente"

GLOBAL.STRINGS.NAMES.PORTO_ENCRUSTEDBOAT = "Barco resistente"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTO_ENCRUSTEDBOAT = "Bastante robusto."
GLOBAL.STRINGS.RECIPE_DESC.PORTO_ENCRUSTEDBOAT = "Altamente resistente"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.THATCHPACK = "Eu chamo-lhe um thatchel"
STRINGS.NAMES.THATCHPACK = "Pacote de palma"
STRINGS.RECIPE_DESC.THATCHPACK = "Carrega uma carga leve."

STRINGS.NAMES.PARROT = "Parrot"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PARROT = "I try not to eat anything with a name."

STRINGS.NAMES.SEAGULLWATER = "Seagull"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEAGULLWATER = "Shoo! Find some other land!"

GLOBAL.STRINGS.NAMES.ICEMAKER = "Ice Maker 3000"
GLOBAL.STRINGS.RECIPE_DESC.ICEMAKER = "Ice, ice, baby!"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.ICEMAKER = "Machine is doing very good job!"

GLOBAL.STRINGS.RECIPE_DESC.PRIMEAPEBARREL = "More monkeys!"

GLOBAL.STRINGS.RECIPE_DESC.BALLPHINHOUSE = "Ballphin House"

STRINGS.NAMES.DORSALFIN = "Dorsalfin"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DORSALFIN = "Dorsalfin"

STRINGS.NAMES.CORALLARVE = "Coral Larve"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CORALLARVE = "Coral Larve"

GLOBAL.STRINGS.NAMES.NUBBIN = "Nubbin"
GLOBAL.STRINGS.RECIPE_DESC.NUBBIN = "Nubbin!"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.NUBBIN = "Nubbin!"

STRINGS.NAMES.SEAWEED_STALK = "Seaweed Stalk"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEAWEED_STALK = "Seaweed Stalk"

STRINGS.NAMES.COCONADE = "Coconade"
GLOBAL.STRINGS.RECIPE_DESC.COCONADE = "Coconade!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.COCONADE = "Coconade"

STRINGS.NAMES.PIRATEPACK = "Pirate Pack"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PIRATEPACK = "Pirate Pack"

GLOBAL.STRINGS.NAMES.TAR_EXTRACTOR = "Tar Extractor"
GLOBAL.STRINGS.RECIPE_DESC.TAR_EXTRACTOR = "Tar Extractor!"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TAR_EXTRACTOR = "Tar Extractor!"

STRINGS.NAMES.TAR_POOL = "Tar Pool"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TAR_POOL = "Tar Pool"

STRINGS.NAMES.TAR = "Tar"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TA = "Tar"

STRINGS.NAMES.TAR_TRAP = "Tar Trap"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TAR_TRAP = "Tar Trap"

GLOBAL.STRINGS.NAMES.FISH_FARM = "Fish Farm"
GLOBAL.STRINGS.RECIPE_DESC.FISH_FARM = "Fish Farm!"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH_FARM = "Fish Farm!"

STRINGS.NAMES.ROE = "Roe"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ROE = "Roe"

STRINGS.NAMES.ROE_COOKED = "Roe Cooked"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ROE_COOKED = "Roe Cooked"

STRINGS.NAMES.FISH3 = "Purple Grouper"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH3 = "Purple Grouper"

STRINGS.NAMES.FISH3_COOKED = "Purple Grouper Cooked"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH3_COOKED = "Purple Grouper Cooked"

STRINGS.NAMES.FISH4 = "Pierrot Fish"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH4 = "Pierrot Fish"

STRINGS.NAMES.FISH4_COOKED = "Pierrot Fish Cooked"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH4_COOKED = "Pierrot Fish Cooked"

STRINGS.NAMES.FISH5 = "Neon Quattro"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH5 = "Neon Quattro"

STRINGS.NAMES.FISH5_COOKED = "Neon Quattro Cooked"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH5_COOKED = "Neon Cooked"

STRINGS.NAMES.FISH5_COOKED = "Neon Quattro Cooked"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH5_COOKED = "Delicious, as you would expect"

GLOBAL.STRINGS.NAMES.BLOWDART_POISON = "Blowdart Poison"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BLOWDART_POISON = "Blowdart Poison."
GLOBAL.STRINGS.RECIPE_DESC.BLOWDART_POISON = "Blowdart Poison"

GLOBAL.STRINGS.NAMES.SEATRAP = "Sea Trap"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEATRAP = "Sea Trap."
GLOBAL.STRINGS.RECIPE_DESC.SEATRAP = "Sea Trap"

GLOBAL.STRINGS.NAMES.SEA_CHIMINEA = "Sea Chiminea"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEA_CHIMINEA = "Sea Chiminea."
GLOBAL.STRINGS.RECIPE_DESC.SEA_CHIMINEA = "Sea Chiminea"

GLOBAL.STRINGS.NAMES.TROPICALBOUILLABAISSE = "Tropical Bouillabaisse"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TROPICALBOUILLABAISSE = "Tropical Bouillabaisse."

GLOBAL.STRINGS.NAMES.CAVIAR = "Caviar"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CAVIAR = "Caviar."

GLOBAL.STRINGS.NAMES.OX_FLUTE = "Ox Flute"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OX_FLUTE = "Ox Flute."
GLOBAL.STRINGS.RECIPE_DESC.OX_FLUTE = "Ox Flute"

GLOBAL.STRINGS.NAMES.OXBABY = "Ox baby"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OXBABY = "Ox baby."

GLOBAL.STRINGS.NAMES.RESEARCHLAB5 = "researchlab5"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.RESEARCHLAB5 = "researchlab5."
GLOBAL.STRINGS.RECIPE_DESC.RESEARCHLAB5 = "researchlab5"

GLOBAL.STRINGS.NAMES.SEA_YARD = "Sea Yard"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEA_YARD = "Sea Yard."
GLOBAL.STRINGS.RECIPE_DESC.SEA_YARD = "Sea Yard"

GLOBAL.STRINGS.NAMES.TARLAMP = "Tar Lamp."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TARLAMP = "Tar Lamp."
GLOBAL.STRINGS.RECIPE_DESC.TARLAMP = "Tar Lamp"

GLOBAL.STRINGS.NAMES.TARSUIT = "Tar Suit"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TARSUIT = "Tar Suit."
GLOBAL.STRINGS.RECIPE_DESC.TARSUIT = "Tar Suit"

GLOBAL.STRINGS.NAMES.BLUBBERSUIT = "Blubber Suit"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BLUBBERSUIT = "Blubber Suit."
GLOBAL.STRINGS.RECIPE_DESC.BLUBBERSUIT = "Blubber Suit"

GLOBAL.STRINGS.NAMES.MUSSEL_BED = "Mussel Bed"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSSEL_BED = "Mussel Bed."
GLOBAL.STRINGS.RECIPE_DESC.MUSSEL_BED = "Mussel Bed"

GLOBAL.STRINGS.NAMES.WATERCHEST1 = "Water Chest"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WATERCHEST1 = "Water Chest."
GLOBAL.STRINGS.RECIPE_DESC.WATERCHEST1 = "Water Chest"

GLOBAL.STRINGS.RECIPE_DESC.SURFBOARDITEM = "Cowabunga dudes!"

GLOBAL.STRINGS.NAMES.HAIL_ICE = "Hail Ice"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.HAIL_ICE = "Hail Ice."
GLOBAL.STRINGS.RECIPE_DESC.ICE = "Ice"

GLOBAL.STRINGS.NAMES.TELESCOPE = "Telescope"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TELESCOPE = "Telescope."
GLOBAL.STRINGS.RECIPE_DESC.TELESCOPE = "Telescope"

GLOBAL.STRINGS.NAMES.SUPERTELESCOPE = "Supertelescope"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SUPERTELESCOPE = "Supertelescope."
GLOBAL.STRINGS.RECIPE_DESC.SUPERTELESCOPE = "Supertelescope"

GLOBAL.STRINGS.NAMES.TIGEREYE = "Tiger Eye"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TIGEREYE = "Tiger Eye."

GLOBAL.STRINGS.RECIPE_DESC.GOLDNUGGET = "Ouro"

GLOBAL.STRINGS.NAMES.ESCADADOVULCAO2 = "Volcano Exit"
GLOBAL.STRINGS.NAMES.LAVAPONDBIG1 = "Big lava pool"

GLOBAL.STRINGS.NAMES.MERM1 = "Merm"
GLOBAL.STRINGS.NAMES.MERM2 = "Merm"

GLOBAL.STRINGS.NAMES.SHARK_GILLS = "Shark Gills"
--------------store---------

--------------actions-------
GLOBAL.STRINGS.ACTIONS.HACK="Cortar"
GLOBAL.STRINGS.ACTIONS.BOATMOUNT="Subir no barco"
GLOBAL.STRINGS.ACTIONS.BOATREPAIR = "Reparar o barco"
GLOBAL.STRINGS.ACTIONS.BOATDISMOUNT = "Descer do barco"
GLOBAL.STRINGS.ACTIONS.STICK = "Graveto"
GLOBAL.STRINGS.NAMES.NAUTICALTAB = "Naútico"
GLOBAL.STRINGS.TABS.NAUTICALTAB = "Náutico"
GLOBAL.STRINGS.ACTIONS.STICK = "Colocar"
GLOBAL.STRINGS.ACTIONS.LANTERNOFF = "Desligar"
GLOBAL.STRINGS.ACTIONS.LANTERNON = "Ligar"
GLOBAL.STRINGS.ACTIONS.BOATCANNON = "Atirar"
GLOBAL.STRINGS.ACTIONS.RETRIEVE = "Pegar"
--------------rawling speak---------------
GLOBAL.STRINGS.NAMES.RAWLING = "Bola do Wilson"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAWLING = "Rolando..."
GLOBAL.STRINGS.RAWLINGon_hit_water = "Swish!"
GLOBAL.STRINGS.RAWLINGon_dropped = "Me drible!"
GLOBAL.STRINGS.RAWLINGon_extinguish = "Salvou!"
GLOBAL.STRINGS.RAWLINGin_container = "Isto não é uma cesta de pêssego..."
GLOBAL.STRINGS.RAWLINGon_ground = "Me apanhe...."
GLOBAL.STRINGS.RAWLINGin_inventory = "Vamos cortar o fundo da cesta."
GLOBAL.STRINGS.RAWLINGother_owner = "Ai!"
GLOBAL.STRINGS.RAWLINGon_ignite = {
"Estou a arder!",
"Ow ow ow ow ow!",
}
GLOBAL.STRINGS.RAWLINGon_pickedup = {
"É você, James?",
"Você é meu melhor amigo!",
}
GLOBAL.STRINGS.RAWLINGon_thrown = {
"Para o cesto de pêssegos!",
"Acerte!",
"Você perde 100% dos tiros que você não toma!",
"Eu consigo voar...!",
}

GLOBAL.STRINGS.RAWLINGon_bounced = 
{
"Ai!",
"Nada além de pêssegos!",
"Splish!",
"Rejeitado!",
}
GLOBAL.STRINGS.RAWLINGequipped = {
"Você pode me carregar. Para um par de passos.",
"Isso é algum tipo de piada canadense?",
"Sinta-se livre para me jogar.",
}
STRINGS.BORE_TALK_FOLLOWWILSON = {"YOU OK BY ME", "I LOVE FRIEND", "YOU IS GOOD", "I FOLLOW!"}
STRINGS.BORE_TALK_FIND_LIGHT = {"SCARY", "NO LIKE DARK", "WHERE IS SUN?", "STAY NEAR FIRE", "FIRE IS GOOD"}
STRINGS.BORE_TALK_LOOKATWILSON = {"WHO ARE YOU?", "YOU NOT BORE.", "UGLY MONKEY MAN", "YOU HAS MEAT?"}
STRINGS.BORE_TALK_RUNAWAY_WILSON = {"TOO CLOSE!", "STAY 'WAY!", "YOU BACK OFF!", "THAT MY SPACE."}
STRINGS.BORE_TALK_FIGHT = {"I KILL NOW!", "YOU GO SMASH!", "RAAAWR!", "NOW YOU DUN IT!", "GO 'WAY!", "I MAKE YOU LEAVE!",}
STRINGS.BORE_TALK_RUN_FROM_SPIDER = {"SPIDER BAD!", "NO LIKE SPIDER!", "SCARY SPIDER!"}
STRINGS.BORE_TALK_HELP_CHOP_WOOD = {"KILL TREE!", "SMASH MEAN TREE!", "I PUNCH TREE!"}
STRINGS.BORE_TALK_HELP_HACK = {"I HELP GET BUSH!", "I PUNCH BUSH!", "WE PUNCHIN' PLANTS NOW?"}
STRINGS.BORE_TALK_ATTEMPT_TRADE = {"WHAT YOU GOT?", "BETTER BE GOOD.", "NO WASTE MY TIME."}
STRINGS.BORE_TALK_PANIC = {"NOOOOO!", "TOO DARK! TOO DARK!", "AAAAAAAAAH!!"}
STRINGS.BORE_TALK_PANICFIRE = {"HOT HOT HOT!", "OWWWWW!", "IT BURNS!"}
STRINGS.BORE_TALK_FIND_MEAT = {"ME HUNGRY!", "YUM!", "I EAT FOOD!", "TIME FOR FOOD!"}
STRINGS.BORE_TALK_EAT_MEAT = {"NOM NOM NOM", "YUM!"}
STRINGS.BORE_TALK_GO_HOME = {"HOME TIME!", "HOME! HOME!"}

STRINGS.NAMES.WALL_LIMESTONE_ITEM = "Limestone Wall"
STRINGS.NAMES.WALL_LIMESTONE = "Limestone Wall"
STRINGS.RECIPE_DESC.WALL_LIMESTONE_ITEM = "Strong wall segments."
STRINGS.RECIPE_DESC.LIMESTONE = "Stone, with a hint of lime."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WALL_LIMESTONE = "Sturdy."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WALL_LIMESTONE_ITEM = "These would do more good if I placed them."

STRINGS.NAMES.WALL_ENFORCEDLIMESTONE_ITEM = "Sea Wall"
STRINGS.NAMES.WALL_ENFORCEDLIMESTONE = "Sea Wall"
STRINGS.RECIPE_DESC.WALL_ENFORCEDLIMESTONE_ITEM = "Strong wall segments to build at sea."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WALL_ENFORCEDLIMESTONE = "I shelled out for the good stuff."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WALL_ENFORCEDLIMESTONE_ITEM = "I have to build it in the water."
------------------mapwrapper---------------
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_MAPWRAP_LOSECONTROL = "Parece que o meu futuro está enevoado."

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_MAPWRAP_RETURN = "Acho que senti algo a roçar na minha perna..."

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_MAPWRAP_WARN = "Os monstros estão aqui."
STRINGS.NAMES.BELL1 = "Old Bell"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BELL1 = "Old Bell."