local STRINGS = GLOBAL.STRINGS

-----------------------------Biome Jungle -----------------------------





-----------------------------Biome Tidal Mash---------------------------

GLOBAL.STRINGS.NAMES.TIGERSHARKPOOL = "Estanque de Tiburones"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TIGERSHARKPOOL = "Hay un tiburón extraño en este estanque."


GLOBAL.STRINGS.NAMES.LAVAPONDBIG = "Gran pozo de lava"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LAVAPONDBIG = "Un poco caliente para mi gusto."

GLOBAL.STRINGS.NAMES.HARPOON = "Arpón"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.HARPOON = "Un arpón para lanzar."



-----------------------------Biome Volcano------------------------------
GLOBAL.STRINGS.NAMES.DRAGOON = "Dragón"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DRAGOON = "Eres rápido, ¿verdad?"

GLOBAL.STRINGS.NAMES.DRAGOONHEART = "Corazón de dragón."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DRAGOONHEART = "Donde el dragón una vez guardó sus sentimientos."

GLOBAL.STRINGS.NAMES.DRAGOONDEN = "Guarida de dragón"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DRAGOONDEN = "Incluso los matones tienen que dormir."

GLOBAL.STRINGS.NAMES.DRAGOONSPIT = "Saliva de dragón"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DRAGOONSPIT = "Es particularmente desagradable!"

GLOBAL.STRINGS.NAMES.DRAGOONEGG = "Huevo de dragón"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DRAGOONEGG = "Oigo agrietamiento?"

GLOBAL.STRINGS.NAMES.OBSIDIAN = "Obsidiana"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OBSIDIAN = "Es una roca de fuego."

GLOBAL.STRINGS.NAMES.BOOK_METEOR1 = "Alegría de Vulcanología"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOOK_METEOR1 = "El prólogo solo dice \"Espero que te gusten los dragones.\""

GLOBAL.STRINGS.NAMES.OBSIDIAN_WORKBENCH = "Mesa de trabajo de obsidiana"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OBSIDIAN_WORKBENCH = "Me siento inspirado."

GLOBAL.STRINGS.NAMES.OBSIDIANFIREPIT = "Hoguera de obsidiana"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OBSIDIANFIREPIT = "Esta hoguera es un conductor para aún más... fuego."


GLOBAL.STRINGS.NAMES.ARMOROBSIDIAN = "Armadura de obsidiana"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.ARMOROBSIDIAN = "Soy un genio."

GLOBAL.STRINGS.NAMES.SPEAR_OBSIDIAN = "Lanza de obsidiana"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPEAR_OBSIDIAN = "Esto dejará una marca."

--GLOBAL.STRINGS.NAMES.OBSIDIANMACHETE = "Machete de obsidiana"
--GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OBSIDIANMACHETE = "Está caliente al tacto."

GLOBAL.STRINGS.NAMES.AXEOBSIDIAN = "Hacha de obsidiana"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.AXEOBSIDIAN = "Una combinación ganadora!"

GLOBAL.STRINGS.NAMES.ROCK_OBSIDIAN = "Mina de obsidiana"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.ROCK_OBSIDIAN = "Maldita sea! No será minada!"

GLOBAL.STRINGS.NAMES.OBSIDIANBOMB = "Bomba de obsidiana"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OBSIDIANBOMB = "Es incluso más bombardero!"

GLOBAL.STRINGS.NAMES.ROCK_CHARCOAL = "Mina de carbón"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.ROCK_CHARCOAL = "Necesitaría medias muy grandes..."

GLOBAL.STRINGS.NAMES.MAGMAROCK = "Pila de magma"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MAGMAROCK_FULL = "Puedo cavarlo."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MAGMAROCK = "Puedo cavarlo."

GLOBAL.STRINGS.NAMES.MAGMAROCK_GOLD = "Pila de magma"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MAGMAROCK_GOLD_FULL = "Veo una oportunidad de oro."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MAGMAROCK_GOLD = "Veo una oportunidad de oro."

GLOBAL.STRINGS.NAMES.FLAMEGEYSER = "Erupción de lava"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FLAMEGEYSER = "Tal vez debería retroceder."

GLOBAL.STRINGS.NAMES.VOLCANO_SHRUB = "Arbol de cenizas quemado"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.VOLCANO_SHRUB = "Te ves ceniciento."

GLOBAL.STRINGS.NAMES.VOLCANO_EXIT = "Volcán"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.VOLCANO_EXIT = "Puedo sentir una brisa fresca afuera."

GLOBAL.STRINGS.NAMES.VULCANO_ENTRANCE = "Entrada de volcán"
GLOBAL.STRINGS.NAMES.ESCADADOVULCAO = "Salida de volcán"

GLOBAL.STRINGS.NAMES.VOLCANO = "Volcán"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.VOLCANO = "Parece seguro."

GLOBAL.STRINGS.NAMES.VOLCANOSTAFF = "Báculo volcánico"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.VOLCANOSTAFF = "La etiqueta dice 'Mantener fuera del alcance de los niños'."

STRINGS.NAMES.LAVAPOOL = "Pozo de lava"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LAVAPOOL = "Un poco caliente para mi gusto."

STRINGS.NAMES.DUG_ELEPHANTCACTUS = "Cactus de elefante cavado"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_ELEPHANTCACTUS = "Una planta urticante transplantable."
STRINGS.NAMES.ELEPHANTCACTUS = "Cactus de elefante"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ELEPHANTCACTUS = "Oh, puedo usar esto para perforar mis ojos!"
STRINGS.NAMES.ELEPHANTCACTUS_ACTIVE = "Cactus de elefante activo"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ELEPHANTCACTUS_ACTIVE = "Las espinas de este cactus son mucho más raras."
STRINGS.NAMES.ELEPHANTCACTUS_STUMP = "Tocón de cactus de elefante"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ELEPHANTCACTUS_STUMP = "Falta mucho antes de que el presidente salga."


STRINGS.TABS.OBSIDIANTAB = "Volcánico"
GLOBAL.STRINGS.RECIPE_DESC.DRAGOONDEN = "Ingrese a la guarida del dragón."
GLOBAL.STRINGS.RECIPE_DESC.OBSIDIANBOMB = "KA-BLAMMIER!"
GLOBAL.STRINGS.RECIPE_DESC.ARMOROBSIDIAN = "Caliente al tacto."
GLOBAL.STRINGS.RECIPE_DESC.SPEAR_OBSIDIAN = "Qué tal un pequeño fuego con tu lanza?"
GLOBAL.STRINGS.RECIPE_DESC.OBSIDIANFIREPIT = "El más fuerte de todos los incendios!"
GLOBAL.STRINGS.RECIPE_DESC.OBSIDIANMACHETE = "Cortar y quemar!"
GLOBAL.STRINGS.RECIPE_DESC.AXEOBSIDIAN = "Como un hacha regular, solo que más caliente."
--GLOBAL.STRINGS.RECIPE_DESC.COFFEE = "Café caliente!"
GLOBAL.STRINGS.RECIPE_DESC.BOOK_METEOR1 = "Meteoro del cielo!"
GLOBAL.STRINGS.RECIPE_DESC.VOLCANOSTAFF = "El cielo está cayendo!"



--GLOBAL.STRINGS.UI.WORLDGEN.VOLCANOTITLE = "MAGMA HIRVIENDO"
--GLOBAL.STRINGS.NAMES.VOLCANO_ALTAR = "Altar volcánico de Snackrificio"
--GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.VOLCANO_ALTAR.GENERIC = "Parece estar cerrado."
--GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.VOLCANO_ALTAR.OPEN = "El altar está abierto y listo para aceptar ofrendas!"
--GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.VOLCANO_ALTAR_BROKEN = "Maldición!"
--GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.VOLCANO_ALTAR_TOWER = "Qué aterrador!"
--GLOBAL.STRINGS.CHARACTERS.GENERIC.ANNOUNCE_VOLCANO_ERUPT = "Eso no puede ser bueno."

GLOBAL.STRINGS.NAMES.COFFEEBUSH = "Planta de Café"
GLOBAL.STRINGS.NAMES.DUG_COFFEEBUSH = "Planta de Café"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_COFFEEBUSH = "Esto pertenece al suelo!"


GLOBAL.STRINGS.NAMES.COFFEEBEANS = "Granos de café"
GLOBAL.STRINGS.NAMES.COFFEEBEANS_COOKED = "Granos de café tostados"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.COFFEEBEANS = "Podrían usar algo para tostar."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.COFFEEBEANS_COOKED = "El calor definitivamente los mejoró."

GLOBAL.STRINGS.NAMES.COFFEE = "Café"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.COFFEEBOT = "Es una cafetera."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.COFFEE = "Huele delicioso y energizante!"


--GLOBAL.STRINGS.SIGA = "Me siga"
GLOBAL.STRINGS.NAMES.WOODLEGS1 = "Woodlegs"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOODLEGS1 = "Es Woodlegs"

GLOBAL.STRINGS.NAMES.WOODLEGSGHOST = "Fantasma de Woodlegs"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOODLEGSGHOST = "Él era mi amigo"

GLOBAL.STRINGS.NAMES.WOODLEGS_KEY1 = "LLave Esqueleto"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOODLEGS_KEY1 = "Algo en algún lugar debe estar cerrado."

GLOBAL.STRINGS.NAMES.WOODLEGS_KEY2 = "Llave de Oro"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOODLEGS_KEY2 = "Esta llave probablemente abra algo."

GLOBAL.STRINGS.NAMES.WOODLEGS_KEY3 = "Llave de Hierro"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOODLEGS_KEY3 = "Esa es una llave."

GLOBAL.STRINGS.NAMES.WOODLEGS_CAGE = "Jaula de Woodlegs"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOODLEGS_CAGE = "Parece una cantidad excesiva de cerraduras."


GLOBAL.STRINGS.NAMES.SLIP = "Slip"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SLIP = "Un pequeño monstruo peludo"

GLOBAL.STRINGS.NAMES.SLIPSTOR = "Slipstor"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SLIPSTOR = "Un gran monstruo peludo"

GLOBAL.STRINGS.NAMES.SLIPSTOR_SPAWNER = "Slipstor Spawner"



GLOBAL.STRINGS.NAMES.TWISTER = "Tornafoca"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TWISTER = "Pensé que era extrañamente ventoso por aquí."

GLOBAL.STRINGS.NAMES.TWISTER_SEAL = "Foca"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TWISTER_SEAL = "Awww."

GLOBAL.STRINGS.NAMES.TWISTER_TORNADO = "Tornado"


GLOBAL.STRINGS.NAMES.MERMFISHER = "Tritón Pescador"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MERMFISHER = "Mejor no intentes nada sospechoso."

GLOBAL.STRINGS.NAMES.FLUP = "Flup"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FLUP = "Déjame en paz!"

GLOBAL.STRINGS.NAMES.TIDALPOOL = "Pozo de marea"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TIDALPOOL = "Un pozo dejado por las mareas."

GLOBAL.STRINGS.NAMES.MERMFISHHOUSE = "Casa de Tritón Pescador"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MERMFISHHOUSE = "No huele muy bien."

GLOBAL.STRINGS.NAMES.POISONHOLE = "Agujero venenoso"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.POISONHOLE = "Creo que me mantendré alejado de eso."

GLOBAL.STRINGS.NAMES.TIGERSHARK = "Tiburón Tigre"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TIGERSHARK = "Bueno, eso es aterrador."

GLOBAL.STRINGS.NAMES.TIGERSHARKSHADOW = "Sombra de Tiburón Tigre"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TIGERSHARKSHADOW = "La sombra de la bestia!"

GLOBAL.STRINGS.NAMES.SNAKESKINFLOOR = "Alfombra de Piel de Serpiente "
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SNAKESKINFLOOR = "Realmente une la habitación."

GLOBAL.STRINGS.NAMES.TURF_MAGMAFIELD = "Suelo de Magma"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_MAGMAFIELD = "Suelo magmático."

GLOBAL.STRINGS.NAMES.TURF_JUNGLE = "Suelo de Jungla"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_JUNGLE = "Suelo muy retorcido."

GLOBAL.STRINGS.NAMES.TURF_ASH = "Suelo de Cenizas"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_ASH = "Suelo de cenizas."

GLOBAL.STRINGS.NAMES.TURF_VOLCANO = "Suelo Volcánico"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_VOLCANO = "Suelo volcánico."

GLOBAL.STRINGS.NAMES.TURF_TIDALMARSH = "Suelo de Marisma"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_TIDALMARSH = "Suelo marismático."

GLOBAL.STRINGS.NAMES.TURF_LAVAROCK = "Suelo de Roca de Lava"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_LAVAROCK = "Suelo de roca de lava."

GLOBAL.STRINGS.NAMES.TURF_MEADOW = "Suelo de Prado"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_MEADOW = "Suelo de prado."

GLOBAL.STRINGS.NAMES.SNAKE = "Serpiente"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SNAKE = "Me pregunto si me venderá algo de aceite?"

GLOBAL.STRINGS.NAMES.SNAKE_POISON = "Serpiente Venenosa"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SNAKE_POISON = "Incluso peor que una serpiente común!"

GLOBAL.STRINGS.NAMES.SNAKESKIN = "Piel de Serpiente"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SNAKESKIN = "Estoy intrigado Y repugnado."

GLOBAL.STRINGS.NAMES.SNAKE_HOLE = "Agujero de Serpiente"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SNAKE_HOLE = "Siento que hubiera podido evitarlo."

GLOBAL.STRINGS.NAMES.SNAKEOIL = "Aceite de Serpiente"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SNAKEOIL = "La etiqueta dice 'Aceite de serpiente Jay Wöundröus!'"


GLOBAL.STRINGS.NAMES.LIVINGJUNGLETREE = "Arbol de Jungla Viviente"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LIVINGJUNGLETREE = "Como cualquier otro árbol."

--jungle tree
GLOBAL.STRINGS.NAMES.JUNGLETREE = "Arbol de Jungla"
GLOBAL.STRINGS.NAMES.TREE_JUNGLE = "Arbol de Jungla"

GLOBAL.STRINGS.NAMES.JUNGLETREESEED = "Semilla de Arbol de Jungla"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.JUNGLETREESEED = "Puedo escuchar el silbido de serpientes pequeñas."

GLOBAL.STRINGS.NAMES.JUNGLE_TREE_SAPLING = "Arbolito de Jungla"

--bamboo
GLOBAL.STRINGS.NAMES.BAMBOO = "Bambú"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BAMBOO = "Tal vez pueda engañar a mis enemigos con esto?"

GLOBAL.STRINGS.NAMES.BAMBOOTREE = "Parcela de Bambú"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BAMBOOTREE = {
	GENERIC = "Parece bastante resistente.",
	BURNING = "Adiós, bambú.",
	BURNT = "Siento que podría haber evitado eso.",
	CHOPPED = "Toma eso, naturaleza!"
}

GLOBAL.STRINGS.NAMES.DUG_BAMBOOTREE = "Planta de Bambú"
GLOBAL.STRINGS.RECIPE_DESC.DUG_BAMBOOTREE = "crece, árbol de bambú"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_BAMBOOTREE = "Necesito plantar esto."

GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DEPLETED_BAMBOOTREE = "Volverá a crecer?"



GLOBAL.STRINGS.NAMES.DOYDOYBABY = "Doydoy Bebé"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOYDOYBABY = "Qué linda y pequeña, uhm, cosa."

GLOBAL.STRINGS.NAMES.DOYDOYTEEN = "Doydoy Adolescente"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOYDOYTEEN = "crece!"

GLOBAL.STRINGS.NAMES.DOYDOY = "Doydoy"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOYDOY = "Me siento extrañamente protector con este pájaro tonto."

GLOBAL.STRINGS.NAMES.DOYDOYEGG = "Huevo de Doydoy"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOYDOYEGG = "Quizás debería haberlo dejado salir del cascarón."

GLOBAL.STRINGS.NAMES.DOYDOYEGG_COOKED = "Huevo de Doydoy Frito"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOYDOYEGG_COOKED = "Una reacción química controlada ha hecho que este huevo sea más nutritivo."

GLOBAL.STRINGS.NAMES.DOYDOYEGG_CRACKED = "Huevo de Doydoy Agrietado"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOYDOYEGG_CRACKED = "Bueno, estoy seguro de que hay muchos más!"

GLOBAL.STRINGS.NAMES.DOYDOYFEATHER = "Pluma de Doydoy"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOYDOYFEATHER = "Suave Y en peligro!"

GLOBAL.STRINGS.NAMES.DOYDOYNEST = "Nido de Doydoy"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOYDOYNEST = "Es para huevos de doydoy, tonto."

GLOBAL.STRINGS.RECIPE_DESC.DOYDOYNEST = "Just doy it."
GLOBAL.STRINGS.RECIPE_DESC.DOYDOYEGG = "Puedes sacar del cascarón tu propio doydoy!"

--wildborehouse
GLOBAL.STRINGS.NAMES.WILDBOREHOUSE = "Casa de Cerdo Salvaje"
GLOBAL.STRINGS.RECIPE_DESC.WILDBOREHOUSE = "Cerdo fuera!"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WILDBOREHOUSE = "Qué casa aburrida."

--wildbore head
GLOBAL.STRINGS.NAMES.WILDBOREHEAD = "Cabeza de Cerdo Salvaje"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WILDBOREHEAD = "Huele tan mal como parece."
--wildbore 

GLOBAL.STRINGS.NAMES.WILDBORE = "Cerdo Salvaje"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WILDBORE = "No estoy salvaje acerca de eso."

--wildbore guard
GLOBAL.STRINGS.NAMES.WILDBOREGUARD = "Guardia de Cerdo Salvaje"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WILDBOREGUARD = "Qué está protegiendo?"






GLOBAL.STRINGS.NAMES.BEAVERKING_SPAWNER = "Beaverking Spawner"

GLOBAL.STRINGS.NAMES.WILDBEAVERGUARD = "Guardia de Castor Salvaje"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WILDBEAVERGUARD = "Se ve serio"

GLOBAL.STRINGS.NAMES.BEAVER_HEAD = "Cabeza de Castor"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BEAVER_HEAD = "Alguien debería contarle a la familia."

GLOBAL.STRINGS.NAMES.BEAVERTORCH = "Antorcha de Castor"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BEAVERTORCH = "Claro que parece amistoso."

GLOBAL.STRINGS.NAMES.BEAVERSKIN = "Piel de Castor"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BEAVERSKIN = "La piel de una criatura castor"

GLOBAL.STRINGS.WILDBEAVER_NAMES = {
	"Castor",
}

GLOBAL.STRINGS.NAMES.BEAVER_KING = "Rey Castor"

GLOBAL.STRINGS.WILDBEAVER_TALK_FIGHT = {
	"Te voy a morder!",
	"Vete!",
	"Volví para luchar!",
}
GLOBAL.STRINGS.WILDBEAVER_TALK_FOLLOW = {
	"Tú me entiendes",
	"Vamos a construir una presa",
	"Necesitamos más madera",
}
GLOBAL.STRINGS.WILDBEAVER_TALK_GOHOME = {
	"Voy a terminar la presa mañana",
	"Hora de dormir",
	"Te veo más tarde",
}
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WILDBEAVER = "Cuál es el nombre de esto...?!"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WILDBEAVER_HOUSE = "Donde vive el castor."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BEAVER_KING = "Este debe gobernarlos a todos."


GLOBAL.STRINGS.CHARACTERS.WILLOW.DESCRIBE.WILDBEAVER = "Tú tomas la madera, yo me quemo: te parece bien?"
GLOBAL.STRINGS.CHARACTERS.WILLOW.DESCRIBE.WILDBEAVER_HOUSE = "Todo el mundo tiene un lugar mejor que el mío..."
GLOBAL.STRINGS.CHARACTERS.WILLOW.DESCRIBE.BEAVER_KING = "Un grande para gobernarlos a todos, supongo."

GLOBAL.STRINGS.CHARACTERS.WENDY.DESCRIBE.WILDBEAVER = "Me puedo subir a su espalda? Por favor, por favor"
GLOBAL.STRINGS.CHARACTERS.WENDY.DESCRIBE.WILDBEAVER_HOUSE = "Cuando la represa se rompe, la inundación consume todo."
GLOBAL.STRINGS.CHARACTERS.WENDY.DESCRIBE.BEAVER_KING = "Rey de las represas."

GLOBAL.STRINGS.CHARACTERS.WX78.DESCRIBE.WILDBEAVER = "Come madera."
GLOBAL.STRINGS.CHARACTERS.WX78.DESCRIBE.WILDBEAVER_HOUSE = "La morada de un comedor de madera."
GLOBAL.STRINGS.CHARACTERS.WX78.DESCRIBE.BEAVER_KING = "El rey de los comedores de madera."

GLOBAL.STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WILDBEAVER = "Un primo perdido del castor canadiense?"
GLOBAL.STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WILDBEAVER_HOUSE = "Para ellos debe ser el equivalente a una represa."
GLOBAL.STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BEAVER_KING = "Un rey para gobernarlos a todos y para coordinarlos en la construcción de represas..."

GLOBAL.STRINGS.CHARACTERS.WOODIE.DESCRIBE.WILDBEAVER = "Oh, bonito. No somos parientes?"
GLOBAL.STRINGS.CHARACTERS.WOODIE.DESCRIBE.WILDBEAVER_HOUSE = "El único inmueble en el que invertiría."
GLOBAL.STRINGS.CHARACTERS.WOODIE.DESCRIBE.BEAVER_KING = "Va bien, no?"

GLOBAL.STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.WILDBEAVER = "Grandes dientitos?"
GLOBAL.STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.WILDBEAVER_HOUSE = "Los dientes viven aquí."
GLOBAL.STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.BEAVER_KING = "El más grande de todos los dientes!"

GLOBAL.STRINGS.CHARACTERS.WEBBER.DESCRIBE.WILDBEAVER = "Tú eres Woodie?"
GLOBAL.STRINGS.CHARACTERS.WEBBER.DESCRIBE.WILDBEAVER_HOUSE = "Aquí es donde viven esas criaturas."
GLOBAL.STRINGS.CHARACTERS.WEBBER.DESCRIBE.BEAVER_KING = "Todos saludan al rey madera primero!"

GLOBAL.STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.WILDBEAVER = "Vamos a hacer una batalla?"
GLOBAL.STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.WILDBEAVER_HOUSE = "La morada de aquellos castores salvajes."
GLOBAL.STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.BEAVER_KING = "Cómo puedes sorportar esta ociosidad?"
GLOBAL.STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WILDBEAVER = "Otro tipo de idiota de la aldea."
GLOBAL.STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WILDBEAVER_HOUSE = "Entonces viven aquí."
GLOBAL.STRINGS.CHARACTERS.WAXWELL.DESCRIBE.BEAVER_KING = "Eres su supervisor o qué?"
GLOBAL.STRINGS.RECIPE_DESC.WILDBEAVER_HOUSE = "Castor fuera!"
GLOBAL.STRINGS.NAMES.DOUBLE_UMBRELLAHAT = "Dumbrella"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOUBLE_UMBRELLAHAT = "Función definitivamente a la moda."
GLOBAL.STRINGS.NAMES.WILDBEAVER_HOUSE = "Casa de Castor"
-- FOI DAQUI --
STRINGS.NAMES.VENOMGLAND = "Glándula Venenosa"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.VENOMGLAND = "Solo el veneno puede curar veneno."

STRINGS.NAMES.BERRYBUSH2_SNAKE = "Arbusto de Bayas"

STRINGS.NAMES.OCTOPUSKING = "Yaarctopus"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.OCTOPUSKING = "Soy un bobo para este tipo."

STRINGS.NAMES.SWEET_POTATO_PLANTED = "Patata Dulce Plantada"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SWEET_POTATO_PLANTED = "Es una zanahoria extraña."

STRINGS.NAMES.SWEET_POTATO = "Patata Dulce"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SWEET_POTATO = "Se ve sabroso!"

STRINGS.NAMES.SWEET_POTATO_COOKED = "Patata Dulce Cocida"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SWEET_POTATO_COOKED = "Se ve incluso más sabroso!!"

STRINGS.NAMES.PARROT = "Loro"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PARROT = "Intento no comer nada con nombre."

STRINGS.NAMES.DUBLOON = "Doblones"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUBLOON = "Soy rico!!"

STRINGS.NAMES.DOYDOYFAN = "Tropical fan"
STRINGS.RECIPE_DESC.DOYDOYFAN = "Lujosamente suave, lujosamente tropical"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOYDOYFAN = "De alguna manera, la brisa sale por atrás dos veces más rápido."

STRINGS.NAMES.FABRIC = "Tela"
STRINGS.RECIPE_DESC.FABRIC = "El bambú es tan versátil!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FABRIC = "Suave tela hecha de duras raíces!"

STRINGS.NAMES.SNAKESKINHAT = "Sombrero de Piel de Serpiente"
STRINGS.RECIPE_DESC.SNAKESKINHAT = "Evita la lluvia, y luce bien haciéndolo." 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SNAKESKINHAT = "Debería repeler la lluvia de mi cabello."

STRINGS.NAMES.ARMOR_SNAKESKIN = "Chaqueta de Serpiente"
STRINGS.RECIPE_DESC.ARMOR_SNAKESKIN = "Mantente seco y correoso."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ARMOR_SNAKESKIN = "Qué elegante!!"

STRINGS.NAMES.TURF_SNAKESKINFLOOR = "Alfombra de Piel de Serpiente"
STRINGS.RECIPE_DESC.TURF_SNAKESKINFLOOR = "Realmente une la habitación."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_SNAKESKINFLOOR = "Ddddeclaración elegannnnte."

--STRINGS.NAMES.TURF_WATER_MANGROVE = "红树林地皮"
--STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_WATER_MANGROVE = "红树林地皮"

STRINGS.NAMES.TURF_BEACH = "Suelo de Playa"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_BEACH = "Suelo arenoso."

STRINGS.NAMES.COCONUT = "Coco"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.COCONUT = "Es una nuez grande."

STRINGS.NAMES.COCONUT_HALVED = "Medio Coco"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.COCONUT_HALVED = "Cuando los clickeo juntos, hacen sonidos de caballo."

STRINGS.NAMES.COCONUT_COOKED = "Coco Cocido"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.COCONUT_COOKED = "Ahora solo necesito un pastel."

STRINGS.NAMES.PALMTREE = "Palmera"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PALMTREE = "Qué tropical."

STRINGS.NAMES.PALMLEAF = "Hoja de Palma"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PALMLEAF = "Mi cabello se ve bien mojado... el problema es cuando se seca."

STRINGS.NAMES.ROCK_LIMPET = "Roca de Lapa"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ROCK_LIMPET = "Podría llenar un balde con todos esos caracoles!"

STRINGS.NAMES.LIMPETS = "Lapa"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LIMPETS = "Quizás morir de hambre no estaría tan mal."

STRINGS.NAMES.LIMPETS_COOKED = "Lapa Cocida"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LIMPETS_COOKED = "Escargotcha!"

STRINGS.NAMES.PALMLEAF_HUT = "Refugio de Hoja de Palma"
STRINGS.RECIPE_DESC.PALMLEAF_HUT = "Escapa de la lluvia. Mayormente."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PALMLEAF_HUT = "Sombra, dulce sombra."

STRINGS.NAMES.SAND_CASTLE = "Castillo de Arena"
STRINGS.RECIPE_DESC.SAND_CASTLE = "Terapéutico y relajante."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SAND_CASTLE = "Mira lo que hice!"

STRINGS.NAMES.SANDHILL = "Colina de Arena"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SANDHILL = "Será mejor que te quedes fuera de mis zapatos."

STRINGS.NAMES.SAND = "Arena"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SAND = "Una práctica pila de arena de bolsillo."

STRINGS.NAMES.SEASHELL_BEACHED = "Concha Marina Varada"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEASHELL_BEACHED = "Desecho de mar."

STRINGS.NAMES.SEASHELL = "Concha Marina"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEASHELL = "Quizás podría venderlos."

STRINGS.NAMES.CRATE = "Caja"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CRATE = "Debe haber una forma de abrirla."

STRINGS.NAMES.CRAB = "Cangrejo"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CRAB = "No sea rápido conmigo, señor."

STRINGS.NAMES.CRABHOLE = "Madriguera de Cangrejo"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CRABHOLE = "Madriguera de cangrejo"

STRINGS.NAMES.CRAB_HIDDEN = "Cangrejo Oculto"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CRAB_HIDDEN = "Me pregunto a dónde fue ese cangrejo?"

STRINGS.NAMES.SEAGULL = "Gaviota"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEAGULL = "Shuu! Búscate otra tierra!"

STRINGS.NAMES.FISH_MEAT_SMALL = "Carne de Pescado Pequeña"

STRINGS.NAMES.TROPICAL_FISH = "Pez Tropical"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TROPICAL_FISH = "Qué pez de aspecto tropical."

STRINGS.NAMES.TUNACAN = "Atún 'Boladelfín Free'"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TUNACAN = "Puedo abrirlo con un machete"

STRINGS.NAMES.TOUCAN = "Tucán"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TOUCAN = "No puedo atraparlo."

STRINGS.NAMES.RAFT = "Balsa"
STRINGS.RECIPE_DESC.RAFT = "Totalmente en buen estado para navegar."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAFT = "Esto parece adecuado."

STRINGS.NAMES.SLOTMACHINE = "Tragamonedas"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SLOTMACHINE = "Supongo que podría demorarme por un momento o dos."

STRINGS.NAMES.VINE = "Vid"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.VINE = "Tal vez pueda atar cosas con esto."

STRINGS.NAMES.BUSH_VINE = "Arbusto de Vid"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BUSH_VINE = "Está lleno de vid!!"

STRINGS.NAMES.DUG_BUSH_VINE = "Arbusto de Vid Excavado"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_BUSH_VINE = "Supongo que debería recogerlo."

STRINGS.NAMES.MACHETE = "Machete"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MACHETE = "Me gusta el corte de esta espada."
STRINGS.RECIPE_DESC.MACHETE = "Cortar cosas!"

STRINGS.NAMES.GOLDENMACHETE = "Machete Lujoso"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GOLDENMACHETE = "Corta con estilo!"
STRINGS.RECIPE_DESC.GOLDENMACHETE = "Corta cosas con ESTILO!"

STRINGS.NAMES.OBSIDIANMACHETE = "Machete de Obsidiana"
STRINGS.RECIPE_DESC.OBSIDIANMACHETE = "Corta y quema!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.OBSIDIANMACHETE = "Está caliente al tacto."

STRINGS.PULAFORA = "Hm...demasiado superficial"
STRINGS.SEMBARCO = "Dónde está mi barco? Voy a morir aquí!"

STRINGS.NAMES.CORMORANT = "Cormorán"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CORMORANT = "Apuesto a que se comió un montón de pescado."

STRINGS.NAMES.SEAWEED = "Alga Marina"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEAWEED = "Un alga. Del mar."

STRINGS.NAMES.SEAWEED_COOKED = "Alga Marina Cocida"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.COOKED = "Asado a la perfección."

STRINGS.NAMES.SEAWEED_DRIED = "Alga Marina Seca"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEAWEED_DRIED = "Salado!"

STRINGS.NAMES.SEAWEED_PLANTED = "Alga Marina"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEAWEED_PLANTED = "Eso es lo que pasa por comida aquí?"

STRINGS.NAMES.CORAL = "Coral"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CORAL = "Material de construcción viviente!"

STRINGS.NAMES.CORALREEF = "Arrecife de Coral"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CORALREEF = "Los corales formaron un arrecife!"

STRINGS.NAMES.FISHINHOLE = "Cardumen"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISHINHOLE = "Esta área parece bastante pescable." --- ATÉ AQUI ----

GLOBAL.STRINGS.NAMES.GRASS_WATER = "Hierba de Agua"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.GRASS_WATER = "Hasta aquí aparecen?"

GLOBAL.STRINGS.NAMES.TREE_MANGROVE = "Arbol de Mangle"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TREE_MANGROVE = "Bien adaptado."

GLOBAL.STRINGS.NAMES.ANTIDOTE = "Antídoto"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.ANTIDOTE = "Esto me ayudará."
GLOBAL.STRINGS.RECIPE_DESC.ANTIDOTE = "Envenenamiento curativo"

GLOBAL.STRINGS.NAMES.QUAGMIRE_SALMON = "Salmón"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.QUAGMIRE_SALMON = "Hm... Debe estar bueno."

GLOBAL.STRINGS.NAMES.QUAGMIRE_POND_SALT = "Estanque de Sal"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.QUAGMIRE_POND_SALT = "Ahora puedo poner sal en mi comida."

GLOBAL.STRINGS.NAMES.QUAGMIRE_SWAMPIG = "Cerdo de Pantano"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.QUAGMIRE_SWAMPIG = "Cerdo de pantano."

GLOBAL.STRINGS.NAMES.QUAGMIRE_SWAMPIG_HOUSE = "Casa de Cerdo de Pantano"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.QUAGMIRE_SWAMPIG_HOUSE = "Han sido mejores."

GLOBAL.STRINGS.NAMES.QUAGMIRE_SWAMPIG_HOUSE_RUBBLE = "Casa de Cerdo de Pantano"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.QUAGMIRE_SWAMPIG_HOUSE_RUBBLE = "Han sido mejores."

GLOBAL.STRINGS.NAMES.CROCODOG = "Crocoperro"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CROCODOG = "La mordida debe doler."

GLOBAL.STRINGS.NAMES.WATERCROCODOG = "Agua de Crocoperro"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WATERCROCODOG = "Debe ser más fuerte en el agua."

GLOBAL.STRINGS.NAMES.POISONCROCODOG = "Crocoperro Venenoso"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.POISONCROCODOG = "Lejos de mí, por favor!"

GLOBAL.STRINGS.NAMES.GRASSWATER = "Hierba de Agua"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.GRASSWATER = "Hierba"

GLOBAL.STRINGS.NAMES.ARMOR_SEASHELL = "Armadura de Concha Marina"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.ARMOR_SEASHELL = "Siento que pertenezco al mar."
GLOBAL.STRINGS.RECIPE_DESC.ARMOR_SEASHELL = "Más protección."

GLOBAL.STRINGS.NAMES.OXHAT = "Casco de Cuernos"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OXHAT = "Muy elegante."
GLOBAL.STRINGS.RECIPE_DESC.OXHAT = "Extra protección."

GLOBAL.STRINGS.NAMES.CHIMINEA = "Chimenea"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CHIMINEA = "Lluvia, adiós."
GLOBAL.STRINGS.RECIPE_DESC.CHIMINEA = "Protegida de la lluvia."

GLOBAL.STRINGS.NAMES.OX_HORN = "Cuerno de Buey"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OX_HORN = "Muy triste."

GLOBAL.STRINGS.NAMES.OX = "Buey"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OX = "Le gusta el agua."

GLOBAL.STRINGS.NAMES.ROWBOAT = "Bote de Remos"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.ROWBOAT = "Ahora mi aventura está completa."
GLOBAL.STRINGS.RECIPE_DESC.ROWBOAT = "Un bote más fuerte"

GLOBAL.STRINGS.NAMES.ENCRUSTEDBOAT = "Bote Incrustado"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.ENCRUSTEDBOAT = "Muy robusto."
GLOBAL.STRINGS.RECIPE_DESC.ENCRUSTEDBOAT = "Altamente resistente"

GLOBAL.STRINGS.NAMES.TURF_QUAGMIRE_PARKFIELD = "Suelo de Quagmire Parkfield"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_QUAGMIRE_PARKFIELD = "Muy elegante."

GLOBAL.STRINGS.NAMES.COTTONTREE = "Arbol de algodón"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.COTTONTREE = "Muy suave."

GLOBAL.STRINGS.NAMES.COTTONTREE_SAPLING = "Arbol de algodón joven"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.COTTONTREE_SAPLING = "Ahora puedo colocarlos en cualqueir lugar."

GLOBAL.STRINGS.NAMES.COTTONTREE_CONE = "Semilla de Arbol de Algodón"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.COTTONTREE_CONE = "Semilla?"

GLOBAL.STRINGS.NAMES.BALLPHINHOUSE = "Casa de Boladelfín"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BALLPHINHOUSE = "Debe haber mucha diversión allí."

GLOBAL.STRINGS.NAMES.BALLPHIN = "Boladelfín"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BALLPHIN = "Qué bonito es."

GLOBAL.STRINGS.NAMES.JELLYFISH = "Medusa"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.JELLYFISH = "Debe quemar."

GLOBAL.STRINGS.NAMES.JELLYFISH_DEAD = "Medusa Muerta"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.JELLYFISH_DEAD = "Todavía quema."

GLOBAL.STRINGS.NAMES.JELLYFISH_COOKED = "Medusa Cocida"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.JELLYFISH_COOKED = "Y no es que sean sabrosas!"

GLOBAL.STRINGS.NAMES.JELLYJERKY = "Cecina Gelatinosa"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.JELLYJERKY = "Sin sustancias quemantes.."

GLOBAL.STRINGS.NAMES.JELLYFISH_PLANTED = "Medusa"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.JELLYFISH_PLANTED = "Cómo es?"

GLOBAL.STRINGS.NAMES.LOGRAFT = "Balsa de Tronco"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LOGRAFT = "balsa de tronco...?"
GLOBAL.STRINGS.RECIPE_DESC.LOGRAFT = "Esto parece... una especie de bote..."

GLOBAL.STRINGS.NAMES.FROG_POISON = "Rana Venenosa"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FROG_POISON = "Se ve peor de lo normal."

GLOBAL.STRINGS.NAMES.SHARKITTENSPAWNER = "Casa de Sharkitten"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHARKITTENSPAWNER = "Dónde está su madre?"

GLOBAL.STRINGS.NAMES.WHALE_BLUE = "Ballena Azul"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WHALE_BLUE = "Esa ballena tiene problemas emocionales."

GLOBAL.STRINGS.NAMES.WHALE_WHITE = "Ballena Blanca"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WHALE_WHITE = "Parece un luchador."

GLOBAL.STRINGS.NAMES.WHALE_CARCASS_WHITE = "Cuerpo de Ballena Blanca"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WHALE_CARCASS_WHITE = "Bruto. Creo que la hinchazón ha comenzado."

GLOBAL.STRINGS.NAMES.WHALE_CARCASS_BLUE = "Cuerpo de Ballena Azul"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WHALE_CARCASS_BLUE = "Bruto. Creo que la hinchazón ha comenzado."

GLOBAL.STRINGS.NAMES.LOBSTER_DEAD_COOKED = "Langosta Muerta Cocida"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LOBSTER_DEAD_COOKED = "Deliciosa Lanwosta."

GLOBAL.STRINGS.NAMES.LOBSTER_DEAD = "Langosta Muerta"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LOBSTER_DEAD = "Deberías cocinarte bien."

GLOBAL.STRINGS.NAMES.FISH_RAW_SMALL_COOKED = "Pescado Crudo Pequeño Cocido"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH_RAW_SMALL_COOKED = "Un pequeño bocado de Pescado Cocido."

GLOBAL.STRINGS.NAMES.FISH_RAW_SMALL = "Pescado Crudo Pequeño"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH_RAW_SMALL = "Un pequeño bocado de pescado."

GLOBAL.STRINGS.NAMES.FISH_MED_COOKED = "Pescado Mediano Cocido"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH_MED_COOKED = "Grillado a la perfección."

GLOBAL.STRINGS.NAMES.FISH_MED = "Pescado Mediano"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH_MED = "Pezperro muerto."

GLOBAL.STRINGS.NAMES.SPOILED_FISH = "Pescado Estropeado"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPOILED_FISH = "No tengo mucha curiosidad por el olor."

GLOBAL.STRINGS.NAMES.FISH_RAW = "Pescado Crudo"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH_RAW = "Un pedazo de carne de pescado."

GLOBAL.STRINGS.NAMES.DEAD_SWORDFISH = "Pez Espada Muerto"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DEAD_SWORDFISH = "Mejor no correr con esto."

GLOBAL.STRINGS.NAMES.BLUBBER = "Grasa de Ballena"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BLUBBER = "Blandito."

GLOBAL.STRINGS.NAMES.KNIGHTBOAT_CANNONSHOT = "tiro de cañón de barco de caballero"

GLOBAL.STRINGS.NAMES.KNIGHTBOAT = "Caballero Flotador"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.KNIGHTBOAT = "Sal del camino acuático, maníaco!"

GLOBAL.STRINGS.NAMES.OCTOPUSCHEST = "Cofre de Pulpo"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OCTOPUSCHEST = "Espero que esa cosa sea impermeable."

GLOBAL.STRINGS.NAMES.KRAKEN = "Quacken"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.KRAKEN = "Ahora no es el momento para que yo sea el sabio Quacken!"

GLOBAL.STRINGS.NAMES.KRAKENCHEST = "Cofre de Quacken"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.KRAKENCHEST = "Para el vencedor, el botín."

GLOBAL.STRINGS.NAMES.KRAKEN_TENTACLE = "Tentáculo de Quacken"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.KRAKEN_TENTACLE = "Una bestia que nunca duerme."

GLOBAL.STRINGS.NAMES.SOLOFISH = "Pezperro"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SOLOFISH = "Tiene ese olor a perro mojado."

GLOBAL.STRINGS.NAMES.SWORDFISH = "Pez Espada"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SWORDFISH = "Creo que este pez evolucionó para hacerme correr."

GLOBAL.STRINGS.NAMES.LOBSTER_LAND= "Lanwosta"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LOBSTER_LAND= "Ese desaliño está durmiendo."

GLOBAL.STRINGS.NAMES.SHARX = "Sabueso de Mar"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHARX = "Estas cosas seguro son persistentes."

GLOBAL.STRINGS.NAMES.STUNGRAY = "Raya de Hedor"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.STUNGRAY = "Creo que mantendré mi distancia."

GLOBAL.STRINGS.NAMES.LUGGAGECHEST = "Cofre de Vapor"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LUGGAGECHEST = "Parece un cofre de vapor premier."

GLOBAL.STRINGS.NAMES.REDBARREL = "Barril de Pólvora"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.REDBARREL = "Qué original."

GLOBAL.STRINGS.NAMES.LOBSTERHOLE = "Cueva de Lanwosta"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LOBSTERHOLE = "Ese desaliñado está durmiendo."

GLOBAL.STRINGS.NAMES.DEBRIS_1 = "Escombros"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DEBRIS_1 = "Había alguien aquí antes que yo!"

GLOBAL.STRINGS.NAMES.DEBRIS_2 = "Escombros"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DEBRIS_2 = "Había alguien aquí antes que yo!"

GLOBAL.STRINGS.NAMES.DEBRIS_3 = "Escombros"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DEBRIS_3 = "Había alguien aquí antes que yo!"

GLOBAL.STRINGS.NAMES.DEBRIS_4 = "Escombros"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DEBRIS_4 = "Había alguien aquí antes que yo!"

GLOBAL.STRINGS.NAMES.BOATREPAIRKIT = "Kit de Reparación para Botes"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOATREPAIRKIT = "Esto agregará algo de flotabilidad a mi bote."
GLOBAL.STRINGS.RECIPE_DESC.BOATREPAIRKIT = "Mantente a flote en ese bote!"

GLOBAL.STRINGS.NAMES.WRECK = "Bote Hundido"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WRECK = "Pobre botecito."

GLOBAL.STRINGS.NAMES.PIRATEGHOST = "Pirata Fantasma"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PIRATEGHOST = "Tuvo un final terrible. Yo también lo tendré si no salgo de aquí."

GLOBAL.STRINGS.NAMES.WRECKOF = "Bote Hundido de %s"
GLOBAL.STRINGS.NAMES.SHIPNAMES =
{"Nautilus",
"Mackay-Bennett",
"Mary Celeste",
"Beagle",
"Santa Maria",
"Bluenose",
"Mauretania",
"Endeavour",
"Edmund Fitzgerald",
"Pequod",
"Mississinewa",
"African Queen",
"Mont-Blanc",
"Caine",
 "Pharaoh",
 "Minnow",
 "Syracusia",
 "Barón de Renfrew",
 "Ariel",
 "Hispaniola",}

GLOBAL.STRINGS.NAMES.MUSSEL_STICK = "Palito de Mejillones"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSSEL_STICK = "Realmente voy a pegarme a esos mejillones."
GLOBAL.STRINGS.RECIPE_DESC.MUSSEL_STICK = "Mussel Stick."

GLOBAL.STRINGS.NAMES.MUSSEL_FARM = "Granja de Mejillones"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSSEL_FARM = "Me pregunto si son de Bruselas."

GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSSEL_FARM = "Me pregunto si son de Bruselas."
GLOBAL.STRINGS.NAMES.MUSSEL_FARM = "Granja de Mejillones"

GLOBAL.STRINGS.NAMES.MUSSEL_COOKED = "Mejillón Cocido"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSSEL_COOKED = "Cocino un mejillón mezquino."

GLOBAL.STRINGS.NAMES.MUSSEL = "Mejillones"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSSEL = "Me pregunto si son de Bruselas."

GLOBAL.STRINGS.NAMES.MOSQUITO_POISON = "Mosquito Venenoso"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOSQUITO_POISON = "Estos malditos mosquitos portan una terrible enfermedad."

GLOBAL.STRINGS.NAMES.WATERYGRAVE= "Sepultura Acuática"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WATERYGRAVE = "Claro, podría pescarlo. Pero debería?"

GLOBAL.STRINGS.NAMES.BIOLUMINESCENCE= "Bioluminiscencia"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BIOLUMINESCENCE = "Hacen un brillo tranquilizador."

GLOBAL.STRINGS.NAMES.BOTTLELANTERN= "Linterna de Botella"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOTTLELANTERN = "Una botella llena de luz."
GLOBAL.STRINGS.RECIPE_DESC.BOTTLELANTERN = "El océano resplandeciente cabe en una botella."

GLOBAL.STRINGS.NAMES.MESSAGEBOTTLEEMPTY1= "Botella Vacía"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MESSAGEBOTTLEEMPTY1 = "Solo una botella vacía."
GLOBAL.STRINGS.RECIPE_DESC.MESSAGEBOTTLEEMPTY1 = "No te olvides de reciclar!"

GLOBAL.STRINGS.NAMES.ARMOUREDBOAT = "Bote Blindado"
GLOBAL.STRINGS.RECIPE_DESC.ARMOUREDBOAT = "Pague por este fuerte bote."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.ARMOUREDBOAT = "Ese es un bote durable."

GLOBAL.STRINGS.NAMES.CARGOBOAT = "Bote de Carga"
GLOBAL.STRINGS.RECIPE_DESC.CARGOBOAT = "Acumulando en el mar!"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CARGOBOAT = "Tiene espacio para todas mis cosas!"

GLOBAL.STRINGS.NAMES.CORAL_BRAIN = "Cerebro Coral"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CORAL_BRAIN = "Alimento para el pensamiento."

GLOBAL.STRINGS.NAMES.CORAL_BRAIN_ROCK = "Cerebro Coral"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CORAL_BRAIN_ROCK = "Me pregunto qué está tramando..."

GLOBAL.STRINGS.NAMES.SANDBAG = "Bolsa de Arena"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SANDBAG = "Esto debería mantener el agua fuera."

GLOBAL.STRINGS.NAMES.SANDBAG_ITEM = "Bolsa de Arena"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SANDBAG_ITEM = "Tecnología de arena, en marcha."
GLOBAL.STRINGS.RECIPE_DESC.SANDBAG_ITEM = "Arena. La mayor enemiga del agua.."

GLOBAL.STRINGS.NAMES.LIMESTONE = "Caliza"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LIMESTONE = "Podría ser un material de construcción útil."
GLOBAL.STRINGS.RECIPE_DESC.LIMESTONE = "Piedra, con un toque de lima.."

GLOBAL.STRINGS.NAMES.CUTLASS = "Chafarote Supremo"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUTLASS = "Espero que esta espada no empiece a apestar..."
GLOBAL.STRINGS.RECIPE_DESC.CUTLASS = "Los peces fueron perjudicados en la fabricación de esto.."

GLOBAL.STRINGS.NAMES.AERODYNAMICHAT = "Sombrero Aerodinámico"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.AERODYNAMICHAT = "Realmente corta a través del aire!"
GLOBAL.STRINGS.RECIPE_DESC.AERODYNAMICHAT = "Diseño aerodinámico para un viaje eficiente."

GLOBAL.STRINGS.NAMES.SHARK_FIN = "Aleta de Tiburón"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHARK_FIN = "Una aleta elegante."

GLOBAL.STRINGS.NAMES.RAINBOWJELLYFISH = "Medusa Arcoiris"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAINBOWJELLYFISH = "Esta criatura es ciencia pura!"

GLOBAL.STRINGS.NAMES.RAINBOWJELLYFISH_DEAD = "Medusa Arcoiris Muerta"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAINBOWJELLYFISH_DEAD = "Vivió una buena vida."

GLOBAL.STRINGS.NAMES.RAINBOWJELLYFISH_COOKED = "Medusa Arcoiris Cocida"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAINBOWJELLYFISH_COOKED = "Está todo retorcido."

GLOBAL.STRINGS.NAMES.RAINBOWJELLYJERKY = "Cecina Arcoiris"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAINBOWJELLYJERKY = "Sería un idiota si no lo comiera."

GLOBAL.STRINGS.NAMES.RAINBOWJELLYFISH_PLANTED = "Medusa Arcoiris"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAINBOWJELLYFISH_PLANTED = "La ciencia funciona de maneras misteriosas y obscenas."

GLOBAL.STRINGS.NAMES.BANANAPOP = "Palito de Banana"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BANANAPOP = "No, no congelación del cerebro!¡Necesito eso para la ciencia!"

GLOBAL.STRINGS.NAMES.CEVICHE = "Ceviche"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CEVICHE = "Puedo conseguir un bowl más grande? Este se ve un poco enclenque."

GLOBAL.STRINGS.NAMES.SWEETPOTATOSOUFFLE = "Soufflé de Patatas Dulces"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SWEETPOTATOSOUFFLE = "Los soufflé de patatas dulces son una tendencia creciente."

GLOBAL.STRINGS.NAMES.SEAFOODGUMBO = "Gumbo de Mariscos"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEAFOODGUMBO = "Es un gumbo de mariscos tamaño jumbo."

GLOBAL.STRINGS.NAMES.SURFNTURF = "Mar y Tierra"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SURFNTURF = "Es perfecto!"

GLOBAL.STRINGS.NAMES.SHARKFINSOUP = "Sopa de Aleta de Tiburón"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHARKFINSOUP = "Es tiburón acabado!"

GLOBAL.STRINGS.NAMES.MUSSELBOUILLABAISE = "Bouillabaise de Mejillón"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSSELBOUILLABAISE = "Imagina los experimentos que podría ejecutar en él!"

GLOBAL.STRINGS.NAMES.MONSTERTARTARE = "Tártara Monstruosa"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MONSTERTARTARE = "Tiene que haber algo más para comer por aquí."

GLOBAL.STRINGS.NAMES.LOBSTERDINNER = "Cena de Lanwosta"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LOBSTERDINNER = "Si lo como en la mañana sigue siendo cena?."

GLOBAL.STRINGS.NAMES.LOBSTERBISQUE = "Bisque de Lanwosta"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LOBSTERBISQUE = "Podría usar más sal, pero eso no es asunto mío."

GLOBAL.STRINGS.NAMES.FRESHFRUITCREPES = "Crepes de Frutas Frescas"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FRESHFRUITCREPES = "Fruta azucarada! Parte de un desayuno equilibrado."

GLOBAL.STRINGS.NAMES.BISQUE = "Bisque"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BISQUE = "Cocinar eso seguro me mantuvo ocupado!"

GLOBAL.STRINGS.NAMES.CALIFORNIAROLL = "California Roll"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CALIFORNIAROLL = "Pero no tengo palillos."

GLOBAL.STRINGS.NAMES.JELLYOPOP = "Gelatina en Palito"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.JELLYOPOP = "Gelatina directo a mi boca!"

GLOBAL.STRINGS.NAMES.PORTO_RAFT = "Balsa"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTO_RAFT = "Esto parece adecuado."
STRINGS.RECIPE_DESC.PORTO_RAFT = "Totalmente en buen estado para navegar."

GLOBAL.STRINGS.NAMES.PORTO_ARMOUREDBOAT = "Bote Blindado"
GLOBAL.STRINGS.RECIPE_DESC.PORTO_ARMOUREDBOAT = "Pague por este fuerte bote."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTO_ARMOUREDBOAT = "Ese es un bote resistente."

GLOBAL.STRINGS.NAMES.PORTO_CARGOBOAT = "Bote de Carga"
GLOBAL.STRINGS.RECIPE_DESC.PORTO_CARGOBOAT = "Acumulando en el mar!"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTO_CARGOBOAT = "Tiene espacio para todas mis cosas!"

GLOBAL.STRINGS.NAMES.PORTO_LOGRAFT = "Balsa de Tronco"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTO_LOGRAFT = "balsa de tronco...?"
GLOBAL.STRINGS.RECIPE_DESC.PORTO_LOGRAFT = "Esto parece... una especie de bote..."

GLOBAL.STRINGS.NAMES.PORTO_ROWBOAT = "Bote de Remos"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTO_ROWBOAT = "Ahora mi aventura está completa."
GLOBAL.STRINGS.RECIPE_DESC.PORTO_ROWBOAT = "Un bote más fuerte"

GLOBAL.STRINGS.NAMES.PORTO_ENCRUSTEDBOAT = "Bote Incrustado"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTO_ENCRUSTEDBOAT = "Muy robusto."
GLOBAL.STRINGS.RECIPE_DESC.PORTO_ENCRUSTEDBOAT = "Altamente resistente"

GLOBAL.STRINGS.NAMES.PRIMEAPE = "Primate"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PRIMEAPE = "Esas cosas van a ser el final de mí."

GLOBAL.STRINGS.NAMES.PRIMEAPEBARREL = "Choza de Primate"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PRIMEAPEBARREL = "Aquí ser malvado."

GLOBAL.STRINGS.NAMES.MONKEYBALL = "Pelota de Mono"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MONKEYBALL = "Tengo un extraño deseo de nombrarlo después de mí."
GLOBAL.STRINGS.RECIPE_DESC.MONKEYBALL = "Ponte a hacer el trabajo de monos."

GLOBAL.STRINGS.NAMES.NEEDLESPEAR = "Espina de Cactus"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.NEEDLESPEAR = "Me alegro de no haber pisado esto."
GLOBAL.STRINGS.RECIPE_DESC.NEEDLESPEAR = "Espina de Cactus"

GLOBAL.STRINGS.NAMES.PEG_LEG = "Pata de Palo"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PEG_LEG = "Puedo realizar amputaciones si alguien quiere usarlo de verdad."
GLOBAL.STRINGS.RECIPE_DESC.PEG_LEG = "Pata de Palo"

GLOBAL.STRINGS.NAMES.SPEAR_POISON = "Lanza Venenosa"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPEAR_POISON = "Ahora es extra mortal."
GLOBAL.STRINGS.RECIPE_DESC.SPEAR_POISON = "Golpéalos con un palo enfermo."

GLOBAL.STRINGS.NAMES.MESSAGEBOTTLE1 = "Mensaje en la Botella"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MESSAGEBOTTLE1 = "Alguien me escribió una nota!."

GLOBAL.STRINGS.NAMES.BURIEDTREASURE = "X del Tesoro"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BURIEDTREASURE = "Por favor sé un buen tesoro!"

GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.COFFEEBUSH = "Creo que necesita ser fertilizado."

GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.JUNGLETREE = "Ese árbol necesita un corte de cabello."

GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.JUNGLETREE_BURNT = "Qué desperdicio de madera."

GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.JUNGLETREE_STUMP = "Toma eso, naturaleza!"

GLOBAL.STRINGS.NAMES.SHARK_GILLS = "Branquias de Tiburón"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHARK_GILLS = "Desearía tener branquias."

GLOBAL.STRINGS.RECIPE_DESC.DOUBLE_UMBRELLAHAT = "Función definitivamente a la moda."

GLOBAL.STRINGS.NAMES.GRASSNOVA = "Hierba"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.GRASSNOVA = "Es un mechón de hierba."

GLOBAL.STRINGS.RECIPE_DESC.DOUBLE_UMBRELLAHAT = "Paraguas Doble"

GLOBAL.STRINGS.NAMES.SAIL = "Vela"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SAIL = "Esto realmente debería transformar mi experiencia de navegación.."
GLOBAL.STRINGS.RECIPE_DESC.SAIL = "Atrapa el viento!"

GLOBAL.STRINGS.NAMES.CLOTHSAIL = "Vela de Tela"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CLOTHSAIL = "Ese viento no se está escapando ahora!"
GLOBAL.STRINGS.RECIPE_DESC.CLOTHSAIL = "Atrapa aún más viento!"

GLOBAL.STRINGS.NAMES.SNAKESKINSAIL = "Vela de Piel de Serpiente"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SNAKESKINSAIL = "Escamarlo y navegarlo!"
GLOBAL.STRINGS.RECIPE_DESC.SNAKESKINSAIL = "Atrapador de viento resistente."

GLOBAL.STRINGS.NAMES.FEATHERSAIL = "Vela de Plumas"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FEATHERSAIL = "Es ligera como una pluma!"
GLOBAL.STRINGS.RECIPE_DESC.FEATHERSAIL = "Como el ala de un pájaro, para tu bote!"

GLOBAL.STRINGS.NAMES.IRONWIND = "Viento de Hierro"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.IRONWIND = "Así es como un científico debería viajar.."
GLOBAL.STRINGS.RECIPE_DESC.IRONWIND = "Motorizado!"

GLOBAL.STRINGS.NAMES.WOODLEGSSAIL = "Vela de Woodlegs"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOODLEGSSAIL = "La vela pirata por excelencia."
GLOBAL.STRINGS.RECIPE_DESC.WOODLEGSSAIL = "Me convertiré en pirata!"

GLOBAL.STRINGS.NAMES.BOAT_LANTERN = "Linterna de Bote"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOAT_LANTERN = "Esto hará maravillas para mi visión nocturna!!"
GLOBAL.STRINGS.RECIPE_DESC.BOAT_LANTERN = "Arroja un poco de luz a la situación."

GLOBAL.STRINGS.NAMES.BOAT_TORCH = "Antorcha de Bote"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOAT_TORCH = "Esto mantendrá mis manos libres."
GLOBAL.STRINGS.RECIPE_DESC.BOAT_TORCH = "Nos vemos en el mar."

GLOBAL.STRINGS.NAMES.BOATCANNON = "Cañón de Barco"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOATCANNON = "Lo único mejor que un bote es un bote con cañón."
GLOBAL.STRINGS.RECIPE_DESC.BOATCANNON = "Te devuelve tu bote."

GLOBAL.STRINGS.NAMES.WOODLEGS_BOATCANNON = "Cañón Pirata"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOODLEGS_BOATCANNON = "Digno de un pirata"
GLOBAL.STRINGS.RECIPE_DESC.WOODLEGS_BOATCANNON = "Bien reforzado"

GLOBAL.STRINGS.NAMES.QUACKERINGRAM = "Ariete de Quacken"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.QUACKERINGRAM = "SMASH!"
GLOBAL.STRINGS.RECIPE_DESC.QUACKERINGRAM = "Mejor todos salgan de su camino"

GLOBAL.STRINGS.NAMES.QUACKENDRILL = "Taladro de Quacken"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.QUACKENDRILL = "Un implemento de perforación en aguas profundas"
GLOBAL.STRINGS.RECIPE_DESC.QUACKENDRILL = "Para el graznido en el mar profundo"

GLOBAL.STRINGS.NAMES.QUACKENBEAK = "Pico de Quacken"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.QUACKENBEAK = "Si ese bruto no puede sujetar su boca, entonces yo lo haré."

GLOBAL.STRINGS.NAMES.TRAWLNET = "Red de Arrastre"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TRAWLNET = "Definitivamente se está hundiendo."
GLOBAL.STRINGS.RECIPE_DESC.TRAWLNET = "El paciente pescador siempre es recompensado."

STRINGS.NAMES.GLASS_SHARDS = "Fragmentos de vidrio"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GLASS_SHARDS = "La temperatura alta convierte la arena en vidrio imperfecto."
STRINGS.RECIPE_DESC.GLASS_SHARDS = "Fragmentos de tu corazón."

STRINGS.NAMES.SHARD_SWORD = "Espada de Fragmentos"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHARD_SWORD = "La pluma es más poderosa."
STRINGS.RECIPE_DESC.SHARD_SWORD = "Para rebanar seres de pesadilla."

STRINGS.NAMES.SHARD_BEAK = "Pico de Fragmentos"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHARD_BEAK = "Un instrumento de deconstrucción."
STRINGS.RECIPE_DESC.SHARD_BEAK = "Rompe nidos fortificados."

STRINGS.NAMES.PORTO_SURFBOARD = "Tabla de Surf"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTO_SURFBOARD = "Si estuviera en mi tabla de surf, podría atraparte."
STRINGS.RECIPE_DESC.PORTO_SURFBOARD = "Hang ten!"

STRINGS.NAMES.SURFBOARD = "Tabla de Surf"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SURFBOARD = "Si estuviera en mi tabla de surf, podría atraparte.."
STRINGS.RECIPE_DESC.SURFBOARD = "Hang ten!"

STRINGS.NAMES.PORTO_WOODLEGSBOAT = "Bote Pirata"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTO_WOODLEGSBOAT = "Un buque adecuado para un canalla."
STRINGS.RECIPE_DESC.PORTO_WOODLEGSBOAT = "Ve a hacer cosas de pirata."

STRINGS.NAMES.PORTO_WOODLEGSBOAT = "Bote Pirata"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTO_WOODLEGSBOAT = "Un buque adecuado para un canalla."
STRINGS.RECIPE_DESC.PORTO_WOODLEGSBOAT = "Ve a hacer cosas de pirata."

STRINGS.NAMESWOODLEGSBOATAMIGO = "Pirate Boat"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOODLEGSBOATAMIGO = "Un buque adecuado para un canalla."
STRINGS.RECIPE_DESC.WOODLEGSBOATAMIGO = "Ve a hacer cosas de pirata."

STRINGS.NAMES.WOODLEGSBOATAMIGO = "Pirate Boat"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOODLEGSBOATAMIGO = "A vessel fit for a scallywag."
STRINGS.RECIPE_DESC.WOODLEGSBOATAMIGO = "Ve a hacer cosas de pirata."

STRINGS.NAMES.TURBINE_BLADES = "Viento Férreo"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURBINE_BLADES = "Quizás esto impulsó esa tormenta bestial?"

STRINGS.NAMES.TRAWLNETDROPPED = "Red de Arrastre"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TRAWLNETDROPPED = "Definitivamente se está hundiendo."

STRINGS.NAMES.SHARKITTEN = "Sharkitten"

STRINGS.NAMES.SAPLINGNOVA = "Arbolito"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SAPLINGNOVA = "Podría estar bien si fuera más fresco."

STRINGS.NAMES.PORTAL_SHIPWRECKED = "Bote Marinero"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTAL_SHIPWRECKED = "Está roto."

STRINGS.NAMES.BUOY = "Boya"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BUOY = "Awww sí, Boya!."
STRINGS.RECIPE_DESC.BUOY = "Marca tu lugar en el agua."

STRINGS.NAMES.ARMOR_LIFEJACKET = "Chaleco Salvavidas"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ARMOR_LIFEJACKET = "Me mantiene a flote, sin mi bote!."
STRINGS.RECIPE_DESC.ARMOR_LIFEJACKET = "Seguridad ante todo!"

STRINGS.WALLY1 = "Tonto."
STRINGS.WALLY2 = "Buena navegación"

STRINGS.NAMES.SURFBOARDITEM = "Tabla de Surf"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.LUCKYHAT = "Me hace parecer vil... Quiero decir, aterrador!?"
STRINGS.NAMES.LUCKYHAT = "Sombrero de la Suerte"
STRINGS.RECIPE_DESC.LUCKYHAT = "Olfatea tesoros."

STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPICEPACK = "Mi bolsa de trucos de chef!"
STRINGS.NAMES.SPICEPACK = "Bolsa de Cocinero"
STRINGS.RECIPE_DESC.SPICEPACK = "Refresque sus productos alimenticios."

STRINGS.CHARACTERS.GENERIC.DESCRIBE.PIRATEHAT = "Adecuado para un canalla despiadado. O yo."
STRINGS.NAMES.PIRATEHAT = "Sombrero Pirata"
STRINGS.RECIPE_DESC.PIRATEHAT = "Es la vida de un pirata para tí!"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CAPTAINHAT = "El atuendo propio de navegación!"
STRINGS.NAMES.CAPTAINHAT = "Sombrero de Capitán"
STRINGS.RECIPE_DESC.CAPTAINHAT = "Usa uno. Tu bote te respetará más."

STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTABLECOOKPOT = "Qué nuevas aventuras debemos emprender, vieja amiga?"
STRINGS.NAMES.PORTABLECOOKPOT = "Olla de Barro Portátil"
STRINGS.NAMES.PORTABLECOOKPOT_ITEM = "Olla de Barro Portátil"
STRINGS.RECIPE_DESC.PORTABLECOOKPOT_ITEM = "Qué nuevas aventuras debemos emprender, vieja amiga?"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.THATCHPACK = "I call it a thatchel"
STRINGS.NAMES.THATCHPACK = "Mochila de Hoja de Palma"
STRINGS.RECIPE_DESC.THATCHPACK = "Lleva una carga liviana."

STRINGS.NAMES.PARROT_PIRATE = "Loro"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PARROT_PIRATE = "Intento no comer nada con nombre."

STRINGS.NAMES.SEAGULLWATER = "Gaviota"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEAGULLWATER = "Shuu! Búscate otra tierra!"

GLOBAL.STRINGS.NAMES.ICEMAKER = "Ice Maker 3000"
GLOBAL.STRINGS.RECIPE_DESC.ICEMAKER = "Ice, ice, baby!"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.ICEMAKER = "Machine is doing very good job!"

GLOBAL.STRINGS.RECIPE_DESC.PRIMEAPEBARREL = "More monkeys!"

GLOBAL.STRINGS.RECIPE_DESC.BALLPHINHOUSE = "Ballphin House"

STRINGS.NAMES.DORSALFIN = "Dorsalfin"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DORSALFIN = "Dorsalfin"

STRINGS.NAMES.CORALLARVE = "Coral Larve"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CORALLARVE = "Coral Larve"

GLOBAL.STRINGS.NAMES.NUBBIN = "Nubbin"
GLOBAL.STRINGS.RECIPE_DESC.NUBBIN = "Nubbin!"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.NUBBIN = "Nubbin!"

STRINGS.NAMES.SEAWEED_STALK = "Seaweed Stalk"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEAWEED_STALK = "Seaweed Stalk"

STRINGS.NAMES.COCONADE = "Coconade"
GLOBAL.STRINGS.RECIPE_DESC.COCONADE = "Coconade!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.COCONADE = "Coconade"

STRINGS.NAMES.PIRATEPACK = "Pirate Pack"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PIRATEPACK = "Pirate Pack"

GLOBAL.STRINGS.NAMES.TAR_EXTRACTOR = "Tar Extractor"
GLOBAL.STRINGS.RECIPE_DESC.TAR_EXTRACTOR = "Tar Extractor!"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TAR_EXTRACTOR = "Tar Extractor!"

STRINGS.NAMES.TAR_POOL = "Tar Pool"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TAR_POOL = "Tar Pool"

STRINGS.NAMES.TAR = "Tar"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TA = "Tar"

STRINGS.NAMES.TAR_TRAP = "Tar Trap"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TAR_TRAP = "Tar Trap"

GLOBAL.STRINGS.NAMES.FISH_FARM = "Fish Farm"
GLOBAL.STRINGS.RECIPE_DESC.FISH_FARM = "Fish Farm!"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH_FARM = "Fish Farm!"

STRINGS.NAMES.ROE = "Roe"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ROE = "Roe"

STRINGS.NAMES.ROE_COOKED = "Roe Cooked"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ROE_COOKED = "Roe Cooked"

STRINGS.NAMES.FISH3 = "Purple Grouper"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH3 = "Purple Grouper"

STRINGS.NAMES.FISH3_COOKED = "Purple Grouper Cooked"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH3_COOKED = "Purple Grouper Cooked"

STRINGS.NAMES.FISH4 = "Pierrot Fish"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH4 = "Pierrot Fish"

STRINGS.NAMES.FISH4_COOKED = "Pierrot Fish Cooked"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH4_COOKED = "Pierrot Fish Cooked"

STRINGS.NAMES.FISH5 = "Neon Quattro"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH5 = "Neon Quattro"

STRINGS.NAMES.FISH5_COOKED = "Neon Quattro Cooked"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH5_COOKED = "Neon Cooked"

STRINGS.NAMES.FISH5_COOKED = "Neon Quattro Cooked"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH5_COOKED = "Delicious, as you would expect"

GLOBAL.STRINGS.NAMES.BLOWDART_POISON = "Blowdart Poison"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BLOWDART_POISON = "Blowdart Poison."
GLOBAL.STRINGS.RECIPE_DESC.BLOWDART_POISON = "Blowdart Poison"

GLOBAL.STRINGS.NAMES.SEATRAP = "Sea Trap"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEATRAP = "Sea Trap."
GLOBAL.STRINGS.RECIPE_DESC.SEATRAP = "Sea Trap"

GLOBAL.STRINGS.NAMES.SEA_CHIMINEA = "Sea Chiminea"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEA_CHIMINEA = "Sea Chiminea."
GLOBAL.STRINGS.RECIPE_DESC.SEA_CHIMINEA = "Sea Chiminea"

GLOBAL.STRINGS.NAMES.TROPICALBOUILLABAISSE = "Tropical Bouillabaisse"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TROPICALBOUILLABAISSE = "Tropical Bouillabaisse."

GLOBAL.STRINGS.NAMES.CAVIAR = "Caviar"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CAVIAR = "Caviar."

GLOBAL.STRINGS.NAMES.OX_FLUTE = "Ox Flute"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OX_FLUTE = "Ox Flute."
GLOBAL.STRINGS.RECIPE_DESC.OX_FLUTE = "Ox Flute"

GLOBAL.STRINGS.NAMES.OXBABY = "Ox baby"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OXBABY = "Ox baby."

GLOBAL.STRINGS.NAMES.RESEARCHLAB5 = "researchlab5"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.RESEARCHLAB5 = "researchlab5."
GLOBAL.STRINGS.RECIPE_DESC.RESEARCHLAB5 = "researchlab5"

GLOBAL.STRINGS.NAMES.SEA_YARD = "Sea Yard"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEA_YARD = "Sea Yard."
GLOBAL.STRINGS.RECIPE_DESC.SEA_YARD = "Sea Yard"

GLOBAL.STRINGS.NAMES.TARLAMP = "Tar Lamp."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TARLAMP = "Tar Lamp."
GLOBAL.STRINGS.RECIPE_DESC.TARLAMP = "Tar Lamp"

GLOBAL.STRINGS.NAMES.TARSUIT = "Tar Suit"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TARSUIT = "Tar Suit."
GLOBAL.STRINGS.RECIPE_DESC.TARSUIT = "Tar Suit"

GLOBAL.STRINGS.NAMES.BLUBBERSUIT = "Blubber Suit"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BLUBBERSUIT = "Blubber Suit."
GLOBAL.STRINGS.RECIPE_DESC.BLUBBERSUIT = "Blubber Suit"

GLOBAL.STRINGS.NAMES.MUSSEL_BED = "Mussel Bed"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSSEL_BED = "Mussel Bed."
GLOBAL.STRINGS.RECIPE_DESC.MUSSEL_BED = "Mussel Bed"

GLOBAL.STRINGS.NAMES.WATERCHEST1 = "Water Chest"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WATERCHEST1 = "Water Chest."
GLOBAL.STRINGS.RECIPE_DESC.WATERCHEST1 = "Water Chest"

GLOBAL.STRINGS.RECIPE_DESC.SURFBOARDITEM = "Cowabunga dudes!"

GLOBAL.STRINGS.NAMES.HAIL_ICE = "Hail Ice"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.HAIL_ICE = "Hail Ice."
GLOBAL.STRINGS.RECIPE_DESC.ICE = "Ice"

GLOBAL.STRINGS.NAMES.TELESCOPE = "Telescope"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TELESCOPE = "Telescope."
GLOBAL.STRINGS.RECIPE_DESC.TELESCOPE = "Telescope"

GLOBAL.STRINGS.NAMES.SUPERTELESCOPE = "Supertelescope"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SUPERTELESCOPE = "Supertelescope."
GLOBAL.STRINGS.RECIPE_DESC.SUPERTELESCOPE = "Supertelescope"

GLOBAL.STRINGS.NAMES.TIGEREYE = "Tiger Eye"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TIGEREYE = "Tiger Eye."

GLOBAL.STRINGS.RECIPE_DESC.GOLDNUGGET = "Gold"

GLOBAL.STRINGS.NAMES.ESCADADOVULCAO2 = "Volcano Exit"
GLOBAL.STRINGS.NAMES.LAVAPONDBIG1 = "Big lava pool"

GLOBAL.STRINGS.NAMES.MERM1 = "Merm"
GLOBAL.STRINGS.NAMES.MERM2 = "Merm"
--------------store---------

--------------actions-------
GLOBAL.STRINGS.ACTIONS.HACK="Tajar"
GLOBAL.STRINGS.ACTIONS.BOATMOUNT="Montar Bote"
GLOBAL.STRINGS.ACTIONS.BOATREPAIR = "Reparar Bote"
GLOBAL.STRINGS.ACTIONS.BOATDISMOUNT = "Desmontar Bote"
GLOBAL.STRINGS.ACTIONS.STICK = "Pegar"
GLOBAL.STRINGS.NAMES.NAUTICALTAB = "Náutico"
GLOBAL.STRINGS.TABS.NAUTICALTAB = "Náutico"
GLOBAL.STRINGS.ACTIONS.LANTERNOFF = "Apagar"
GLOBAL.STRINGS.ACTIONS.LANTERNON = "Encender"
GLOBAL.STRINGS.ACTIONS.BOATCANNON = "Disparar"
GLOBAL.STRINGS.ACTIONS.RETRIEVE = "Recoger"
--------------rawling speak---------------
GLOBAL.STRINGS.NAMES.RAWLING = "rawling"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAWLING = "rawling"
GLOBAL.STRINGS.RAWLINGon_hit_water = "Chasquea!"
GLOBAL.STRINGS.RAWLINGon_dropped = "Dribléame!"
GLOBAL.STRINGS.RAWLINGon_extinguish = "Salvado!"
GLOBAL.STRINGS.RAWLINGin_container = "Esta no es una canasta de durazno..."
GLOBAL.STRINGS.RAWLINGon_ground = "Podría usar un poco de tónico estimulante."
GLOBAL.STRINGS.RAWLINGin_inventory = "Vamos a cortar el fondo de la canasta."
GLOBAL.STRINGS.RAWLINGother_owner = "Ouch!"
GLOBAL.STRINGS.RAWLINGon_ignite = {
"Estoy en llamas!",
"Ow ow ow ow ow!",
}
GLOBAL.STRINGS.RAWLINGon_pickedup = {
"Eres tú, James?",
"Eres MI MVP!",
}
GLOBAL.STRINGS.RAWLINGon_thrown = {
"A la canasta de durazno!",
"Dispara!",
"Pierdes el 100% de los disparos!",
"Creo que puedo volar!",
}

GLOBAL.STRINGS.RAWLINGon_bounced = 
{
"Ouch!",
"Nada más que duraznos!",
"Splish!",
"Rechazado!",
}
GLOBAL.STRINGS.RAWLINGequipped = {
"Puedes llevarme. Por un par de pasos.",
"Es esto una especie de broma canadiense?",
"Siéntete 'libre' de tirarme.",
}

STRINGS.BORE_TALK_FOLLOWWILSON = {"YOU OK BY ME", "I LOVE FRIEND", "YOU IS GOOD", "I FOLLOW!"}
STRINGS.BORE_TALK_FIND_LIGHT = {"SCARY", "NO LIKE DARK", "WHERE IS SUN?", "STAY NEAR FIRE", "FIRE IS GOOD"}
STRINGS.BORE_TALK_LOOKATWILSON = {"WHO ARE YOU?", "YOU NOT BORE.", "UGLY MONKEY MAN", "YOU HAS MEAT?"}
STRINGS.BORE_TALK_RUNAWAY_WILSON = {"TOO CLOSE!", "STAY 'WAY!", "YOU BACK OFF!", "THAT MY SPACE."}
STRINGS.BORE_TALK_FIGHT = {"I KILL NOW!", "YOU GO SMASH!", "RAAAWR!", "NOW YOU DUN IT!", "GO 'WAY!", "I MAKE YOU LEAVE!",}
STRINGS.BORE_TALK_RUN_FROM_SPIDER = {"SPIDER BAD!", "NO LIKE SPIDER!", "SCARY SPIDER!"}
STRINGS.BORE_TALK_HELP_CHOP_WOOD = {"KILL TREE!", "SMASH MEAN TREE!", "I PUNCH TREE!"}
STRINGS.BORE_TALK_HELP_HACK = {"I HELP GET BUSH!", "I PUNCH BUSH!", "WE PUNCHIN' PLANTS NOW?"}
STRINGS.BORE_TALK_ATTEMPT_TRADE = {"WHAT YOU GOT?", "BETTER BE GOOD.", "NO WASTE MY TIME."}
STRINGS.BORE_TALK_PANIC = {"NOOOOO!", "TOO DARK! TOO DARK!", "AAAAAAAAAH!!"}
STRINGS.BORE_TALK_PANICFIRE = {"HOT HOT HOT!", "OWWWWW!", "IT BURNS!"}
STRINGS.BORE_TALK_FIND_MEAT = {"ME HUNGRY!", "YUM!", "I EAT FOOD!", "TIME FOR FOOD!"}
STRINGS.BORE_TALK_EAT_MEAT = {"NOM NOM NOM", "YUM!"}
STRINGS.BORE_TALK_GO_HOME = {"HOME TIME!", "HOME! HOME!"}
STRINGS.NAMES.BELL1 = "Old Bell"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BELL1 = "Old Bell."

STRINGS.NAMES.WALL_LIMESTONE_ITEM = "Limestone Wall"
STRINGS.NAMES.WALL_LIMESTONE = "Limestone Wall"
STRINGS.RECIPE_DESC.WALL_LIMESTONE_ITEM = "Strong wall segments."
STRINGS.RECIPE_DESC.LIMESTONE = "Stone, with a hint of lime."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WALL_LIMESTONE = "Sturdy."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WALL_LIMESTONE_ITEM = "These would do more good if I placed them."

STRINGS.NAMES.WALL_ENFORCEDLIMESTONE_ITEM = "Sea Wall"
STRINGS.NAMES.WALL_ENFORCEDLIMESTONE = "Sea Wall"
STRINGS.RECIPE_DESC.WALL_ENFORCEDLIMESTONE_ITEM = "Strong wall segments to build at sea."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WALL_ENFORCEDLIMESTONE = "I shelled out for the good stuff."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WALL_ENFORCEDLIMESTONE_ITEM = "I have to build it in the water."
------------------mapwrapper---------------
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_MAPWRAP_LOSECONTROL = "Parecería que mi futuro es confuso."

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_MAPWRAP_RETURN = "Creo que sentí algo rozar mi pierna..."

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_MAPWRAP_WARN = "Aquí ser monstruos."