local STRINGS = GLOBAL.STRINGS
------------------------------------creeps------------------------------------
STRINGS.NAMES.GEOTHERMAL_VENT = "Geothermal Vent"
STRINGS.NAMES.CRABHOLE = "Mud Hole"
STRINGS.NAMES.UNDERWATER_ENTRANCE = "Underwater Entrance"
STRINGS.NAMES.UNDERWATER_ENTRANCE1 = "Underwater Entrance"
STRINGS.NAMES.UNDERWATER_ENTRANCE2 = "Underwater Entrance"
STRINGS.NAMES.UNDERWATER_ENTRANCE3 = "Underwater Entrance"
STRINGS.NAMES.UNDERWATER_ENTRANCE_OPEN = "Underwater Entrance"
STRINGS.NAMES.UNDERWATER_ENTRANCE_CLOSED = "Sealed Underwater Entrance"
STRINGS.NAMES.UNDERWATER_ENTRANCE_OPEN_CAVE = "Deeper Underwater Entrance"
STRINGS.NAMES.UNDERWATER_ENTRANCE_CLOSED_CAVE = "Sealed Deeper Underwater Entrance"
STRINGS.NAMES.UNDERWATER_EXIT = "Underwater Exit"
STRINGS.NAMES.UNDERWATER_EXIT1 = "Underwater Exit"
STRINGS.NAMES.UNDERWATER_EXIT2 = "Underwater Exit"
STRINGS.NAMES.UNDERWATER_EXIT3 = "Underwater Exit"
STRINGS.NAMES.MERMNOBLEHOUSE = "Prestigious Merm House"
STRINGS.NAMES.MERMWORKERHOUSE = "Merm House"
STRINGS.NAMES.MERMGUARDHOUSE = "Merm Guardhouse"
STRINGS.NAMES.ROTTING_TRUNK = "Rotting Tree Trunk"
STRINGS.NAMES.SUNKEN_CHEST = "Ancient Sea Chest"
STRINGS.NAMES.SEAGRASS = "Seagrass"
STRINGS.NAMES.DEPLETED_SEAGRASS = "Seagrass"
STRINGS.NAMES.UW_CORAL = "Fire Coral"
STRINGS.NAMES.UW_CORAL_BLUE = "Turquoise Coral"
STRINGS.NAMES.UW_CORAL_GREEN = "Emerald Coral"
STRINGS.NAMES.FLOWER_SEA = "Sea Flower"
STRINGS.NAMES.SANDSTONE_BOULDER = "Sandstone Boulder"
STRINGS.NAMES.IRON_BOULDER = "Iron Ore Vein"
STRINGS.NAMES.SUNKEN_CHEST = "Sea Chest"
STRINGS.NAMES.KELPUNDERWATER = "Kelp"
STRINGS.NAMES.WORMPLANT = "Worm Plant"
STRINGS.NAMES.DECORATIVE_SHELL = "Pretty Shell"
STRINGS.NAMES.SPONGE = "Sea Sponge"
STRINGS.NAMES.BUBBLE_VENT = "Bubbling Vent"
STRINGS.NAMES.UW_FLOWERS = "Sea Flowers"


-- Craftable items
STRINGS.NAMES.HAT_DIVING = "Diving Helmet"
STRINGS.RECIPE_DESC.HAT_DIVING = "For aquatic exploration."
STRINGS.NAMES.SNORKEL = "Snorkelling Gear"
STRINGS.RECIPE_DESC.SNORKEL = "Perfect for observing the reef."
STRINGS.NAMES.PEARL_AMULET = "Pearl Amulet"
STRINGS.RECIPE_DESC.PEARL_AMULET = "Converts sea water into fresh air."
STRINGS.NAMES.FLARE = "Flare"
STRINGS.RECIPE_DESC.FLARE = "Illuminate the ocean's depths."
STRINGS.NAMES.DIVING_SUIT_SUMMER = "Wetsuit"
STRINGS.RECIPE_DESC.DIVING_SUIT_SUMMER = "Clothing for dives into the ocean."
STRINGS.NAMES.DIVING_SUIT_WINTER = "Drysuit"
STRINGS.RECIPE_DESC.DIVING_SUIT_WINTER = "Sure to keep you warm while underwater."
STRINGS.NAMES.JELLY_LANTERN = "Jelly O' Lantern'"
STRINGS.RECIPE_DESC.JELLY_LANTERN = "Lasting light for longer dives."
STRINGS.RECIPE_DESC.CORAL_CLUSTER = "When a bouquet of flowers just won't do the trick."
STRINGS.NAMES.CORAL_CLUSTER = "Coral Cluster"


-- Inventory items
STRINGS.NAMES.PEARL = "Mysterious Pearl"
STRINGS.NAMES.CORAL_PIECES = "Coral Fragments"
STRINGS.NAMES.SANDSTONE = "Pile of Sand"
STRINGS.NAMES.IRON_ORE = "Iron Ore"
STRINGS.NAMES.BUBBLE_ITEM = "Bubble"
STRINGS.NAMES.LAVASTONE = "Lavastone"
STRINGS.NAMES.SPONGE_PIECE = "Piece of Sponge"
STRINGS.NAMES.JELLY_CAP = "Jelly Cap"
STRINGS.NAMES.SALT = "Salt"
STRINGS.NAMES.SEA_CUCUMBER = "Sea Cucumber"
STRINGS.NAMES.SEAGRASS_CHUNK = "Chunk of Seagrass"
STRINGS.NAMES.CUT_ORANGE_CORAL = "Precious Fire Coral"
STRINGS.NAMES.CUT_GREEN_CORAL = "Precious Emerald Coral"
STRINGS.NAMES.CUT_BLUE_CORAL = "Precious Turquoise Coral"
STRINGS.NAMES.SEA_PETALS = "Sea Petals"


-- Food
STRINGS.NAMES.FISH_FILLET = "Fish Fillet"
STRINGS.NAMES.FISH_FILLET_COOKED = "Cooked Fish Fillet"
STRINGS.NAMES.FISH_GAZPACHO = "Gazpacho Soup"
STRINGS.NAMES.SPONGE_CAKE = "Sponge Cake"
STRINGS.NAMES.FISH_N_CHIPS = "Fish 'n Chips"
STRINGS.NAMES.TUNA_MUFFIN = "Tuna Muffin"
STRINGS.NAMES.TENTACLE_SUSHI = "Geso Sushi"
STRINGS.NAMES.FLOWER_SUSHI = "Bento Sushi"
STRINGS.NAMES.FISH_SUSHI = "Aji Sushi"
STRINGS.NAMES.SHRIMP_TAIL = "Shrimp Tail"
STRINGS.NAMES.SEAJELLY = "Sea Jelly"


-- Monsters and mobs
STRINGS.NAMES.COMMONFISH = "Sea Bass"
STRINGS.NAMES.REEF_JELLYFISH = "Deep-Sea Jellyfish"
STRINGS.NAMES.SQUIDUNDERWATER = "Squiddy"
STRINGS.NAMES.CRAB = "Crab"
STRINGS.NAMES.MERMNOBLE = "Gentle-Merm"
STRINGS.NAMES.MERMWORKER = "Merm Labourer"
STRINGS.NAMES.MERMGUARD = "Merm Guard"
STRINGS.NAMES.SEATENTACLE = "Sea Tentacle"
STRINGS.NAMES.SEAQUAKETENTACLE = "Tentacle of the Kraken"
STRINGS.NAMES.CLAM = "Giant Clam"
STRINGS.NAMES.SEA_EEL = "Giant Eel"
STRINGS.NAMES.SHRIMP = "Shrimpet"


-- Names
STRINGS.MERMNAMES = {MERM_NOBLE = {}, MERM_WORKER = {}}
STRINGS.MERMNAMES.MERM_NOBLE[1] = 
{
	"Lampwick",
	"Warren",
	"William",
	"Rudderford",
}
STRINGS.MERMNAMES.MERM_NOBLE[2] = 
{
	"Helena",
	"Priscilla",
	"Elizabeth",
	"Evelyn",
}
STRINGS.MERMNAMES.MERM_WORKER[1] = 
{
	"Frank",
	"Boris",
	"Bill",
	"Joe",
}
STRINGS.MERMNAMES.MERM_WORKER[2] = 
{
	"Maggie",
	"Leslie",
	"Beth",
	"Freda",
}

-- Merm strings
STRINGS.MERM_TALK_HELP_CHOP_WOOD = 
{
	MERM_NOBLE = {"Physical toil is best suited to others, I think.", "Sorry ol' thing, but my back you see...", "Good swing you have there.", "Don't worry, I'll wait."},
	MERM_WORKER = {"Alright, let's get to it.", "Lunch'll be afterwards, right?", "It won't know what hit it!", "I'll get that down in a jiffy."},
	MERM_GUARD = {"'Fraid that's outside my pay grade.", "I'll wait here.", "", ""},
}
STRINGS.MERM_TALK_FOLLOWWILSON =
{
	MERM_NOBLE = {"Lovely day.", "Will there be tea sometime soon?", "Smashing!", "I do enjoy a good walk after lunch."},
	MERM_WORKER = {"I'm being paid by the hour, right?", "'Fraid I can't do overtime.", "Are you a union member?", "What's the next job?"},
	MERM_GUARD = {"", "", "", ""},
}
STRINGS.MERM_TALK_RUNAWAY_WILSON =
{
	MERM_NOBLE = {"Do you mind?", "Little too close there, ol' thing.", "Don't you know anything about personal space?", "Off with you!"},
	MERM_WORKER = {"Hey, what's your problem?", "I don't think so...", "Not pickin' my pocket are you?", "Clear off!"},
	MERM_GUARD = {"Move along!", "Stay clear of defence personnel at all times.", "I'll have my eye on you.", "Back off you!"},
}
STRINGS.MERM_TALK_LOOKATWILSON =
{
	MERM_NOBLE = {"", "", "", ""},
	MERM_WORKER = {"", "", "", ""},
	MERM_GUARD = {"", "", "", ""},
}
STRINGS.MERM_TALK_PANICFIRE =
{
	MERM_NOBLE = {"I'm burning up!", "Someone put it out! PUT IT OUT!", "AHH! AHH! FIIIIREE!"},
	MERM_WORKER = {"I'm burning up!", "Someone put it out! PUT IT OUT!", "AHH! AHH! FIIIIREE!"},
	MERM_GUARD = {"I'm burning up!", "Someone put it out! PUT IT OUT!", "AHH! AHH! FIIIIREE!"},
}
STRINGS.MERM_TALK_FIGHT =
{
	MERM_NOBLE = {"Tally-ho!", "Guards! GUUUAAARRDDSSS!", "Thief! Murderer! Vagrant!", "Your mother was a hamster, and your father smelt of elderberries!"},
	MERM_WORKER = {"Clear out you!", "I'll clean your clock!", "Let's get 'em!", "Come and fight, you pansy!"},
	MERM_GUARD = {"Out of here, you scoundrel!", "Tally-ho!", "I'll give you a good seeing too, ruffian!", "Halt! You're under arrest!"},
}
STRINGS.MERM_TALK_ATTEMPT_TRADE =
{
	MERM_NOBLE = {"A gift?", "Yes?"},
	MERM_WORKER = {"What's this then?", "Need a hired hand?"},
	MERM_GUARD = {"You have something for me?", "Bribery is a crime, ya-know."},
}
STRINGS.MERM_TALK_GO_HOME =
{
	MERM_NOBLE = {"Time to retire.", "Brilliant day that!", "Time for a nightcap.", "Must be off!"},
	MERM_WORKER = {"Time to knock off!", "Home time!", "At last!", "What's for supper?"},
	MERM_GUARD = {"Better get some shut eye.", "Thought that shift would never end.", "Me legs are all stiff!", "I'm getting too old for this."},
}


-----------------new adde by vagner-----------------------
STRINGS.NAMES.DEAD_SWORDFISH = "Dead Swordfish"
STRINGS.NAMES.SWORDFISH = "Swordfish"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DEAD_SWORDFISH = "I'd better not run with this."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SWORDFISH = "I think this fish evolved to run me through."

STRINGS.NAMES.STUNGRAYUNDERWATER = "Stink Ray"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.STUNGRAYUNDERWATER = "I think I'll keep my distance."

STRINGS.NAMES.DOGFISH_UNDER = "Dogfish"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOGFISH_UNDER = "It has that wet-dog smell."


STRINGS.NAMES.RAINBOWJELLYFISH_UNDERWATER = "Rainbow Jellyfish"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAINBOWJELLYFISH_UNDERWATER = "That's a lot of tendrils."

STRINGS.NAMES.LOBSTERUNDERWATER = "Wobster"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LOBSTERUNDERWATER = "That wascal is sleeping."

STRINGS.NAMES.JELLYFISH_UNDERWATER = "Jellyfish"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.JELLYFISH_UNDERWATER = "This creature is pure science!"

STRINGS.NAMES.CORAL = "Coral"
STRINGS.NAMES.CORALREEFUNDERWATER = "Coral Reef"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CORAL = "Living building material!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CORALREEFUNDERWATER = "The coral's formed a reef!"

STRINGS.NAMES.CORAL_BRAIN_ROCKUNDERWATER = "Coral Brain"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CORAL_BRAIN_ROCKUNDERWATER = "I wonder what it's plotting..."

GLOBAL.STRINGS.NAMES.CORAL_BRAIN = "Coral Brain"

STRINGS.NAMES.COMMONFISH = "Sea Bass"
STRINGS.NAMES.COMMONFISH = "Sea Bass"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHARXUNDERWATER = "These things sure are persistent."
STRINGS.NAMES.SHARXUNDERWATER = "Sharx"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.OCTOPUSKING = "I'm a sucker for this guy."
STRINGS.NAMES.OCTOPUSKING = "Yaarctopus"

STRINGS.NAMES.LIMPETS = "Limpet"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LIMPETS = "Maybe starving wouldn't be so bad."
STRINGS.NAMES.LIMPETS_COOKED = "Cooked Limpet"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LIMPETS_COOKED = "Escargotcha!"

STRINGS.NAMES.SANDHILL = "Sand Hill"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SANDHILL = "You better stay out of my shoes."
STRINGS.NAMES.SAND = "Sand"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SAND = "A handy pile of pocket sand."

GLOBAL.STRINGS.NAMES.LIMESTONE = "Limestone"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LIMESTONE = "It could be a useful building material."
GLOBAL.STRINGS.RECIPE_DESC.LIMESTONE = "Stone, with a hint of lime."

GLOBAL.STRINGS.NAMES.ARMOR_SEASHELL = "Seashell Suit"
GLOBAL.STRINGS.RECIPE_DESC.ARMOR_SEASHELL = "Pretty poison prevention."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.ARMOR_SEASHELL = "Arts and crafts!"

GLOBAL.STRINGS.NAMES.WRECKUNDERWATER = "Wreck"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WRECKUNDERWATER = "Poor little boat."
GLOBAL.STRINGS.NAMES.SHIPNAMES =
{"Nautilus",
"Mackay-Bennett",
"Mary Celeste",
"Beagle",
"Santa Maria",
"Bluenose",
"Mauretania",
"Endeavour",
"Edmund Fitzgerald",
"Pequod",
"Mississinewa",
"African Queen",
"Mont-Blanc",
"Caine",
 "Pharaoh",
 "Minnow",
 "Syracusia",
 "Baron of Renfrew",
 "Ariel",
 "Hispaniola",}
 
STRINGS.NAMES.CRATE = "Crate"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CRATE = "There must be a way to open it."

GLOBAL.STRINGS.NAMES.REDBARRELUNDERWATER = "Gunpowder Barrel"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.REDBARRELUNDERWATER = "How original."

GLOBAL.STRINGS.NAMES.FISH_RAW_SMALL_COOKED = "Cooked Fish Morsel"
GLOBAL.STRINGS.NAMES.FISH_RAW_SMALL = "Fish Morsel"
GLOBAL.STRINGS.NAMES.FISH_MED_COOKED = "Fish Steak"
GLOBAL.STRINGS.NAMES.FISH_MED = "Dead Dogfish"
GLOBAL.STRINGS.NAMES.SPOILED_FISH = "Spoiled Fish"
GLOBAL.STRINGS.NAMES.FISH_RAW = "Raw Fish"

GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH_RAW_SMALL_COOKED = "A small bit of cooked fish."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH_RAW_SMALL = "A small bit of fish."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH_MED_COOKED = "Grilled to perfection."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH_MED = "Good dog."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPOILED_FISH = "I'm not terribly curious about the smell."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH_RAW = "A chunk of fish meat."

STRINGS.NAMES.ROCK_LIMPET = "Limpet Rock"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ROCK_LIMPET = "I could fill a pail with all those snails!"

STRINGS.NAMES.SEASHELL_BEACHED = "Seashell"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEASHELL_BEACHED = "Sea refuse."
STRINGS.NAMES.SEASHELL = "Seashell"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEASHELL = "Maybe I could sell these."

STRINGS.NAMES.SPIDER_WATER = "spider_water"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPIDER_WATER = "Maybe I could sell these."

GLOBAL.STRINGS.NAMES.ROCK_OBSIDIAN = "Obsidian Boulder"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.ROCK_OBSIDIAN = "Blast it! It won't be mined!"

GLOBAL.STRINGS.NAMES.ROCK_CHARCOAL = "Charcoal Boulder"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.ROCK_CHARCOAL = "Would need an awfully big stocking..."

GLOBAL.STRINGS.NAMES.ROCK_CAVE = "Rock Boulder"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.ROCK_CAVE = "Rock Boulder"

GLOBAL.STRINGS.NAMES.MAGMAROCK = "Magma Pile"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MAGMAROCK = "I can dig it."

GLOBAL.STRINGS.NAMES.MAGMAROCK_GOLD = "Magma Pile"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MAGMAROCK_GOLD = "I see a golden opportunity."

GLOBAL.STRINGS.NAMES.FLAMEGEYSER = "Krissure"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FLAMEGEYSER = "Maybe I should stand back."

GLOBAL.STRINGS.NAMES.MERMSTATUE = "Merm Statue"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MERMSTATUE = "Merm Statue."

GLOBAL.STRINGS.NAMES.OCTOPUSCHEST = "Octopus Chest"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OCTOPUSCHEST = "I hope that thing is waterproof."

GLOBAL.STRINGS.NAMES.KRAKENCHEST = "Quacken Chest"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.KRAKENCHEST = "To the victor, the spoils."

GLOBAL.STRINGS.NAMES.KRAKENUNDERWATER_TENTACLE = "Quacken Tentacle"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.KRAKENUNDERWATER_TENTACLE = "A beast that never sleeps."

GLOBAL.STRINGS.NAMES.KRAKENUNDERWATER = "Quacken"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.KRAKENUNDERWATER = "A beast that never sleeps."

GLOBAL.STRINGS.NAMES.KRAKENHOLEFUNDO = "Quacken Hole"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.KRAKENHOLEFUNDO = "Quacken Hole."

GLOBAL.STRINGS.NAMES.KRAKENHOLEFRENTE = "Quacken Hole"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.KRAKENHOLEFRENTE = "Quacken Hole."

GLOBAL.STRINGS.NAMES.KRAKEN_SPAWNER = "kraken_spawner"
GLOBAL.STRINGS.NAMES.KRAKEN_PROJECTILE = "kraken_projectile"
GLOBAL.STRINGS.NAMES.KRAKEN_INKPATCH = "kraken_inkpatch"
GLOBAL.STRINGS.NAMES.GAZE_BEAM = "gaze_beam"

GLOBAL.STRINGS.NAMES.LUGGAGECHEST = "Treasure Chest"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LUGGAGECHEST = "Treasure Chest."

GLOBAL.STRINGS.NAMES.LAVARENACHEST = "Treasure Chest"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LAVARENACHEST = "Treasure Chest."

GLOBAL.STRINGS.NAMES.BIOLUMINESCENCE= "Bioluminescence"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BIOLUMINESCENCE = "These make a soothing glow."

GLOBAL.STRINGS.NAMES.BALLPHINHOUSE = "Coral House"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BALLPHINHOUSE = "The place where creatures hide."

STRINGS.NAMES.FISH2 = "Tropical Fish"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH2 = "What a tropical looking fish."

STRINGS.NAMES.FISH2_COOKED = "Cooked Tropical Fish."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH2_COOKED = "Cooked Tropical Fish."

STRINGS.NAMES.FISH3 = "Purple Grouper"
STRINGS.NAMES.FISH3_COOKED = "Cooked Purple Grouper"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH3 = "Surf and turf, hold the turf."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH3_COOKED = "That fish is fin-ished."

STRINGS.NAMES.FISH4 = "Pierrot Fish"
STRINGS.NAMES.FISH4_COOKED = "Cooked Pierrot Fish"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH4 = "This one's extra water repellent."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH4_COOKED = "Gilled to perfection."

STRINGS.NAMES.FISH5 = "Neon Quattro"
STRINGS.NAMES.FISH5_COOKED = "Cooked Neon Quattro"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH5 = "It looks like a fish, but it feels clammy."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH5_COOKED = "Fried fry."


STRINGS.NAMES.FISH2_ALIVE = "Tropical Fish"
STRINGS.NAMES.FISH3_ALIVE = "Purple Grouper"
STRINGS.NAMES.FISH4_ALIVE = "Pierrot Fish"
STRINGS.NAMES.FISH5_ALIVE = "Neon Quattro"
STRINGS.NAMES.QUAGMIRE_SALMON_ALIVE = "Salmon"

STRINGS.NAMES.SPIDERHOLE_WATER = "Coral Hole"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPIDERHOLE_WATER = "Coral Hole."

STRINGS.NAMES.FROG_WATER = "Frog"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FROG_WATER = "Frog."

STRINGS.NAMES.FENNEL = "fennel"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FENNEL = "fennel."

STRINGS.NAMES.FENNEL_COOKED = "Cooked Fennel"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FENNEL_COOKED = "Cooked Fennel."

STRINGS.NAMES.FENNEL_PLANTED = "fennel"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FENNEL_PLANTED = "fennel."

GLOBAL.STRINGS.NAMES.MUSSEL_STICK = "Mussel Stick"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSSEL_STICK = "I'm really going to stick it to those mussels."
GLOBAL.STRINGS.RECIPE_DESC.MUSSEL_STICK = "Mussel Stick."

GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSSEL_FARM = "I wonder if they are from Brussels."
GLOBAL.STRINGS.NAMES.MUSSEL_FARM = "Mussel Farm"

GLOBAL.STRINGS.NAMES.MUSSEL_COOKED = "Mussel Cooked"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSSEL_COOKED = "I cook a mean mussel."

GLOBAL.STRINGS.NAMES.MUSSEL = "Mussel"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSSEL = "I wonder if they are from Brussels."

GLOBAL.STRINGS.NAMES.MERMFISHER = "Merm Fisher"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MERMFISHER = "You better not try anything fishy."

GLOBAL.STRINGS.NAMES.MERM1 = "Merm"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MERM1 = "Merm."

GLOBAL.STRINGS.NAMES.MERM2 = "Merm"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MERM2 = "Merm."

GLOBAL.STRINGS.NAMES.MERMEXPERIMENT = "mermexperiment"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MERMEXPERIMENT = "mermexperiment."

GLOBAL.STRINGS.NAMES.HAT_SUBMARINE = "Submarine Helmet"
GLOBAL.STRINGS.RECIPE_DESC.HAT_SUBMARINE = "Submarine Helmet."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.HAT_SUBMARINE = "Submarine Helmet!"

GLOBAL.STRINGS.NAMES.PIRATEGHOST = "Pirate ghost"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PIRATEGHOST = "Pirate Ghost."

GLOBAL.STRINGS.NAMES.FISH_COI = "Coi"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH_COI = "Coi."

GLOBAL.STRINGS.NAMES.SECRETCAVEENTRANCE = "Under Water Cave"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SECRETCAVEENTRANCE = "Under Water Cave."




GLOBAL.STRINGS.NAMES.OCEANFISH_SMALL_UNDERWATER_1 = "Ocean Fish"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OCEANFISH_SMALL_UNDERWATER_1 = "Ocean Fish."

GLOBAL.STRINGS.NAMES.OCEANFISH_SMALL_UNDERWATER_2 = "Ocean Fish"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OCEANFISH_SMALL_UNDERWATER_2 = "Ocean Fish."

GLOBAL.STRINGS.NAMES.OCEANFISH_SMALL_UNDERWATER_3 = "Ocean Fish"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OCEANFISH_SMALL_UNDERWATER_3 = "Ocean Fish."

GLOBAL.STRINGS.NAMES.OCEANFISH_SMALL_UNDERWATER_4 = "Ocean Fish"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OCEANFISH_SMALL_UNDERWATER_4 = "Ocean Fish."

GLOBAL.STRINGS.NAMES.OCEANFISH_SMALL_UNDERWATER_5 = "Ocean Fish"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OCEANFISH_SMALL_UNDERWATER_5 = "Ocean Fish."

GLOBAL.STRINGS.NAMES.OCEANFISH_SMALL_UNDERWATER_6 = "Ocean Fish"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OCEANFISH_SMALL_UNDERWATER_6 = "Ocean Fish."

GLOBAL.STRINGS.NAMES.OCEANFISH_SMALL_UNDERWATER_7 = "Ocean Fish"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OCEANFISH_SMALL_UNDERWATER_7 = "Ocean Fish."

GLOBAL.STRINGS.NAMES.OCEANFISH_SMALL_UNDERWATER_8 = "Ocean Fish"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OCEANFISH_SMALL_UNDERWATER_8 = "Ocean Fish."

GLOBAL.STRINGS.NAMES.OCEANFISH_SMALL_UNDERWATER_9 = "Ocean Fish"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OCEANFISH_SMALL_UNDERWATER_9 = "Ocean Fish."

GLOBAL.STRINGS.NAMES.OCEANFISH_MEDIUM_UNDERWATER_1 = "Ocean Fish"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OCEANFISH_MEDIUM_UNDERWATER_1 = "Ocean Fish."

GLOBAL.STRINGS.NAMES.OCEANFISH_MEDIUM_UNDERWATER_2 = "Ocean Fish"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OCEANFISH_MEDIUM_UNDERWATER_2 = "Ocean Fish."

GLOBAL.STRINGS.NAMES.OCEANFISH_MEDIUM_UNDERWATER_3 = "Ocean Fish"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OCEANFISH_MEDIUM_UNDERWATER_3 = "Ocean Fish."

GLOBAL.STRINGS.NAMES.OCEANFISH_MEDIUM_UNDERWATER_4 = "Ocean Fish"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OCEANFISH_MEDIUM_UNDERWATER_4 = "Ocean Fish."

GLOBAL.STRINGS.NAMES.OCEANFISH_MEDIUM_UNDERWATER_5 = "Ocean Fish"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OCEANFISH_MEDIUM_UNDERWATER_5 = "Ocean Fish."

GLOBAL.STRINGS.NAMES.OCEANFISH_MEDIUM_UNDERWATER_6 = "Ocean Fish"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OCEANFISH_MEDIUM_UNDERWATER_6 = "Ocean Fish."

GLOBAL.STRINGS.NAMES.OCEANFISH_MEDIUM_UNDERWATER_7 = "Ocean Fish"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OCEANFISH_MEDIUM_UNDERWATER_7 = "Ocean Fish."

GLOBAL.STRINGS.NAMES.OCEANFISH_MEDIUM_UNDERWATER_8 = "Ocean Fish"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OCEANFISH_MEDIUM_UNDERWATER_8 = "Ocean Fish."

STRINGS.NAMES.KELPY = "Kelpy"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.KELPY = "Kelpy."

STRINGS.NAMES.WOODLEGS_CAGE_UNDERWATER = "Cage"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOODLEGS_CAGE_UNDERWATER = "Cage."

STRINGS.NAMES.SQUIDUNDERWATER2 = "Squiddy"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SQUIDUNDERWATER2 = "Squiddy."

STRINGS.NAMES.SWORDFISHUNDERWATER = "Swordfish"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SWORDFISHUNDERWATER = "Swordfish."

STRINGS.NAMES.MERMKINGUNDERWATER = "Merm king"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MERMKINGUNDERWATER = "Merm king."

STRINGS.NAMES.MERMWATCHTOWERUNDERWATER = "Merm Watch Tower"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MERMWATCHTOWERUNDERWATER = "Merm Watch Tower."

STRINGS.NAMES.MERMTHRONEUNDERWATER = "Merm Throne"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MERMTHRONEUNDERWATER = "Merm Throne."

STRINGS.NAMES.MERMFISHERGUARDUNDERWATER = "Merm Guard"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MERMFISHERGUARDUNDERWATER = "Merm Guard."

STRINGS.NAMES.MECFISH_ALIVE = "Mecfish"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MECFISH_ALIVE = "Gear in the water."

STRINGS.NAMES.GOLDFISH_ALIVE = "Goldfish"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GOLDFISH_ALIVE = "Gold in the water."

STRINGS.NAMES.FISH6_ALIVE = "Ocean Fish"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH6_ALIVE = "Ocean Fish."

STRINGS.NAMES.FISH7_ALIVE = "Ocean Fish"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH7_ALIVE = "Ocean Fish."

STRINGS.NAMES.FISH2 = "Dead Tropical Fish"
STRINGS.NAMES.FISH2_COOKED = "Tropical Fish Cooked"
STRINGS.NAMES.FISH6 = "Dead Red Fish"
STRINGS.NAMES.FISH6_COOKED = "Red Fish Cooked"
STRINGS.NAMES.FISH7 = "Dead Hutch Fish"
STRINGS.NAMES.FISH7_COOKED = "Hutch Fish Cooked"

STRINGS.NAMES.COI = "Dead Coi"
STRINGS.NAMES.COI_COOKED = "Coi Cooked"
STRINGS.NAMES.SALMON = "Dead Salmon"
STRINGS.NAMES.SALMON_COOKED = "Salmon Cooked"

STRINGS.NAMES.BALLPHINOCEAN = "Dead Ballphin"
STRINGS.NAMES.MECFISH = "Dead Mecfich"
STRINGS.NAMES.GOLDFISH = "Dead Goldfish"
STRINGS.NAMES.WHALEBLUEOCEAN = "Dead Blue Whale"
STRINGS.NAMES.DOGFISHOCEAN = "Dead Dog Fish"
STRINGS.NAMES.SWORDFISHJOCEAN = "Dead Sword Fish"
STRINGS.NAMES.SWORDFISHJOCEAN2 = "Dead Rare Sword Fish"


STRINGS.NAMES.OCEANFISH_SMALL_61_INV = "Tropical Fish"
STRINGS.NAMES.OCEANFISH_SMALL_71_INV = "Purple Grouper"
STRINGS.NAMES.OCEANFISH_SMALL_81_INV = "Pierrot Fish"
STRINGS.NAMES.OCEANFISH_SMALL_91_INV = "Neon Quattro"
STRINGS.NAMES.OCEANFISH_SMALL_10_INV = "Coi"
STRINGS.NAMES.OCEANFISH_SMALL_11_INV = "Salmon"
STRINGS.NAMES.OCEANFISH_SMALL_12_INV = "Ballphin"
STRINGS.NAMES.OCEANFISH_SMALL_13_INV = "Mecfish"
STRINGS.NAMES.OCEANFISH_SMALL_14_INV = "Gold Fish"
STRINGS.NAMES.OCEANFISH_SMALL_15_INV = "Blue Whale"
STRINGS.NAMES.OCEANFISH_SMALL_16_INV = "Dog Fish"
STRINGS.NAMES.OCEANFISH_SMALL_17_INV = "Hutch Fish"
STRINGS.NAMES.OCEANFISH_SMALL_18_INV = "Red Fish"
STRINGS.NAMES.OCEANFISH_SMALL_19_INV = "Sword Fish"
STRINGS.NAMES.OCEANFISH_SMALL_20_INV = "Rare Sword Fish"
STRINGS.NAMES.OCEANFISH_SMALL_21_INV = "Sharx"
STRINGS.NAMES.SHARXOCEAN = "Sharx"
GLOBAL.STRINGS.NAMES.JELLYFISH = "Jellyfish"
GLOBAL.STRINGS.NAMES.JELLYFISH_DEAD = "Dead Jellyfish"
GLOBAL.STRINGS.NAMES.JELLYFISH_COOKED = "Cooked Jellyfish"
GLOBAL.STRINGS.NAMES.RAINBOWJELLYFISH = "Rainbow Jellyfish"
GLOBAL.STRINGS.NAMES.RAINBOWJELLYFISH_DEAD = "Dead Rainbow Jellyfish"
GLOBAL.STRINGS.NAMES.RAINBOWJELLYFISH_COOKED = "Cooked Rainbow Jellyfish"

GLOBAL.STRINGS.NAMES.GNARWAILUNDERWATER = "Gnarwail"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.GNARWAILUNDERWATER = "Gnarwail"
GLOBAL.STRINGS.NAMES.GNARWAILHOLEFUNDOFINAL = "Gnarwail den"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.GNARWAILHOLEFUNDOFINAL = "Gnarwail den"
GLOBAL.STRINGS.NAMES.GNARWAIL_ATTACK_HORNUNDERWATER = "Gnarwail"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.GNARWAIL_ATTACK_HORNUNDERWATER = "Gnarwail"

GLOBAL.STRINGS.NAMES.SEAWEEDUNDERWATER = "Seaweed"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEAWEEDUNDERWATER = "Is that what passes for food around here?"

STRINGS.NAMES.SEAWEED = "Seaweed"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEAWEED = "A weed. Of the sea."

STRINGS.NAMES.SEAWEED_COOKED = "Seaweed Cooked"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.COOKED = "Char broiled to perfection."

STRINGS.NAMES.SEAWEED_DRIED = "Seaweed Dried"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEAWEED_DRIED = "Salty!"

    --NOTE: Limit to 7 strings per table! (Using net_tinybyte for NPC chatter)
GLOBAL.STRINGS.MERM_TALK_FOLLOWWILSON   = {"Will come with you.", "Flort glut.", "Make Mermfolk strong!", "Blut gloppy Glurtsu!", "You help Mermfolk!", "Glut Glurtsu flopt!", "You okay.", "Florpy flort."}
GLOBAL.STRINGS.MERM_TALK_HELP_CHOP_WOOD = {"Will come with you.", "Flort glut.", "Make Mermfolk strong!", "Blut gloppy Glurtsu!", "Chop, choppy, chop!", "Grop, groppy, grop!", "Work hard, florp!", "Glort blut, florp!"}
GLOBAL.STRINGS.MERM_TALK_HELP_MINE_ROCK = {"Will come with you.", "Flort glut.", "Make Mermfolk strong!", "Blut gloppy Glurtsu!", "Break rock, easy!", "Wult wop, florty flort!", "Work hard, florp!", "Glort blut, florp!"}
GLOBAL.STRINGS.MERM_TALK_HELP_HAMMER    = {"Will come with you.", "Flort glut.", "Make Mermfolk strong!", "Blut gloppy Glurtsu!", "Smash! Smash!", "Florph! Florph!", "Work hard, florp!", "Glort blut, florp!"}
GLOBAL.STRINGS.MERM_TALK_FIND_FOOD      = {"Will come with you.", "Flort glut.", "Make Mermfolk strong!", "Blut gloppy Glurtsu!", "This do fine.", "Glort grolt flut.", "Find something tasty!", "Glurt florpy flut!"}
GLOBAL.STRINGS.MERM_BATTLECRY           = {"Glorp! Go away!", "Glorp! Glorpy glup!", "Destroy you!", "Wult glut!"}
GLOBAL.STRINGS.MERM_GUARD_BATTLECRY     = {"To battle!", "Wult flrot!", "For glory of Mermfolk!", "Flort Glurtsu flut!", "ATTAAAACK!!", "GLOT FLOOOORPH!!", "Defend King!", "Glurph Glurtsen!"}
GLOBAL.STRINGS.MERM_TALK_PANICBOSS      = {"Something coming!", "Gloppy flort!", "Aaah!! Bad thing! Bad thing!", "Gloooorph!! Glurph glot! Glurph glot!", "It come to destroy us!", "Flort wult Glurtsu!"}
GLOBAL.STRINGS.MERM_TALK_PANICBOSS_KING = {"Rally to King!", "Glurtsen blut flort!", "Hurry! Protect kingdom!", "Flurph flrot! Gloppy Glurtsam!", "S-stay brave!!", "G-glop blut flrot!!"}

GLOBAL.STRINGS.MERM_KING_TALK_HUNGER_STARVING = "Hungry... HUNGRY! HUNGRYYYY!!!"
GLOBAL.STRINGS.MERM_KING_TALK_HUNGER_CLOSE_STARVING = "Treachery... villainy! To let King waste away like this..."
GLOBAL.STRINGS.MERM_KING_TALK_HUNGER_VERY_HUNGRY = "What take so long? Make offerings to your King!"
GLOBAL.STRINGS.MERM_KING_TALK_HUNGER_HUNGRY = "King desires food!"
GLOBAL.STRINGS.MERM_KING_TALK_HUNGER_HUNGRISH = "King feeling a bit peckish..."
GLOBAL.STRINGS.MERM_KING_TALK_HUNGER_FULL =  "Have done well. Now go."

------------------------------------gorge------------------------------------------
GLOBAL.STRINGS.ACTIONS.COLLECTSAP = "Collect Sap"
GLOBAL.STRINGS.ACTIONS.TAPSUGARTREE = "Tap Tree"
GLOBAL.STRINGS.ACTIONS.SETUPITEM = "Install"	
GLOBAL.STRINGS.ACTIONS.SLAUGHTER = "Slaughter"

STRINGS.NAMES.FLOUR = "Flour"
STRINGS.NAMES.SAPTREE = "Sugarwood Tree"
STRINGS.NAMES.SAPBUCKET = "Sapbucket"
STRINGS.NAMES.SAP = "Sap"
STRINGS.NAMES.SYRUP = "Syrup"
STRINGS.NAMES.BREAD = "Bread"
STRINGS.NAMES.CHIPS = "Chips"
STRINGS.NAMES.VEGGIE_SOUP = "Veggie Soup"
STRINGS.NAMES.JELLY_SANDWICH = "Jelly Sandwich"
STRINGS.NAMES.FISH_STEW = "Fish Stew"
STRINGS.NAMES.TURNIP_CAKE = "Turnip Cake"
STRINGS.NAMES.POTATO_PANCAKES = "Potato Pancakes"
STRINGS.NAMES.POTATO_SOUP = "Potato Soup"
STRINGS.NAMES.FISHBALL_SKEWERS = "Fishball Skewers"
STRINGS.NAMES.MEATBALLS = "Meatballs"
STRINGS.NAMES.MEAT_SKEWERS = "Meat Skewers"
STRINGS.NAMES.STONE_SOUP = "Stone Soup"
STRINGS.NAMES.CROQUETTE = "Croquette"
STRINGS.NAMES.ROASTED_VEGGIES = "Roasted Veggies"
STRINGS.NAMES.MEATLOAF = "Meatloaf"
STRINGS.NAMES.CARROT_SOUP = "Carrot Soup"
STRINGS.NAMES.FISH_PIE = "Fish Pie"
STRINGS.NAMES.FISH_AND_CHIPS = "Fish And Chips"
STRINGS.NAMES.MEAT_PIE = "Meat Pie"
STRINGS.NAMES.SLIDER = "Slider"
STRINGS.NAMES.JAM = "Jam"
STRINGS.NAMES.JELLY_ROLL = "Jelly Roll"
STRINGS.NAMES.CARROT_CAKE = "Carrot Cake"
STRINGS.NAMES.MASHED_POTATOES = "Mashed Potatoes"
STRINGS.NAMES.GARLIC_BREAD = "Garlic Bread"
STRINGS.NAMES.TOMATO_SOUP = "Tomato Soup"
STRINGS.NAMES.SAUSAGE = "Sausage"
STRINGS.NAMES.CANDIED_FISH = "Candied Fish"
STRINGS.NAMES.STUFFED_MUSHROOM = "Stuffed Mushroom"
STRINGS.NAMES.RATATOUILLE = "Ratatouille"
STRINGS.NAMES.BRUSCHETTA = "Bruschetta"
STRINGS.NAMES.MEAT_STEW = "Meat Stew"
STRINGS.NAMES.HAMBURGER = "Hamburger"
STRINGS.NAMES.FISH_BURGER = "Fish Burger"
STRINGS.NAMES.MUSHROOM_BURGER = "Mushroom Burger"
STRINGS.NAMES.FISH_STEAK = "Fish Steak"
STRINGS.NAMES.CURRY = "Curry"
STRINGS.NAMES.SPAGHETTI_AND_MEATBALLS = "Spaghetti And Meatballs"
STRINGS.NAMES.LASAGNA = "Lasagna"
STRINGS.NAMES.POACHED_FISH = "Poached Fish"
STRINGS.NAMES.SHEPHERDS_PIE = "Shepherds Pie"
STRINGS.NAMES.CANDY = "Candy"
STRINGS.NAMES.PUDDING = "Pudding"
STRINGS.NAMES.WAFFLES = "Waffles"
STRINGS.NAMES.BERRY_TART = "Berry Tart"
STRINGS.NAMES.MAC_N_CHEESE = "Mac N Cheese"
STRINGS.NAMES.BAGEL_N_FISH = "Bagel N Fish"
STRINGS.NAMES.GRILLED_CHEESE = "Grilled Cheese"
STRINGS.NAMES.CREAM_OF_MUSHROOM = "Cream Of Mushroom"
STRINGS.NAMES.PIEROGIES = "Pierogies"
STRINGS.NAMES.MANICOTTI = "Manicotti"
STRINGS.NAMES.CHEESEBURGER = "Cheeseburger"
STRINGS.NAMES.FETTUCCINE = "Fettuccine"
STRINGS.NAMES.ONION_SOUP = "Onion Soup"
STRINGS.NAMES.BREADED_CUTLET = "Breaded Cutlet"
STRINGS.NAMES.CREAMY_FISH = "Creamy Fish"
STRINGS.NAMES.PIZZA = "Pizza"
STRINGS.NAMES.POT_ROAST = "Pot Roast"
STRINGS.NAMES.CRAB_CAKE = "Crab Cake"
STRINGS.NAMES.STEAK_FRITES = "Steak Frites"
STRINGS.NAMES.SHOOTER_SANDWICH = "Shooter Sandwich"
STRINGS.NAMES.BACON_WRAPPED_MEAT = "Bacon Wrapped Meat"
STRINGS.NAMES.CRAB_ROLL = "Crab Roll"
STRINGS.NAMES.MEAT_WELLINGTON = "Meat Wellington"
STRINGS.NAMES.CRAB_RAVIOLI = "Crab Ravioli"
STRINGS.NAMES.CARAMEL_CUBE = "Caramel Cube"
STRINGS.NAMES.SCONE = "Scone"
STRINGS.NAMES.TRIFLE = "Trifle"
STRINGS.NAMES.CHEESECAKE = "Cheesecake"
STRINGS.NAMES.QUAGMIRE_SYRUP = "Quagmire Syrup"
STRINGS.NAMES.JELLY_SANDWICH = "Jelly Sandwich"
STRINGS.NAMES.GORGE_MEATBALLS = STRINGS.NAMES.MEATBALLS
STRINGS.NAMES.GORGE_RATATOUILLE = STRINGS.NAMES.RATATOUILLE
STRINGS.NAMES.GORGE_JAM = STRINGS.NAMES.JAM

STRINGS.NAMES.CRATE_GRILL_SMALL = "Small Grill Crate"
STRINGS.NAMES.CRATE_GRILL = "Grill Crate"
STRINGS.NAMES.CRATE_POT_HANGER = "Pot Hanger Crate"
STRINGS.NAMES.CRATE_OVEN = "Oven Crate"
STRINGS.NAMES.GRILL = "Large Grill"
STRINGS.NAMES.GRILL_SMALL = "Small Grill"
STRINGS.NAMES.POT_HANGER = "Pot Hanger"
STRINGS.NAMES.GRILL_ITEM = "Grill"
STRINGS.NAMES.GRILL_SMALL_ITEM = "Small Grill"
STRINGS.NAMES.POT_HANGER_ITEM = "Pot Hanger"
STRINGS.NAMES.POT = "Cooking Pot"
STRINGS.NAMES.POT_SMALL = "Small Cooking Pot"
STRINGS.NAMES.POT_SYRUP = "Syrup Pot"
STRINGS.NAMES.OVEN = "Oven"
STRINGS.NAMES.OVEN_ITEM = "Oven"
STRINGS.NAMES.CASSEROLEDISH = "Casseroledish"
STRINGS.NAMES.CASSEROLEDISH_SMALL = "Small Casseroledish"
STRINGS.NAMES.SALT_RACK = "Saltrack"
STRINGS.NAMES.SALT_RACK_ITEM = "Saltrack Item"
STRINGS.NAMES.GORGE_ALTAR = "Altar"
STRINGS.NAMES.PLATE_GENERIC = "Plate"
STRINGS.NAMES.BOWL_GENERIC = "Bowl"
STRINGS.NAMES.PLATE_SILVER = "Silver Plate"
STRINGS.NAMES.BOWL_SILVER = "Silver Bowl"
STRINGS.NAMES.WHEAT = "Wheat"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WHEAT = "Better grind this into flour."

STRINGS.NAMES.WHEAT_COOKED = "Cooked Wheat"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WHEAT_COOKED = "Nicely toasted grains."	

STRINGS.NAMES.WHEAT_OVERSIZED_ROTTEN = "Wheat Oversized Rotten"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WHEAT_OVERSIZED_ROTTEN = "Wheat Oversized Rotten."

STRINGS.NAMES.WHEAT_OVERSIZED = "Wheat Oversized"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WHEAT_OVERSIZED = "Wheat Oversized."

STRINGS.NAMES.WHEAT_OVERSIZED_WAXED = "Wheat Oversized Waxed"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WHEAT_OVERSIZED_WAXED = "Wheat Oversized Waxed."

STRINGS.NAMES.FARM_PLANT_WHEAT = "Wheat planted"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FARM_PLANT_WHEAT = "Wheat planted."

STRINGS.NAMES.TURNIP_OVERSIZED_ROTTEN = "Turnip Oversized Rotten"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURNIP_OVERSIZED_ROTTEN = "Turnip Oversized Rotten."

STRINGS.NAMES.TURNIP_OVERSIZED = "Turnip Oversized"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURNIP_OVERSIZED = "Turnip Oversized."

STRINGS.NAMES.TURNIP_OVERSIZED_WAXED = "Turnip Oversized Waxed"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURNIP_OVERSIZED_WAXED = "Turnip Oversized Waxed."

STRINGS.NAMES.FARM_PLANT_TURNIP = "Turnip planted"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FARM_PLANT_TURNIP = "Turnip planted."
-- Pig Elder

STRINGS.ELDERPIG_TALK_GREETING =
	{
		"Hello...",
		"You is good goat.",
		"Little one...",
		"SNORT",
		"*COUGH*",
	}
	

STRINGS.ELDERPIG_TALK_FARWELL =
	{
		"...",
	}
	
STRINGS.NAMES.QUAGMIRE_TRADER_MERM3 = "Oliver The Merm Banker"


-------------------------------------------------------------

if STRINGS.GF == nil then return end

local SPELLS = 
{
    TFWP_SPEAR_GUNG =
    {
        TITLE = "Pyre Poker",
        DESC = "User rushes forward, damaging anything in its path.",
    },
    TFWP_LAVA_HAMMER =
    {
        TITLE = "Anvil Strike",
        DESC = "User hits a spell-circle-sized area, doing 30 damage to enemies inside.",
    },
    TFWP_SPEAR_LANCE =
    {
        TITLE = "Sky Lunge",
        DESC = "User leaps into the sky, then divebombing a small area for huge damage.",
    },
    TFWP_SUMMON_BOOK =
    {
        TITLE = "Magma Golem",
        DESC = "Summons a Magma Golem that attacks nearby enemies.",
    },
    TFWP_CONTROL_BOOK =
    {
        TITLE = "Frost Nova",
        DESC = "Freezes all enemies in an area.",
    },
    TFWP_HEALING_STAFF =
    {
        TITLE = "Life Blossom",
        DESC = "Heals players and puts other to sleep.",
    },
    TFWP_INFERNAL_STAFF =
    {
        TITLE = "Cataclysm Meteor",
        DESC = "Summons a meteor that does heavy damage to all enemies.",
    },
    TFWP_DRAGON_DART =
    {
        TITLE = "Molten Bolt",
        DESC = "Sends a fire shot at the enemy, dealing huge damage.",
    },
    TFWP_LAVA_DART =
    {
        TITLE = "Barrage",
        DESC = "Fires off 8 darts in rapid succession.",
    },
    TFWP_PARRY =
    {
        TITLE = "Preparation",
        DESC = "Protects you from damage for a shot time.",
    },
    TFWP_FIRE_BOMB =
    {
        TITLE = "Hearths fire",
        DESC = "Protects you from damage for a shot time.",
    },
}

local EFFECTS = 
{
    TUSK_VEST_SPEED = 
    {
        TITLE = "Tusk Vest (day)",
        DESC = "Movement speed is increased",
    },
    TUSK_VEST_DAMAGE = 
    {
        TITLE = "Tusk vest (dusk)",
        DESC = "Physical damage and spell power are increased",
    },
    TUSK_VEST_HEAL = 
    {
        TITLE = "Tusk vest (night)",
        DESC = "Slowly regenerates health and sanity",
    },
    WORM_SUIT_BUFF = 
    {
        TITLE = "Monster Thirst",
        DESC = "Physical damage is increased, restores health on attacks.",
    },
}

for name, data in pairs(SPELLS) do
    STRINGS.GF.SPELLS[name] = data
end

for name, data in pairs(EFFECTS) do
    STRINGS.GF.EFFECTS[name] = data
end

SPELLS = nil
EFFECTS = nil