local STRINGS = GLOBAL.STRINGS

-----------------------------Biome Jungle -----------------------------





-----------------------------Biome Tidal Mash---------------------------

GLOBAL.STRINGS.NAMES.TIGERSHARKPOOL = "Shark Pond"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TIGERSHARKPOOL = "There is a strange shark in this pond."


GLOBAL.STRINGS.NAMES.LAVAPONDBIG = "Big lava pool"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LAVAPONDBIG = "A bit hot for my tastes."

GLOBAL.STRINGS.NAMES.HARPOON = "Harpoon"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.HARPOON = "A harpoon to throw."



-----------------------------Biome Volcano------------------------------
GLOBAL.STRINGS.NAMES.DRAGOON = "Dragoon"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DRAGOON = "You're a quick one, aren't you?"

GLOBAL.STRINGS.NAMES.DRAGOONHEART = "Dragon's Heart."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DRAGOONHEART = "Where the dragoon once stored its feelings."

GLOBAL.STRINGS.NAMES.DRAGOONDEN = "Dragoon Den"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DRAGOONDEN = "Even goons gotta sleep."

GLOBAL.STRINGS.NAMES.DRAGOONSPIT = "Dragoon Saliva"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DRAGOONSPIT = "It's acularly disgusting!"

GLOBAL.STRINGS.NAMES.DRAGOONEGG = "Dragoon Egg"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DRAGOONEGG = "Do I hear cracking?"

GLOBAL.STRINGS.NAMES.OBSIDIAN = "Obsidian"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OBSIDIAN = "It's a fire rock."

GLOBAL.STRINGS.NAMES.BOOK_METEOR = "Joy of Volcanology"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOOK_METEOR = "The foreword just says \"Hope you like dragoons.\""

GLOBAL.STRINGS.NAMES.OBSIDIAN_WORKBENCH = "Obsidian Workbench"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OBSIDIAN_WORKBENCH = "I feel inspired."

GLOBAL.STRINGS.NAMES.OBSIDIANFIREPIT = "Obsidian Fire Pit"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OBSIDIANFIREPIT = "This fire pit is a conductor for even more... fire."


GLOBAL.STRINGS.NAMES.ARMOROBSIDIAN = "Obsidian Armour"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.ARMOROBSIDIAN = "I'm a genius."

GLOBAL.STRINGS.NAMES.SPEAR_OBSIDIAN = "Obsidian Spear"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPEAR_OBSIDIAN = "This will leave a mark."

--GLOBAL.STRINGS.NAMES.OBSIDIANMACHETE = "Obsidian Machete"
--GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OBSIDIANMACHETE = "It's hot to the touch."

GLOBAL.STRINGS.NAMES.AXEOBSIDIAN = "Obsidian Axe"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.AXEOBSIDIAN = "A winning combination!"

GLOBAL.STRINGS.NAMES.ROCK_OBSIDIAN = "Obsidian Boulder"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.ROCK_OBSIDIAN = "Blast it! It won't be mined!"

GLOBAL.STRINGS.NAMES.OBSIDIANBOMB = "Obsidian Bomb"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OBSIDIANBOMB = "It's even bombier!"

GLOBAL.STRINGS.NAMES.ROCK_CHARCOAL = "Charcoal Boulder"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.ROCK_CHARCOAL = "Would need an awfully big stocking..."

GLOBAL.STRINGS.NAMES.MAGMAROCK = "Magma Pile"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MAGMAROCK_FULL = "I can dig it."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MAGMAROCK = "I can dig it."

GLOBAL.STRINGS.NAMES.MAGMAROCK_GOLD = "Magma Pile"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MAGMAROCK_GOLD_FULL = "I see a golden opportunity."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MAGMAROCK_GOLD = "I see a golden opportunity."

GLOBAL.STRINGS.NAMES.FLAMEGEYSER = "Krissure"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FLAMEGEYSER = "Maybe I should stand back."

GLOBAL.STRINGS.NAMES.VOLCANO_SHRUB = "Burnt Ash Tree"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.VOLCANO_SHRUB = "You look ashen."

GLOBAL.STRINGS.NAMES.VOLCANO_EXIT = "Volcano"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.VOLCANO_EXIT = "I can feel a cool breeze outside."

GLOBAL.STRINGS.NAMES.VULCANO_ENTRANCE = "Volcano Entrance"
GLOBAL.STRINGS.NAMES.ESCADADOVULCAO = "Volcano Exit"

GLOBAL.STRINGS.NAMES.VOLCANO = "Volcano"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.VOLCANO = "That seems safe."

GLOBAL.STRINGS.NAMES.VOLCANOSTAFF = "Volcano Staff"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.VOLCANOSTAFF = "The label says 'Keep out of reach of children'."

STRINGS.NAMES.LAVAPOOL = "Lava Pool"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LAVAPOOL = "A bit hot for my tastes."

STRINGS.NAMES.DUG_ELEPHANTCACTUS = "Dug Elephant Cactus"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_ELEPHANTCACTUS = "A transplantable stinging plant."
STRINGS.NAMES.ELEPHANTCACTUS = "Elephant Cactus"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ELEPHANTCACTUS = "Oh, I can use this to pierce my eyes!"
STRINGS.NAMES.ELEPHANTCACTUS_ACTIVE = "Active Elephant Cactus"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ELEPHANTCACTUS_ACTIVE = "The thorns on this cactus are much more unusual."
STRINGS.NAMES.ELEPHANTCACTUS_STUMP = "Elephant Cactus Stump"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ELEPHANTCACTUS_STUMP = "It's long before the president will be out."


STRINGS.TABS.OBSIDIANTAB = "Volcanic"
GLOBAL.STRINGS.RECIPE_DESC.DRAGOONDEN = "Enter the Dragoon's Den."
GLOBAL.STRINGS.RECIPE_DESC.OBSIDIANBOMB = "KA-BLAMMIER!"
GLOBAL.STRINGS.RECIPE_DESC.ARMOROBSIDIAN = "Hot to the touch."
GLOBAL.STRINGS.RECIPE_DESC.SPEAR_OBSIDIAN = "How 'bout a lil' fire with your spear?"
GLOBAL.STRINGS.RECIPE_DESC.OBSIDIANFIREPIT = "The firiest of all fires!"
GLOBAL.STRINGS.RECIPE_DESC.OBSIDIANMACHETE = "Hack 'n burn!"
GLOBAL.STRINGS.RECIPE_DESC.AXEOBSIDIAN = "Like a regular axe only hotter."
--GLOBAL.STRINGS.RECIPE_DESC.COFFEE = "Hot Coffee!"
GLOBAL.STRINGS.RECIPE_DESC.BOOK_METEOR = "Meteor from sky!"
GLOBAL.STRINGS.RECIPE_DESC.VOLCANOSTAFF = "The sky is falling!"



--GLOBAL.STRINGS.UI.WORLDGEN.VOLCANOTITLE = "BOILING MAGMA"
--GLOBAL.STRINGS.NAMES.VOLCANO_ALTAR = "Volcano Altar of Snackrifice"
--GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.VOLCANO_ALTAR.GENERIC = "It appears to be closed."
--GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.VOLCANO_ALTAR.OPEN = "The altar is open and ready to accept offerings!"
--GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.VOLCANO_ALTAR_BROKEN = "Darn it!"
--GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.VOLCANO_ALTAR_TOWER = "How scary!"
--GLOBAL.STRINGS.CHARACTERS.GENERIC.ANNOUNCE_VOLCANO_ERUPT = "That can't be good."

GLOBAL.STRINGS.NAMES.COFFEEBUSH = "Coffee Plant"
GLOBAL.STRINGS.NAMES.DUG_COFFEEBUSH = "Coffee Plant"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_COFFEEBUSH = "This belongs in the ground!"


GLOBAL.STRINGS.NAMES.COFFEEBEANS = "Coffee Beans"
GLOBAL.STRINGS.NAMES.COFFEEBEANS_COOKED = "Roasted Coffee Beans"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.COFFEEBEANS = "They could use some roasting."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.COFFEEBEANS_COOKED = "Heat definitely improved them."

GLOBAL.STRINGS.NAMES.COFFEE = "Coffee"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.COFFEEBOT = "It's a coffee maker."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.COFFEE = "Smells delicious and energizing!"


--GLOBAL.STRINGS.SIGA = "Me siga"
GLOBAL.STRINGS.NAMES.WOODLEGS1 = "Woodlegs"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOODLEGS1 = "This is Woodlegs"

GLOBAL.STRINGS.NAMES.WOODLEGSGHOST = "Woodlegs Ghost"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOODLEGSGHOST = "He was my friend"

GLOBAL.STRINGS.NAMES.WOODLEGS_KEY1 = "Bone Key"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOODLEGS_KEY1 = "Something somewhere must be locked."

GLOBAL.STRINGS.NAMES.WOODLEGS_KEY2 = "Golden Key"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOODLEGS_KEY2 = "This key probably unlocks something."

GLOBAL.STRINGS.NAMES.WOODLEGS_KEY3 = "Iron Key"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOODLEGS_KEY3 = "That's a key."

GLOBAL.STRINGS.NAMES.WOODLEGS_CAGE = "Woodlegs' Cage"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOODLEGS_CAGE = "That seems like an excessive amount of locks."


GLOBAL.STRINGS.NAMES.SLIP = "Slip"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SLIP = "a small, furry monster"

GLOBAL.STRINGS.NAMES.SLIPSTOR = "Slipstor"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SLIPSTOR = "A big, furry monster"

GLOBAL.STRINGS.NAMES.SLIPSTOR_SPAWNER = "Slipstor Spawner"



GLOBAL.STRINGS.NAMES.TWISTER = "Sealnado"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TWISTER = "I thought it was oddly windy around here."

GLOBAL.STRINGS.NAMES.TWISTER_SEAL = "Seal"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TWISTER_SEAL = "D'awww."

GLOBAL.STRINGS.NAMES.TWISTER_TORNADO = "Tornado"


GLOBAL.STRINGS.NAMES.MERMFISHER = "Merm Fisher"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MERMFISHER = "You better not try anything fishy."

GLOBAL.STRINGS.NAMES.FLUP = "Flup"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FLUP = "Leave me alone!"

GLOBAL.STRINGS.NAMES.TIDALPOOL = "tidalpool"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TIDALPOOL = "A pool left by the tides."

GLOBAL.STRINGS.NAMES.MERMFISHHOUSE = "Mermhouse Fisher"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MERMFISHHOUSE = "Doesn't smell very good."

GLOBAL.STRINGS.NAMES.POISONHOLE = "Poisonous Hole"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.POISONHOLE = "I think I'll stay away from that."

GLOBAL.STRINGS.NAMES.TIGERSHARK = "Tiger Shark"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TIGERSHARK = "Well that's terrifying."

GLOBAL.STRINGS.NAMES.TIGERSHARKSHADOW = "Tiger Shark Shadow"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TIGERSHARKSHADOW = "The shadow of the beast!"

GLOBAL.STRINGS.NAMES.SNAKESKINFLOOR = "Snakeskin Rug "
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SNAKESKINFLOOR = "Really ties the room together."

GLOBAL.STRINGS.NAMES.TURF_MAGMAFIELD = "Magmafield Turf"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_MAGMAFIELD = "Lava-y floor."

GLOBAL.STRINGS.NAMES.TURF_JUNGLE = "Jungle Turf"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_JUNGLE = "Very gnarled ground."

GLOBAL.STRINGS.NAMES.TURF_ASH = "Ashy Turf"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_ASH = "Ashy turf."

GLOBAL.STRINGS.NAMES.TURF_VOLCANO = "Volcano Turf"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_VOLCANO = "Volcano-y turf."

GLOBAL.STRINGS.NAMES.TURF_TIDALMARSH = "Tidal Marsh Turf"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_TIDALMARSH = "Marsh-y floor."

GLOBAL.STRINGS.NAMES.TURF_LAVAROCK = "Lavarock Turf"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_LAVAROCK = "Lavarock-y floor."

GLOBAL.STRINGS.NAMES.TURF_MEADOW = "Meadow Turf"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_MEADOW = "Meadow floor."

GLOBAL.STRINGS.NAMES.SNAKE = "Snake"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SNAKE = "I wonder if it'll sell me some oil?"

GLOBAL.STRINGS.NAMES.SNAKE_POISON = "Poison Snake"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SNAKE_POISON = "Even worse than a common snake!"

GLOBAL.STRINGS.NAMES.SNAKESKIN = "Snakeskin"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SNAKESKIN = "I'm intrigued AND repelled."

GLOBAL.STRINGS.NAMES.SNAKE_HOLE = "Snake Hole"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SNAKE_HOLE = "I feel like I could have prevented that."

GLOBAL.STRINGS.NAMES.SNAKEOIL = "Snake Oil"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SNAKEOIL = "The label says 'Jay's Wondrous Snake Oil!'"


GLOBAL.STRINGS.NAMES.LIVINGJUNGLETREE = "Living Jungle Tree"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LIVINGJUNGLETREE = "Just like any other tree."

--jungle tree
GLOBAL.STRINGS.NAMES.JUNGLETREE = "Jungle Tree"
GLOBAL.STRINGS.NAMES.TREE_JUNGLE = "Jungle Tree"

GLOBAL.STRINGS.NAMES.JUNGLETREESEED = "Jungle Tree Seed"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.JUNGLETREESEED = "I can hear the hissing of tiny snakes."

GLOBAL.STRINGS.NAMES.JUNGLE_TREE_SAPLING = "Jungle Tree Sapling"

--bamboo
GLOBAL.STRINGS.NAMES.BAMBOO = "Bamboo"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BAMBOO = "Maybe I can bamboozle my enemies with this?"

GLOBAL.STRINGS.NAMES.BAMBOOTREE = "Bamboo Patch"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BAMBOOTREE = {
	GENERIC = "Looks pretty sturdy.",
	BURNING = "Bye bye, bamboo.",
	BURNT = "I feel like I could have prevented that.",
	CHOPPED = "Take that, nature!"
}

GLOBAL.STRINGS.NAMES.DUG_BAMBOOTREE = "Bamboo Root"
GLOBAL.STRINGS.RECIPE_DESC.DUG_BAMBOOTREE = "grow bamboo tree"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_BAMBOOTREE = "I need to plant this."

GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DEPLETED_BAMBOOTREE = "Will it grow again?"



GLOBAL.STRINGS.NAMES.DOYDOYBABY = "Baby Doydoy"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOYDOYBABY = "What a cute little, uh, thing."

GLOBAL.STRINGS.NAMES.DOYDOYTEEN = "Teen Doydoy"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOYDOYTEEN = "grow up!"

GLOBAL.STRINGS.NAMES.DOYDOY = "Doydoy"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOYDOY = "I feel oddly protective of this dumb bird."

GLOBAL.STRINGS.NAMES.DOYDOYEGG = "Doydoy Egg"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOYDOYEGG = "Maybe I should have let it hatch."

GLOBAL.STRINGS.NAMES.DOYDOYEGG_COOKED = "Fried Doydoy Egg"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOYDOYEGG_COOKED = "A controlled chemical reaction has made this egg matter more nutritious."

GLOBAL.STRINGS.NAMES.DOYDOYEGG_CRACKED = "Cracked Doydoy Egg"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOYDOYEGG_CRACKED = "Oh well. I'm sure there are lots more!"

GLOBAL.STRINGS.NAMES.DOYDOYFEATHER = "Doydoy Feather"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOYDOYFEATHER = "Soft AND endangered!"

GLOBAL.STRINGS.NAMES.DOYDOYNEST = "Doydoy Nest"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOYDOYNEST = "It's for doydoy eggs, dummy."

GLOBAL.STRINGS.RECIPE_DESC.DOYDOYNEST = "Just doy it."
GLOBAL.STRINGS.RECIPE_DESC.DOYDOYEGG = "You can to hatch your own doydoy!"

--wildborehouse
GLOBAL.STRINGS.NAMES.WILDBOREHOUSE = "Wildbore House"
GLOBAL.STRINGS.RECIPE_DESC.WILDBOREHOUSE = "Pig out!"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WILDBOREHOUSE = "What a bore-ing house."

--wildbore head
GLOBAL.STRINGS.NAMES.WILDBOREHEAD = "Wildbore Head"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WILDBOREHEAD = "It smells as bad as it looks."
--wildbore 

GLOBAL.STRINGS.NAMES.WILDBORE = "Wildbore"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WILDBORE = "I'm not wild about it."

--wildbore guard
GLOBAL.STRINGS.NAMES.WILDBOREGUARD = "Wildbore Guard"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WILDBOREGUARD = "What's it guarding?"






GLOBAL.STRINGS.NAMES.BEAVERKING_SPAWNER = "Beaverking Spawner"

GLOBAL.STRINGS.NAMES.WILDBEAVERGUARD = "Wildbeaver Guard"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WILDBEAVERGUARD = "He looks serious"

GLOBAL.STRINGS.NAMES.BEAVER_HEAD = "Beaver head"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BEAVER_HEAD = "Someone should tell his family."

GLOBAL.STRINGS.NAMES.BEAVERTORCH = "Beaver Torch"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BEAVERTORCH = "Sure looks cozy."

GLOBAL.STRINGS.NAMES.BEAVERSKIN = "Beaver Skin"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BEAVERSKIN = "The hide of a beaver creature"

GLOBAL.STRINGS.WILDBEAVER_NAMES = {
	"Castor",
}

GLOBAL.STRINGS.NAMES.BEAVER_KING = "Rei Castor"

GLOBAL.STRINGS.WILDBEAVER_TALK_FIGHT = {
	"VOU TE MORDER!",
	"VA EMBORA!",
	"VOLTEI PARA LUTAR!",
}
GLOBAL.STRINGS.WILDBEAVER_TALK_FOLLOW = {
	"VOCÊ ME ENTENDE",
	"VAMOS CONSTRUIR UMA BARRAGEM",
	"NÓS PRECISAMOS DE MAIS MADEIRA",
}
GLOBAL.STRINGS.WILDBEAVER_TALK_GOHOME = {
	"VOU TERMINAR A BARRAGEM AMANHÃ",
	"HORA DE DORMIR",
	"VEJO VOCÊ MAIS TARDE",
}
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WILDBEAVER = "Qual o nome disso...?!"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WILDBEAVER_HOUSE = "Onde o Castor mora."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BEAVER_KING = "Este deve governar todos eles."


GLOBAL.STRINGS.CHARACTERS.WILLOW.DESCRIBE.WILDBEAVER = "Você pega madeira, eu queimo: parece bom?"
GLOBAL.STRINGS.CHARACTERS.WILLOW.DESCRIBE.WILDBEAVER_HOUSE = "Ttodo mundo tem um lugar melhor que o meu..."
GLOBAL.STRINGS.CHARACTERS.WILLOW.DESCRIBE.BEAVER_KING = "Um grande para governar todos eles, suponho."

GLOBAL.STRINGS.CHARACTERS.WENDY.DESCRIBE.WILDBEAVER = "Posso montar em suas costas? Por favor, por favor"
GLOBAL.STRINGS.CHARACTERS.WENDY.DESCRIBE.WILDBEAVER_HOUSE = "Quando a represa se rompe, a inundação consome tudo."
GLOBAL.STRINGS.CHARACTERS.WENDY.DESCRIBE.BEAVER_KING = "Rei das represas."

GLOBAL.STRINGS.CHARACTERS.WX78.DESCRIBE.WILDBEAVER = "ELE COME MADEIRA."
GLOBAL.STRINGS.CHARACTERS.WX78.DESCRIBE.WILDBEAVER_HOUSE = "A MORADA DE UM COMEDOR DE MADEIRA."
GLOBAL.STRINGS.CHARACTERS.WX78.DESCRIBE.BEAVER_KING = "O REI DOS COMEDORES DE MADEIRA."

GLOBAL.STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WILDBEAVER = "Um primo perdido dO Castor canadense?"
GLOBAL.STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WILDBEAVER_HOUSE = "Deve ser para eles o equivalente a uma represa."
GLOBAL.STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BEAVER_KING = "Um rei para governar todos eles e para coordená-los na construção de barragens..."

GLOBAL.STRINGS.CHARACTERS.WOODIE.DESCRIBE.WILDBEAVER = "Ho, bonito. Não somos parentes?"
GLOBAL.STRINGS.CHARACTERS.WOODIE.DESCRIBE.WILDBEAVER_HOUSE = "O único imóvel em que investiria."
GLOBAL.STRINGS.CHARACTERS.WOODIE.DESCRIBE.BEAVER_KING = "Indo bem, né?"

GLOBAL.STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.WILDBEAVER = "Grandes dentuços?"
GLOBAL.STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.WILDBEAVER_HOUSE = "Os dentuços vivem aqui."
GLOBAL.STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.BEAVER_KING = "O maior de todos os dentuços!"

GLOBAL.STRINGS.CHARACTERS.WEBBER.DESCRIBE.WILDBEAVER = "WOODIE é você?"
GLOBAL.STRINGS.CHARACTERS.WEBBER.DESCRIBE.WILDBEAVER_HOUSE = "É aqui que esses criaturas vivem."
GLOBAL.STRINGS.CHARACTERS.WEBBER.DESCRIBE.BEAVER_KING = "Todos saudam o rei madeira primeiro!"

GLOBAL.STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.WILDBEAVER = "Vamos fazer uma batalha?"
GLOBAL.STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.WILDBEAVER_HOUSE = "A morada daqueles Castores selvagens."
GLOBAL.STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.BEAVER_KING = "Como você pode suportar esta ociosidade?"
GLOBAL.STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WILDBEAVER = "Outro tipo de idiotas da aldeia."
GLOBAL.STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WILDBEAVER_HOUSE = "Então eles vivem aqui."
GLOBAL.STRINGS.CHARACTERS.WAXWELL.DESCRIBE.BEAVER_KING = "Você é o supervisor deles ou o quê?"
GLOBAL.STRINGS.RECIPE_DESC.WILDBEAVER_HOUSE = "Beaver out!"
GLOBAL.STRINGS.NAMES.DOUBLE_UMBRELLAHAT = "Dumbrella"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOUBLE_UMBRELLAHAT = "Function definitely over fashion."
GLOBAL.STRINGS.NAMES.WILDBEAVER_HOUSE = "Beaver House"
-- FOI DAQUI --
STRINGS.NAMES.VENOMGLAND = "Venom Gland"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.VENOMGLAND = "Only poison can cure poison."

STRINGS.NAMES.BERRYBUSH2_SNAKE = "Berry Bush"

STRINGS.NAMES.OCTOPUSKING = "Yaarctopus"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.OCTOPUSKING = "I'm a sucker for this guy."

STRINGS.NAMES.SWEET_POTATO_PLANTED = "Sweet Potato Planted"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SWEET_POTATO_PLANTED = "That's an odd looking carrot."

STRINGS.NAMES.SWEET_POTATO = "Sweet Potato"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SWEET_POTATO = "Looks yammy!"

STRINGS.NAMES.SWEET_POTATO_COOKED = "Sweet Potato Cooked"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SWEET_POTATO_COOKED = "Looks even yammier!!"

STRINGS.NAMES.PARROT_PIRATE = "Parrot Pirate"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PARROT_PIRATE = "I try not to eat anything with a name."

STRINGS.NAMES.DUBLOON = "Dubbloon"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUBLOON = "I'm rich!!"

STRINGS.NAMES.DOYDOYFAN = "Tropical fan"
STRINGS.RECIPE_DESC.DOYDOYFAN = "Luxuriously soft, luxuriously tropical"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOYDOYFAN = "Somehow the breeze comes out the back twice as fast."

STRINGS.NAMES.FABRIC = "Cloth"
STRINGS.RECIPE_DESC.FABRIC = "Bamboo is so versatile!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FABRIC = "Soft cloth made from hard roots!"

STRINGS.NAMES.SNAKESKINHAT = "Snake Skin Hat"
STRINGS.RECIPE_DESC.SNAKESKINHAT = "Keep the rain out, and look cool doing it." 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SNAKESKINHAT = "It should repel the rain from my hair."

STRINGS.NAMES.ARMOR_SNAKESKIN = "Snake Jacket"
STRINGS.RECIPE_DESC.ARMOR_SNAKESKIN = "Stay dry and leathery."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ARMOR_SNAKESKIN = "How fashionable!!"

STRINGS.NAMES.TURF_SNAKESKINFLOOR = "Snake Skin Floor"
STRINGS.RECIPE_DESC.TURF_SNAKESKINFLOOR = "Really ties the room together."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_SNAKESKINFLOOR = "Sssstylish ssssstatement."

--STRINGS.NAMES.TURF_WATER_MANGROVE = "红树林地皮"
--STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_WATER_MANGROVE = "红树林地皮"

STRINGS.NAMES.TURF_BEACH = "Turf Beach"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_BEACH = "Sandy ground."

STRINGS.NAMES.COCONUT = "Coconut"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.COCONUT = "It requires a large nut hacker."

STRINGS.NAMES.COCONUT_HALVED = "Coconut Halved"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.COCONUT_HALVED = "When I click them together, they make horsey sounds."

STRINGS.NAMES.COCONUT_COOKED = "Coconut Cooked"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.COCONUT_COOKED = "Now I just need a cake."

STRINGS.NAMES.PALMTREE = "Palm tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PALMTREE = "How tropical."

STRINGS.NAMES.PALMLEAF = "Palm Leaf"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PALMLEAF = "My hair looks good wet... it's when it dries that's the problem."

STRINGS.NAMES.ROCK_LIMPET = "Limpet Rock"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ROCK_LIMPET = "I could fill a pail with all those snails!"

STRINGS.NAMES.LIMPETS = "Limpet"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LIMPETS = "Maybe starving wouldn't be so bad."

STRINGS.NAMES.LIMPETS_COOKED = "Limpet Cooked"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LIMPETS_COOKED = "Escargotcha!"

STRINGS.NAMES.PALMLEAF_HUT = "Palm Leaf Hut"
STRINGS.RECIPE_DESC.PALMLEAF_HUT = "Escape the rain. Mostly."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PALMLEAF_HUT = "Shade, sweet shade."

STRINGS.NAMES.SAND_CASTLE = "Sand Castle"
STRINGS.RECIPE_DESC.SAND_CASTLE = "Therapeutic and relaxing."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SAND_CASTLE = "Look what I made!"

STRINGS.NAMES.SANDHILL = "Sand Hill"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SANDHILL = "You better stay out of my shoes."

STRINGS.NAMES.SAND = "Sand"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SAND = "A handy pile of pocket sand."

STRINGS.NAMES.SEASHELL_BEACHED = "Seashell Beached"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEASHELL_BEACHED = "Sea refuse."

STRINGS.NAMES.SEASHELL = "Seashell"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEASHELL = "Maybe I could sell these."

STRINGS.NAMES.CRATE = "Crate"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CRATE = "There must be a way to open it."

STRINGS.NAMES.CRAB = "Crab"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CRAB = "Don't get snappy with me, mister."

STRINGS.NAMES.CRABHOLE = "Crab Hole"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CRABHOLE = "Crab Hole"

STRINGS.NAMES.CRAB_HIDDEN = "Crab Hidden"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CRAB_HIDDEN = "I wonder where that crabbit went?"

STRINGS.NAMES.SEAGULL = "Seagull"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEAGULL = "Shoo! Find some other land!"

STRINGS.NAMES.FISH_MEAT_SMALL = "Fish Meat Small"

STRINGS.NAMES.TROPICAL_FISH = "Tropical Fish"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TROPICAL_FISH = "What a tropical looking fish."

STRINGS.NAMES.TUNACAN = "Tunacan"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TUNACAN = "I can open it with a machete"

STRINGS.NAMES.TOUCAN = "Toucan"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TOUCAN = "I tou-can't catch him."

STRINGS.NAMES.RAFT = "Raft"
STRINGS.RECIPE_DESC.RAFT = "Totally sort of seaworthy."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAFT = "This looks adequate."

STRINGS.NAMES.SLOTMACHINE = "Slot Machine"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SLOTMACHINE = "I suppose I could linger for a moment or two."

STRINGS.NAMES.VINE = "Vine"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.VINE = "Maybe I can tie stuff up with this."

STRINGS.NAMES.BUSH_VINE = "Bush Vine"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BUSH_VINE = "It's all viney!!"

STRINGS.NAMES.DUG_BUSH_VINE = "Dug Bush Vine"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_BUSH_VINE = "I suppose I should pick it up."

STRINGS.NAMES.MACHETE = "Machete"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MACHETE = "I like the cut of this blade."
STRINGS.RECIPE_DESC.MACHETE = "Hack stuff!"

STRINGS.NAMES.GOLDENMACHETE = "Golden Machete"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GOLDENMACHETE = "Hack in style!"
STRINGS.RECIPE_DESC.GOLDENMACHETE = "Hack stuff in STYLE!"

STRINGS.NAMES.OBSIDIANMACHETE = "Obsidian Machete"
STRINGS.RECIPE_DESC.OBSIDIANMACHETE = "Hack'n'burn!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.OBSIDIANMACHETE = "It's hot to the touch."

STRINGS.PULAFORA = "Hm...too shallow"
STRINGS.SEMBARCO = "Where are my boat? I will dead here!"

STRINGS.NAMES.CORMORANT = "Cormorant"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CORMORANT = "I bet it ate a lot of fish."

STRINGS.NAMES.SEAWEED = "Seaweed"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEAWEED = "A weed. Of the sea."

STRINGS.NAMES.SEAWEED_COOKED = "Seaweed Cooked"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.COOKED = "Char broiled to perfection."

STRINGS.NAMES.SEAWEED_DRIED = "Seaweed Dried"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEAWEED_DRIED = "Salty!"

STRINGS.NAMES.SEAWEED_PLANTED = "Seaweed"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEAWEED_PLANTED = "Is that what passes for food around here?"

STRINGS.NAMES.CORAL = "Coral"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CORAL = "Living building material!"

STRINGS.NAMES.CORALREEF = "Coral Reef"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CORALREEF = "The coral's formed a reef!"

STRINGS.NAMES.FISHINHOLE = "Shoal"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISHINHOLE = "This area seems pretty fishy." --- ATÉ AQUI ----

GLOBAL.STRINGS.NAMES.GRASS_WATER = "Water Grass"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.GRASS_WATER = "Until here they appear?"

GLOBAL.STRINGS.NAMES.TREE_MANGROVE = "Mangrove Tree"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TREE_MANGROVE = "Well adapted."

GLOBAL.STRINGS.NAMES.ANTIDOTE = "Antidote"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.ANTIDOTE = "This is going to help me."
GLOBAL.STRINGS.RECIPE_DESC.ANTIDOTE = "Cure poisoning"

GLOBAL.STRINGS.NAMES.QUAGMIRE_SALMON = "Salmon"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.QUAGMIRE_SALMON = "Hm... Must be good."

GLOBAL.STRINGS.NAMES.QUAGMIRE_POND_SALT = "Pond Salt"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.QUAGMIRE_POND_SALT = "Now I can put salt in my food."

GLOBAL.STRINGS.NAMES.QUAGMIRE_SWAMPIG = "Swamp Pig"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.QUAGMIRE_SWAMPIG = "Swamp Pig."

GLOBAL.STRINGS.NAMES.QUAGMIRE_SWAMPIG_HOUSE = "Swamp Pig House"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.QUAGMIRE_SWAMPIG_HOUSE = "They've been better."

GLOBAL.STRINGS.NAMES.QUAGMIRE_SWAMPIG_HOUSE_RUBBLE = "Swamp Pig House"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.QUAGMIRE_SWAMPIG_HOUSE_RUBBLE = "They've been better."

GLOBAL.STRINGS.NAMES.CROCODOG = "Crocodog"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CROCODOG = "The bite must hurt."

GLOBAL.STRINGS.NAMES.WATERCROCODOG = "Crocodog Water"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WATERCROCODOG = "He must be stronger in the water."

GLOBAL.STRINGS.NAMES.POISONCROCODOG = "Crocodog Poison"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.POISONCROCODOG = "Away from me, please!"

GLOBAL.STRINGS.NAMES.GRASSWATER = "Water grass"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.GRASSWATER = "Grass"

GLOBAL.STRINGS.NAMES.ARMOR_SEASHELL = "Armor Seashell"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.ARMOR_SEASHELL = "I feel I belong to the sea."
GLOBAL.STRINGS.RECIPE_DESC.ARMOR_SEASHELL = "More protection."

GLOBAL.STRINGS.NAMES.OXHAT = "Horned Helmet"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OXHAT = "Very stylish."
GLOBAL.STRINGS.RECIPE_DESC.OXHAT = "Extra protection."

GLOBAL.STRINGS.NAMES.CHIMINEA = "Chiminea"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CHIMINEA = "Rain, goodbye."
GLOBAL.STRINGS.RECIPE_DESC.CHIMINEA = "Protected from rain."

GLOBAL.STRINGS.NAMES.OX_HORN = "Ox horn"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OX_HORN = "Very sad."

GLOBAL.STRINGS.NAMES.OX = "Water Beefalo"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OX = "He likes the water."

GLOBAL.STRINGS.NAMES.ROWBOAT = "Row Boat"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.ROWBOAT = "Now my adventure is complete."
GLOBAL.STRINGS.RECIPE_DESC.ROWBOAT = "A tougher boat"

GLOBAL.STRINGS.NAMES.ENCRUSTEDBOAT = "Encrusted Boat"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.ENCRUSTEDBOAT = "Pretty sturdy."
GLOBAL.STRINGS.RECIPE_DESC.ENCRUSTEDBOAT = "Highly resistant"

GLOBAL.STRINGS.NAMES.TURF_QUAGMIRE_PARKFIELD = "Quagmire Parkfield Turf"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_QUAGMIRE_PARKFIELD = "Very stylish."

GLOBAL.STRINGS.NAMES.COTTONTREE = "Cotton Tree"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.COTTONTREE = "Very soft."

GLOBAL.STRINGS.NAMES.COTTONTREE_SAPLING = "Cotton Tree Sapling"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.COTTONTREE_SAPLING = "Now I can place them anywhere."

GLOBAL.STRINGS.NAMES.COTTONTREE_CONE = "Cotton Tree Seed"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.COTTONTREE_CONE = "Seed?"

GLOBAL.STRINGS.NAMES.BALLPHINHOUSE = "Ballphin House"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BALLPHINHOUSE = "Must be a lot of fun in there."

GLOBAL.STRINGS.NAMES.BALLPHIN = "Ballphin"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BALLPHIN = "How cute he is."

GLOBAL.STRINGS.NAMES.JELLYFISH = "Jellyfish"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.JELLYFISH = "It must burn."

GLOBAL.STRINGS.NAMES.JELLYFISH_DEAD = "Jellyfish Dead"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.JELLYFISH_DEAD = "It still burns."

GLOBAL.STRINGS.NAMES.JELLYFISH_COOKED = "Jellyfish Cooked"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.JELLYFISH_COOKED = "And it's not that they're tasty!"

GLOBAL.STRINGS.NAMES.JELLYJERKY = "Jelly jerky"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.JELLYJERKY = "No burning substances.."

GLOBAL.STRINGS.NAMES.JELLYFISH_PLANTED = "Jellyfish"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.JELLYFISH_PLANTED = "What's it like?"

GLOBAL.STRINGS.NAMES.LOGRAFT = "Log raft"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LOGRAFT = "log raft...?"
GLOBAL.STRINGS.RECIPE_DESC.LOGRAFT = "This looks... sort of boat-like..."

GLOBAL.STRINGS.NAMES.FROG_POISON = "Frog Poison"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FROG_POISON = "It looks meaner than usual."

GLOBAL.STRINGS.NAMES.SHARKITTENSPAWNER = "Sharkitten House"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHARKITTENSPAWNER = "Where's their mother?"

GLOBAL.STRINGS.NAMES.WHALE_BLUE = "Blue Whale"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WHALE_BLUE = "That whale has emotional issues."

GLOBAL.STRINGS.NAMES.WHALE_WHITE = "White Whale"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WHALE_WHITE = "Looks like a fighter."

GLOBAL.STRINGS.NAMES.WHALE_CARCASS_WHITE = "White Whale Carcass"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WHALE_CARCASS_WHITE = "Gross. I think the bloating has begun."

GLOBAL.STRINGS.NAMES.WHALE_CARCASS_BLUE = "Blue Whale Carcass"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WHALE_CARCASS_BLUE = "Gross. I think the bloating has begun."

GLOBAL.STRINGS.NAMES.LOBSTER_DEAD_COOKED = "Lobster Dead Cooked"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LOBSTER_DEAD_COOKED = "Delicious Wobster."

GLOBAL.STRINGS.NAMES.LOBSTER_DEAD = "Lobster Dead"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LOBSTER_DEAD = "You should cook up nicely."

GLOBAL.STRINGS.NAMES.FISH_RAW_SMALL_COOKED = "Fish Raw Small Cooked"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH_RAW_SMALL_COOKED = "A small bit of cooked fish."

GLOBAL.STRINGS.NAMES.FISH_RAW_SMALL = "Fish Raw Small"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH_RAW_SMALL = "A small bit of fish."

GLOBAL.STRINGS.NAMES.FISH_MED_COOKED = "Fish Med Cooked"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH_MED_COOKED = "Grilled to perfection."

GLOBAL.STRINGS.NAMES.FISH_MED = "Fish Med"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH_MED = "Dead Dogfish."

GLOBAL.STRINGS.NAMES.SPOILED_FISH = "Spoiled Fish"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPOILED_FISH = "I'm not terribly curious about the smell."

GLOBAL.STRINGS.NAMES.FISH_RAW = "Fish Raw"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH_RAW = "A chunk of fish meat."

GLOBAL.STRINGS.NAMES.DEAD_SWORDFISH = "Dead Swordfish"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DEAD_SWORDFISH = "I better not run with this."

GLOBAL.STRINGS.NAMES.BLUBBER = "Blubber"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BLUBBER = "Squishy."

GLOBAL.STRINGS.NAMES.KNIGHTBOAT_CANNONSHOT = "knightboat cannonshot"

GLOBAL.STRINGS.NAMES.KNIGHTBOAT = "Floaty Boaty Knight"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.KNIGHTBOAT = "Get off the waterway, you maniac!"

GLOBAL.STRINGS.NAMES.OCTOPUSCHEST = "Octopus Chest"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OCTOPUSCHEST = "I hope that thing is waterproof."

GLOBAL.STRINGS.NAMES.KRAKEN = "Quacken"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.KRAKEN = "Now's not the time for me to be Quacken wise!"

GLOBAL.STRINGS.NAMES.KRAKENCHEST = "Quacken Chest"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.KRAKENCHEST = "To the victor, the spoils."

GLOBAL.STRINGS.NAMES.KRAKEN_TENTACLE = "Quacken Tentacle"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.KRAKEN_TENTACLE = "A beast that never sleeps."

GLOBAL.STRINGS.NAMES.SOLOFISH = "Dogfish"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SOLOFISH = "It has that wet-dog smell."

GLOBAL.STRINGS.NAMES.SWORDFISH = "Sword Fish"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SWORDFISH = "I think this fish evolved to run me through."

GLOBAL.STRINGS.NAMES.LOBSTER_LAND= "Wobster"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LOBSTER_LAND= "That Wascal is sleeping."

GLOBAL.STRINGS.NAMES.SHARX = "Sharx"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHARX = "These things sure are persistent."

GLOBAL.STRINGS.NAMES.STUNGRAY = "Stink Ray"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.STUNGRAY = "I think I'll keep my distance."

GLOBAL.STRINGS.NAMES.LUGGAGECHEST = "Steamer Trunk"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LUGGAGECHEST = "It looks like a premier steamer trunk."

GLOBAL.STRINGS.NAMES.REDBARREL = "Gunpowder Barrel"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.REDBARREL = "How original."

GLOBAL.STRINGS.NAMES.LOBSTERHOLE = "Wobster Den"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LOBSTERHOLE = "That Wascal is sleeping."

GLOBAL.STRINGS.NAMES.DEBRIS_1 = "Debris"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DEBRIS_1 = "There was someone here before me!"

GLOBAL.STRINGS.NAMES.DEBRIS_2 = "Debris"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DEBRIS_2 = "There was someone here before me!"

GLOBAL.STRINGS.NAMES.DEBRIS_3 = "Debris"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DEBRIS_3 = "There was someone here before me!"

GLOBAL.STRINGS.NAMES.DEBRIS_4 = "Debris"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DEBRIS_4 = "There was someone here before me!"

GLOBAL.STRINGS.NAMES.BOATREPAIRKIT = "Boat Repair Kit"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOATREPAIRKIT = "This will add some float to my boat."
GLOBAL.STRINGS.RECIPE_DESC.BOATREPAIRKIT = "Stay afloat in that boat!"

GLOBAL.STRINGS.NAMES.WRECK = "Wreck"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WRECK = "Poor little boat."

GLOBAL.STRINGS.NAMES.PIRATEGHOST = "pirateghost"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PIRATEGHOST = "He met a terrible end. I will too if I don't get out of here."

GLOBAL.STRINGS.NAMES.WRECKOF = "Wreck of the %s"
GLOBAL.STRINGS.NAMES.SHIPNAMES =
{"Nautilus",
"Mackay-Bennett",
"Mary Celeste",
"Beagle",
"Santa Maria",
"Bluenose",
"Mauretania",
"Endeavour",
"Edmund Fitzgerald",
"Pequod",
"Mississinewa",
"African Queen",
"Mont-Blanc",
"Caine",
 "Pharaoh",
 "Minnow",
 "Syracusia",
 "Baron of Renfrew",
 "Ariel",
 "Hispaniola",}

GLOBAL.STRINGS.NAMES.MUSSEL_STICK = "Mussel Stick"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSSEL_STICK = "I'm really going to stick it to those mussels."
GLOBAL.STRINGS.RECIPE_DESC.MUSSEL_STICK = "Mussel Stick."

GLOBAL.STRINGS.NAMES.MUSSEL_FARM = "Mussel Farm"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSSEL_FARM = "I wonder if they are from Brussels."

GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSSEL_FARM = "I wonder if they are from Brussels."
GLOBAL.STRINGS.NAMES.MUSSEL_FARM = "Mussel Farm"

GLOBAL.STRINGS.NAMES.MUSSEL_COOKED = "Mussel Cooked"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSSEL_COOKED = "I cook a mean mussel."

GLOBAL.STRINGS.NAMES.MUSSEL = "Mussel"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSSEL = "I wonder if they are from Brussels."

GLOBAL.STRINGS.NAMES.MOSQUITO_POISON = "Mosquito Poison"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOSQUITO_POISON = "These blasted mosquitoes carry a terrible sickness."

GLOBAL.STRINGS.NAMES.WATERYGRAVE= "Watery Grave"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WATERYGRAVE = "Sure, I could fish it out of there. But should I?"

GLOBAL.STRINGS.NAMES.BIOLUMINESCENCE= "Bioluminescence"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BIOLUMINESCENCE = "These make a soothing glow."

GLOBAL.STRINGS.NAMES.BOTTLELANTERN= "Bottle lantern"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOTTLELANTERN = "A bottle full of sunshine."
GLOBAL.STRINGS.RECIPE_DESC.BOTTLELANTERN = "Glowing ocean goo in a bottle."

GLOBAL.STRINGS.NAMES.MESSAGEBOTTLEEMPTY1= "Bottle Empty"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MESSAGEBOTTLEEMPTY1 = "Just an empty bottle"
GLOBAL.STRINGS.RECIPE_DESC.MESSAGEBOTTLEEMPTY1 = "Don't forget to recycle!"

GLOBAL.STRINGS.NAMES.ARMOUREDBOAT = "Armoured Boat"
GLOBAL.STRINGS.RECIPE_DESC.ARMOUREDBOAT = "Shell out for this hearty vessel."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.ARMOUREDBOAT = "That is one durable boat."

GLOBAL.STRINGS.NAMES.CARGOBOAT = "Cargo Boat"
GLOBAL.STRINGS.RECIPE_DESC.CARGOBOAT = "Hoarding at sea!"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CARGOBOAT = "It has room for all my stuff!"

GLOBAL.STRINGS.NAMES.CORAL_BRAIN = "Coral Brain"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CORAL_BRAIN = "Food for thought."

GLOBAL.STRINGS.NAMES.CORAL_BRAIN_ROCK = "Coral Brain"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CORAL_BRAIN_ROCK = "I wonder what it's plotting..."

GLOBAL.STRINGS.NAMES.SANDBAG = "Sandbag"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SANDBAG = "This should keep the water out."

GLOBAL.STRINGS.NAMES.SANDBAG_ITEM = "Sandbag"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SANDBAG_ITEM = "Sand technology, on the go."
GLOBAL.STRINGS.RECIPE_DESC.SANDBAG_ITEM = "Sand. Water's greatest enemy.."

GLOBAL.STRINGS.NAMES.LIMESTONE = "Limestone"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LIMESTONE = "Could be a useful building material."
GLOBAL.STRINGS.RECIPE_DESC.LIMESTONE = "Stone, with a hint of lime.."

GLOBAL.STRINGS.NAMES.CUTLASS = "Cutlass Supreme"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUTLASS = "I hope this sword doesn't start to smell..."
GLOBAL.STRINGS.RECIPE_DESC.CUTLASS = "Fish were harmed in the making of this.."

GLOBAL.STRINGS.NAMES.AERODYNAMICHAT = "Sleek Hat"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.AERODYNAMICHAT = "It really cuts through the air!"
GLOBAL.STRINGS.RECIPE_DESC.AERODYNAMICHAT = "Aerodynamic design for efficient travel."

GLOBAL.STRINGS.NAMES.SHARK_FIN = "Shark fin"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHARK_FIN = "A sleek fin."

GLOBAL.STRINGS.NAMES.RAINBOWJELLYFISH = "Rainbow Jellyfish"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAINBOWJELLYFISH = "This creature is pure science!"

GLOBAL.STRINGS.NAMES.RAINBOWJELLYFISH_DEAD = "Rainbow Jellyfish Dead"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAINBOWJELLYFISH_DEAD = "He lived a good life."

GLOBAL.STRINGS.NAMES.RAINBOWJELLYFISH_COOKED = "Rainbow Jellyfish Cooked"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAINBOWJELLYFISH_COOKED = "It's all wriggly."

GLOBAL.STRINGS.NAMES.RAINBOWJELLYJERKY = "Rainbow Jelly jerky"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAINBOWJELLYJERKY = "I'd be a jerk not to eat this."

GLOBAL.STRINGS.NAMES.RAINBOWJELLYFISH_PLANTED = "Rainbow Jellyfish"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAINBOWJELLYFISH_PLANTED = "Science works in mysterious, blobby ways."

GLOBAL.STRINGS.NAMES.BANANAPOP = "Banana Pop"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BANANAPOP = "No, not brain freeze! I need that for science!"

GLOBAL.STRINGS.NAMES.CEVICHE = "Ceviche"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CEVICHE = "Can I get a bigger bowl? This one looks a little shrimpy."

GLOBAL.STRINGS.NAMES.SWEETPOTATOSOUFFLE = "Sweet Potato Souffle"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SWEETPOTATOSOUFFLE = "Sweet potato souffles are a rising trend."

GLOBAL.STRINGS.NAMES.SEAFOODGUMBO = "Seafood Gumbo"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEAFOODGUMBO = "It's a jumbo seafood gumbo."

GLOBAL.STRINGS.NAMES.SURFNTURF = "Surf 'n' Turf"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SURFNTURF = "It's perf!"

GLOBAL.STRINGS.NAMES.SHARKFINSOUP = "Shark Fin Soup"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHARKFINSOUP = "It's shark fin-ished!"

GLOBAL.STRINGS.NAMES.MUSSELBOUILLABAISE = "Mussel Bouillabaise"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSSELBOUILLABAISE = "Imagine the experiments I could run on it!"

GLOBAL.STRINGS.NAMES.MONSTERTARTARE = "Monster Tartare"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MONSTERTARTARE = "There's got to be something else to eat around here."

GLOBAL.STRINGS.NAMES.LOBSTERDINNER = "Wobster Dinner"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LOBSTERDINNER = "If I eat it in the morning is it still dinner?."

GLOBAL.STRINGS.NAMES.LOBSTERBISQUE = "Wobster Bisque"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LOBSTERBISQUE = "Could use more salt, but that's none of my bisque-ness."

GLOBAL.STRINGS.NAMES.FRESHFRUITCREPES = "Fresh Fruit Crepes"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FRESHFRUITCREPES = "Sugary fruit! Part of a balanced breakfast."

GLOBAL.STRINGS.NAMES.BISQUE = "Bisque"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BISQUE = "Cooking that sure kept me bisque-y!"

GLOBAL.STRINGS.NAMES.CALIFORNIAROLL = "California Roll"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CALIFORNIAROLL = "But I don't have chopsticks."

GLOBAL.STRINGS.NAMES.JELLYOPOP = "Jelly-O Pop"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.JELLYOPOP = "Jelly-O pop it right in my mouth!"

GLOBAL.STRINGS.NAMES.PORTO_RAFT = "Raft"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTO_RAFT = "This looks adequate."
STRINGS.RECIPE_DESC.PORTO_RAFT = "Totally sort of seaworthy."

GLOBAL.STRINGS.NAMES.PORTO_ARMOUREDBOAT = "Armoured Boat"
GLOBAL.STRINGS.RECIPE_DESC.PORTO_ARMOUREDBOAT = "Shell out for this hearty vessel."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTO_ARMOUREDBOAT = "That is one durable boat."

GLOBAL.STRINGS.NAMES.PORTO_CARGOBOAT = "Cargo Boat"
GLOBAL.STRINGS.RECIPE_DESC.PORTO_CARGOBOAT = "Hoarding at sea!"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTO_CARGOBOAT = "It has room for all my stuff!"

GLOBAL.STRINGS.NAMES.PORTO_LOGRAFT = "Log raft"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTO_LOGRAFT = "log raft...?"
GLOBAL.STRINGS.RECIPE_DESC.PORTO_LOGRAFT = "This looks... sort of boat-like..."

GLOBAL.STRINGS.NAMES.PORTO_ROWBOAT = "Row Boat"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTO_ROWBOAT = "Now my adventure is complete."
GLOBAL.STRINGS.RECIPE_DESC.PORTO_ROWBOAT = "A tougher boat"

GLOBAL.STRINGS.NAMES.PORTO_ENCRUSTEDBOAT = "Encrusted Boat"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTO_ENCRUSTEDBOAT = "Pretty sturdy."
GLOBAL.STRINGS.RECIPE_DESC.PORTO_ENCRUSTEDBOAT = "Highly resistant"

GLOBAL.STRINGS.NAMES.PRIMEAPE = "Prime Ape"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PRIMEAPE = "Those things are going to be the end of me."

GLOBAL.STRINGS.NAMES.PRIMEAPEBARREL = "Prime Ape Hut"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PRIMEAPEBARREL = "Here be evil."

GLOBAL.STRINGS.NAMES.MONKEYBALL = "Silly Monkey Ball"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MONKEYBALL = "I have a strange desire to name it after myself."
GLOBAL.STRINGS.RECIPE_DESC.MONKEYBALL = "Get down to monkey business."

GLOBAL.STRINGS.NAMES.NEEDLESPEAR = "Cactus Spike"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.NEEDLESPEAR = "I'm glad I didn't step on this."
GLOBAL.STRINGS.RECIPE_DESC.NEEDLESPEAR = "needlespear"

GLOBAL.STRINGS.NAMES.PEG_LEG = "Peg Leg"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PEG_LEG = "I can perform amputations if anyone'd like to wear it for real."
GLOBAL.STRINGS.RECIPE_DESC.PEG_LEG = "Peg Leg"

GLOBAL.STRINGS.NAMES.SPEAR_POISON = "Spear Poison"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPEAR_POISON = "Now it's extra deadly."
GLOBAL.STRINGS.RECIPE_DESC.SPEAR_POISON = "Jab'em with a sick stick."

GLOBAL.STRINGS.NAMES.MESSAGEBOTTLE1 = "Message in a Bottle"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MESSAGEBOTTLE1 = "Someone wrote me a note!."

GLOBAL.STRINGS.NAMES.BURIEDTREASURE = "X Marks the Spot"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BURIEDTREASURE = "Please be a good treasure!"

GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.COFFEEBUSH = "I think it needs to be fertilized."

GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.JUNGLETREE = "That tree needs a hair cut."

GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.JUNGLETREE_BURNT = "What a waste of wood."

GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.JUNGLETREE_STUMP = "Take that, nature!"

GLOBAL.STRINGS.NAMES.SHARK_GILLS = "Shark Gills"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHARK_GILLS = "I wish I had gills."

GLOBAL.STRINGS.RECIPE_DESC.DOUBLE_UMBRELLAHAT = "Function definitely over fashion."

GLOBAL.STRINGS.NAMES.GRASSNOVA = "Grass"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.GRASSNOVA = "It's a tuft of grass."

GLOBAL.STRINGS.RECIPE_DESC.DOUBLE_UMBRELLAHAT = "Shark Umbrela"

GLOBAL.STRINGS.NAMES.SAIL = "Sail"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SAIL = "This should really transform my boating experience.."
GLOBAL.STRINGS.RECIPE_DESC.SAIL = "Catch the wind!"

GLOBAL.STRINGS.NAMES.CLOTHSAIL = "Cloth Sail"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CLOTHSAIL = "That wind isn't getting away now!"
GLOBAL.STRINGS.RECIPE_DESC.CLOTHSAIL = "Catch even more wind!"

GLOBAL.STRINGS.NAMES.SNAKESKINSAIL = "Snakeskin Sail"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SNAKESKINSAIL = "Scale it and sail it!"
GLOBAL.STRINGS.RECIPE_DESC.SNAKESKINSAIL = "Heavy duty wind catcher."

GLOBAL.STRINGS.NAMES.FEATHERSAIL = "Feather Sail"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FEATHERSAIL = "It's feather-light!"
GLOBAL.STRINGS.RECIPE_DESC.FEATHERSAIL = "Like a bird's wing, for your boat!"

GLOBAL.STRINGS.NAMES.IRONWIND = "Iron Wind"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.IRONWIND = "This is how a scientist should travel.."
GLOBAL.STRINGS.RECIPE_DESC.IRONWIND = "Motorin'!"

GLOBAL.STRINGS.NAMES.WOODLEGSSAIL = "Woodlegs Sail"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOODLEGSSAIL = "The quintessential pirate sail."
GLOBAL.STRINGS.RECIPE_DESC.WOODLEGSSAIL = "I'll become a pirate!"

GLOBAL.STRINGS.NAMES.BOAT_LANTERN = "Boat Lantern"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOAT_LANTERN = "This will do wonders for my nightvision!"
GLOBAL.STRINGS.RECIPE_DESC.BOAT_LANTERN = "Shed some light on the situation."

GLOBAL.STRINGS.NAMES.BOAT_TORCH = "Boat Torch"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOAT_TORCH = "This'll keep my hands free."
GLOBAL.STRINGS.RECIPE_DESC.BOAT_TORCH = "See at sea."

GLOBAL.STRINGS.NAMES.BOATCANNON = "Boat Cannon"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOATCANNON = "The only thing better than a boat is a boat with a cannon."
GLOBAL.STRINGS.RECIPE_DESC.BOATCANNON = "It's got your boat's back."

GLOBAL.STRINGS.NAMES.WOODLEGS_BOATCANNON = "Pirate Cannon"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOODLEGS_BOATCANNON = "Worthy of a pirate"
GLOBAL.STRINGS.RECIPE_DESC.WOODLEGS_BOATCANNON = "Well reinforced"

GLOBAL.STRINGS.NAMES.QUACKERINGRAM = "Quackering Ram"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.QUACKERINGRAM = "SMASH!"
GLOBAL.STRINGS.RECIPE_DESC.QUACKERINGRAM = "Everybody better get out of your way"

GLOBAL.STRINGS.NAMES.QUACKENDRILL = "Quacken Drill"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.QUACKENDRILL = "An implement of deepwater drilling"
GLOBAL.STRINGS.RECIPE_DESC.QUACKENDRILL = "For deep sea quacking"

GLOBAL.STRINGS.NAMES.QUACKENBEAK = "Quacken Beak"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.QUACKENBEAK = "If that brute can't hold its mouth then I will."

GLOBAL.STRINGS.NAMES.TRAWLNET = "Trawl Net"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TRAWLNET = "It is definitely sinking."
GLOBAL.STRINGS.RECIPE_DESC.TRAWLNET = "The patient fisher is always rewarded."

STRINGS.NAMES.GLASS_SHARDS = "Glass Shards"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GLASS_SHARDS = "High temperature turns sand into imperfect glass."
STRINGS.RECIPE_DESC.GLASS_SHARDS = "Shards of your heart."

STRINGS.NAMES.SHARD_SWORD = "Shard Sword"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHARD_SWORD = "The pen is mightier."
STRINGS.RECIPE_DESC.SHARD_SWORD = "To slice nightmare beings."

STRINGS.NAMES.SHARD_BEAK = "Shard Beak"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHARD_BEAK = "An instrument of deconstruction."
STRINGS.RECIPE_DESC.SHARD_BEAK = "Shatters strongholded nests."

STRINGS.NAMES.PORTO_SURFBOARD = "Surfboard"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTO_SURFBOARD = "If I was on my surfboard I could catch you."
STRINGS.RECIPE_DESC.PORTO_SURFBOARD = "Hang ten!"

STRINGS.NAMES.SURFBOARD = "Surfboard"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SURFBOARD = "If I was on my surfboard I could catch you.."
STRINGS.RECIPE_DESC.SURFBOARD = "Hang ten!"

STRINGS.NAMES.WOODLEGSBOAT = "The 'Sea Legs'"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOODLEGSBOAT = "A vessel fit for a scallywag."
STRINGS.RECIPE_DESC.WOODLEGSBOAT = "Go do some pirate stuff."

STRINGS.NAMES.PORTO_WOODLEGSBOAT = "The 'Sea Legs'"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTO_WOODLEGSBOAT = "A vessel fit for a scallywag."
STRINGS.RECIPE_DESC.PORTO_WOODLEGSBOAT = "Go do some pirate stuff."

STRINGS.NAMES.WOODLEGSBOATAMIGO = "Pirate Boat"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOODLEGSBOATAMIGO = "A vessel fit for a scallywag."
STRINGS.RECIPE_DESC.WOODLEGSBOATAMIGO = "Go do some pirate stuff."

STRINGS.NAMES.TURBINE_BLADES = "Turbine Blades"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURBINE_BLADES = "Perhaps this powered that beastly storm?"

STRINGS.NAMES.TRAWLNETDROPPED = "Trawl Net"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TRAWLNETDROPPED = "It is definitely sinking."

STRINGS.NAMES.SHARKITTEN = "Sharkitten"

STRINGS.NAMES.SAPLINGNOVA = "Sapling"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SAPLINGNOVA = "It might be okay if it was cooler."

STRINGS.NAMES.PORTAL_SHIPWRECKED = "Seaworthy"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTAL_SHIPWRECKED = "It's broken."

STRINGS.NAMES.BUOY = "Buoy"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BUOY = "Awww yaaaaa Buoy!."
STRINGS.RECIPE_DESC.BUOY = "Mark your place in the water."

STRINGS.NAMES.ARMOR_LIFEJACKET = "Life jacket"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ARMOR_LIFEJACKET = "Keeps me afloat, without my boat!."
STRINGS.RECIPE_DESC.ARMOR_LIFEJACKET = "Safety first!"

STRINGS.WALLY1 = "Chump."
STRINGS.WALLY2 = "Nice Sailing"

STRINGS.NAMES.SURFBOARDITEM = "Surfboard"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.LUCKYHAT = "Does it make me look scurvy... I mean scary!?"
STRINGS.NAMES.LUCKYHAT = "Lucky Hat"
STRINGS.RECIPE_DESC.LUCKYHAT = "Sniff out treasures."

STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPICEPACK = "My bag of chef's tricks!"
STRINGS.NAMES.SPICEPACK = "Chef Pouch"
STRINGS.RECIPE_DESC.SPICEPACK = "Freshen up your foodstuffs."

STRINGS.CHARACTERS.GENERIC.DESCRIBE.PIRATEHAT = "Fit for a cutthroat scallywag. Or me."
STRINGS.NAMES.PIRATEHAT = "Pirate Hat"
STRINGS.RECIPE_DESC.PIRATEHAT = "It's a pirate's life for ye!"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CAPTAINHAT = "The proper boating attire!"
STRINGS.NAMES.CAPTAINHAT = "Captain Hat"
STRINGS.RECIPE_DESC.CAPTAINHAT = "Wear one. Your boat will respect you more."

STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTABLECOOKPOT = "What new culinary adventures shall we undertake, old friend?"
STRINGS.NAMES.PORTABLECOOKPOT = "Portable Crock Pot"
STRINGS.NAMES.PORTABLECOOKPOT_ITEM = "Portable Crock Pot"
STRINGS.RECIPE_DESC.PORTABLECOOKPOT_ITEM = "What new culinary adventures shall we undertake, old friend?"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.THATCHPACK = "I call it a thatchel"
STRINGS.NAMES.THATCHPACK = "Thatch Pack"
STRINGS.RECIPE_DESC.THATCHPACK = "Carry a light load."

STRINGS.NAMES.PARROT = "Parrot"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PARROT = "I try not to eat anything with a name."

STRINGS.NAMES.SEAGULLWATER = "Seagull"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEAGULLWATER = "Shoo! Find some other land!"

GLOBAL.STRINGS.NAMES.ICEMAKER = "Ice Maker 3000"
GLOBAL.STRINGS.RECIPE_DESC.ICEMAKER = "Ice, ice, baby!"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.ICEMAKER = "Machine is doing very good job!"

GLOBAL.STRINGS.RECIPE_DESC.PRIMEAPEBARREL = "More monkeys!"

GLOBAL.STRINGS.RECIPE_DESC.BALLPHINHOUSE = "Must be a lot of fun in there."

STRINGS.NAMES.DORSALFIN = "Dorsalfin"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DORSALFIN = "Very Sad"

STRINGS.NAMES.CORALLARVE = "Coral Larve"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CORALLARVE = "Is that alive?"

GLOBAL.STRINGS.NAMES.NUBBIN = "Nubbin"
GLOBAL.STRINGS.RECIPE_DESC.NUBBIN = "Anywhere!"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.NUBBIN = "Coral in its essence!"

STRINGS.NAMES.SEAWEED_STALK = "Seaweed Stalk"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEAWEED_STALK = "Now I can make my own farm"

STRINGS.NAMES.COCONADE = "Coconade"
GLOBAL.STRINGS.RECIPE_DESC.COCONADE = "KA-BLAM!!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.COCONADE = "I'll need to light it first or no!"

STRINGS.NAMES.PIRATEPACK = "Pirate Pack"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PIRATEPACK = "I can keep my booty in here."

GLOBAL.STRINGS.NAMES.TAR_EXTRACTOR = "Tar Extractor"
GLOBAL.STRINGS.RECIPE_DESC.TAR_EXTRACTOR = "I'm Rich"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TAR_EXTRACTOR = "Now I dominate the fuel!"

STRINGS.NAMES.TAR_POOL = "Tar Pool"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TAR_POOL = "This must be profound"

STRINGS.NAMES.TAR = "Tar"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TA = "Pure hydrocarbons!"

STRINGS.NAMES.TAR_TRAP = "Tar Trap"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TAR_TRAP = "Pretty sticky"

GLOBAL.STRINGS.NAMES.FISH_FARM = "Fish Farm"
GLOBAL.STRINGS.RECIPE_DESC.FISH_FARM = "Fish"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH_FARM = "Now my iodine supplementation is complete!"

STRINGS.NAMES.ROE = "Roe"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ROE = "Caviar, maybe?"

STRINGS.NAMES.ROE_COOKED = "Roe Cooked"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ROE_COOKED = "Caviar"

STRINGS.NAMES.FISH3 = "Purple Grouper"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH3 = "Typical tropical climate fish."

STRINGS.NAMES.FISH3_COOKED = "Purple Grouper Cooked"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH3_COOKED = "Delicious, as you would expect"

STRINGS.NAMES.FISH4 = "Pierrot Fish"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH4 = "Typical tropical climate fish."

STRINGS.NAMES.FISH4_COOKED = "Pierrot Fish Cooked"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH4_COOKED = "Delicious, as you would expect"

STRINGS.NAMES.FISH5 = "Neon Quattro"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH5 = "Typical tropical climate fish."

STRINGS.NAMES.FISH5_COOKED = "Neon Quattro Cooked"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH5_COOKED = "Delicious, as you would expect"

GLOBAL.STRINGS.NAMES.BLOWDART_POISON = "Blowdart Poison"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BLOWDART_POISON = "Blowdart Poison."
GLOBAL.STRINGS.RECIPE_DESC.BLOWDART_POISON = "Blowdart Poison"

GLOBAL.STRINGS.NAMES.SEATRAP = "Sea Trap"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEATRAP = "Sea Trap."
GLOBAL.STRINGS.RECIPE_DESC.SEATRAP = "Sea Trap"

GLOBAL.STRINGS.NAMES.SEA_CHIMINEA = "Sea Chiminea"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEA_CHIMINEA = "Sea Chiminea."
GLOBAL.STRINGS.RECIPE_DESC.SEA_CHIMINEA = "Sea Chiminea"

GLOBAL.STRINGS.NAMES.TROPICALBOUILLABAISSE = "Tropical Bouillabaisse"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TROPICALBOUILLABAISSE = "Tropical Bouillabaisse."

GLOBAL.STRINGS.NAMES.CAVIAR = "Caviar"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CAVIAR = "Caviar."

GLOBAL.STRINGS.NAMES.OX_FLUTE = "Ox Flute"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OX_FLUTE = "Ox Flute."
GLOBAL.STRINGS.RECIPE_DESC.OX_FLUTE = "Ox Flute"

GLOBAL.STRINGS.NAMES.OXBABY = "Ox baby"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OXBABY = "Ox baby."
--------------store---------
GLOBAL.STRINGS.STORE = {}
modimport("functions/MagicStore.lua")
modimport("functions/DataProvider.lua")
GLOBAL.STRINGS.STORE.UI = {}
GLOBAL.STRINGS.STORE.UI.LASTPAGE = "BACK"
GLOBAL.STRINGS.STORE.UI.NEXTPAGE = "NEXT"
GLOBAL.STRINGS.STORE.UI.SOLDOUT = "SOLDOUT"
GLOBAL.STRINGS.NAMES.STORE = "STORE"

--------------actions-------
GLOBAL.STRINGS.ACTIONS.HACK="Hack"
GLOBAL.STRINGS.ACTIONS.BOATMOUNT="Boat Mount"
GLOBAL.STRINGS.ACTIONS.BOATREPAIR = "Boat Repair"
GLOBAL.STRINGS.ACTIONS.BOATDISMOUNT = "Boat Dismount"
GLOBAL.STRINGS.ACTIONS.STICK = "Stick"
GLOBAL.STRINGS.NAMES.NAUTICALTAB = "Nautical"
GLOBAL.STRINGS.TABS.NAUTICALTAB = "Nautical"
GLOBAL.STRINGS.ACTIONS.LANTERNOFF = "Turn Off"
GLOBAL.STRINGS.ACTIONS.LANTERNON = "Turn On"
GLOBAL.STRINGS.ACTIONS.BOATCANNON = "Shot"
GLOBAL.STRINGS.ACTIONS.RETRIEVE = "Get"
--------------rawling speak---------------
GLOBAL.STRINGS.NAMES.RAWLING = "rawling"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAWLING = "rawling"
GLOBAL.STRINGS.RAWLINGon_hit_water = "Swish!"
GLOBAL.STRINGS.RAWLINGon_dropped = "Dribble me!"
GLOBAL.STRINGS.RAWLINGon_extinguish = "Saved!"
GLOBAL.STRINGS.RAWLINGin_container = "This isn't a peach basket..."
GLOBAL.STRINGS.RAWLINGon_ground = "I could use a little pick me up."
GLOBAL.STRINGS.RAWLINGin_inventory = "Let's cut the bottom out of the basket."
GLOBAL.STRINGS.RAWLINGother_owner = "Ouch!"
GLOBAL.STRINGS.RAWLINGon_ignite = {
"I'm on fire!",
"Ow ow ow ow ow!",
}
GLOBAL.STRINGS.RAWLINGon_pickedup = {
"Is that you James?",
"You're MY MVP!",
}
GLOBAL.STRINGS.RAWLINGon_thrown = {
"To the peach basket!",
"Shoot!",
"You miss 100% of the shots you don't take!",
"I believe I can fly!",
}

GLOBAL.STRINGS.RAWLINGon_bounced = 
{
"Ouch!",
"Nothin' but peaches!",
"Splish!",
"Rejected!",
}
GLOBAL.STRINGS.RAWLINGequipped = {
"You can carry me. For a couple of steps.",
"Is this some kind of Canadian joke?",
"Feel 'free' to throw me.",
}

------------------mapwrapper---------------
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_MAPWRAP_LOSECONTROL = "It would seem my future is foggy."

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_MAPWRAP_RETURN = "I think I felt something brush against my leg..."

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_MAPWRAP_WARN = "Here be monsters."

-------------death causes--------------
STRINGS.NAMES.DROWNING="Drowning"
STRINGS.NAMES.POISON="Poison"