local STRINGS = GLOBAL.STRINGS

-----------------------------Biome Jungle -----------------------------





-----------------------------Biome Tidal Mash---------------------------

GLOBAL.STRINGS.NAMES.TIGERSHARKPOOL = "상어 호수"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TIGERSHARKPOOL = "이상하게 생긴 상어가 살고 있어."


GLOBAL.STRINGS.NAMES.LAVAPONDBIG = "큰 용암 웅덩이"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LAVAPONDBIG = "좀 많이 뜨거워 보이는데."

GLOBAL.STRINGS.NAMES.HARPOON = "작살"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.HARPOON = "투척용 작살이야."



-----------------------------Biome Volcano------------------------------
GLOBAL.STRINGS.NAMES.DRAGOON = "드라군"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DRAGOON = "너 꽤나 빠르다?"

GLOBAL.STRINGS.NAMES.DRAGOONHEART = "드라군 심장"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DRAGOONHEART = "한때는 드라군들의 감정이 담겨있던 곳이었지."

GLOBAL.STRINGS.NAMES.DRAGOONDEN = "드라군 집"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DRAGOONDEN = "저 덩치들도 잠은 자야겠지."

GLOBAL.STRINGS.NAMES.DRAGOONSPIT = "드라군 침"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DRAGOONSPIT = "윽, 역겨워!"

GLOBAL.STRINGS.NAMES.DRAGOONEGG = "드라군 알"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DRAGOONEGG = "방금 그거 금 가는 소리인가?"

GLOBAL.STRINGS.NAMES.OBSIDIAN = "흑요석"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OBSIDIAN = "불의 기운이 담긴 돌이야."

GLOBAL.STRINGS.NAMES.BOOK_METEOR1 = "화산학의 즐거움"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOOK_METEOR1 = "표지에 \"드라군을 좋아하셔야 할 텐데요.\"라고 쓰여있어"

GLOBAL.STRINGS.NAMES.OBSIDIAN_WORKBENCH = "흑요석 작업대"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OBSIDIAN_WORKBENCH = "뭔가 해봐야겠다는 기분이 들어."

GLOBAL.STRINGS.NAMES.OBSIDIANFIREPIT = "흑요석 화덕"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OBSIDIANFIREPIT = "이 화덕은... 더 큰 불을 담는 전도체야."


GLOBAL.STRINGS.NAMES.ARMOROBSIDIAN = "흑요석 갑옷"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.ARMOROBSIDIAN = "난 정말 똑똑해."

GLOBAL.STRINGS.NAMES.SPEAR_OBSIDIAN = "흑요석 창"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPEAR_OBSIDIAN = "깊은 상처를 내겠는걸."

--GLOBAL.STRINGS.NAMES.OBSIDIANMACHETE = "흑요석 마체테"
--GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OBSIDIANMACHETE = "뜨거워서 건드릴 수도 없겠어."

GLOBAL.STRINGS.NAMES.AXEOBSIDIAN = "흑요석 도끼"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.AXEOBSIDIAN = "약속된 승리의 조합!"

GLOBAL.STRINGS.NAMES.ROCK_OBSIDIAN = "흑요석"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.ROCK_OBSIDIAN = "캘 수 없다면 깨 버리겠다!"

GLOBAL.STRINGS.NAMES.OBSIDIANBOMB = "흑요석 폭탄"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OBSIDIANBOMB = "훨씬 크고 아름다운 폭발!"

GLOBAL.STRINGS.NAMES.ROCK_CHARCOAL = "석탄"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.ROCK_CHARCOAL = "커다란 스타킹이 필요하겠어..."

GLOBAL.STRINGS.NAMES.MAGMAROCK = "마그마 더미"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MAGMAROCK_FULL = "삽으로 팔 수 있겠어."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MAGMAROCK = "삽으로 팔 수 있겠어."

GLOBAL.STRINGS.NAMES.MAGMAROCK_GOLD = "황금 마그마 더미"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MAGMAROCK_GOLD_FULL = "황금같은 기회야."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MAGMAROCK_GOLD = "황금같은 기회야."

GLOBAL.STRINGS.NAMES.FLAMEGEYSER = "불 구멍"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FLAMEGEYSER = "물러나는 게 좋겠어."

GLOBAL.STRINGS.NAMES.VOLCANO_SHRUB = "재가 된 나무"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.VOLCANO_SHRUB = "잿더미가 되었네."

GLOBAL.STRINGS.NAMES.VOLCANO_EXIT = "화산"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.VOLCANO_EXIT = "밖에서 시원한 바람이 불어오고 있어."

GLOBAL.STRINGS.NAMES.VULCANO_ENTRANCE = "화산 입구"
GLOBAL.STRINGS.NAMES.ESCADADOVULCAO = "화산 출구"

GLOBAL.STRINGS.NAMES.VOLCANO = "화산"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.VOLCANO = "안전해 보이는군."

GLOBAL.STRINGS.NAMES.VOLCANOSTAFF = "화산 지팡이"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.VOLCANOSTAFF = "'어린이의 손이 닿지 않는 곳에 두시오'라고 쓰여있어."

STRINGS.NAMES.LAVAPOOL = "용암 웅덩이"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LAVAPOOL = "좀 많이 뜨거워 보이는데."

STRINGS.NAMES.DUG_ELEPHANTCACTUS = "코끼리 선인장"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_ELEPHANTCACTUS = "뾰족뾰족해 보이지만 옮겨심을 수 있겠어."
STRINGS.NAMES.ELEPHANTCACTUS = "코끼리 선인장"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ELEPHANTCACTUS = "으, 눈 찔리겠네!"
STRINGS.NAMES.ELEPHANTCACTUS_ACTIVE = "코끼리 선인장"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ELEPHANTCACTUS_ACTIVE = "특이하게 생긴 가시가 나 있어."
STRINGS.NAMES.ELEPHANTCACTUS_STUMP = "코끼리 선인장 뿌리"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ELEPHANTCACTUS_STUMP = "본체가 나오기 전이야."


STRINGS.TABS.OBSIDIANTAB = "볼케닉"
GLOBAL.STRINGS.RECIPE_DESC.DRAGOONDEN = "드라군을 잡으려면 드라군 굴 속으로."
GLOBAL.STRINGS.RECIPE_DESC.OBSIDIANBOMB = "화르륵 쾅쾅!"
GLOBAL.STRINGS.RECIPE_DESC.ARMOROBSIDIAN = "닿기만 해도 데일 것 같은 느낌."
GLOBAL.STRINGS.RECIPE_DESC.SPEAR_OBSIDIAN = "창 속에 담긴 불꽃."
GLOBAL.STRINGS.RECIPE_DESC.OBSIDIANFIREPIT = "모든 불의 왕!"
GLOBAL.STRINGS.RECIPE_DESC.OBSIDIANMACHETE = "베고 태워라!"
GLOBAL.STRINGS.RECIPE_DESC.AXEOBSIDIAN = "보통 도끼랑 똑같아요. 뜨거운 것만 빼면."
--GLOBAL.STRINGS.RECIPE_DESC.COFFEE = "따끈한 커피!"
GLOBAL.STRINGS.RECIPE_DESC.BOOK_METEOR1 = "하늘에서 운석이!"
GLOBAL.STRINGS.RECIPE_DESC.VOLCANOSTAFF = "하늘이 무너집니다!"



--GLOBAL.STRINGS.UI.WORLDGEN.VOLCANOTITLE = "마그마 끓이는 중"
--GLOBAL.STRINGS.NAMES.VOLCANO_ALTAR = "화산 제단"
--GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.VOLCANO_ALTAR.GENERIC = "길이 닫혀있어."
--GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.VOLCANO_ALTAR.OPEN = "제단이 열렸어. 제물을 바치자!"
--GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.VOLCANO_ALTAR_BROKEN = "젠장!"
--GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.VOLCANO_ALTAR_TOWER = "무시무시하게 생겼어!"
--GLOBAL.STRINGS.CHARACTERS.GENERIC.ANNOUNCE_VOLCANO_ERUPT = "좋은 징조가 아닌데."

GLOBAL.STRINGS.NAMES.COFFEEBUSH = "커피나무"
GLOBAL.STRINGS.NAMES.DUG_COFFEEBUSH = "거피니무"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_COFFEEBUSH = "땅으로 돌아가야지!"


GLOBAL.STRINGS.NAMES.COFFEEBEANS = "커피콩"
GLOBAL.STRINGS.NAMES.COFFEEBEANS_COOKED = "볶은 커피콩"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.COFFEEBEANS = "볶아보면 좋은 일이 있을 것 같아."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.COFFEEBEANS_COOKED = "열을 가했더니 확연히 좋아졌어."

GLOBAL.STRINGS.NAMES.COFFEE = "커피"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.COFFEEBOT = "커피 만드는 기계로군."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.COFFEE = "아, 이 감미로운 향기!"


--GLOBAL.STRINGS.SIGA = "Me siga"
GLOBAL.STRINGS.NAMES.WOODLEGS1 = "우드렉스스"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOODLEGS1 = "이 사람은 우드렉스야."

GLOBAL.STRINGS.NAMES.WOODLEGSGHOST = "우드렉스 유령"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOODLEGSGHOST = "한때는 내 친구였지."

GLOBAL.STRINGS.NAMES.WOODLEGS_KEY1 = "뼈 열쇠"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOODLEGS_KEY1 = "어딘가의 무언지는 몰라도 열 수 있겠지."

GLOBAL.STRINGS.NAMES.WOODLEGS_KEY2 = "금 열쇠"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOODLEGS_KEY2 = "무언가를 열 수 있게 생겼어."

GLOBAL.STRINGS.NAMES.WOODLEGS_KEY3 = "철 열쇠"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOODLEGS_KEY3 = "열쇠잖아."

GLOBAL.STRINGS.NAMES.WOODLEGS_CAGE = "우드렉스 감옥"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOODLEGS_CAGE = "쓸데없이 자물쇠가 많네."


GLOBAL.STRINGS.NAMES.SLIP = "슬립"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SLIP = "작고 털 많은 괴눌이야."

GLOBAL.STRINGS.NAMES.SLIPSTOR = "슬립스터"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SLIPSTOR = "크고 털 많은 괴물이야."

GLOBAL.STRINGS.NAMES.SLIPSTOR_SPAWNER = "슬립스터 스포너"



GLOBAL.STRINGS.NAMES.TWISTER = "물개바람"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TWISTER = "어째 이상하게 바람이 불더라니."

GLOBAL.STRINGS.NAMES.TWISTER_SEAL = "물개"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TWISTER_SEAL = "죽ㅇ, 아아."

GLOBAL.STRINGS.NAMES.TWISTER_TORNADO = "토네이도"


GLOBAL.STRINGS.NAMES.MERMFISHER = "낚시꾼 어인"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MERMFISHER = "물고기같이 행동하지 않는 게 좋을거야."

GLOBAL.STRINGS.NAMES.FLUP = "플럽"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FLUP = "나 좀 내버려 둬!"

GLOBAL.STRINGS.NAMES.TIDALPOOL = "갯벌 웅덩이"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TIDALPOOL = "썰물이 남기고 간 웅덩이야."

GLOBAL.STRINGS.NAMES.MERMFISHHOUSE = "낚시꾼 어인 집"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MERMFISHHOUSE = "이상한 냄새가 나."

GLOBAL.STRINGS.NAMES.POISONHOLE = "독 구덩이"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.POISONHOLE = "멀리 떨어지는 게 좋겠어."

GLOBAL.STRINGS.NAMES.TIGERSHARK = "범상어"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TIGERSHARK = "그거 한번 무섭게 생겼네."

GLOBAL.STRINGS.NAMES.TIGERSHARKSHADOW = "범상어 그림자"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TIGERSHARKSHADOW = "녀석의 그림자야!"

GLOBAL.STRINGS.NAMES.SNAKESKINFLOOR = "뱀 비늘 카펫"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SNAKESKINFLOOR = "방과 방을 이어준달까."

GLOBAL.STRINGS.NAMES.TURF_MAGMAFIELD = "용암 대지 토탄"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_MAGMAFIELD = "용암처럼 생긴 땅이야."

GLOBAL.STRINGS.NAMES.TURF_JUNGLE = "정글 토탄"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_JUNGLE = "풀이 아주 무성해."

GLOBAL.STRINGS.NAMES.TURF_ASH = "화산재 토탄"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_ASH = "재가 날려."

GLOBAL.STRINGS.NAMES.TURF_VOLCANO = "화산 토탄"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_VOLCANO = "화산 느낌이 물씬 나."

GLOBAL.STRINGS.NAMES.TURF_TIDALMARSH = "갯벌 습지 토탄"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_TIDALMARSH = "늪 느낌이 나."

GLOBAL.STRINGS.NAMES.TURF_LAVAROCK = "용암 바위 토탄"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_LAVAROCK = "용암 바위 느낌이 나."

GLOBAL.STRINGS.NAMES.TURF_MEADOW = "초원 토탄"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_MEADOW = "초원 바닥이야."

GLOBAL.STRINGS.NAMES.SNAKE = "뱀"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SNAKE = "몸 보신에 좋으려나?"

GLOBAL.STRINGS.NAMES.SNAKE_POISON = "독뱀"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SNAKE_POISON = "그냥 뱀보다 더하네!"

GLOBAL.STRINGS.NAMES.SNAKESKIN = "뱀 가죽"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SNAKESKIN = "뭔가 끌리는 듯 안 끌려."

GLOBAL.STRINGS.NAMES.SNAKE_HOLE = "뱀 구멍"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SNAKE_HOLE = "미리 막을 수 있었을 텐데."

GLOBAL.STRINGS.NAMES.SNAKEOIL = "뱀 기름"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SNAKEOIL = "딱지에 '제이의 만병통치약!'이라고 쓰여있어."


GLOBAL.STRINGS.NAMES.LIVINGJUNGLETREE = "살아있는 정글 나무"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LIVINGJUNGLETREE = "아주 평범한 나무야."

--jungle tree
GLOBAL.STRINGS.NAMES.JUNGLETREE = "정글나무"
GLOBAL.STRINGS.NAMES.TREE_JUNGLE = "정글나무"

GLOBAL.STRINGS.NAMES.JUNGLETREESEED = "정글나무 씨앗"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.JUNGLETREESEED = "속에서 하악대는 소리가 들려."

GLOBAL.STRINGS.NAMES.JUNGLE_TREE_SAPLING = "정글나무 묘목"

--bamboo
GLOBAL.STRINGS.NAMES.BAMBOO = "대나무"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BAMBOO = "저 녀석들을 대나무에 대롱대롱 매달아버릴까?"

GLOBAL.STRINGS.NAMES.BAMBOOTREE = "대나무"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BAMBOOTREE = {
	GENERIC = "꽤나 단단해 보여.",
	BURNING = "잘 가라, 대나무야.",
	BURNT = "막을 수 있었을 텐데.",
	CHOPPED = "받아라, 자연아!"
}

GLOBAL.STRINGS.NAMES.DUG_BAMBOOTREE = "대나무"
GLOBAL.STRINGS.RECIPE_DESC.DUG_BAMBOOTREE = "대나무를 기릅니다."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_BAMBOOTREE = "어디다 심어야겠어."

GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DEPLETED_BAMBOOTREE = "다시 자라긴 할까?"



GLOBAL.STRINGS.NAMES.DOYDOYBABY = "아기 도이도이"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOYDOYBABY = "아, 귀여운, 어, 녀석."

GLOBAL.STRINGS.NAMES.DOYDOYTEEN = "어린 도이도이"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOYDOYTEEN = "쑥쑥 크렴!"

GLOBAL.STRINGS.NAMES.DOYDOY = "도이도이"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOYDOY = "이 바보새, 이상하게 지켜주고 싶어."

GLOBAL.STRINGS.NAMES.DOYDOYEGG = "도이도이 알"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOYDOYEGG = "알이 깰 때까지 놔두자."

GLOBAL.STRINGS.NAMES.DOYDOYEGG_COOKED = "구운 도이도이 알"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOYDOYEGG_COOKED = "적절한 화학적 반응을 통해 더 영양가있게 변형되었어."

GLOBAL.STRINGS.NAMES.DOYDOYEGG_CRACKED = "금이 간 도이도이 알"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOYDOYEGG_CRACKED = "오 이런, 새가 더 있었네!"

GLOBAL.STRINGS.NAMES.DOYDOYFEATHER = "도이도이 깃털"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOYDOYFEATHER = "부드럽지만 멸종위기에 처해있지!"

GLOBAL.STRINGS.NAMES.DOYDOYNEST = "도이도이 새 둥지"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOYDOYNEST = "도이도이 알을 위한 거야, 이 바보야."

GLOBAL.STRINGS.RECIPE_DESC.DOYDOYNEST = "싸우지 말고 도이도이해."
GLOBAL.STRINGS.RECIPE_DESC.DOYDOYEGG = "도이도이를 키워보세요!"

--wildborehouse
GLOBAL.STRINGS.NAMES.WILDBOREHOUSE = "멧돼지 집"
GLOBAL.STRINGS.RECIPE_DESC.WILDBOREHOUSE = "돼지 나가신다!"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WILDBOREHOUSE = "참 돼지같은 집이야."

--wildbore head
GLOBAL.STRINGS.NAMES.WILDBOREHEAD = "멧돼지 머리"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WILDBOREHEAD = "생긴 것처럼 이상한 냄새가 나."
--wildbore 

GLOBAL.STRINGS.NAMES.WILDBORE = "멧돼지"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WILDBORE = "난 거친 사람이 아니라고."

--wildbore guard
GLOBAL.STRINGS.NAMES.WILDBOREGUARD = "멧돼지 경비병"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WILDBOREGUARD = "무엇을 지키는 것이지?"






GLOBAL.STRINGS.NAMES.BEAVERKING_SPAWNER = "Beaverking Spawner"

GLOBAL.STRINGS.NAMES.WILDBEAVERGUARD = "Wildbeaver Guard"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WILDBEAVERGUARD = "He looks serious"

GLOBAL.STRINGS.NAMES.BEAVER_HEAD = "Beaver head"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BEAVER_HEAD = "Someone should tell his family."

GLOBAL.STRINGS.NAMES.BEAVERTORCH = "Beaver Torch"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BEAVERTORCH = "Sure looks cozy."

GLOBAL.STRINGS.NAMES.BEAVERSKIN = "Beaver Skin"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BEAVERSKIN = "The hide of a beaver creature"

GLOBAL.STRINGS.WILDBEAVER_NAMES = {
	"Castor",
}

GLOBAL.STRINGS.NAMES.BEAVER_KING = "Rei Castor"

GLOBAL.STRINGS.WILDBEAVER_TALK_FIGHT = {
	"VOU TE MORDER!",
	"VA EMBORA!",
	"VOLTEI PARA LUTAR!",
}
GLOBAL.STRINGS.WILDBEAVER_TALK_FOLLOW = {
	"VOCÊ ME ENTENDE",
	"VAMOS CONSTRUIR UMA BARRAGEM",
	"NÓS PRECISAMOS DE MAIS MADEIRA",
}
GLOBAL.STRINGS.WILDBEAVER_TALK_GOHOME = {
	"VOU TERMINAR A BARRAGEM AMANHÃ",
	"HORA DE DORMIR",
	"VEJO VOCÊ MAIS TARDE",
}
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WILDBEAVER = "Qual o nome disso...?!"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WILDBEAVER_HOUSE = "Onde o Castor mora."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BEAVER_KING = "Este deve governar todos eles."


GLOBAL.STRINGS.CHARACTERS.WILLOW.DESCRIBE.WILDBEAVER = "Você pega madeira, eu queimo: parece bom?"
GLOBAL.STRINGS.CHARACTERS.WILLOW.DESCRIBE.WILDBEAVER_HOUSE = "Ttodo mundo tem um lugar melhor que o meu..."
GLOBAL.STRINGS.CHARACTERS.WILLOW.DESCRIBE.BEAVER_KING = "Um grande para governar todos eles, suponho."

GLOBAL.STRINGS.CHARACTERS.WENDY.DESCRIBE.WILDBEAVER = "Posso montar em suas costas? Por favor, por favor"
GLOBAL.STRINGS.CHARACTERS.WENDY.DESCRIBE.WILDBEAVER_HOUSE = "Quando a represa se rompe, a inundação consome tudo."
GLOBAL.STRINGS.CHARACTERS.WENDY.DESCRIBE.BEAVER_KING = "Rei das represas."

GLOBAL.STRINGS.CHARACTERS.WX78.DESCRIBE.WILDBEAVER = "ELE COME MADEIRA."
GLOBAL.STRINGS.CHARACTERS.WX78.DESCRIBE.WILDBEAVER_HOUSE = "A MORADA DE UM COMEDOR DE MADEIRA."
GLOBAL.STRINGS.CHARACTERS.WX78.DESCRIBE.BEAVER_KING = "O REI DOS COMEDORES DE MADEIRA."

GLOBAL.STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WILDBEAVER = "Um primo perdido dO Castor canadense?"
GLOBAL.STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WILDBEAVER_HOUSE = "Deve ser para eles o equivalente a uma represa."
GLOBAL.STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BEAVER_KING = "Um rei para governar todos eles e para coordená-los na construção de barragens..."

GLOBAL.STRINGS.CHARACTERS.WOODIE.DESCRIBE.WILDBEAVER = "Ho, bonito. Não somos parentes?"
GLOBAL.STRINGS.CHARACTERS.WOODIE.DESCRIBE.WILDBEAVER_HOUSE = "O único imóvel em que investiria."
GLOBAL.STRINGS.CHARACTERS.WOODIE.DESCRIBE.BEAVER_KING = "Indo bem, né?"

GLOBAL.STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.WILDBEAVER = "Grandes dentuços?"
GLOBAL.STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.WILDBEAVER_HOUSE = "Os dentuços vivem aqui."
GLOBAL.STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.BEAVER_KING = "O maior de todos os dentuços!"

GLOBAL.STRINGS.CHARACTERS.WEBBER.DESCRIBE.WILDBEAVER = "WOODIE é você?"
GLOBAL.STRINGS.CHARACTERS.WEBBER.DESCRIBE.WILDBEAVER_HOUSE = "É aqui que esses criaturas vivem."
GLOBAL.STRINGS.CHARACTERS.WEBBER.DESCRIBE.BEAVER_KING = "Todos saudam o rei madeira primeiro!"

GLOBAL.STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.WILDBEAVER = "Vamos fazer uma batalha?"
GLOBAL.STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.WILDBEAVER_HOUSE = "A morada daqueles Castores selvagens."
GLOBAL.STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.BEAVER_KING = "Como você pode suportar esta ociosidade?"
GLOBAL.STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WILDBEAVER = "Outro tipo de idiotas da aldeia."
GLOBAL.STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WILDBEAVER_HOUSE = "Então eles vivem aqui."
GLOBAL.STRINGS.CHARACTERS.WAXWELL.DESCRIBE.BEAVER_KING = "Você é o supervisor deles ou o quê?"
GLOBAL.STRINGS.RECIPE_DESC.WILDBEAVER_HOUSE = "Beaver out!"
GLOBAL.STRINGS.NAMES.DOUBLE_UMBRELLAHAT = "덤브렐라"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOUBLE_UMBRELLAHAT = "기능은 패션을 정당화하는 법이지."
GLOBAL.STRINGS.NAMES.WILDBEAVER_HOUSE = "Beaver House"
-- FOI DAQUI --
STRINGS.NAMES.VENOMGLAND = "독샘"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.VENOMGLAND = "이열치열이고 이독치독이야."

STRINGS.NAMES.BERRYBUSH2_SNAKE = "베리 덤불"

STRINGS.NAMES.OCTOPUSKING = "문어왕"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.OCTOPUSKING = "봐, 나랑 닮았네."

STRINGS.NAMES.SWEET_POTATO_PLANTED = "고구마"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SWEET_POTATO_PLANTED = "이상하게 생긴 당근이야."

STRINGS.NAMES.SWEET_POTATO = "고구마"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SWEET_POTATO = "맛있어 보이는군!!"

STRINGS.NAMES.SWEET_POTATO_COOKED = "군고구마"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SWEET_POTATO_COOKED = "훨씬 맛있어보여!!"

STRINGS.NAMES.PARROT_PIRATE = "해적 앵무새"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PARROT_PIRATE = "이름이 달린 녀석은 먹기 싫어."

STRINGS.NAMES.DUBLOON = "금화"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUBLOON = "난 부자가 될 거야!!"

STRINGS.NAMES.DOYDOYFAN = "부채"
STRINGS.RECIPE_DESC.DOYDOYFAN = "고풍스럽고 부드러운 열대풍 부채."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOYDOYFAN = "이상하게 바람이 두 배는 빠르게 불어."

STRINGS.NAMES.FABRIC = "펀"
STRINGS.RECIPE_DESC.FABRIC = "대나무가 못할 것은 없다!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FABRIC = "단단한 줄기에서 이렇게 부드러운 천이 나올 수가!"

STRINGS.NAMES.SNAKESKINHAT = "뱀 비늘 모자"
STRINGS.RECIPE_DESC.SNAKESKINHAT = "비도 피하고, 시원해 보입니다." 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SNAKESKINHAT = "머리가 젖지 않게 해주겠어."

STRINGS.NAMES.ARMOR_SNAKESKIN = "뱀 비늘 자켓"
STRINGS.RECIPE_DESC.ARMOR_SNAKESKIN = "절대로 젖지 않는 가죽 자켓입니다."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ARMOR_SNAKESKIN = "정말 멋져!!"

STRINGS.NAMES.TURF_SNAKESKINFLOOR = "뱀 비늘 카펫"
STRINGS.RECIPE_DESC.TURF_SNAKESKINFLOOR = "집을 하나로 묶는달까요."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_SNAKESKINFLOOR = "스스스스타일리시하군."

--STRINGS.NAMES.TURF_WATER_MANGROVE = "红树林地皮"
--STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_WATER_MANGROVE = "红树林地皮"

STRINGS.NAMES.TURF_BEACH = "해변 토탄"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_BEACH = "모래가 날려."

STRINGS.NAMES.COCONUT = "코코넛"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.COCONUT = "쪼갤 도구가 필요해."

STRINGS.NAMES.COCONUT_HALVED = "자른 코코넛"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.COCONUT_HALVED = "잡고 두드리면 말 울음소리가 나."

STRINGS.NAMES.COCONUT_COOKED = "구운 코코넛"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.COCONUT_COOKED = "케이크만 있으면 좋겠는데."

STRINGS.NAMES.PALMTREE = "야자수"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PALMTREE = "열대지방에 왔다는 게 실감나네."

STRINGS.NAMES.PALMLEAF = "야자수 잎"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PALMLEAF = "난 젖은 머리도 멋있어...... 단지 말리는 게 일일 뿐."

STRINGS.NAMES.ROCK_LIMPET = "따개비 바위"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ROCK_LIMPET = "따개비를 양동이 가득 잡을 수도 있겠어!"

STRINGS.NAMES.LIMPETS = "따개비"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LIMPETS = "차라리 굶는 게 나을지도."

STRINGS.NAMES.LIMPETS_COOKED = "구운 따개비"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LIMPETS_COOKED = "맛있겠다, 요놈!"

STRINGS.NAMES.PALMLEAF_HUT = "나무 그늘"
STRINGS.RECIPE_DESC.PALMLEAF_HUT = "비를 막아줍니다. 일단은요."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PALMLEAF_HUT = "그늘이 좋다니까."

STRINGS.NAMES.SAND_CASTLE = "모래성"
STRINGS.RECIPE_DESC.SAND_CASTLE = "보고 있으면 편안합니다."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SAND_CASTLE = "내가 만들었어!"

STRINGS.NAMES.SANDHILL = "모래 더미"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SANDHILL = "신발에 들어오기만 해 봐라."

STRINGS.NAMES.SAND = "모래"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SAND = "그저 모래 한 줌이야."

STRINGS.NAMES.SEASHELL_BEACHED = "해변에 박힌 조개 껍데기"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEASHELL_BEACHED = "바다가 그대를 거부하리라."

STRINGS.NAMES.SEASHELL = "조개 껍데기"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEASHELL = "옛날에는 돈 대신 썼다지."

STRINGS.NAMES.CRATE = "상자"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CRATE = "열 수 있는 방법이 있을거야."

STRINGS.NAMES.CRAB = "게끼"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CRAB = "녀석 한 번 팔팔하네."

STRINGS.NAMES.CRABHOLE = "게구멍"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CRABHOLE = "그냥 게구멍이야."

STRINGS.NAMES.CRAB_HIDDEN = "게끼"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CRAB_HIDDEN = "저 녀석 어디서 나온거지?"

STRINGS.NAMES.SEAGULL = "갈매기"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEAGULL = "훠이! 다른 곳으로 가!"

STRINGS.NAMES.FISH_MEAT_SMALL = "작은 생선살"

STRINGS.NAMES.TROPICAL_FISH = "열대어"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TROPICAL_FISH = "열대어같은데."

STRINGS.NAMES.TUNACAN = "참치캔"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TUNACAN = "마체테로 열 수 있겠어."

STRINGS.NAMES.TOUCAN = "큰부리새"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TOUCAN = "좀처럼 건드릴 수가 없어."

STRINGS.NAMES.RAFT = "대나무 뗏목"
STRINGS.RECIPE_DESC.RAFT = "항해에 꽤나 좋습니다."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAFT = "이 정도면 괜찮겠어."

STRINGS.NAMES.SLOTMACHINE = "슬롯머신"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SLOTMACHINE = "한번 붙잡으면 떠나기 힘들겠어."

STRINGS.NAMES.VINE = "덩굴"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.VINE = "이걸 가지고 뭔가를 묶을 수 있겠어."

STRINGS.NAMES.BUSH_VINE = "덩굴"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BUSH_VINE = "온통 덩굴져!!"

STRINGS.NAMES.DUG_BUSH_VINE = "덩굴"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_BUSH_VINE = "어서 주워야겠어."

STRINGS.NAMES.MACHETE = "마체테"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MACHETE = "참 잘 드는 칼이야."
STRINGS.RECIPE_DESC.MACHETE = "무엇이든 싹싹!"

STRINGS.NAMES.GOLDENMACHETE = "금 마체테"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GOLDENMACHETE = "멋지게 싹싹!"
STRINGS.RECIPE_DESC.GOLDENMACHETE = "무엇이든 멋지게 싹싹!"

STRINGS.NAMES.OBSIDIANMACHETE = "흑요석 마체테"
STRINGS.RECIPE_DESC.OBSIDIANMACHETE = "베고 태워라!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.OBSIDIANMACHETE = "건드리기 힘들 정도로 뜨거워."

STRINGS.PULAFORA = "음... 너무 얕아."
STRINGS.SEMBARCO = "내 배 어디갔지? 난 여기서 죽고 말 거야!"

STRINGS.NAMES.CORMORANT = "가마우지"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CORMORANT = "생선을 많이 먹은 모양이야."

STRINGS.NAMES.SEAWEED = "해초"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEAWEED = "바다에서 나는 풀이야."

STRINGS.NAMES.SEAWEED_COOKED = "구운 해초"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.COOKED = "숯불에 잘 구워졌어."

STRINGS.NAMES.SEAWEED_DRIED = "말린 해초"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEAWEED_DRIED = "짭짤해요!"

STRINGS.NAMES.SEAWEED_PLANTED = "해초"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEAWEED_PLANTED = "이거 먹을 수 있는건가?"

STRINGS.NAMES.CORAL = "산호"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CORAL = "살아있는 재료라!"

STRINGS.NAMES.CORALREEF = "산호초"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CORALREEF = "산호가 암초를 이루었어!"

STRINGS.NAMES.FISHINHOLE = "물고기 떼"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISHINHOLE = "꽤나 물고기가 많아보여." --- ATÉ AQUI ----

GLOBAL.STRINGS.NAMES.GRASS_WATER = "풀"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.GRASS_WATER = "여기서도 자라네?"

GLOBAL.STRINGS.NAMES.TREE_MANGROVE = "맹그로브 나무"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TREE_MANGROVE = "아주 잘 적응했어."

GLOBAL.STRINGS.NAMES.ANTIDOTE = "해독제"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.ANTIDOTE = "큰 도움이 되겠어."
GLOBAL.STRINGS.RECIPE_DESC.ANTIDOTE = "중독을 치료합니다."

GLOBAL.STRINGS.NAMES.QUAGMIRE_SALMON = "연어"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.QUAGMIRE_SALMON = "흠... 꽤나 좋아보여."

GLOBAL.STRINGS.NAMES.QUAGMIRE_POND_SALT = "소금 호수"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.QUAGMIRE_POND_SALT = "이제야 짠맛 좀 보겠네."

GLOBAL.STRINGS.NAMES.QUAGMIRE_SWAMPIG = "늪돼지"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.QUAGMIRE_SWAMPIG = "늪에 사는 돼지야."

GLOBAL.STRINGS.NAMES.QUAGMIRE_SWAMPIG_HOUSE = "늪돼지집"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.QUAGMIRE_SWAMPIG_HOUSE = "내가 아는 돼지들보다는 낫네."

GLOBAL.STRINGS.NAMES.QUAGMIRE_SWAMPIG_HOUSE_RUBBLE = "늪돼지집"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.QUAGMIRE_SWAMPIG_HOUSE_RUBBLE = "내가 아는 돼지들보다는 낫네."

GLOBAL.STRINGS.NAMES.CROCODOG = "악어개"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CROCODOG = "물리면 아프겠지."

GLOBAL.STRINGS.NAMES.WATERCROCODOG = "바다 악어개"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WATERCROCODOG = "당연히 바다에 있을 때 더 세겠지."

GLOBAL.STRINGS.NAMES.POISONCROCODOG = "독 악어개"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.POISONCROCODOG = "제발 좀 저리 가!"

GLOBAL.STRINGS.NAMES.GRASSWATER = "풀"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.GRASSWATER = "그냥 풀이야."

GLOBAL.STRINGS.NAMES.ARMOR_SEASHELL = "조개껍질 갑옷"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.ARMOR_SEASHELL = "바다생물이 된 기분이야."
GLOBAL.STRINGS.RECIPE_DESC.ARMOR_SEASHELL = "더 강력한 보호구를."

GLOBAL.STRINGS.NAMES.OXHAT = "뿔 모자"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OXHAT = "스타일리시하군."
GLOBAL.STRINGS.RECIPE_DESC.OXHAT = "좀 더 보호받으세요."

GLOBAL.STRINGS.NAMES.CHIMINEA = "아궁이"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CHIMINEA = "비 걱정, 이젠 안녕."
GLOBAL.STRINGS.RECIPE_DESC.CHIMINEA = "비로부터 보호받습니다."

GLOBAL.STRINGS.NAMES.OX_HORN = "물소 뿔"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OX_HORN = "슬프구만."

GLOBAL.STRINGS.NAMES.OX = "물소"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OX = "물을 좋아하는구나."

GLOBAL.STRINGS.NAMES.ROWBOAT = "나룻배"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.ROWBOAT = "이제 진짜 모험이 시작되는구나."
GLOBAL.STRINGS.RECIPE_DESC.ROWBOAT = "더 튼튼한 배입니다."

GLOBAL.STRINGS.NAMES.ENCRUSTEDBOAT = "딱지배"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.ENCRUSTEDBOAT = "꽤나 튼튼한데."
GLOBAL.STRINGS.RECIPE_DESC.ENCRUSTEDBOAT = "매우 튼튼합니다."

GLOBAL.STRINGS.NAMES.TURF_QUAGMIRE_PARKFIELD = "공원 토탄"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_QUAGMIRE_PARKFIELD = "스타일리시해."

GLOBAL.STRINGS.NAMES.COTTONTREE = "사탕나무"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.COTTONTREE = "부드러워."

GLOBAL.STRINGS.NAMES.COTTONTREE_SAPLING = "사탕나무 묘목"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.COTTONTREE_SAPLING = "이제 어디든지 심을 수 있겠어."

GLOBAL.STRINGS.NAMES.COTTONTREE_CONE = "솜 나무 씨앗"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.COTTONTREE_CONE = "씨앗?"

GLOBAL.STRINGS.NAMES.BALLPHINHOUSE = "병고래 궁전"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BALLPHINHOUSE = "재미있는 일이 가득해보여."

GLOBAL.STRINGS.NAMES.BALLPHIN = "병고래"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BALLPHIN = "정말 귀여워."

GLOBAL.STRINGS.NAMES.JELLYFISH = "해파리"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.JELLYFISH = "쏘아대는 녀석이야."

GLOBAL.STRINGS.NAMES.JELLYFISH_DEAD = "죽은 해파리"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.JELLYFISH_DEAD = "이 상태에서도 쏘아."

GLOBAL.STRINGS.NAMES.JELLYFISH_COOKED = "구운 해파리"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.JELLYFISH_COOKED = "심지어 맛도 없어!"

GLOBAL.STRINGS.NAMES.JELLYJERKY = "말린 해파리"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.JELLYJERKY = "더는 쏘지 않아."

GLOBAL.STRINGS.NAMES.JELLYFISH_PLANTED = "해파리"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.JELLYFISH_PLANTED = "이게 뭐지?"

GLOBAL.STRINGS.NAMES.LOGRAFT = "뗏목"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LOGRAFT = "통나무 땟목...?"
GLOBAL.STRINGS.RECIPE_DESC.LOGRAFT = "대강... 배 모양은 나는군요..."

GLOBAL.STRINGS.NAMES.FROG_POISON = "독 개구리"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FROG_POISON = "그냥 개구리보다 못되어 보이는군."

GLOBAL.STRINGS.NAMES.SHARKITTENSPAWNER = "상냥이 집"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHARKITTENSPAWNER = "엄마는 어디갔지?"

GLOBAL.STRINGS.NAMES.WHALE_BLUE = "파란 고래"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WHALE_BLUE = "저 고래는 감정적인 문제가 있나봐."

GLOBAL.STRINGS.NAMES.WHALE_WHITE = "하얀 고래"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WHALE_WHITE = "싸움꾼같아 보여."

GLOBAL.STRINGS.NAMES.WHALE_CARCASS_WHITE = "하얀 고래 시체"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WHALE_CARCASS_WHITE = "징그러워. 벌써 부패가 시작된 것 같은데."

GLOBAL.STRINGS.NAMES.WHALE_CARCASS_BLUE = "파란 고래 시체"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WHALE_CARCASS_BLUE = "징그러워. 벌써 부패가 시작된 것 같은데."

GLOBAL.STRINGS.NAMES.LOBSTER_DEAD_COOKED = "구운 웝스터"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LOBSTER_DEAD_COOKED = "맛있는 웝스터야.."

GLOBAL.STRINGS.NAMES.LOBSTER_DEAD = "죽은 웝스터"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LOBSTER_DEAD = "맛있어져라!"

GLOBAL.STRINGS.NAMES.FISH_RAW_SMALL_COOKED = "구운 작은 생선"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH_RAW_SMALL_COOKED = "작은 물고기를 요리했어."

GLOBAL.STRINGS.NAMES.FISH_RAW_SMALL = "작은 생선"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH_RAW_SMALL = "작은 물고기야."

GLOBAL.STRINGS.NAMES.FISH_MED_COOKED = "구운 개물고기"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH_MED_COOKED = "완벽하게 구워졌어."

GLOBAL.STRINGS.NAMES.FISH_MED = "개물고기"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH_MED = "죽은 개물고기야."

GLOBAL.STRINGS.NAMES.SPOILED_FISH = "썩은 생선"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPOILED_FISH = "냄새가 영 아닌데."

GLOBAL.STRINGS.NAMES.FISH_RAW = "생선"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH_RAW = "생선살 덩어리야."

GLOBAL.STRINGS.NAMES.DEAD_SWORDFISH = "죽은 청새치"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DEAD_SWORDFISH = "달고 다니면 큰일나겠지."

GLOBAL.STRINGS.NAMES.BLUBBER = "고래 지방"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BLUBBER = "질척질척하군."

GLOBAL.STRINGS.NAMES.KNIGHTBOAT_CANNONSHOT = "나이트의 포탄"

GLOBAL.STRINGS.NAMES.KNIGHTBOAT = "보트 탄 나이트"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.KNIGHTBOAT = "물길을 열어라, 이 미치광이야!"

GLOBAL.STRINGS.NAMES.OCTOPUSCHEST = "문어 상자"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OCTOPUSCHEST = "물에 가라앉지는 않겠지."

GLOBAL.STRINGS.NAMES.KRAKEN = "꾸왁켄"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.KRAKEN = "지금은 장난칠 때가 아니야!"

GLOBAL.STRINGS.NAMES.KRAKENCHEST = "쿠왁켄 상자"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.KRAKENCHEST = "승자에게 보상이 있나니."

GLOBAL.STRINGS.NAMES.KRAKEN_TENTACLE = "쿠왁켄 촉수"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.KRAKEN_TENTACLE = "영원히 잠들지 않는 짐승이여."

GLOBAL.STRINGS.NAMES.SOLOFISH = "개물고기"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SOLOFISH = "젖은 개 털 냄새가 나."

GLOBAL.STRINGS.NAMES.SWORDFISH = "청새치"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SWORDFISH = "이 녀석은 나에게 돌진하는 데에 적합하게 진화한 모양이야."

GLOBAL.STRINGS.NAMES.LOBSTER_LAND= "웝스터"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LOBSTER_LAND= "이 녀석 자고 있어."

GLOBAL.STRINGS.NAMES.SHARX = "바다 하운드"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHARX = "꽤나 끈질긴 녀석들이군."

GLOBAL.STRINGS.NAMES.STUNGRAY = "가오리"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.STUNGRAY = "거리를 두는 게 좋겠어."

GLOBAL.STRINGS.NAMES.LUGGAGECHEST = "유실물"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LUGGAGECHEST = "특급 유람선이라도 가라앉았던 모양이야."

GLOBAL.STRINGS.NAMES.REDBARREL = "화약통"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.REDBARREL = "참 새롭구만."

GLOBAL.STRINGS.NAMES.LOBSTERHOLE = "랍스터 굴"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LOBSTERHOLE = "이 녀석 자고 있어."

GLOBAL.STRINGS.NAMES.DEBRIS_1 = "잔해"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DEBRIS_1 = "내가 오기 전에 누군가가 왔던 흔적이야!"

GLOBAL.STRINGS.NAMES.DEBRIS_2 = "잔해"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DEBRIS_2 = "내가 오기 전에 누군가가 왔던 흔적이야!"

GLOBAL.STRINGS.NAMES.DEBRIS_3 = "잔해"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DEBRIS_3 = "내가 오기 전에 누군가가 왔던 흔적이야!"

GLOBAL.STRINGS.NAMES.DEBRIS_4 = "잔해"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DEBRIS_4 = "내가 오기 전에 누군가가 왔던 흔적이야!"

GLOBAL.STRINGS.NAMES.BOATREPAIRKIT = "배 수리 키트"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOATREPAIRKIT = "내 배에 부력을 더해줄거야."
GLOBAL.STRINGS.RECIPE_DESC.BOATREPAIRKIT = "배를 더 오래오래!"

GLOBAL.STRINGS.NAMES.WRECK = "난파선"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WRECK = "불행한 최후를 맞았구나."

GLOBAL.STRINGS.NAMES.PIRATEGHOST = "해적유령"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PIRATEGHOST = "끔찍한 최후를 맞이한 유령이야. 잘못하면 나도 그렇게 되겠어."

GLOBAL.STRINGS.NAMES.WRECKOF = "%s 호의 잔해"
GLOBAL.STRINGS.NAMES.SHIPNAMES =
{"노틸러스",
"맥케이 베넷",
"메리 셀레스트",
"비글",
"산타 마리아",
"블루노즈",
"마우레타니아",
"엔데버",
"에드먼드 피츠제럴드",
"피쿼드",
"미시시네바",
"아프리칸 프린세스",
"몽블랑",
"케인",
 "파라오",
 "미노프",
 "시라쿠샤",
 "바론 오브 렌프루",
 "아리엘",
 "히스파니올라",}

GLOBAL.STRINGS.NAMES.MUSSEL_STICK = "홍합 막대"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSSEL_STICK = "저기 홍합 무리에 꽂아넣으면 되겠지."
GLOBAL.STRINGS.RECIPE_DESC.MUSSEL_STICK = "홍합을 잡는 막대입니다."

GLOBAL.STRINGS.NAMES.MUSSEL_FARM = "홍합 더미"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSSEL_FARM = "홍합은 왜 홍합일까? 붉지도 않은데."

GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSSEL_FARM = "홍합은 왜 홍합일까? 붉지도 않은데."
GLOBAL.STRINGS.NAMES.MUSSEL_FARM = "홍합 더미"

GLOBAL.STRINGS.NAMES.MUSSEL_COOKED = "구운 홍합"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSSEL_COOKED = "못된 녀석, 벌 받아라."

GLOBAL.STRINGS.NAMES.MUSSEL = "홍합"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSSEL = "홍합은 왜 홍합일까? 붉지도 않은데."

GLOBAL.STRINGS.NAMES.MOSQUITO_POISON = "독모기"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOSQUITO_POISON = "끔찍한 병을 옮기고 다니는 모기야."

GLOBAL.STRINGS.NAMES.WATERYGRAVE= "바다의 무덤"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WATERYGRAVE = "여기서 뭔가 낚아올릴 수는 있겠지만 꼭 그래야 할까?"

GLOBAL.STRINGS.NAMES.BIOLUMINESCENCE= "유광충"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BIOLUMINESCENCE = "은은한 빛을 내고 있어."

GLOBAL.STRINGS.NAMES.BOTTLELANTERN= "병 랜턴"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOTTLELANTERN = "마치 햇빛을 담은 것 같아."
GLOBAL.STRINGS.RECIPE_DESC.BOTTLELANTERN = "병 속에 담긴 발광생물."

GLOBAL.STRINGS.NAMES.MESSAGEBOTTLEEMPTY1= "빈 병"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MESSAGEBOTTLEEMPTY1 = "그냥 빈 병이야."
GLOBAL.STRINGS.RECIPE_DESC.MESSAGEBOTTLEEMPTY1 = "재활용하는 것 잊지 마세요!"

GLOBAL.STRINGS.NAMES.ARMOUREDBOAT = "장갑선"
GLOBAL.STRINGS.RECIPE_DESC.ARMOUREDBOAT = "조가비를 달아서 더 아늑합니다."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.ARMOUREDBOAT = "꽤나 튼튼하네."

GLOBAL.STRINGS.NAMES.CARGOBOAT = "화물선"
GLOBAL.STRINGS.RECIPE_DESC.CARGOBOAT = "만선이다!"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CARGOBOAT = "물건을 넣어둘 공간이 있어!"

GLOBAL.STRINGS.NAMES.CORAL_BRAIN = "뇌 산호 조각"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CORAL_BRAIN = "생각하는 사람을 위한 음식이랄까."

GLOBAL.STRINGS.NAMES.CORAL_BRAIN_ROCK = "뇌 산호"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CORAL_BRAIN_ROCK = "무슨 생각을 하는걸까?"

GLOBAL.STRINGS.NAMES.SANDBAG = "모래 주머니"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SANDBAG = "물이 들어오지 못하게 막아줄 거야."

GLOBAL.STRINGS.NAMES.SANDBAG_ITEM = "모래 주머니"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SANDBAG_ITEM = "모래가 간다!"
GLOBAL.STRINGS.RECIPE_DESC.SANDBAG_ITEM = "물은 모래의 훌륭한 먹잇감입니다."

GLOBAL.STRINGS.NAMES.LIMESTONE = "석회석"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LIMESTONE = "쓸만한 건축 재료가 될 거야."
GLOBAL.STRINGS.RECIPE_DESC.LIMESTONE = "석회로 이루어진 돌입니다."

GLOBAL.STRINGS.NAMES.CUTLASS = "청새치 칼"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUTLASS = "칼에서 비린내가 나지는 않겠지...?"
GLOBAL.STRINGS.RECIPE_DESC.CUTLASS = "이 검을 만드는 데에 물고기는 해쳐지지 않지 않았습니다."

GLOBAL.STRINGS.NAMES.AERODYNAMICHAT = "매끈한 모자"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.AERODYNAMICHAT = "바람을 뚫고 달리는 거야!"
GLOBAL.STRINGS.RECIPE_DESC.AERODYNAMICHAT = "효율적인 이동을 위한 공기역학적 구조."

GLOBAL.STRINGS.NAMES.SHARK_FIN = "상어 지느러미"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHARK_FIN = "매끈한 지느러미야."

GLOBAL.STRINGS.NAMES.RAINBOWJELLYFISH = "무지개 해파리"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAINBOWJELLYFISH = "과학적 호기심을 자극하는군!"

GLOBAL.STRINGS.NAMES.RAINBOWJELLYFISH_DEAD = "죽은 무지개 해파리"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAINBOWJELLYFISH_DEAD = "좋은 곳으로 갔겠지."

GLOBAL.STRINGS.NAMES.RAINBOWJELLYFISH_COOKED = "구운 무지개 해파리"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAINBOWJELLYFISH_COOKED = "하늘하늘해."

GLOBAL.STRINGS.NAMES.RAINBOWJELLYJERKY = "말린 무리개 해파리"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAINBOWJELLYJERKY = "이런 걸 안 먹으면 바보지."

GLOBAL.STRINGS.NAMES.RAINBOWJELLYFISH_PLANTED = "무지개 해파리"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAINBOWJELLYFISH_PLANTED = "기이하고 이상한 과학이랄까."

GLOBAL.STRINGS.NAMES.BANANAPOP = "바나나 팝"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BANANAPOP = "악, 내 머리! 얼어버리면 안 되는데!"

GLOBAL.STRINGS.NAMES.CEVICHE = "세비체"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CEVICHE = "더 큰 그릇 없나? 무슨 새우같이 생긴 게 있네."

GLOBAL.STRINGS.NAMES.SWEETPOTATOSOUFFLE = "고구마 수플레"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SWEETPOTATOSOUFFLE = "요즘 신선한 고구마 수플레가 인기라지."

GLOBAL.STRINGS.NAMES.SEAFOODGUMBO = "해산물 검보"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEAFOODGUMBO = "점보 사이즈 해산물 검보다!"

GLOBAL.STRINGS.NAMES.SURFNTURF = "서프 앤 터프"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SURFNTURF = "완벽해!"

GLOBAL.STRINGS.NAMES.SHARKFINSOUP = "샥스핀 스프"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHARKFINSOUP = "완전히 끝장났군!"

GLOBAL.STRINGS.NAMES.MUSSELBOUILLABAISE = "홍합 부야베스"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSSELBOUILLABAISE = "얼마나 많은 실험을 할 수 있겠냐고!"

GLOBAL.STRINGS.NAMES.MONSTERTARTARE = "몬스터 타르타르"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MONSTERTARTARE = "먹을 게 있긴 한 모양이야."

GLOBAL.STRINGS.NAMES.LOBSTERDINNER = "랍스터 정식"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LOBSTERDINNER = "랍스터만 먹어도 정식이라고 해야 하나?"

GLOBAL.STRINGS.NAMES.LOBSTERBISQUE = "랍스터 비스크"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LOBSTERBISQUE = "간을 더 해도 되겠지만 내 비스크에는 그러지 않을거야."

GLOBAL.STRINGS.NAMES.FRESHFRUITCREPES = "신선한 과일 크레페"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FRESHFRUITCREPES = "아, 달콤한 과일! 훌륭한 아침식사지."

GLOBAL.STRINGS.NAMES.BISQUE = "비스크"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BISQUE = "이걸 끓이고 있자니 참 살아있는 느낌이야!"

GLOBAL.STRINGS.NAMES.CALIFORNIAROLL = "캘리포니아 롤"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CALIFORNIAROLL = "젓가락이 없는데 어떻게 먹을까.0"

GLOBAL.STRINGS.NAMES.JELLYOPOP = "젤리 오 팝 "
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.JELLYOPOP = "입안에서 톡톡 터지는 이 맛!"

GLOBAL.STRINGS.NAMES.PORTO_RAFT = "대나무 뗏목"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTO_RAFT = "꽤나 적당해보이는군."
STRINGS.RECIPE_DESC.PORTO_RAFT = "꽤나 항해에 적합합니다."

GLOBAL.STRINGS.NAMES.PORTO_ARMOUREDBOAT = "장갑선"
GLOBAL.STRINGS.RECIPE_DESC.PORTO_ARMOUREDBOAT = "장갑을 두르니 더욱 아늑합니다."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTO_ARMOUREDBOAT = "꽤나 튼튼해보여."

GLOBAL.STRINGS.NAMES.PORTO_CARGOBOAT = "화물선"
GLOBAL.STRINGS.RECIPE_DESC.PORTO_CARGOBOAT = "만선이다!"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTO_CARGOBOAT = "물건을 넣어둘 수 있는 공간이 있어!"

GLOBAL.STRINGS.NAMES.PORTO_LOGRAFT = "뗏목"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTO_LOGRAFT = "통나무 뗏목...?"
GLOBAL.STRINGS.RECIPE_DESC.PORTO_LOGRAFT = "나름... 배 모양은 갖췄네요..."

GLOBAL.STRINGS.NAMES.PORTO_ROWBOAT = "나무배"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTO_ROWBOAT = "이거 하나면 다 되겠어."
GLOBAL.STRINGS.RECIPE_DESC.PORTO_ROWBOAT = "더 튼튼한 배입니다"

GLOBAL.STRINGS.NAMES.PORTO_ENCRUSTEDBOAT = "딱딱한 배"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTO_ENCRUSTEDBOAT = "굳건하게 생겼어."
GLOBAL.STRINGS.RECIPE_DESC.PORTO_ENCRUSTEDBOAT = "매우 튼튼합니다."

GLOBAL.STRINGS.NAMES.PRIMEAPE = "원숭이"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PRIMEAPE = "나도 결국 저렇게 되는 걸까."

GLOBAL.STRINGS.NAMES.PRIMEAPEBARREL = "원숭이 집"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PRIMEAPEBARREL = "그 사악한 놈들이 사는 집이야."

GLOBAL.STRINGS.NAMES.MONKEYBALL = "바보 원숭이 공"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MONKEYBALL = "어째 내 이름을 붙이면 좋을 것 같아."
GLOBAL.STRINGS.RECIPE_DESC.MONKEYBALL = "원숭이들은 신경쓰지 마세요."

GLOBAL.STRINGS.NAMES.NEEDLESPEAR = "선인장 가시"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.NEEDLESPEAR = "밟지 않아서 다행이야."
GLOBAL.STRINGS.RECIPE_DESC.NEEDLESPEAR = "선인장 가시"

GLOBAL.STRINGS.NAMES.PEG_LEG = "의족"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PEG_LEG = "누구든지 이걸 신어보고 싶다면 내가 다리를 잘라주지."
GLOBAL.STRINGS.RECIPE_DESC.PEG_LEG = "Peg Leg"

GLOBAL.STRINGS.NAMES.SPEAR_POISON = "독 창"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPEAR_POISON = "훨씬 더 위협적이야."
GLOBAL.STRINGS.RECIPE_DESC.SPEAR_POISON = "더 아프게 찌르세요."

GLOBAL.STRINGS.NAMES.MESSAGEBOTTLE1 = "메세지가 들어있는 병"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MESSAGEBOTTLE1 = "누군가가 나에게 메시지를 남겼어!."

GLOBAL.STRINGS.NAMES.BURIEDTREASURE = "X 마크"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BURIEDTREASURE = "제발 좋은 것이 나왔으면!"

GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.COFFEEBUSH = "비료를 줘야 할 것 같아."

GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.JUNGLETREE = "이발 좀 해야겠는걸."

GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.JUNGLETREE_BURNT = "완전 나무 낭비야."

GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.JUNGLETREE_STUMP = "받아라, 자연아!"

GLOBAL.STRINGS.NAMES.SHARK_GILLS = "상어 아가미"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHARK_GILLS = "나도 아가미가 있었으면."

GLOBAL.STRINGS.RECIPE_DESC.DOUBLE_UMBRELLAHAT = "기능이 모양을 무마합니다."

GLOBAL.STRINGS.NAMES.GRASSNOVA = "풀"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.GRASSNOVA = "그냥 풀이야."

GLOBAL.STRINGS.RECIPE_DESC.DOUBLE_UMBRELLAHAT = "덤브렐라"

GLOBAL.STRINGS.NAMES.SAIL = "나뭇잎 돛"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SAIL = "내 항해를 좀 더 쉽게 해줄거야."
GLOBAL.STRINGS.RECIPE_DESC.SAIL = "Catch the wind!"

GLOBAL.STRINGS.NAMES.CLOTHSAIL = "천 돛"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CLOTHSAIL = "바람 한 점 놓치지 않겠어!"
GLOBAL.STRINGS.RECIPE_DESC.CLOTHSAIL = "더 많은 바람을 잡아라!"

GLOBAL.STRINGS.NAMES.SNAKESKINSAIL = "뱀가죽 돛"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SNAKESKINSAIL = "비늘을 타고 스르륵!"
GLOBAL.STRINGS.RECIPE_DESC.SNAKESKINSAIL = "아주 튼튼한 돛입니다."

GLOBAL.STRINGS.NAMES.FEATHERSAIL = "깃털 돛"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FEATHERSAIL = "깃털처럼 가벼워!"
GLOBAL.STRINGS.RECIPE_DESC.FEATHERSAIL = "당신의 배에 날개를!"

GLOBAL.STRINGS.NAMES.IRONWIND = "강철 바람"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.IRONWIND = "과학자들이 항해하는 방식이랄까."
GLOBAL.STRINGS.RECIPE_DESC.IRONWIND = "빙글빙글!"

GLOBAL.STRINGS.NAMES.WOODLEGSSAIL = "해적 돛"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOODLEGSSAIL = "악명높은 해적의 돛이야."
GLOBAL.STRINGS.RECIPE_DESC.WOODLEGSSAIL = "난 해적왕이 될거야!"

GLOBAL.STRINGS.NAMES.BOAT_LANTERN = "배 랜턴"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOAT_LANTERN = "밤바다를 환히 밝혀주겠어!"
GLOBAL.STRINGS.RECIPE_DESC.BOAT_LANTERN = "실수하면 불빛이 흘러내릴 수도."

GLOBAL.STRINGS.NAMES.BOAT_TORCH = "배 횃불"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOAT_TORCH = "손이 편해지겠어."
GLOBAL.STRINGS.RECIPE_DESC.BOAT_TORCH = "바다 위를 환하게."

GLOBAL.STRINGS.NAMES.BOATCANNON = "배 대포"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOATCANNON = "배를 이길 수 있는 건 대포를 단 배이지."
GLOBAL.STRINGS.RECIPE_DESC.BOATCANNON = "배를 더 강력하게."

GLOBAL.STRINGS.NAMES.WOODLEGS_BOATCANNON = "해적 대포"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOODLEGS_BOATCANNON = "해적의 상징이지."
GLOBAL.STRINGS.RECIPE_DESC.WOODLEGS_BOATCANNON = "오래 쓸 수 있습니다."

GLOBAL.STRINGS.NAMES.QUACKERINGRAM = "꽥꽥 충각"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.QUACKERINGRAM = "돌격!"
GLOBAL.STRINGS.RECIPE_DESC.QUACKERINGRAM = "비키는 게 좋을걸!"

GLOBAL.STRINGS.NAMES.QUACKENDRILL = "쿠왁켄 드릴"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.QUACKENDRILL = "심해 굴착용 도구야."
GLOBAL.STRINGS.RECIPE_DESC.QUACKENDRILL = "심해에서도 꽥꽥"

GLOBAL.STRINGS.NAMES.QUACKENBEAK = "꾸왁켄 부리"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.QUACKENBEAK = "입을 다물지 못하겠다면 내가 다물게 해주지."

GLOBAL.STRINGS.NAMES.TRAWLNET = "그물망"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TRAWLNET = "확실히 가라앉는군."
GLOBAL.STRINGS.RECIPE_DESC.TRAWLNET = "기다리는 낚시꾼에게 복이 있나니."

STRINGS.NAMES.GLASS_SHARDS = "유리 조각"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GLASS_SHARDS = "높은 열이 모래를 불완전하게나마 유리로 만들었어."
STRINGS.RECIPE_DESC.GLASS_SHARDS = "당신의 심장의 조각입니다."

STRINGS.NAMES.SHARD_SWORD = "유리 조각 검"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHARD_SWORD = "펜보다 못하지."
STRINGS.RECIPE_DESC.SHARD_SWORD = "악몽의 존재를 말살하라."

STRINGS.NAMES.SHARD_BEAK = "유리 조각 부리"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHARD_BEAK = "철거 도구야."
STRINGS.RECIPE_DESC.SHARD_BEAK = "Shatters strongholded nests."

STRINGS.NAMES.PORTO_SURFBOARD = "서핑보드"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTO_SURFBOARD = "내가 서핑보드만 있었어도 널 따라잡았어."
STRINGS.RECIPE_DESC.PORTO_SURFBOARD = "야호!"

STRINGS.NAMES.SURFBOARD = "서핑보드"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SURFBOARD = "내가 서핑보드만 있었어도 널 따라잡았어."
STRINGS.RECIPE_DESC.SURFBOARD = "Hang ten!"

STRINGS.NAMES.WOODLEGSBOAT = "'바다 다리'"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOODLEGSBOAT = "부랑자에게나 어울릴 법하네."
STRINGS.RECIPE_DESC.WOODLEGSBOAT = "해적질을 해봅시다."

STRINGS.NAMES.PORTO_WOODLEGSBOAT = "'바다 다리'"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTO_WOODLEGSBOAT = "부랑자에게나 어울릴 법하네."
STRINGS.RECIPE_DESC.PORTO_WOODLEGSBOAT = "해적질을 해봅시다."

STRINGS.NAMES.WOODLEGSBOATAMIGO = "'바다 다리'"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOODLEGSBOATAMIGO = "부랑자에게나 어울릴 법하네."
STRINGS.RECIPE_DESC.WOODLEGSBOATAMIGO = "해적질을 해봅시다."

STRINGS.NAMES.TURBINE_BLADES = "터빈 날개"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURBINE_BLADES = "그 폭풍의 힘의 원천인 걸까?"

STRINGS.NAMES.TRAWLNETDROPPED = "그물망"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TRAWLNETDROPPED = "확실히 가라앉고 있어."

STRINGS.NAMES.SHARKITTEN = "상냥이"

STRINGS.NAMES.SAPLINGNOVA = "잔가지"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SAPLINGNOVA = "더 멋지게 생겼으면 좋을텐데."

STRINGS.NAMES.PORTAL_SHIPWRECKED = "항해용 배"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTAL_SHIPWRECKED = "고장났어."

STRINGS.NAMES.BUOY = "부표"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BUOY = "아우우우 예에에!."
STRINGS.RECIPE_DESC.BUOY = "바다 위에 표시를 하세요."

STRINGS.NAMES.ARMOR_LIFEJACKET = "구명조끼"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ARMOR_LIFEJACKET = "배가 없어도 뜰 수 있어!."
STRINGS.RECIPE_DESC.ARMOR_LIFEJACKET = "안전 제일!"

STRINGS.WALLY1 = "바보."
STRINGS.WALLY2 = "배 잘 모네."

STRINGS.NAMES.SURFBOARDITEM = "서핑보드"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.LUCKYHAT = "이거 쓰면 무겁... 아니 무서워 보이나!?"
STRINGS.NAMES.LUCKYHAT = "행운의 모자"
STRINGS.RECIPE_DESC.LUCKYHAT = "보물을 포착했다."

STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPICEPACK = "요리사의 수작이로군!"
STRINGS.NAMES.SPICEPACK = "요리사 가방"
STRINGS.RECIPE_DESC.SPICEPACK = "음식을 신선하게 보관하세요."

STRINGS.CHARACTERS.GENERIC.DESCRIBE.PIRATEHAT = "부랑자 아저씨한테 어울리겠어. 아님 나나."
STRINGS.NAMES.PIRATEHAT = "해적 모자"
STRINGS.RECIPE_DESC.PIRATEHAT = "네놈의 해적으로서의 삶이다!"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CAPTAINHAT = "배를 타는 것이 더 멋져지겠어!"
STRINGS.NAMES.CAPTAINHAT = "선장 모자"
STRINGS.RECIPE_DESC.CAPTAINHAT = "이걸 쓰면 배가 당신을 더 존중해줍니다."

STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTABLECOOKPOT = "어떤 요리를 만들어볼까, 친구?"
STRINGS.NAMES.PORTABLECOOKPOT = "휴대용 요리솥"
STRINGS.NAMES.PORTABLECOOKPOT_ITEM = "휴대용 요리솥"
STRINGS.RECIPE_DESC.PORTABLECOOKPOT_ITEM = "어떤 요리를 만들어볼까요?"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.THATCHPACK = "꽤나 편리하네"
STRINGS.NAMES.THATCHPACK = "나뭇잎 가방"
STRINGS.RECIPE_DESC.THATCHPACK = "가벼운 짐을 가지고 다니세요."

STRINGS.NAMES.PARROT = "앵무새"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PARROT = "이름이 붙은 건 먹지 않을거야."

STRINGS.NAMES.SEAGULLWATER = "갈매기"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEAGULLWATER = "훠이! 다른 데 알아봐!"

GLOBAL.STRINGS.NAMES.ICEMAKER = "아이스 메이커 3000"
GLOBAL.STRINGS.RECIPE_DESC.ICEMAKER = "얼음, 얼음, 얼음, 땡!"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.ICEMAKER = "이 기계 일 잘 하네!"

GLOBAL.STRINGS.RECIPE_DESC.PRIMEAPEBARREL = "더 많은 원숭이!"

GLOBAL.STRINGS.RECIPE_DESC.BALLPHINHOUSE = "즐거움이 가득해보이네요."

STRINGS.NAMES.DORSALFIN = "등지느러미"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DORSALFIN = "슬프군."

STRINGS.NAMES.CORALLARVE = "산호 유생"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CORALLARVE = "이거 살아있는거야?"

GLOBAL.STRINGS.NAMES.NUBBIN = "산호 싹"
GLOBAL.STRINGS.RECIPE_DESC.NUBBIN = "어디든지!"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.NUBBIN = "산호의 원초적인 모습이랄까!"

STRINGS.NAMES.SEAWEED_STALK = "해초 줄기"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEAWEED_STALK = "나만의 양식장을 만들 수 있겠어."

STRINGS.NAMES.COCONADE = "코코네이드"
GLOBAL.STRINGS.RECIPE_DESC.COCONADE = "푸쾅!!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.COCONADE = "우선 불을 붙여야 쓸 수 있겠어!"

STRINGS.NAMES.PIRATEPACK = "해적 가방"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PIRATEPACK = "내 보물을 여기 담을 수 있겠어."

GLOBAL.STRINGS.NAMES.TAR_EXTRACTOR = "타르 추출기"
GLOBAL.STRINGS.RECIPE_DESC.TAR_EXTRACTOR = "만수르 부럽지 않다"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TAR_EXTRACTOR = "나는 석유왕이다!"

STRINGS.NAMES.TAR_POOL = "타르 웅덩이"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TAR_POOL = "꽤나 깊은 모양이야."

STRINGS.NAMES.TAR = "타르"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TA = "순수한 탄화수소야!"

STRINGS.NAMES.TAR_TRAP = "타르 함정"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TAR_TRAP = "되게 끈적해."

GLOBAL.STRINGS.NAMES.FISH_FARM = "양식장"
GLOBAL.STRINGS.RECIPE_DESC.FISH_FARM = "생선을 길러서 먹자!"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH_FARM = "더 이상 아이오딘 결핍에 시달릴 일은 없어!"

STRINGS.NAMES.ROE = "생선알"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ROE = "캐비어인가?"

STRINGS.NAMES.ROE_COOKED = "조리된 생선알"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ROE_COOKED = "캐비어네."

STRINGS.NAMES.FISH3 = "보라색 볼락"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH3 = "흔한 열대어야."

STRINGS.NAMES.FISH3_COOKED = "구운 보라색 볼락"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH3_COOKED = "예상대로 맛있어."

STRINGS.NAMES.FISH4 = "광대고기"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH4 = "흔한 열대어야."

STRINGS.NAMES.FISH4_COOKED = "구운 광대고기"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH4_COOKED = "예상대로 맛있어."

STRINGS.NAMES.FISH5 = "네온 콰트로"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH5 = "흔한 열대어야."

STRINGS.NAMES.FISH5_COOKED = "구운 네온 콰트로"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH5_COOKED = "예상대로 맛있어."

STRINGS.NAMES.FISH5_COOKED = "Neon Quattro Cooked"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH5_COOKED = "Delicious, as you would expect"

GLOBAL.STRINGS.NAMES.BLOWDART_POISON = "Blowdart Poison"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BLOWDART_POISON = "Blowdart Poison."
GLOBAL.STRINGS.RECIPE_DESC.BLOWDART_POISON = "Blowdart Poison"

GLOBAL.STRINGS.NAMES.SEATRAP = "Sea Trap"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEATRAP = "Sea Trap."
GLOBAL.STRINGS.RECIPE_DESC.SEATRAP = "Sea Trap"

GLOBAL.STRINGS.NAMES.SEA_CHIMINEA = "Sea Chiminea"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEA_CHIMINEA = "Sea Chiminea."
GLOBAL.STRINGS.RECIPE_DESC.SEA_CHIMINEA = "Sea Chiminea"

GLOBAL.STRINGS.NAMES.TROPICALBOUILLABAISSE = "Tropical Bouillabaisse"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TROPICALBOUILLABAISSE = "Tropical Bouillabaisse."

GLOBAL.STRINGS.NAMES.CAVIAR = "Caviar"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CAVIAR = "Caviar."

GLOBAL.STRINGS.NAMES.OX_FLUTE = "Ox Flute"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OX_FLUTE = "Ox Flute."
GLOBAL.STRINGS.RECIPE_DESC.OX_FLUTE = "Ox Flute"

GLOBAL.STRINGS.NAMES.OXBABY = "Ox baby"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OXBABY = "Ox baby."

GLOBAL.STRINGS.NAMES.RESEARCHLAB5 = "researchlab5"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.RESEARCHLAB5 = "researchlab5."
GLOBAL.STRINGS.RECIPE_DESC.RESEARCHLAB5 = "researchlab5"

GLOBAL.STRINGS.NAMES.SEA_YARD = "Sea Yard"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEA_YARD = "Sea Yard."
GLOBAL.STRINGS.RECIPE_DESC.SEA_YARD = "Sea Yard"

GLOBAL.STRINGS.NAMES.TARLAMP = "Tar Lamp."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TARLAMP = "Tar Lamp."
GLOBAL.STRINGS.RECIPE_DESC.TARLAMP = "Tar Lamp"

GLOBAL.STRINGS.NAMES.TARSUIT = "Tar Suit"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TARSUIT = "Tar Suit."
GLOBAL.STRINGS.RECIPE_DESC.TARSUIT = "Tar Suit"

GLOBAL.STRINGS.NAMES.BLUBBERSUIT = "Blubber Suit"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BLUBBERSUIT = "Blubber Suit."
GLOBAL.STRINGS.RECIPE_DESC.BLUBBERSUIT = "Blubber Suit"

GLOBAL.STRINGS.NAMES.MUSSEL_BED = "Mussel Bed"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSSEL_BED = "Mussel Bed."
GLOBAL.STRINGS.RECIPE_DESC.MUSSEL_BED = "Mussel Bed"

GLOBAL.STRINGS.NAMES.WATERCHEST1 = "Water Chest"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WATERCHEST1 = "Water Chest."
GLOBAL.STRINGS.RECIPE_DESC.WATERCHEST1 = "Water Chest"

GLOBAL.STRINGS.RECIPE_DESC.SURFBOARDITEM = "Cowabunga dudes!"

GLOBAL.STRINGS.NAMES.HAIL_ICE = "Hail Ice"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.HAIL_ICE = "Hail Ice."
GLOBAL.STRINGS.RECIPE_DESC.ICE = "Ice"

GLOBAL.STRINGS.NAMES.TELESCOPE = "Telescope"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TELESCOPE = "Telescope."
GLOBAL.STRINGS.RECIPE_DESC.TELESCOPE = "Telescope"

GLOBAL.STRINGS.NAMES.SUPERTELESCOPE = "Supertelescope"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SUPERTELESCOPE = "Supertelescope."
GLOBAL.STRINGS.RECIPE_DESC.SUPERTELESCOPE = "Supertelescope"

GLOBAL.STRINGS.NAMES.TIGEREYE = "Tiger Eye"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TIGEREYE = "Tiger Eye."

GLOBAL.STRINGS.RECIPE_DESC.GOLDNUGGET = "Gold"

GLOBAL.STRINGS.NAMES.ESCADADOVULCAO2 = "Volcano Exit"
GLOBAL.STRINGS.NAMES.LAVAPONDBIG1 = "Big lava pool"

GLOBAL.STRINGS.NAMES.MERM1 = "Merm"
GLOBAL.STRINGS.NAMES.MERM2 = "Merm"
--------------store---------
--------------actions-------
GLOBAL.STRINGS.ACTIONS.HACK="베기"
GLOBAL.STRINGS.ACTIONS.BOATMOUNT="배에 탑승하기"
GLOBAL.STRINGS.ACTIONS.BOATREPAIR = "배 수리하기"
GLOBAL.STRINGS.ACTIONS.BOATDISMOUNT = "배에서 내리기"
GLOBAL.STRINGS.ACTIONS.STICK = "꽂기"
GLOBAL.STRINGS.NAMES.NAUTICALTAB = "항해"
GLOBAL.STRINGS.TABS.NAUTICALTAB = "항해"
GLOBAL.STRINGS.ACTIONS.LANTERNOFF = "끄기"
GLOBAL.STRINGS.ACTIONS.LANTERNON = "켜기"
GLOBAL.STRINGS.ACTIONS.BOATCANNON = "발사하기"
GLOBAL.STRINGS.ACTIONS.COLETAR = "걷어내기"
--------------rawling speak---------------
GLOBAL.STRINGS.NAMES.RAWLING = "롤링"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAWLING = "롤링이야."
GLOBAL.STRINGS.RAWLINGon_hit_water = "첨벙!"
GLOBAL.STRINGS.RAWLINGon_dropped = "나 좀 놀아줘!"
GLOBAL.STRINGS.RAWLINGon_extinguish = "살았다!"
GLOBAL.STRINGS.RAWLINGin_container = "여긴 바스켓이 아닌데..."
GLOBAL.STRINGS.RAWLINGon_ground = "나 좀 주워주라."
GLOBAL.STRINGS.RAWLINGin_inventory = "바스켓 바닥을 뚫어버리자고!"
GLOBAL.STRINGS.RAWLINGother_owner = "아야!"
GLOBAL.STRINGS.RAWLINGon_ignite = {
"나 불 붙었어!",
"아야 아야 아야 아야 아야!",
}
GLOBAL.STRINGS.RAWLINGon_pickedup = {
"제임스?",
"넌 나의 MVP!",
}
GLOBAL.STRINGS.RAWLINGon_thrown = {
"바스켓을 향해서!",
"슛!",
"잡지 않는 슛은 100% 놓치는 법이라구!",
"난 날 수 있다!",
}

GLOBAL.STRINGS.RAWLINGon_bounced = 
{
"아야!",
"공놀이가 아니면 죽음을!",
"핫차!",
"또용!",
}
GLOBAL.STRINGS.RAWLINGequipped = {
"날 들고 걸어도 좋아. 두 걸음까지만.",
"캐나다식 유머인가?",
"맘대로 던져도 좋아.",
}
STRINGS.BORE_TALK_FOLLOWWILSON = {"YOU OK BY ME", "I LOVE FRIEND", "YOU IS GOOD", "I FOLLOW!"}
STRINGS.BORE_TALK_FIND_LIGHT = {"SCARY", "NO LIKE DARK", "WHERE IS SUN?", "STAY NEAR FIRE", "FIRE IS GOOD"}
STRINGS.BORE_TALK_LOOKATWILSON = {"WHO ARE YOU?", "YOU NOT BORE.", "UGLY MONKEY MAN", "YOU HAS MEAT?"}
STRINGS.BORE_TALK_RUNAWAY_WILSON = {"TOO CLOSE!", "STAY 'WAY!", "YOU BACK OFF!", "THAT MY SPACE."}
STRINGS.BORE_TALK_FIGHT = {"I KILL NOW!", "YOU GO SMASH!", "RAAAWR!", "NOW YOU DUN IT!", "GO 'WAY!", "I MAKE YOU LEAVE!",}
STRINGS.BORE_TALK_RUN_FROM_SPIDER = {"SPIDER BAD!", "NO LIKE SPIDER!", "SCARY SPIDER!"}
STRINGS.BORE_TALK_HELP_CHOP_WOOD = {"KILL TREE!", "SMASH MEAN TREE!", "I PUNCH TREE!"}
STRINGS.BORE_TALK_HELP_HACK = {"I HELP GET BUSH!", "I PUNCH BUSH!", "WE PUNCHIN' PLANTS NOW?"}
STRINGS.BORE_TALK_ATTEMPT_TRADE = {"WHAT YOU GOT?", "BETTER BE GOOD.", "NO WASTE MY TIME."}
STRINGS.BORE_TALK_PANIC = {"NOOOOO!", "TOO DARK! TOO DARK!", "AAAAAAAAAH!!"}
STRINGS.BORE_TALK_PANICFIRE = {"HOT HOT HOT!", "OWWWWW!", "IT BURNS!"}
STRINGS.BORE_TALK_FIND_MEAT = {"ME HUNGRY!", "YUM!", "I EAT FOOD!", "TIME FOR FOOD!"}
STRINGS.BORE_TALK_EAT_MEAT = {"NOM NOM NOM", "YUM!"}
STRINGS.BORE_TALK_GO_HOME = {"HOME TIME!", "HOME! HOME!"}

STRINGS.NAMES.WALL_LIMESTONE_ITEM = "Limestone Wall"
STRINGS.NAMES.WALL_LIMESTONE = "Limestone Wall"
STRINGS.RECIPE_DESC.WALL_LIMESTONE_ITEM = "Strong wall segments."
STRINGS.RECIPE_DESC.LIMESTONE = "Stone, with a hint of lime."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WALL_LIMESTONE = "Sturdy."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WALL_LIMESTONE_ITEM = "These would do more good if I placed them."

STRINGS.NAMES.WALL_ENFORCEDLIMESTONE_ITEM = "Sea Wall"
STRINGS.NAMES.WALL_ENFORCEDLIMESTONE = "Sea Wall"
STRINGS.RECIPE_DESC.WALL_ENFORCEDLIMESTONE_ITEM = "Strong wall segments to build at sea."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WALL_ENFORCEDLIMESTONE = "I shelled out for the good stuff."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WALL_ENFORCEDLIMESTONE_ITEM = "I have to build it in the water."
------------------mapwrapper---------------
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_MAPWRAP_LOSECONTROL = "내 앞날에 안개가 낀 것 같아."

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_MAPWRAP_RETURN = "뭔가가 내 다리를 훑고 지나갔어..."

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_MAPWRAP_WARN = "괴물이라도 있을 것 같아."

-------------death causes--------------
STRINGS.NAMES.DROWNING="익사"
STRINGS.NAMES.POISON="독"
STRINGS.NAMES.BELL1 = "Old Bell"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BELL1 = "Old Bell."