local STRINGS = GLOBAL.STRINGS

-----------------------------Biome Jungle -----------------------------





-----------------------------Biome Tidal Mash---------------------------
 
GLOBAL.STRINGS.NAMES.TIGERSHARKPOOL = "Stagno dello squalo tigre"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TIGERSHARKPOOL = "C'è uno strano squalo nello stagno."
 
 
GLOBAL.STRINGS.NAMES.LAVAPONDBIG = "Grade pozzo di lava"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LAVAPONDBIG = "Un pò caldo per i miei gusti."
 
GLOBAL.STRINGS.NAMES.HARPOON = "Arpione"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.HARPOON = "Un arpione da lanciare."
 
 
 
-----------------------------Biome Volcano------------------------------
GLOBAL.STRINGS.NAMES.DRAGOON = "Dragoon"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DRAGOON = "Sei veloce, non è vero?"
 
GLOBAL.STRINGS.NAMES.DRAGOONHEART = "Cuore di dragoon."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DRAGOONHEART = "Dove il dragoon conserva i suoi sentimenti."
 
GLOBAL.STRINGS.NAMES.DRAGOONDEN = "Tana di dragoon"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DRAGOONDEN = "Anche i dragoon devono dormire."
 
GLOBAL.STRINGS.NAMES.DRAGOONSPIT = "Saliva di dragoon"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DRAGOONSPIT = "È davvero disgustoso!"
 
GLOBAL.STRINGS.NAMES.DRAGOONEGG = "Uovo di dragoon"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DRAGOONEGG = "L'ho sentito schiudersi?"
 
GLOBAL.STRINGS.NAMES.OBSIDIAN = "Ossidiana"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OBSIDIAN = "È una roccia di fuoco."
 
GLOBAL.STRINGS.NAMES.BOOK_METEOR1 = "Gioia della vulcanologia"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOOK_METEOR1 = "L'avertenza dice 'Spero che ti piacciano i dragoon'"
 
GLOBAL.STRINGS.NAMES.OBSIDIAN_WORKBENCH = "Tavolo da lavoro in ossidiana"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OBSIDIAN_WORKBENCH = "Mi sento ispirato."
 
GLOBAL.STRINGS.NAMES.OBSIDIANFIREPIT = "Focolare in ossidiana"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OBSIDIANFIREPIT = "Questo focolare è un conduttore per ancora più... fuoco."
 
 
GLOBAL.STRINGS.NAMES.ARMOROBSIDIAN = "Armatura in ossidiana"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.ARMOROBSIDIAN = "Sono un genio."
 
GLOBAL.STRINGS.NAMES.SPEAR_OBSIDIAN = "Lancia in ossidiana"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPEAR_OBSIDIAN = "Questo lascerà il segno."
 
--GLOBAL.STRINGS.NAMES.OBSIDIANMACHETE = "Machete d'ossidiana"
--GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OBSIDIANMACHETE = "È caldo al tatto"
 
GLOBAL.STRINGS.NAMES.AXEOBSIDIAN = "Ascia in ossidiana"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.AXEOBSIDIAN = "Una combinazione vincente!"
 
GLOBAL.STRINGS.NAMES.ROCK_OBSIDIAN = "Masso di ossidiana"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.ROCK_OBSIDIAN = "Deve esplodere! non vuole essere minato!"
 
GLOBAL.STRINGS.NAMES.OBSIDIANBOMB = "Coccobomba in ossidiana"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OBSIDIANBOMB = "Sembra più potente!"
 
GLOBAL.STRINGS.NAMES.ROCK_CHARCOAL = "Masso di carbone"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.ROCK_CHARCOAL = "Mi servirebbe una calza terrebilmente grande..."
 
GLOBAL.STRINGS.NAMES.MAGMAROCK = "Mucchio di roccie magmatiche"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MAGMAROCK_FULL = "Posso scavarlo."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MAGMAROCK = "Posso scavarlo."
 
GLOBAL.STRINGS.NAMES.MAGMAROCK_GOLD = "Mucchio di roccie magmatiche"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MAGMAROCK_GOLD_FULL = "Vedo un'oportunità d'oro."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MAGMAROCK_GOLD = "Vedo un'oportunità d'oro."
 
GLOBAL.STRINGS.NAMES.FLAMEGEYSER = "Frattura magmatica"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FLAMEGEYSER = "Forse è meglio starne lontano."
 
GLOBAL.STRINGS.NAMES.VOLCANO_SHRUB = "Albero bruciato"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.VOLCANO_SHRUB = "Sembra incenerito."
 
GLOBAL.STRINGS.NAMES.VOLCANO_EXIT = "Vulcano"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.VOLCANO_EXIT = "Sento una brezza fuori"
 
GLOBAL.STRINGS.NAMES.VULCANO_ENTRANCE = "Entrata del vulcano"
GLOBAL.STRINGS.NAMES.ESCADADOVULCAO = "Uscita del vulcano"
 
GLOBAL.STRINGS.NAMES.VOLCANO = "Vulcano"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.VOLCANO = "Sembra sicuro."

GLOBAL.STRINGS.NAMES.VOLCANOSTAFF = "Staffa del vulcano"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.VOLCANOSTAFF = "L'etichetta dice 'tenere fuori dalla portata dei bambini'."
 
STRINGS.NAMES.LAVAPOOL = "Pozza di lava"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LAVAPOOL = "Un pò caldo per i miei gusti."
 
STRINGS.NAMES.DUG_ELEPHANTCACTUS = "Catus elefante estirpato"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_ELEPHANTCACTUS = "Trapiantabile ma pungente."
STRINGS.NAMES.ELEPHANTCACTUS = "Catus elefante"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ELEPHANTCACTUS = "Oh, potrei cavare un occhio con questo!"
STRINGS.NAMES.ELEPHANTCACTUS_ACTIVE = "Catus elefante attivo"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ELEPHANTCACTUS_ACTIVE = "Gli agli di questo catus sono molto più insoliti."
STRINGS.NAMES.ELEPHANTCACTUS_STUMP = "Tronco del catus elefante"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ELEPHANTCACTUS_STUMP = "C'è vorrà di tempo prima che esca."
 
 
STRINGS.TABS.OBSIDIANTAB = "Vulcanico"
GLOBAL.STRINGS.RECIPE_DESC.DRAGOONDEN = "Entra nella tana dei dragoon."
GLOBAL.STRINGS.RECIPE_DESC.OBSIDIANBOMB = "KA-BOOM!"
GLOBAL.STRINGS.RECIPE_DESC.ARMOROBSIDIAN = "Caldo al tatto."
GLOBAL.STRINGS.RECIPE_DESC.SPEAR_OBSIDIAN = "Potrai mandare a fuoco i tuoi nemici!"
GLOBAL.STRINGS.RECIPE_DESC.OBSIDIANFIREPIT = "Il focolare dei focolari!"
GLOBAL.STRINGS.RECIPE_DESC.OBSIDIANMACHETE = "Taglia e Brucia!"
GLOBAL.STRINGS.RECIPE_DESC.AXEOBSIDIAN = "Come un'ascia regole ma calda."
--GLOBAL.STRINGS.RECIPE_DESC.COFFEE = "Energizante!"
GLOBAL.STRINGS.RECIPE_DESC.BOOK_METEOR1 = "Meteore dal cielo!"
GLOBAL.STRINGS.RECIPE_DESC.VOLCANOSTAFF = "Il cielo sta cadendo!"
 
 
 
--GLOBAL.STRINGS.UI.WORLDGEN.VOLCANOTITLE = "BOILING MAGMA"
--GLOBAL.STRINGS.NAMES.VOLCANO_ALTAR = "Volcano Altar of Snackrifice"
--GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.VOLCANO_ALTAR.GENERIC = "It appears to be closed."
--GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.VOLCANO_ALTAR.OPEN = "The altar is open and ready to accept offerings!"
--GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.VOLCANO_ALTAR_BROKEN = "Darn it!"
--GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.VOLCANO_ALTAR_TOWER = "How scary!"
--GLOBAL.STRINGS.CHARACTERS.GENERIC.ANNOUNCE_VOLCANO_ERUPT = "That can't be good."
 
GLOBAL.STRINGS.NAMES.COFFEEBUSH = "Pianta di caffè"
GLOBAL.STRINGS.NAMES.DUG_COFFEEBUSH = "Pianta di caffè"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_COFFEEBUSH = "Questa è una pianta che potrei imparare ad amare!"
 
 
GLOBAL.STRINGS.NAMES.COFFEEBEANS = "Cicchi di caffè"
GLOBAL.STRINGS.NAMES.COFFEEBEANS_COOKED = "Chicchi di caffè tostati"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.COFFEEBEANS = "Potrebbe andagli bene un pò di tostatura."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.COFFEEBEANS_COOKED = "Il calore li ha definitamente migliorati."
 
GLOBAL.STRINGS.NAMES.COFFEE = "caffè"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.COFFEEBOT = "È un generatore di caffè."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.COFFEE = "Ha un odere delizioso ed energizante!"
 
 
--GLOBAL.STRINGS.SIGA = "Me siga"
GLOBAL.STRINGS.NAMES.WOODLEGS1 = "Woodlegs"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOODLEGS1 = "Questo è Woodlegs"
 
GLOBAL.STRINGS.NAMES.WOODLEGSGHOST = "Fantasma di Woodlegs"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOODLEGSGHOST = "Lui era il mio amico"
 
GLOBAL.STRINGS.NAMES.WOODLEGS_KEY1 = "Chiave d'osso"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOODLEGS_KEY1 = "Qualcosa da qualche parte è chiuso."
 
GLOBAL.STRINGS.NAMES.WOODLEGS_KEY2 = "Chiave d'oro"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOODLEGS_KEY2 = "Questa chiave probabilmente aprirà qualcosa."
 
GLOBAL.STRINGS.NAMES.WOODLEGS_KEY3 = "Chiave di ferro"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOODLEGS_KEY3 = "È una chiave."
 
GLOBAL.STRINGS.NAMES.WOODLEGS_CAGE = "Gabbia di Woodlegs"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOODLEGS_CAGE = "Sembra un eccessivo numero di lucchetti."
 
 
GLOBAL.STRINGS.NAMES.SLIP = "Slip"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SLIP = "Un essere peloso, piccolo e mostruoso."
 
GLOBAL.STRINGS.NAMES.SLIPSTOR = "Slipstor"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SLIPSTOR = "Questo mostro peloso ha un'aria minacciosa."
 
GLOBAL.STRINGS.NAMES.SLIPSTOR_SPAWNER = "Generatore Di Slipstor"
 
 
 
GLOBAL.STRINGS.NAMES.TWISTER = "Sealnado"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TWISTER = "Pareva strano che fosse cosi esageratamente ventoso."
 
GLOBAL.STRINGS.NAMES.TWISTER_SEAL = "Foca"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TWISTER_SEAL = "D'awww."
 
GLOBAL.STRINGS.NAMES.TWISTER_TORNADO = "Tornado"
 
 
GLOBAL.STRINGS.NAMES.MERMFISHER = "Uomopesce pescatore"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MERMFISHER = "Non ti conviene fare mosse azzardate."
 
GLOBAL.STRINGS.NAMES.FLUP = "Flup"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FLUP = "Lasciami in pace!"
 
GLOBAL.STRINGS.NAMES.TIDALPOOL = "Stagno paludoso"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TIDALPOOL = "Stagno lasciato dalle onde."
 
GLOBAL.STRINGS.NAMES.MERMFISHHOUSE = "Casa dell'uomopesce pescatore"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MERMFISHHOUSE = "Non ha un buon odore."
 
GLOBAL.STRINGS.NAMES.POISONHOLE = "Buco velenoso"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.POISONHOLE = "Penso che starò lontano da quello."
 
GLOBAL.STRINGS.NAMES.TIGERSHARK = "Squalo tigre"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TIGERSHARK = "Beh, è terrificante."
 
GLOBAL.STRINGS.NAMES.TIGERSHARKSHADOW = "Ombra dell'squalo tigre"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TIGERSHARKSHADOW = "L'ombra di una bestia!"
 
GLOBAL.STRINGS.NAMES.SNAKESKINFLOOR = "Tappeto in serpente"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SNAKESKINFLOOR = "Lega davvero la stanza insieme."
 
GLOBAL.STRINGS.NAMES.TURF_MAGMAFIELD = "Terreno magmatico"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_MAGMAFIELD = "Terreno focoso."
 
GLOBAL.STRINGS.NAMES.TURF_JUNGLE = "Terreno di giungla"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_JUNGLE = "Un terreno molto nodoso."
 
GLOBAL.STRINGS.NAMES.TURF_ASH = "Terreno incenerito"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_ASH = "Un terreno incenerito."
 
GLOBAL.STRINGS.NAMES.TURF_VOLCANO = "Terreno vulcanico"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_VOLCANO = "Terreno vulcan-oso."
 
GLOBAL.STRINGS.NAMES.TURF_TIDALMARSH = "Terreno acquitrino"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_TIDALMARSH = "Terreno Fradicio."
 
GLOBAL.STRINGS.NAMES.TURF_LAVAROCK = "Terreno di roccia lavica"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_LAVAROCK = "Terreno fatto di roccie laviche."
 
GLOBAL.STRINGS.NAMES.TURF_MEADOW = "Terreno di prateria"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_MEADOW = "Un terreno erboso."
 
GLOBAL.STRINGS.NAMES.SNAKE = "Serpente"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SNAKE = "Mi chiedo se proverà a vendermi dell'olio..."
 
GLOBAL.STRINGS.NAMES.SNAKE_POISON = "Serpente velenoso"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SNAKE_POISON = "Persino peggio dei serpenti comuni!"
 
GLOBAL.STRINGS.NAMES.SNAKESKIN = "Pelle di serpente"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SNAKESKIN = "Sono incuriosito È ma allo stesso tempo allarmato."
 
GLOBAL.STRINGS.NAMES.SNAKE_HOLE = "Buca del serpente"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SNAKE_HOLE = "Da quel buco si può udire il sibilio dei serpenti."
 
GLOBAL.STRINGS.NAMES.SNAKEOIL = "Olio di serpente"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SNAKEOIL = "L'etichetta dice *Il meraviglioso olio di serpente di Jay*"
 
 
GLOBAL.STRINGS.NAMES.LIVINGJUNGLETREE = "Albero della giungla regolare"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LIVINGJUNGLETREE = "Propio come qualsiasi altro albero."
 
--jungle tree
GLOBAL.STRINGS.NAMES.JUNGLETREE = "Albero della giungla"
GLOBAL.STRINGS.NAMES.TREE_JUNGLE = "Albero della giungla"
 
GLOBAL.STRINGS.NAMES.JUNGLETREESEED = "Semi dell'albero della giungla"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.JUNGLETREESEED = "Sento il sibilio dei serpenti al suo interno."
 
GLOBAL.STRINGS.NAMES.JUNGLE_TREE_SAPLING = "Alberello della giungla"
 
--bamboo
GLOBAL.STRINGS.NAMES.BAMBOO = "Bambo"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BAMBOO = "Forse potrei usarle per stordire qualcuno?"
 
GLOBAL.STRINGS.NAMES.BAMBOOTREE = "Canne di bambo"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BAMBOOTREE = {
    GENERIC = "Sembra piutosto resistente.",
    BURNING = "Sta bruciando velocemente!",
    BURNT = "Mi sento come se avessi potuto impedirlo.",
    CHOPPED = "Prendi questo, natura!"
}
 
GLOBAL.STRINGS.NAMES.DUG_BAMBOOTREE = "Radice di bambo"
GLOBAL.STRINGS.RECIPE_DESC.DUG_BAMBOOTREE = "Cresi delle canne di bambo"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_BAMBOOTREE = "Ho bisogno di piantarlo da qualche parte."
 
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DEPLETED_BAMBOOTREE = "Ricrescerà dinuovo?"
 
 
 
GLOBAL.STRINGS.NAMES.DOYDOYBABY = "Cucciolo di doydoy"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOYDOYBABY = "Mi sento stranamente protettivo per questo stupido uccello."
 
GLOBAL.STRINGS.NAMES.DOYDOYTEEN = "Doydoy adolescente"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOYDOYTEEN = "Mi sento stranamente protettivo per questo stupido uccello."
 
GLOBAL.STRINGS.NAMES.DOYDOY = "Doydoy"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOYDOY = "Mi sento stranamente protettivo per questo stupido uccello."
 
GLOBAL.STRINGS.NAMES.DOYDOYEGG = "Uovo di doydoy"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOYDOYEGG = "Forse avrei dovuto lasciarlo schiudere."
 
GLOBAL.STRINGS.NAMES.DOYDOYEGG_COOKED = "Uovo di doydoy fritto"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOYDOYEGG_COOKED = "Una reazione chimica controllata ha reso quest'uovo più nutriente."
 
GLOBAL.STRINGS.NAMES.DOYDOYEGG_CRACKED = "Uovo di doydoy crepato"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOYDOYEGG_CRACKED = "Oh bene. Sta dando segni di vita!"
 
GLOBAL.STRINGS.NAMES.DOYDOYFEATHER = "Piume di doydoy"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOYDOYFEATHER = "Soffici e in via di estinzione!"
 
GLOBAL.STRINGS.NAMES.DOYDOYNEST = "Nido di doydoy"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOYDOYNEST = "È per le uova di DoyDoy. Scemotto."
 
GLOBAL.STRINGS.RECIPE_DESC.DOYDOYNEST = "Fate l'amore con il sapore."
GLOBAL.STRINGS.RECIPE_DESC.DOYDOYEGG = "Per covare il tuo stesso doydoy!"
 
--wildborehouse
GLOBAL.STRINGS.NAMES.WILDBOREHOUSE = "Casa dell'uomochinghiale"
GLOBAL.STRINGS.RECIPE_DESC.WILDBOREHOUSE = "Fuori Chinghiale!"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WILDBOREHOUSE = "Ma che casa Ching-iolante."
 
--wildbore head
GLOBAL.STRINGS.NAMES.WILDBOREHEAD = "Testa di uomochinghiale"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WILDBOREHEAD = "L'odore è sgradevole quanto il suo aspetto."
--wildbore
 
GLOBAL.STRINGS.NAMES.WILDBORE = "UomoChinghiale"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WILDBORE = "Non mi sta molto simpatico."
 
--wildbore guard
GLOBAL.STRINGS.NAMES.WILDBOREGUARD = "Uomochinghiale guardia"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WILDBOREGUARD = "che cosa sta proteggendo?"
 
 
 
 
 
 
GLOBAL.STRINGS.NAMES.BEAVERKING_SPAWNER = "Wilbbeaver Guard"
 
GLOBAL.STRINGS.NAMES.WILDBEAVERGUARD = "Wildbeaver Guard"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WILDBEAVERGUARD = "He looks serious"
 
GLOBAL.STRINGS.NAMES.BEAVER_HEAD = "Beaver head"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BEAVER_HEAD = "Someone should tell his family."
 
GLOBAL.STRINGS.NAMES.BEAVERTORCH = "Beaver Torch"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BEAVERTORCH = "Sure looks cozy."
 
GLOBAL.STRINGS.NAMES.BEAVERSKIN = "Beaver Skin"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BEAVERSKIN = "The hide of a beaver creature"
 
GLOBAL.STRINGS.WILDBEAVER_NAMES = {
    "Castor",
}
 
GLOBAL.STRINGS.NAMES.BEAVER_KING = "Rei Castor"
 
GLOBAL.STRINGS.WILDBEAVER_TALK_FIGHT = {
    "VOU TE MORDER!",
    "VA EMBORA!",
    "VOLTEI PARA LUTAR!",
}
GLOBAL.STRINGS.WILDBEAVER_TALK_FOLLOW = {
    "VOCÊ ME ENTENDE",
    "VAMOS CONSTRUIR UMA BARRAGEM",
    "NÓS PRECISAMOS DE MAIS MADEIRA",
}
GLOBAL.STRINGS.WILDBEAVER_TALK_GOHOME = {
    "VOU TERMINAR A BARRAGEM AMANHÃ",
    "HORA DE DORMIR",
    "VEJO VOCÊ MAIS TARDE",
}
 
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WILDBEAVER = "Qual o nome disso...?!"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WILDBEAVER_HOUSE = "Onde o Castor mora."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BEAVER_KING = "Este deve governar todos eles."
 
 
GLOBAL.STRINGS.CHARACTERS.WILLOW.DESCRIBE.WILDBEAVER = "Você pega madeira, eu queimo: parece bom?"
GLOBAL.STRINGS.CHARACTERS.WILLOW.DESCRIBE.WILDBEAVER_HOUSE = "Ttodo mundo tem um lugar melhor que o meu..."
GLOBAL.STRINGS.CHARACTERS.WILLOW.DESCRIBE.BEAVER_KING = "Um grande para governar todos eles, suponho."
 
GLOBAL.STRINGS.CHARACTERS.WENDY.DESCRIBE.WILDBEAVER = "Posso montar em suas costas? Por favor, por favor"
GLOBAL.STRINGS.CHARACTERS.WENDY.DESCRIBE.WILDBEAVER_HOUSE = "Quando a represa se rompe, a inundação consome tudo."
GLOBAL.STRINGS.CHARACTERS.WENDY.DESCRIBE.BEAVER_KING = "Rei das represas."
 
GLOBAL.STRINGS.CHARACTERS.WX78.DESCRIBE.WILDBEAVER = "ELE COME MADEIRA."
GLOBAL.STRINGS.CHARACTERS.WX78.DESCRIBE.WILDBEAVER_HOUSE = "A MORADA DE UM COMEDOR DE MADEIRA."
GLOBAL.STRINGS.CHARACTERS.WX78.DESCRIBE.BEAVER_KING = "O REI DOS COMEDORES DE MADEIRA."
 
GLOBAL.STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WILDBEAVER = "Um primo perdido dO Castor canadense?"
GLOBAL.STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WILDBEAVER_HOUSE = "Deve ser para eles o equivalente a uma represa."
GLOBAL.STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BEAVER_KING = "Um rei para governar todos eles e para coordená-los na construção de barragens..."
 
GLOBAL.STRINGS.CHARACTERS.WOODIE.DESCRIBE.WILDBEAVER = "Ho, bonito. Não somos parentes?"
GLOBAL.STRINGS.CHARACTERS.WOODIE.DESCRIBE.WILDBEAVER_HOUSE = "O único imóvel em que investiria."
GLOBAL.STRINGS.CHARACTERS.WOODIE.DESCRIBE.BEAVER_KING = "Indo bem, né?"
 
GLOBAL.STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.WILDBEAVER = "Grandes dentuços?"
GLOBAL.STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.WILDBEAVER_HOUSE = "Os dentuços vivem aqui."
GLOBAL.STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.BEAVER_KING = "O maior de todos os dentuços!"
 
GLOBAL.STRINGS.CHARACTERS.WEBBER.DESCRIBE.WILDBEAVER = "WOODIE é você?"
GLOBAL.STRINGS.CHARACTERS.WEBBER.DESCRIBE.WILDBEAVER_HOUSE = "É aqui que esses criaturas vivem."
GLOBAL.STRINGS.CHARACTERS.WEBBER.DESCRIBE.BEAVER_KING = "Todos saudam o rei madeira primeiro!"
 
GLOBAL.STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.WILDBEAVER = "Vamos fazer uma batalha?"
GLOBAL.STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.WILDBEAVER_HOUSE = "A morada daqueles Castores selvagens."
GLOBAL.STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.BEAVER_KING = "Como você pode suportar esta ociosidade?"
GLOBAL.STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WILDBEAVER = "Outro tipo de idiotas da aldeia."
GLOBAL.STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WILDBEAVER_HOUSE = "Então eles vivem aqui."
GLOBAL.STRINGS.CHARACTERS.WAXWELL.DESCRIBE.BEAVER_KING = "Você é o supervisor deles ou o quê?"
GLOBAL.STRINGS.RECIPE_DESC.WILDBEAVER_HOUSE = "Beaver out!"
GLOBAL.STRINGS.NAMES.DOUBLE_UMBRELLAHAT = "Doppiombrello"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOUBLE_UMBRELLAHAT = "Il secondo ombrello tiene asciutto il primo."
GLOBAL.STRINGS.RECIPE_DESC.DOUBLE_UMBRELLAHAT = "Il sua funziona è più importante del suo aspetto"
GLOBAL.STRINGS.NAMES.WILDBEAVER_HOUSE = "Beaver House"
STRINGS.NAMES.VENOMGLAND = "Ghiandola velenifera"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.VENOMGLAND = "Solo il veleno può curare il veleno."

STRINGS.NAMES.BERRYBUSH2_SNAKE = "Cespuglio di bacche"

STRINGS.NAMES.OCTOPUSKING = "Polpo bucaniere"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.OCTOPUSKING = "Sono un dilettante per questo tizio."

STRINGS.NAMES.SWEET_POTATO_PLANTED = "Patata dolce"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SWEET_POTATO_PLANTED = "È una carota dall'aspetto strano."

STRINGS.NAMES.SWEET_POTATO = "Patata dolce"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SWEET_POTATO = "Sembra gustosa!"

STRINGS.NAMES.SWEET_POTATO_COOKED = "Patata dolce cotta"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SWEET_POTATO_COOKED = "Sembra ancora più gustosa!"

STRINGS.NAMES.PARROT_PIRATE = "Pappagallo"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PARROT_PIRATE = "Non mangio esseri con nomi."

STRINGS.NAMES.PARROT = "Pappagallo"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PARROT = "Non mangio esseri con nomi."

STRINGS.NAMES.DUBLOON = "Dobloni"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUBLOON = "Delle vecchie monete luccicanti!"

STRINGS.NAMES.DOYDOYFAN = "Ventaglio tropicale"
STRINGS.RECIPE_DESC.DOYDOYFAN = "Lussuosamente tropicale."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOYDOYFAN = "In qualche modo la brezza esce dal retro due volte più velocemente. "

STRINGS.NAMES.FABRIC = "Stoffa"
STRINGS.RECIPE_DESC.FABRIC = "Il bambù è cosi versatile!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FABRIC = "Stoffa morbida fatta con radici dure!"

STRINGS.NAMES.SNAKESKINHAT = "Cappello di oelle di serpente"
STRINGS.RECIPE_DESC.SNAKESKINHAT = "Stai asciutto e stiloso." 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SNAKESKINHAT = "Dovrebbe coprire dalla pioggia i miei capelli."

STRINGS.NAMES.ARMOR_SNAKESKIN = "Giacca in pelle di serpente "
STRINGS.RECIPE_DESC.ARMOR_SNAKESKIN = "Stai asciutto e coriaceo."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ARMOR_SNAKESKIN = "Che Stile!"

STRINGS.NAMES.TURF_SNAKESKINFLOOR = "Tappeto in pelle di serpente"
STRINGS.RECIPE_DESC.TURF_SNAKESKINFLOOR = "Lega davvero la stanza insieme."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_SNAKESKINFLOOR = "È parecchio sssstiloso!"

--STRINGS.NAMES.TURF_WATER_MANGROVE = "红树林地皮"
--STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_WATER_MANGROVE = "红树林地皮"

STRINGS.NAMES.TURF_BEACH = "Terreno Di Spiaggia"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_BEACH = "Terreno piutosto sabbioso."

STRINGS.NAMES.COCONUT = "Noce di cocco"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.COCONUT = "Mi servirebbe un grande schiaccianoci."

STRINGS.NAMES.COCONUT_HALVED = "Noce di cocco dimezzata"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.COCONUT_HALVED = "Quando le sbatto assieme fanno il rumore degli zoccoli."

STRINGS.NAMES.COCONUT_COOKED = "Noce di cocco cotta"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.COCONUT_COOKED = "Manca solo la torta."

STRINGS.NAMES.PALMTREE = "Palma"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PALMTREE = "Molto Tropicale."

STRINGS.NAMES.PALMLEAF = "Fronda di palma"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PALMLEAF = "Mi piaciono queste fronde."

STRINGS.NAMES.ROCK_LIMPET = "Masso patelloso"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ROCK_LIMPET = "Potrei riempire un secchio con tutte queste patelle!"

STRINGS.NAMES.LIMPETS = "Patelle"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LIMPETS = "Forse morire di fame non sarebbe poi cosi male..."

STRINGS.NAMES.LIMPETS_COOKED = "Patelle cotte"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LIMPETS_COOKED = "Adesso hanno un aspetto migliore!"

STRINGS.NAMES.PALMLEAF_HUT = "Capanna di fronde di palma"
STRINGS.RECIPE_DESC.PALMLEAF_HUT = "Fuggi sopratutto dalla pioggia."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PALMLEAF_HUT = "Ombra, dolce ombra."

STRINGS.NAMES.SAND_CASTLE = "Castello di sabbia"
STRINGS.RECIPE_DESC.SAND_CASTLE = "Terapeutico e rilassante."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SAND_CASTLE = "Guarda cosa ho fatto!"

STRINGS.NAMES.SANDHILL = "Collinetta di sabbia"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SANDHILL = "Faresti meglio a stare fuori dalle mie scarpe."

STRINGS.NAMES.SAND = "Sabbia"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SAND = "Un comodo mucchio di sabbia tascabile."

STRINGS.NAMES.SEASHELL_BEACHED = "Conchiglia"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEASHELL_BEACHED = "Rifiuto marino."

STRINGS.NAMES.SEASHELL = "Conchiglia"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEASHELL = "Forse potrei venderle."

STRINGS.NAMES.CRATE = "Cassa"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CRATE = "Ci deve essere un modo per aprirla."

STRINGS.NAMES.CRAB = "Granchio"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CRAB = "Non azzardarti a pizzicarmi, mister granchio."

STRINGS.NAMES.CRABHOLE = "Buca del granchio"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CRABHOLE = "Chiamano un buco nella sabbia la loro casa."

STRINGS.NAMES.CRAB_HIDDEN = "Granchio nascosto"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CRAB_HIDDEN = "Mi chiedo dove sia andato il granchio."

STRINGS.NAMES.SEAGULL = "Gabbiano"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEAGULL = "Sciò! trova un altro posto!"

STRINGS.NAMES.SEAGULLWATER = "Gabbiano"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEAGULLWATER = "Sciò! trova un altro posto!"

STRINGS.NAMES.FISH_MEAT_SMALL = "Boccone di pesce"

STRINGS.NAMES.TROPICAL_FISH = "Pesce tropicale"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TROPICAL_FISH = "Che pesce dall'aspetto tropicale!"

STRINGS.NAMES.TUNACAN = "Tonno in scatola"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TUNACAN = "Da dove può venire questo?"

STRINGS.NAMES.TOUCAN = "Tucano"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TOUCAN = "Non posso tuca-fferarlo."

STRINGS.NAMES.RAFT = "Zattera"
STRINGS.RECIPE_DESC.RAFT = "Abbastanza affidabile per navigare."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAFT = "Questa zattera sembra adeguata."

STRINGS.NAMES.SLOTMACHINE = "Slot machine"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SLOTMACHINE = "Suppongo che potrei soffermarmi per un momento o due."

STRINGS.NAMES.VINE = "Rovi"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.VINE = "Forse potrei legare cose con questo."

STRINGS.NAMES.BUSH_VINE = "Cespuglio di rovi"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BUSH_VINE = "È tutto rovoso!"

STRINGS.NAMES.DUG_BUSH_VINE = "Cespuglio di rovi estirpato"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_BUSH_VINE = "Credo che mi convenga raccoglierlo."

STRINGS.NAMES.MACHETE = "Machete"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MACHETE = "Mi piace il taglio di questa lama."
STRINGS.RECIPE_DESC.MACHETE = "Taglia cose!"

STRINGS.NAMES.GOLDENMACHETE = "Machete di lusso"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GOLDENMACHETE = "Taglia con stile!"
STRINGS.RECIPE_DESC.GOLDENMACHETE = "Taglia cose con STILE!"

STRINGS.NAMES.OBSIDIANMACHETE = "Machete in ossidiana"
STRINGS.RECIPE_DESC.OBSIDIANMACHETE = "Taglia e brucia!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.OBSIDIANMACHETE = "È caldo al tatto."

GLOBAL.STRINGS.PULAFORA = "Non posso navigare nella terraferma."

STRINGS.NAMES.CORMORANT = "Cormorano"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CORMORANT = "Scommetto che mangia molto pesce."

STRINGS.NAMES.SEAWEED = "Alga"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEAWEED = "Un'erba, del mare."

STRINGS.NAMES.SEAWEED_COOKED = "Alga Cotta"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.COOKED = "Bollita alla perfezione."

STRINGS.NAMES.SEAWEED_DRIED = "Alga Secca"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEAWEED_DRIED = "Salato!"

STRINGS.NAMES.SEAWEED_PLANTED = "Alghe"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEAWEED_PLANTED = "Is that what passes for food around here?"

STRINGS.NAMES.CORAL = "Corallo"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CORAL = "Materiale da costruzione vivente!"

STRINGS.NAMES.CORALREEF = "Barriera corallina"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CORALREEF = "Il corallo ha formato uno scoglio!"

STRINGS.NAMES.FISHINHOLE = "Bassofondo"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISHINHOLE = "Questa zona sembra perfetta per l'ittica."
 
GLOBAL.STRINGS.NAMES.GRASS_WATER = "Erba"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.GRASS_WATER = "Spero che non abbia sete, erba."
 
GLOBAL.STRINGS.NAMES.TREE_MANGROVE = "Mangrovia"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TREE_MANGROVE = "Mi chiedo se prendono abbastanza acqua."
 
GLOBAL.STRINGS.NAMES.ANTIDOTE = "Antidoto"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.ANTIDOTE = "Il gusto è orribile."
GLOBAL.STRINGS.RECIPE_DESC.ANTIDOTE = "L'unico modo per curarti dal veleno"
 
GLOBAL.STRINGS.NAMES.QUAGMIRE_SALMON = "Salmone"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.QUAGMIRE_SALMON = "Hm... pesce fresco!"
 
GLOBAL.STRINGS.NAMES.QUAGMIRE_POND_SALT = "Stagno salato"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.QUAGMIRE_POND_SALT = "Adesso posso mettere il sale sul mio cibo."
 
GLOBAL.STRINGS.NAMES.QUAGMIRE_SWAMPIG = "Uomomaiale di palude"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.QUAGMIRE_SWAMPIG = "È un maiale molto peloso."
 
GLOBAL.STRINGS.NAMES.QUAGMIRE_SWAMPIG_HOUSE = "Casa del maiale della palude"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.QUAGMIRE_SWAMPIG_HOUSE = "Hanno visto giorni migliori."

GLOBAL.STRINGS.NAMES.QUAGMIRE_SWAMPIG_HOUSE_RUBBLE = "Casa del maiale della palude"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.QUAGMIRE_SWAMPIG_HOUSE_RUBBLE = "Hanno visto giorni migliori."

GLOBAL.STRINGS.NAMES.CROCODOG = "Coccodrillo"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CROCODOG = "Preferirei stare lontano da lui."
 
GLOBAL.STRINGS.NAMES.WATERCROCODOG = "Coccodrillo d'acqua"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WATERCROCODOG = "Ha veramente quell'odere da ."
 
GLOBAL.STRINGS.NAMES.POISONCROCODOG = "Coccodrillo velenoso"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.POISONCROCODOG = "Sembra un esperimento andato male!"
 
GLOBAL.STRINGS.NAMES.GRASSWATER = "Erba"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.GRASSWATER = "Spero che tu non abbia sete, erba."
 
GLOBAL.STRINGS.NAMES.ARMOR_SEASHELL = "Armatura in conchiglie"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.ARMOR_SEASHELL = "Mi sento appartenente al mare."
GLOBAL.STRINGS.RECIPE_DESC.ARMOR_SEASHELL = "Ti protegge dal veleno."
 
GLOBAL.STRINGS.NAMES.OXHAT = "Elmetto cornuto"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OXHAT = "Un elmetto farfallone."
GLOBAL.STRINGS.RECIPE_DESC.OXHAT = "Elmetto che protegge dal veleno."
 
GLOBAL.STRINGS.NAMES.CHIMINEA = "Ciminiera"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CHIMINEA = "Prendi Questo, Vento!"
GLOBAL.STRINGS.RECIPE_DESC.CHIMINEA = "Protegge il fuoco dai fattori meteorologici."
 
GLOBAL.STRINGS.NAMES.OX_HORN = "Corno di bue"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OX_HORN = "Ho preso il bue dal corno."
 
GLOBAL.STRINGS.NAMES.OX = "Bue"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OX = "È un mammifero a cui piace l'acqua."
 
GLOBAL.STRINGS.NAMES.ROWBOAT = "Barca a remi"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.ROWBOAT = "Alimentato da grasso di gomito."
GLOBAL.STRINGS.RECIPE_DESC.ROWBOAT = "Rema, rema, rema la tua barca!"
 
GLOBAL.STRINGS.NAMES.ENCRUSTEDBOAT = "Barca di calcare"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.ENCRUSTEDBOAT = "Piutosto resistente."
GLOBAL.STRINGS.RECIPE_DESC.ENCRUSTEDBOAT = "Un carro armato in alto mare!"
 
GLOBAL.STRINGS.NAMES.TURF_QUAGMIRE_PARKFIELD = "Terreno zuccheroso"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_QUAGMIRE_PARKFIELD = "Molto dolce."
 
GLOBAL.STRINGS.NAMES.COTTONTREE = "Albero zuccheroso"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.COTTONTREE = "Molto soffice."
 
GLOBAL.STRINGS.NAMES.COTTONTREE_SAPLING = "Alberello zuccheroso"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.COTTONTREE_SAPLING = "Mi fa venire le carie ai denti."
 
GLOBAL.STRINGS.NAMES.COTTONTREE_CONE = "Seme di albero zuccheroso"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.COTTONTREE_CONE = "Semi per produrre l'albero di cotone "
 
GLOBAL.STRINGS.NAMES.BALLPHINHOUSE = "Palazzo dei delfini"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BALLPHINHOUSE = "Deve essere molto divertente stare li dentro."
 
GLOBAL.STRINGS.NAMES.BALLPHIN = "Delfino tursiope"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BALLPHIN = "Un tipo tondo e gommoso."
 
GLOBAL.STRINGS.NAMES.JELLYFISH = "Medusa"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.JELLYFISH = "Odio questi esseri."
 
GLOBAL.STRINGS.NAMES.JELLYFISH_DEAD = "Medusa morta"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.JELLYFISH_DEAD = "Ha vissuto una buona vita, forse."
 
GLOBAL.STRINGS.NAMES.JELLYFISH_COOKED = "Medusa cotta"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.JELLYFISH_COOKED = "È tutto storto."
 
GLOBAL.STRINGS.NAMES.JELLYJERKY = "Medusa essicata"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.JELLYJERKY = "Sembra extra gommoso."
 
GLOBAL.STRINGS.NAMES.JELLYFISH_PLANTED = "Medusa"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.JELLYFISH_PLANTED = "Odio questi esseri."

GLOBAL.STRINGS.NAMES.LOGRAFT = "Zattera di tronchi"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LOGRAFT = "Non sembra molto sicura."
GLOBAL.STRINGS.RECIPE_DESC.LOGRAFT = "Naviga a tuo rischio e pericolo"

GLOBAL.STRINGS.NAMES.FROG_POISON = "Rana velenosa"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FROG_POISON = "È cosi carina tanto quanto velenoso"

GLOBAL.STRINGS.NAMES.SHARKITTENSPAWNER = "Tana dei scquali gatti"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHARKITTENSPAWNER = "È quel mucchio di sabbia che miagola?"

GLOBAL.STRINGS.NAMES.WHALE_BLUE = "Balena blu"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WHALE_BLUE = "Sembra triste e sola."

GLOBAL.STRINGS.NAMES.WHALE_WHITE = "Balena bianca"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WHALE_WHITE = "Ha un aria minacciosa"

GLOBAL.STRINGS.NAMES.WHALE_CARCASS_WHITE = "Carcassa della balena bianca"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WHALE_CARCASS_WHITE = "Mi sento come il capitano Achab."

GLOBAL.STRINGS.NAMES.WHALE_CARCASS_BLUE = "Carcassa della balena blu"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WHALE_CARCASS_BLUE = "Ho posto fine alla sua triste vita."

GLOBAL.STRINGS.NAMES.LOBSTER_DEAD_COOKED = "Aragosta cotta"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LOBSTER_DEAD_COOKED = "Non vedo l'ora di mangiarti."

GLOBAL.STRINGS.NAMES.LOBSTER_DEAD = "Aragosta morta"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LOBSTER_DEAD = "Dovresti cucinare bene."

GLOBAL.STRINGS.NAMES.FISH_RAW_SMALL_COOKED = "Boccone di pesce cotto"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH_RAW_SMALL_COOKED = "Un pò di pesce cotto."

GLOBAL.STRINGS.NAMES.FISH_RAW_SMALL = "Boccone di pesce"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH_RAW_SMALL = "Un piccolo pezzo di pesce."

GLOBAL.STRINGS.NAMES.FISH_MED_COOKED = "Bistecca di pesce"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH_MED_COOKED = "Grigliato alla perfezione."

GLOBAL.STRINGS.NAMES.FISH_MED = "Pesce crudo"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH_MED = "Un pezzo di carne di pesce."

GLOBAL.STRINGS.NAMES.SPOILED_FISH = "Pesce marcio"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPOILED_FISH = "Non sono terribilmente curioso dell'odore."

GLOBAL.STRINGS.NAMES.FISH_RAW = "Pesce crudo"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH_RAW = "Un pezzo di carne di pesce"

GLOBAL.STRINGS.NAMES.DEAD_SWORDFISH = "Pesce spada morto"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DEAD_SWORDFISH = "Meglio non correre con questo"

GLOBAL.STRINGS.NAMES.BLUBBER = "Grasso di balena"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BLUBBER = "Morbidoso e disgustoso"

GLOBAL.STRINGS.NAMES.KNIGHTBOAT_CANNONSHOT = "Cannoniere"

GLOBAL.STRINGS.NAMES.KNIGHTBOAT = "Cannoniere"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.KNIGHTBOAT = "Vattene dalle mie acque, maniaco!"

GLOBAL.STRINGS.NAMES.OCTOPUSCHEST = "Cassa del polpo bucaniere"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OCTOPUSCHEST = "Spero che quella cosa sia impermeabile."

GLOBAL.STRINGS.NAMES.KRAKEN = "Quacken"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.KRAKEN = "Alla fine le leggende erano vere, esiste veramente!"

GLOBAL.STRINGS.NAMES.KRAKENCHEST = "Forziere del Quacken"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.KRAKENCHEST = "Al vincitore, il bottino!"

GLOBAL.STRINGS.NAMES.KRAKEN_TENTACLE = "Tentacoli Del Quacken"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.KRAKEN_TENTACLE = "Non mi affonderai cosi facilmente!"

GLOBAL.STRINGS.NAMES.SOLOFISH = "Pesce cane"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SOLOFISH = "Ridammi le mie pantofole!"

GLOBAL.STRINGS.NAMES.SWORDFISH = "Pesce spada"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SWORDFISH = "In guardia!"

GLOBAL.STRINGS.NAMES.LOBSTER_LAND= "Aragosta"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LOBSTER_LAND= "Disicuro avrai un gusto delizioso."

GLOBAL.STRINGS.NAMES.SHARX = "Mastino marino"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHARX = "Questi esseri sono sicuramente persistenti."

GLOBAL.STRINGS.NAMES.STUNGRAY = "Manta odorante"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.STUNGRAY = "Penso che terrò le distanze."

GLOBAL.STRINGS.NAMES.LUGGAGECHEST = "Valigia"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LUGGAGECHEST = "Chissà da dove sia saltata fuori."

GLOBAL.STRINGS.NAMES.REDBARREL = "Barile di polvere da sparo"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.REDBARREL = "Sembra pericoloso."

GLOBAL.STRINGS.NAMES.LOBSTERHOLE = "Tana dell'aragosta"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LOBSTERHOLE = "Dove l'aragosta va a nascondersi."

GLOBAL.STRINGS.NAMES.DEBRIS_1 = "Detriti"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DEBRIS_1 = "Parti di una nave distrutta."

GLOBAL.STRINGS.NAMES.DEBRIS_2 = "Detriti"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DEBRIS_2 = "Parti di una nave distrutta."

GLOBAL.STRINGS.NAMES.DEBRIS_3 = "Detriti"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DEBRIS_3 = "Parti di una nave distrutta."

GLOBAL.STRINGS.NAMES.DEBRIS_4 = "Detriti"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DEBRIS_4 = "Parti di una nave distrutta."

GLOBAL.STRINGS.NAMES.BOATREPAIRKIT = "Kit Di Riparazione"
GLOBAL.STRINGS.RECIPE_DESC.BOATREPAIRKIT = "Stai a galla in un quella barca!"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOATREPAIRKIT = "Tornerà utile quando avro bisogno di tappare qualche perdita."

--GLOBAL.STRINGS.NAMES.WRECK = "Relitto"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WRECK = "Povera barca."

GLOBAL.STRINGS.NAMES.PIRATEGHOST = "Pirata fantasma"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PIRATEGHOST = "É in cerca di vendetta!"

GLOBAL.STRINGS.NAMES.WRECKOF = "Relitto della"
GLOBAL.STRINGS.NAMES.SHIPNAMES =
{"Nautilus",
"Mackay-Bennett",
"Mary Celeste",
"Beagle",
"Santa Maria",
"Bluenoseblue",
"Mauretania",
"Endeavour",
"Edmund Fitzgerald",
"Pequod",
"Mississinewa",
"Regina Africana",
"Mont-Blanc",
"Caine",
 "Pharaoh",
 "Minnow",
 "Syracusia",
 "Barone di Renfrew",
 "Ariel",
 "Hispaniola",}

GLOBAL.STRINGS.NAMES.MUSSEL_STICK = "Bastone per cozze"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSSEL_STICK = "Lo infilzerò su quei molluschi."

GLOBAL.STRINGS.NAMES.MUSSEL_FARM = "Letto di cozze"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSSEL_FARM = "Mi chiedo se vengano da Bruxelles."

GLOBAL.STRINGS.NAMES.MUSSEL_FARM = "Letto di cozze"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSSEL_FARM = "Mi chiedo se vengano da Bruxelles."

GLOBAL.STRINGS.NAMES.MUSSEL_COOKED = "Cozza cotta"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSSEL_COOKED = "Non mangiare il guscio."

GLOBAL.STRINGS.NAMES.MUSSEL = "Cozze"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSSEL = "Mi ci vorrà un pò di forza."

GLOBAL.STRINGS.NAMES.MOSQUITO_POISON = "Zanzara velenosa"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOSQUITO_POISON = "Porta con se una terribile malattia."

GLOBAL.STRINGS.NAMES.WATERYGRAVE= "Tomba acquosa"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WATERYGRAVE = "Certo, potrei tirarlo fuori di li. Ma dovrei?"

GLOBAL.STRINGS.NAMES.BIOLUMINESCENCE= "Bioluminescenza"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BIOLUMINESCENCE = "Questi esseri fanno un bagliore lenitivo."

GLOBAL.STRINGS.NAMES.BOTTLELANTERN= "Lanterna bottiglia"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOTTLELANTERN = "La luce incandescente dell'oceano in una bottiglia"
GLOBAL.STRINGS.RECIPE_DESC.BOTTLELANTERN = "Una bottiglia piena di luce solare"

GLOBAL.STRINGS.NAMES.MESSAGEBOTTLEEMPTY1= "Bottiglia vuota"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MESSAGEBOTTLEEMPTY1 = "Non dimenticarti di riciclare!"
GLOBAL.STRINGS.RECIPE_DESC.MESSAGEBOTTLEEMPTY1 = "É solo una bottiglia vuota"

GLOBAL.STRINGS.NAMES.ARMOUREDBOAT = "Barca corazzata"
GLOBAL.STRINGS.RECIPE_DESC.ARMOUREDBOAT = "Un battello ricco di investimenti e gusci."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.ARMOUREDBOAT = "Quella si che è una barca resistente."
 
GLOBAL.STRINGS.NAMES.CARGOBOAT = "Nave da carico"
GLOBAL.STRINGS.RECIPE_DESC.CARGOBOAT = "Un accampamento in mezzo al mare!"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CARGOBOAT = "Ha spazio per tutte le mie cose!"

GLOBAL.STRINGS.NAMES.CORAL_BRAIN = "Materia grigia"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CORAL_BRAIN = "Un cibo per la mente."

GLOBAL.STRINGS.NAMES.CORAL_BRAIN_ROCK = "Germoglio Pensante"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CORAL_BRAIN_ROCK = "Mi chiedo cosa stia tramando..."

GLOBAL.STRINGS.NAMES.SANDBAG = "Sacchi di sabbia"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SANDBAG = "Tieni l'acqua sulla riva"

GLOBAL.STRINGS.NAMES.SANDBAG_ITEM = "Sacchi di sabbia"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SANDBAG_ITEM = "Tieni l'acqua sulla riva"
GLOBAL.STRINGS.RECIPE_DESC.SANDBAG_ITEM = "Anti-allagamento."

GLOBAL.STRINGS.NAMES.LIMESTONE = "Arenaria"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LIMESTONE = "Potrebbe essere un utile materiale da costruzione."
GLOBAL.STRINGS.RECIPE_DESC.LIMESTONE = "Roccia con un tocco di corallo."

GLOBAL.STRINGS.NAMES.CUTLASS = "Sciabola suprema"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUTLASS = "Spero che questa spada non inizi a puzzare..."
GLOBAL.STRINGS.RECIPE_DESC.CUTLASS = "Molti marlin sono stati maltrattati nello svolgimento di questo."

GLOBAL.STRINGS.NAMES.AERODYNAMICHAT = "Cappello aereodinamico"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.AERODYNAMICHAT = "Taglia davvero l'aria!"
GLOBAL.STRINGS.RECIPE_DESC.AERODYNAMICHAT = "Design aereodinamico per viaggi efficenti!"

GLOBAL.STRINGS.NAMES.SHARK_FIN = "Pinna del mastino marino"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHARK_FIN = "Ci ha lasciato la pinna."

GLOBAL.STRINGS.NAMES.RAINBOWJELLYFISH = "Medusa arcobaleno"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAINBOWJELLYFISH = "Non vedo alcun motivo per disturbarlo."

GLOBAL.STRINGS.NAMES.RAINBOWJELLYFISH_DEAD = "Medusa arcobaleno morta"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAINBOWJELLYFISH_DEAD = "Una scarica elettrica non lo farà rivevere. Ci ho provato."

GLOBAL.STRINGS.NAMES.RAINBOWJELLYFISH_COOKED = "Medusa arcobaleno cotta"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAINBOWJELLYFISH_COOKED = "Uno spuntino colorato."

GLOBAL.STRINGS.NAMES.RAINBOWJELLYJERKY = "Medusa arcobaleno essicata"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAINBOWJELLYJERKY = "Sembra colorato e gommoso."

GLOBAL.STRINGS.NAMES.RAINBOWJELLYFISH_PLANTED = "Medusa arcobaleno"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAINBOWJELLYFISH_PLANTED = "Non vedo alcun motivo per disturbarlo."

GLOBAL.STRINGS.NAMES.BANANAPOP = "Ghiacciolo alla banana"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BANANAPOP = "No, non congelarmi il cervello! Ne ho bisogno."

GLOBAL.STRINGS.NAMES.CEVICHE = "Cebiche"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CEVICHE = "Posso avere una ciotola più grande? Questa è fin troppo minuscola."

GLOBAL.STRINGS.NAMES.SWEETPOTATOSOUFFLE = "Soufflè di patate dolci"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SWEETPOTATOSOUFFLE = "I soufflè di patate dolci sono una moda sempre più in crescita."

GLOBAL.STRINGS.NAMES.SEAFOODGUMBO = "Zuppa di pesce"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEAFOODGUMBO = "È una zuppa di pesce formato Jumbo."

GLOBAL.STRINGS.NAMES.SURFNTURF = "Surf e Turf"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SURFNTURF = "È perfetto!"

GLOBAL.STRINGS.NAMES.SHARKFINSOUP = "Zuppa di Pinna di mastino marino"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHARKFINSOUP = "D'ora in poi nuoterà nel mio stomaco."

GLOBAL.STRINGS.NAMES.MUSSELBOUILLABAISE = "Cozze In umido"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSSELBOUILLABAISE = "Mmmh. Hanno un buon odore!"

GLOBAL.STRINGS.NAMES.MONSTERTARTARE = "Tartar di mostro"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MONSTERTARTARE = "Dev'esserci qualcos'altro da mangiato qui intorno."

GLOBAL.STRINGS.NAMES.LOBSTERDINNER = "Cena a base di aragosta"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LOBSTERDINNER = "Se lo mangio la mattina è ancora la cena?"

GLOBAL.STRINGS.NAMES.LOBSTERBISQUE = "Zuppa di aragosta"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LOBSTERBISQUE = "Ha un aspetto invitante!"

GLOBAL.STRINGS.NAMES.FRESHFRUITCREPES = "Crepes di frutta fresca"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FRESHFRUITCREPES = "Frutta zuccherosa! Parte di una colazione equilibrata."

GLOBAL.STRINGS.NAMES.BISQUE = "Zuppa"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BISQUE = "Non è poi cosi male."

GLOBAL.STRINGS.NAMES.CALIFORNIAROLL = "Rotoli di California"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CALIFORNIAROLL = "Ma io non ho le bacchette."


GLOBAL.STRINGS.NAMES.JELLYOPOP = "Ghiacciolo alla medusa"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.JELLYOPOP = "Sembra dolce, ma sa di carne!"

GLOBAL.STRINGS.NAMES.PORTO_RAFT = "Zattera"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTO_RAFT = "Questa zattera sembra adeguata."
STRINGS.RECIPE_DESC.PORTO_RAFT = "Abbastanza affidabile per navigare."

GLOBAL.STRINGS.NAMES.PORTO_ARMOUREDBOAT = "Barca corazzata"
GLOBAL.STRINGS.RECIPE_DESC.PORTO_ARMOUREDBOAT = "Un batello ricco di investimenti e gusci."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTO_ARMOUREDBOAT = "Quella si che è una barca resistente."

GLOBAL.STRINGS.NAMES.PORTO_CARGOBOAT = "Nave da carico"
GLOBAL.STRINGS.RECIPE_DESC.PORTO_CARGOBOAT = "Un accampamento in mezzo al mare!"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTO_CARGOBOAT = "Ha spazio per tutte le mie cose!"

GLOBAL.STRINGS.NAMES.PORTO_LOGRAFT = "Zattera di tronchi"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTO_LOGRAFT = "Non sembra molto sicura."
GLOBAL.STRINGS.RECIPE_DESC.PORTO_LOGRAFT = "Naviga a tuo rischio e pericolo."

GLOBAL.STRINGS.NAMES.PORTO_ROWBOAT = "Barca a remi"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTO_ROWBOAT = "Alimentato con olio di gomito."
GLOBAL.STRINGS.RECIPE_DESC.PORTO_ROWBOAT = "Rema, rema, rema la tua barca!"

GLOBAL.STRINGS.NAMES.PORTO_ENCRUSTEDBOAT = "Barca di calcare"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTO_ENCRUSTEDBOAT = "Piutosto resistente."
GLOBAL.STRINGS.RECIPE_DESC.PORTO_ENCRUSTEDBOAT = "Un carro armato in alto mare!"

GLOBAL.STRINGS.NAMES.PRIMEAPE = "Scimpanzé"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PRIMEAPE = "Questi esseri saranno la mia fine."

GLOBAL.STRINGS.NAMES.PRIMEAPEBARREL = "Tana dei scimpanzè"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PRIMEAPEBARREL = "Che porcile."

GLOBAL.STRINGS.NAMES.MONKEYBALL = "Palla a forma di scimpanzè"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MONKEYBALL = "Sembra un vero peccato sprecare una buona banana per questo. Però è piutosto carina."
GLOBAL.STRINGS.RECIPE_DESC.MONKEYBALL = "Mettiti al lavoro con le scimmie."

GLOBAL.STRINGS.NAMES.NEEDLESPEAR = "Spina di catus"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.NEEDLESPEAR = "Sono contento di non averlo calpestato."
GLOBAL.STRINGS.RECIPE_DESC.NEEDLESPEAR = "Spinoso!"

GLOBAL.STRINGS.NAMES.PEG_LEG = "Gamba di legno"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PEG_LEG = "Sarà un buon sostituto se perderò la mia gamba."
GLOBAL.STRINGS.RECIPE_DESC.PEG_LEG = "Prendili a calci nel culo!"

GLOBAL.STRINGS.NAMES.SPEAR_POISON = "Lancia velenosa"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPEAR_POISON = "Adesso è molto più nocivo."
GLOBAL.STRINGS.RECIPE_DESC.SPEAR_POISON = "Trasmettigli la malattia con questo."

GLOBAL.STRINGS.NAMES.MESSAGEBOTTLE1 = "Messaggio in bottiglia"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MESSAGEBOTTLE1 = "Qualcuno mi ha scritto una nota!"

GLOBAL.STRINGS.NAMES.BURIEDTREASURE = "Tesoro Sepolto"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BURIEDTREASURE = "Per favore, sii un buon tesoro!"

GLOBAL.STRINGS.NAMES.SHARK_GILLS = "Branchie di squalo"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHARK_GILLS = "Vorrei avere anche io le branchie."

GLOBAL.STRINGS.NAMES.GRASSNOVA = "Erba"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.GRASSNOVA = "È un ciuffo d'erba."

GLOBAL.STRINGS.NAMES.SAIL = "Vela di fronde di palma"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SAIL = "Questo dovrebbe davvero trasformare la mia esperienza navigativa."
GLOBAL.STRINGS.RECIPE_DESC.SAIL = "Prendi il vento!"

GLOBAL.STRINGS.NAMES.CLOTHSAIL = "Vela di stoffa"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CLOTHSAIL = "Cloth Sail."
GLOBAL.STRINGS.RECIPE_DESC.CLOTHSAIL = "Prendi ancora più vento!"

GLOBAL.STRINGS.NAMES.SNAKESKINSAIL = "Vela di pelle di serpente"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SNAKESKINSAIL = "Scaglia e naviga!"
GLOBAL.STRINGS.RECIPE_DESC.SNAKESKINSAIL = "Collettore di vento resistente."

GLOBAL.STRINGS.NAMES.FEATHERSAIL = "Vela di piume"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FEATHERSAIL = "È leggera come una piuma."
GLOBAL.STRINGS.RECIPE_DESC.FEATHERSAIL = "Come un'ala di uccello per la tua barca!"

GLOBAL.STRINGS.NAMES.IRONWIND = "Turbina"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.IRONWIND = "Veloce e ingegnoso."
GLOBAL.STRINGS.RECIPE_DESC.IRONWIND = ""

GLOBAL.STRINGS.NAMES.WOODLEGSSAIL = "Vela piratesca"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOODLEGSSAIL = "Ahoy!"
GLOBAL.STRINGS.RECIPE_DESC.WOODLEGSSAIL = "Per una nave da furfante."

GLOBAL.STRINGS.NAMES.BOAT_LANTERN = "Lanterna per barche"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOAT_LANTERN = "Dona un bagliore inquietante a tutto ciò che lo circonda."
GLOBAL.STRINGS.RECIPE_DESC.BOAT_LANTERN = "Fai un pò di luce sulla situazione."

GLOBAL.STRINGS.NAMES.BOAT_TORCH = "Torcia per barche"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOAT_TORCH = "Questo manterrà le mie mani libere."
GLOBAL.STRINGS.RECIPE_DESC.BOAT_TORCH = "Fai luce sul mare."

GLOBAL.STRINGS.NAMES.BOATCANNON = "Cannone"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOATCANNON = "L'unica cosa migliore di una barca è una barca con un cannone."
GLOBAL.STRINGS.RECIPE_DESC.BOATCANNON = "Proteggerà la tua barca."

GLOBAL.STRINGS.NAMES.WOODLEGS_BOATCANNON = "Cannone da pirata"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOODLEGS_BOATCANNON = "Ecco il motivo per cui i furfanti non vanno molto lontano."
GLOBAL.STRINGS.RECIPE_DESC.WOODLEGS_BOATCANNON = "Fuoco alle polveri!"

GLOBAL.STRINGS.NAMES.QUACKERINGRAM = "Ariete del Quacken"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.QUACKERINGRAM = "Scusatemi tutti, fuori dai piedi, perfavore."
GLOBAL.STRINGS.RECIPE_DESC.QUACKERINGRAM = "Tutti fuori dai piedi!"

GLOBAL.STRINGS.NAMES.QUACKENDRILL = "Trapano del Quacken"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.QUACKENDRILL = "È molto pesante!"
GLOBAL.STRINGS.RECIPE_DESC.QUACKENDRILL = "Per un quacking in mare aperto."

GLOBAL.STRINGS.NAMES.QUACKENBEAK = "Becco del Quacken"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.QUACKENBEAK = "Sono riuscito a farlo tacere."

GLOBAL.STRINGS.NAMES.TRAWLNET = "Rete da pesca"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TRAWLNET = "Li acchiappero tutti!"
GLOBAL.STRINGS.RECIPE_DESC.TRAWLNET = "Il pescatore paziente è sempre premiato."

STRINGS.NAMES.GLASS_SHARDS = "Frammenti di vetro"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GLASS_SHARDS = "Dei semplici cocci di vetro."
STRINGS.RECIPE_DESC.GLASS_SHARDS = "Fai attenzione a tagliarti con queste."

STRINGS.NAMES.SHARD_SWORD = "Spada di cocci di vetro"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHARD_SWORD = "Non sarà cosi resistente ma sa il fatto suo."
STRINGS.RECIPE_DESC.SHARD_SWORD = "Non farti male mentre la usi."

STRINGS.NAMES.SHARD_BEAK = "Falce di vetro"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHARD_BEAK = "Mi sento un pò cupo a tenerlo in mano."
STRINGS.RECIPE_DESC.SHARD_BEAK = "Un taglia teste portatile ma fragile."

STRINGS.NAMES.PORTO_SURFBOARD = "Tavola da surf"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTO_SURFBOARD = "Spero di non cadere in acqua con questo."
STRINGS.RECIPE_DESC.PORTO_SURFBOARD = "Cowabunga!"

STRINGS.NAMES.SURFBOARD = "Tavola da surf"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SURFBOARD = "Spero di non cadere in acqua con questo."
STRINGS.RECIPE_DESC.SURFBOARD = "Cowabunga!"

STRINGS.NAMES.PORTO_WOODLEGSBOAT = "Barca da pirata"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTO_WOODLEGSBOAT = "Disicuro farò imppalidire i navigli con questa barca."
STRINGS.RECIPE_DESC.PORTO_WOODLEGSBOAT = "Vai in giro a fare cose da pirata."

STRINGS.NAMES.WOODLEGSBOAT = "Barca da pirata"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOODLEGSBOAT = "Una barca adatta ad un furfante."
STRINGS.RECIPE_DESC.WOODLEGSBOAT = "Vai in giro a fare cose da pirata."

STRINGS.NAMES.TURBINE_BLADES = "Pale della turbina"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURBINE_BLADES = "Mi fa girare la testa"

STRINGS.NAMES.SAPLING1 = "Alberello"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SAPLING1 = "Sarebbe meglio se fosse un pochino più al fresco."
STRINGS.NAMES.TRAWLNETDROPPED = "Rete da pesca"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TRAWLNETDROPPED = "Fa acqua da tutti i pori."

STRINGS.NAMES.SHARKITTEN = "Squalo gatto"

STRINGS.NAMES.SAPLINGNOVA = "Sapling"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SAPLINGNOVA = "It might be okay if it was cooler."

STRINGS.NAMES.PORTAL_SHIPWRECKED = "Dondolante"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTAL_SHIPWRECKED = "È rotto."

STRINGS.NAMES.BUOY = "Buoy"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BUOY = "Awww yaaaaa Buoy!."
STRINGS.RECIPE_DESC.BUOY = "Mark your place in the water."

STRINGS.NAMES.ARMOR_LIFEJACKET = "Giubbotto salvavita"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ARMOR_LIFEJACKET = "Mi tiene a galla senza la mia barca!"
STRINGS.RECIPE_DESC.ARMOR_LIFEJACKET = "La sicurezza prima di tutto!"

STRINGS.WALLY1 = "Chump."
STRINGS.WALLY2 = "Nice Sailing"

STRINGS.NAMES.SURFBOARDITEM = "Surfboard"

STRINGS.LUCKYHAT = "Lucky Hat"
STRINGS.NAMES.LUCKYHAT = "Lucky Hat"
STRINGS.RECIPE_DESC.LUCKYHAT = "Bring out treasures."

STRINGS.SPICEPACK = "Chef Pack"
STRINGS.NAMES.SPICEPACK = "Chef Pack"
STRINGS.RECIPE_DESC.SPICEPACK = "Chef Pack."

STRINGS.PORTABLECOOKPOT = "Portable Crock Pot"
STRINGS.NAMES.PORTABLECOOKPOT = "Portable Crock Pot"
STRINGS.NAMES.PORTABLECOOKPOT_ITEM = "Portable Crock Pot"
STRINGS.RECIPE_DESC.PORTABLECOOKPOT_ITEM = "Portable Crock Pot"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.THATCHPACK = "I call it a thatchel"
STRINGS.NAMES.THATCHPACK = "Thatch Pack"
STRINGS.RECIPE_DESC.THATCHPACK = "Carry a light load."

STRINGS.NAMES.PARROT = "Parrot"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PARROT = "I try not to eat anything with a name."

STRINGS.NAMES.SEAGULLWATER = "Seagull"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEAGULLWATER = "Shoo! Find some other land!"

GLOBAL.STRINGS.NAMES.ICEMAKER = "Ice Maker 3000"
GLOBAL.STRINGS.RECIPE_DESC.ICEMAKER = "Ice, ice, baby!"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.ICEMAKER = "Machine is doing very good job!"

GLOBAL.STRINGS.RECIPE_DESC.PRIMEAPEBARREL = "More monkeys!"

GLOBAL.STRINGS.RECIPE_DESC.BALLPHINHOUSE = "Ballphin House"

STRINGS.NAMES.DORSALFIN = "Dorsalfin"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DORSALFIN = "Dorsalfin"

STRINGS.NAMES.CORALLARVE = "Coral Larve"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CORALLARVE = "Coral Larve"

GLOBAL.STRINGS.NAMES.NUBBIN = "Nubbin"
GLOBAL.STRINGS.RECIPE_DESC.NUBBIN = "Nubbin!"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.NUBBIN = "Nubbin!"

STRINGS.NAMES.SEAWEED_STALK = "Seaweed Stalk"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEAWEED_STALK = "Seaweed Stalk"

STRINGS.NAMES.COCONADE = "Coconade"
GLOBAL.STRINGS.RECIPE_DESC.COCONADE = "Coconade!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.COCONADE = "Coconade"

STRINGS.NAMES.PIRATEPACK = "Pirate Pack"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PIRATEPACK = "Pirate Pack"

GLOBAL.STRINGS.NAMES.TAR_EXTRACTOR = "Tar Extractor"
GLOBAL.STRINGS.RECIPE_DESC.TAR_EXTRACTOR = "Tar Extractor!"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TAR_EXTRACTOR = "Tar Extractor!"

STRINGS.NAMES.TAR_POOL = "Tar Pool"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TAR_POOL = "Tar Pool"

STRINGS.NAMES.TAR = "Tar"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TA = "Tar"

STRINGS.NAMES.TAR_TRAP = "Tar Trap"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TAR_TRAP = "Tar Trap"

GLOBAL.STRINGS.NAMES.FISH_FARM = "Fish Farm"
GLOBAL.STRINGS.RECIPE_DESC.FISH_FARM = "Fish Farm!"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH_FARM = "Fish Farm!"

STRINGS.NAMES.ROE = "Roe"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ROE = "Roe"

STRINGS.NAMES.ROE_COOKED = "Roe Cooked"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ROE_COOKED = "Roe Cooked"

STRINGS.NAMES.FISH3 = "Purple Grouper"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH3 = "Purple Grouper"

STRINGS.NAMES.FISH3_COOKED = "Purple Grouper Cooked"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH3_COOKED = "Purple Grouper Cooked"

STRINGS.NAMES.FISH4 = "Pierrot Fish"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH4 = "Pierrot Fish"

STRINGS.NAMES.FISH4_COOKED = "Pierrot Fish Cooked"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH4_COOKED = "Pierrot Fish Cooked"

STRINGS.NAMES.FISH5 = "Neon Quattro"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH5 = "Neon Quattro"

STRINGS.NAMES.FISH5_COOKED = "Neon Quattro Cooked"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH5_COOKED = "Neon Cooked"

STRINGS.NAMES.FISH5_COOKED = "Neon Quattro Cooked"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH5_COOKED = "Delicious, as you would expect"

GLOBAL.STRINGS.NAMES.BLOWDART_POISON = "Blowdart Poison"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BLOWDART_POISON = "Blowdart Poison."
GLOBAL.STRINGS.RECIPE_DESC.BLOWDART_POISON = "Blowdart Poison"

GLOBAL.STRINGS.NAMES.SEATRAP = "Sea Trap"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEATRAP = "Sea Trap."
GLOBAL.STRINGS.RECIPE_DESC.SEATRAP = "Sea Trap"

GLOBAL.STRINGS.NAMES.SEA_CHIMINEA = "Sea Chiminea"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEA_CHIMINEA = "Sea Chiminea."
GLOBAL.STRINGS.RECIPE_DESC.SEA_CHIMINEA = "Sea Chiminea"

GLOBAL.STRINGS.NAMES.TROPICALBOUILLABAISSE = "Tropical Bouillabaisse"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TROPICALBOUILLABAISSE = "Tropical Bouillabaisse."

GLOBAL.STRINGS.NAMES.CAVIAR = "Caviar"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CAVIAR = "Caviar."

GLOBAL.STRINGS.NAMES.OX_FLUTE = "Ox Flute"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OX_FLUTE = "Ox Flute."
GLOBAL.STRINGS.RECIPE_DESC.OX_FLUTE = "Ox Flute"

GLOBAL.STRINGS.NAMES.OXBABY = "Ox baby"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OXBABY = "Ox baby."

GLOBAL.STRINGS.NAMES.RESEARCHLAB5 = "researchlab5"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.RESEARCHLAB5 = "researchlab5."
GLOBAL.STRINGS.RECIPE_DESC.RESEARCHLAB5 = "researchlab5"

GLOBAL.STRINGS.NAMES.SEA_YARD = "Sea Yard"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEA_YARD = "Sea Yard."
GLOBAL.STRINGS.RECIPE_DESC.SEA_YARD = "Sea Yard"

GLOBAL.STRINGS.NAMES.TARLAMP = "Tar Lamp."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TARLAMP = "Tar Lamp."
GLOBAL.STRINGS.RECIPE_DESC.TARLAMP = "Tar Lamp"

GLOBAL.STRINGS.NAMES.TARSUIT = "Tar Suit"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TARSUIT = "Tar Suit."
GLOBAL.STRINGS.RECIPE_DESC.TARSUIT = "Tar Suit"

GLOBAL.STRINGS.NAMES.BLUBBERSUIT = "Blubber Suit"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BLUBBERSUIT = "Blubber Suit."
GLOBAL.STRINGS.RECIPE_DESC.BLUBBERSUIT = "Blubber Suit"

GLOBAL.STRINGS.NAMES.MUSSEL_BED = "Mussel Bed"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSSEL_BED = "Mussel Bed."
GLOBAL.STRINGS.RECIPE_DESC.MUSSEL_BED = "Mussel Bed"

GLOBAL.STRINGS.NAMES.WATERCHEST1 = "Water Chest"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.WATERCHEST1 = "Water Chest."
GLOBAL.STRINGS.RECIPE_DESC.WATERCHEST1 = "Water Chest"

GLOBAL.STRINGS.RECIPE_DESC.SURFBOARDITEM = "Cowabunga dudes!"

GLOBAL.STRINGS.NAMES.HAIL_ICE = "Hail Ice"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.HAIL_ICE = "Hail Ice."
GLOBAL.STRINGS.RECIPE_DESC.ICE = "Ice"

GLOBAL.STRINGS.NAMES.TELESCOPE = "Telescope"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TELESCOPE = "Telescope."
GLOBAL.STRINGS.RECIPE_DESC.TELESCOPE = "Telescope"

GLOBAL.STRINGS.NAMES.SUPERTELESCOPE = "Supertelescope"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SUPERTELESCOPE = "Supertelescope."
GLOBAL.STRINGS.RECIPE_DESC.SUPERTELESCOPE = "Supertelescope"

GLOBAL.STRINGS.NAMES.TIGEREYE = "Tiger Eye"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TIGEREYE = "Tiger Eye."

GLOBAL.STRINGS.RECIPE_DESC.GOLDNUGGET = "Gold"

GLOBAL.STRINGS.NAMES.ESCADADOVULCAO2 = "Volcano Exit"
GLOBAL.STRINGS.NAMES.LAVAPONDBIG1 = "Big lava pool"

GLOBAL.STRINGS.NAMES.MERM1 = "Merm"
GLOBAL.STRINGS.NAMES.MERM2 = "Merm"
--------------store---------
--------------actions-------
GLOBAL.STRINGS.ACTIONS.HACK="Taglia"
GLOBAL.STRINGS.ACTIONS.BOATMOUNT="Sali a bordo"
GLOBAL.STRINGS.ACTIONS.BOATREPAIR = "Ripara"
GLOBAL.STRINGS.ACTIONS.BOATDISMOUNT = "Boat Dismount"
GLOBAL.STRINGS.ACTIONS.STICK = "Bastone"
GLOBAL.STRINGS.NAMES.NAUTICALTAB = "Nautico"
GLOBAL.STRINGS.TABS.NAUTICALTAB = "Nautico"
GLOBAL.STRINGS.ACTIONS.LANTERNOFF = "Turn Off"
GLOBAL.STRINGS.ACTIONS.LANTERNON = "Turn On"
GLOBAL.STRINGS.ACTIONS.BOATCANNON = "Shot"
GLOBAL.STRINGS.ACTIONS.RETRIEVE = "Retrieve"
--------------rawling speak---------------
GLOBAL.STRINGS.NAMES.RAWLING = "Rowley"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAWLING = "È mio amico."
GLOBAL.STRINGS.RAWLINGon_hit_water = "Swish!"
GLOBAL.STRINGS.RAWLINGon_dropped = "Dribblami!"
GLOBAL.STRINGS.RAWLINGon_extinguish = "Salvo!"
GLOBAL.STRINGS.RAWLINGin_container = "Questo non è un canestro..."
GLOBAL.STRINGS.RAWLINGon_ground = "Potresti usarmi un pò."
GLOBAL.STRINGS.RAWLINGin_inventory = "Tagliamo il fondo del cestino."
GLOBAL.STRINGS.RAWLINGother_owner = "Ouch!"
GLOBAL.STRINGS.RAWLINGon_ignite = {
"VADO A FUOCO!",
"OW OW OW OW OW!",
}
GLOBAL.STRINGS.RAWLINGon_pickedup = {
"Sei tu James?",
"Sei il mio miglior giocatore!",
}
GLOBAL.STRINGS.RAWLINGon_thrown = {
"Verso il canestro!",
"Lancia!",
"Sbagli il 100% dei tuoi tiri!",
"I believe I can fly!",
}

GLOBAL.STRINGS.RAWLINGon_bounced = 
{
"Ouch!",
"Tutto tranne che canestri!",
"Splish!",
"Mancato!",
}
GLOBAL.STRINGS.RAWLINGequipped = {
"Poi portarmi a fare una passeggiata.",
"Questa è una specie di battuta canadese?",
"Sentiti 'libero' di lanciarmi.",
}
STRINGS.BORE_TALK_FOLLOWWILSON = {"YOU OK BY ME", "I LOVE FRIEND", "YOU IS GOOD", "I FOLLOW!"}
STRINGS.BORE_TALK_FIND_LIGHT = {"SCARY", "NO LIKE DARK", "WHERE IS SUN?", "STAY NEAR FIRE", "FIRE IS GOOD"}
STRINGS.BORE_TALK_LOOKATWILSON = {"WHO ARE YOU?", "YOU NOT BORE.", "UGLY MONKEY MAN", "YOU HAS MEAT?"}
STRINGS.BORE_TALK_RUNAWAY_WILSON = {"TOO CLOSE!", "STAY 'WAY!", "YOU BACK OFF!", "THAT MY SPACE."}
STRINGS.BORE_TALK_FIGHT = {"I KILL NOW!", "YOU GO SMASH!", "RAAAWR!", "NOW YOU DUN IT!", "GO 'WAY!", "I MAKE YOU LEAVE!",}
STRINGS.BORE_TALK_RUN_FROM_SPIDER = {"SPIDER BAD!", "NO LIKE SPIDER!", "SCARY SPIDER!"}
STRINGS.BORE_TALK_HELP_CHOP_WOOD = {"KILL TREE!", "SMASH MEAN TREE!", "I PUNCH TREE!"}
STRINGS.BORE_TALK_HELP_HACK = {"I HELP GET BUSH!", "I PUNCH BUSH!", "WE PUNCHIN' PLANTS NOW?"}
STRINGS.BORE_TALK_ATTEMPT_TRADE = {"WHAT YOU GOT?", "BETTER BE GOOD.", "NO WASTE MY TIME."}
STRINGS.BORE_TALK_PANIC = {"NOOOOO!", "TOO DARK! TOO DARK!", "AAAAAAAAAH!!"}
STRINGS.BORE_TALK_PANICFIRE = {"HOT HOT HOT!", "OWWWWW!", "IT BURNS!"}
STRINGS.BORE_TALK_FIND_MEAT = {"ME HUNGRY!", "YUM!", "I EAT FOOD!", "TIME FOR FOOD!"}
STRINGS.BORE_TALK_EAT_MEAT = {"NOM NOM NOM", "YUM!"}
STRINGS.BORE_TALK_GO_HOME = {"HOME TIME!", "HOME! HOME!"}

STRINGS.NAMES.WALL_LIMESTONE_ITEM = "Limestone Wall"
STRINGS.NAMES.WALL_LIMESTONE = "Limestone Wall"
STRINGS.RECIPE_DESC.WALL_LIMESTONE_ITEM = "Strong wall segments."
STRINGS.RECIPE_DESC.LIMESTONE = "Stone, with a hint of lime."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WALL_LIMESTONE = "Sturdy."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WALL_LIMESTONE_ITEM = "These would do more good if I placed them."

STRINGS.NAMES.WALL_ENFORCEDLIMESTONE_ITEM = "Sea Wall"
STRINGS.NAMES.WALL_ENFORCEDLIMESTONE = "Sea Wall"
STRINGS.RECIPE_DESC.WALL_ENFORCEDLIMESTONE_ITEM = "Strong wall segments to build at sea."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WALL_ENFORCEDLIMESTONE = "I shelled out for the good stuff."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WALL_ENFORCEDLIMESTONE_ITEM = "I have to build it in the water."
------------------mapwrapper---------------
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_MAPWRAP_LOSECONTROL = "It would seem my future is foggy."

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_MAPWRAP_RETURN = "I think I felt something brush against my leg..."

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_MAPWRAP_WARN = "Here be monsters."
STRINGS.NAMES.BELL1 = "Old Bell"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BELL1 = "Old Bell."