local TUNING = GLOBAL.TUNING

local TUNING = GLOBAL.TUNING

TUNING.TFWP_SPEAR_GUNG = 
{
    USES = 200,
    DAMAGE = 40,
    SPELL_DAMAGE = 75,
    RECHARGE = 15,
    DECAY_PER_CAST = 200 * 0.05,
}

TUNING.TFWP_LAVA_HAMMER = 
{
    USES = 250,
    DAMAGE = 35,
    SPELL_DAMAGE = 50,
    RECHARGE = 15,
    DECAY_PER_CAST = 250 * 0.05,
}

TUNING.TFWP_SPEAR_LANCE = 
{
    USES = 150,
    DAMAGE = 45,
    SPELL_DAMAGE = 150,
    RECHARGE = 15,
    DECAY_PER_CAST = 100 * 0.05,
}

TUNING.TFWP_SUMMON_BOOK = 
{
    USES = 60,
    DAMAGE = 20,
    RECHARGE = 60,
    DECAY_PER_CAST = 60 * 0.1,
}

TUNING.TFWP_CONTROL_BOOK = 
{
    USES = 60,
    DAMAGE = 20,
    RECHARGE = 45,
    DECAY_PER_CAST = 60 * 0.1,
}

TUNING.TFWP_HEALING_STAFF = 
{
    USES = 80,
    DAMAGE = 20,
    RECHARGE = 30,
    HEALTH_PER_SECOND = 3,
    SANITY_PER_SECOND = 1,
    DECAY_PER_CAST = 80 * 0.1,
}

TUNING.TFWP_INFERNAL_STAFF = 
{
    USES = 80,
    DAMAGE = 25,
    RECHARGE = 20,
    SPELL_DAMAGE = 300,
    DECAY_PER_CAST = 80 * 0.05,
}

TUNING.TFWP_DRAGON_DART = 
{
    USES = 30,
    DAMAGE = 20,
    RECHARGE = 5,
    SPELL_DAMAGE = 60,
    DECAY_PER_CAST = 1,
}

TUNING.TFWP_LAVA_DART = 
{
    USES = 40,
    DAMAGE = 15,
    RECHARGE = 15,
    SPELL_DAMAGE = 15,
    DECAY_PER_CAST = 2,
}

TUNING.TFWP_HEAVY_SWORD = 
{
    USES = 300,
    DAMAGE = 37,
    SPELL_DAMAGE = 90,
}

--Elemetal
TUNING.TFWP_ELEMENTAL = 
{
    HEALTH = 50,
    DAMAGE = 5,
    RANGE = 15,
    ATTACK_PERIOD = 0.7,
}

--turtle----------------------
------------------------------
TUNING.SPIKY_TURTLE_TFC = {}
TUNING.SPIKY_TURTLE_TFC.HEALTH = 1200
TUNING.SPIKY_TURTLE_TFC.KEEPDIST = 30
TUNING.SPIKY_TURTLE_TFC.WALKSPEED = 3
TUNING.SPIKY_TURTLE_TFC.TARGET_DIST = 25
--melee
TUNING.SPIKY_TURTLE_TFC.DAMAGE = 45
TUNING.SPIKY_TURTLE_TFC.RANGE = 4
TUNING.SPIKY_TURTLE_TFC.ATTACK_PERIOD = 1.7
--slides
TUNING.SPIKY_TURTLE_TFC.SLIDEDAMAGE = 45
TUNING.SPIKY_TURTLE_TFC.SLIDE_RADIUS = 3
TUNING.SPIKY_TURTLE_TFC.SLIDES_ALLOWED = 5
--hider
TUNING.SPIKY_TURTLE_TFC.SHELL_REQ_DAMAGE = 350
TUNING.SPIKY_TURTLE_TFC.INSHELL_TIME = 5
TUNING.SPIKY_TURTLE_TFC.SHIELDED_DAMAGE_REDUCTION = 0.95

--scorpion------------------------
----------------------------------
TUNING.STRANGE_SCORPION_TFC = {}
TUNING.STRANGE_SCORPION_TFC.HEALTH = 1200
TUNING.STRANGE_SCORPION_TFC.RUNSPEED = 3
TUNING.STRANGE_SCORPION_TFC.TARGET_DIST = 25
TUNING.STRANGE_SCORPION_TFC.KEEPDIST = 30
--melee
TUNING.STRANGE_SCORPION_TFC.DAMAGE = 45
TUNING.STRANGE_SCORPION_TFC.RANGE = 4
TUNING.STRANGE_SCORPION_TFC.ATTACK_PERIOD = 1.5
--range
TUNING.STRANGE_SCORPION_TFC.RANGE_ATTACK_PERIOD = 10
TUNING.STRANGE_SCORPION_TFC.SPITRANGE = 20
TUNING.STRANGE_SCORPION_TFC.SPITDAMAGE = 5
--splash
TUNING.STRANGE_SCORPION_TFC.STICKY_SPIT = true
TUNING.STRANGE_SCORPION_TFC.SPLASHRADIUS = 3
TUNING.STRANGE_SCORPION_TFC.SPLASHDAMAGE = 40
--spread
TUNING.STRANGE_SCORPION_TFC.SPREAD_TARGETS = 3

--piggy---------------------------
----------------------------------
TUNING.HATTY_PIGGY_TFC = {}
TUNING.HATTY_PIGGY_TFC.HEALTH = 400
TUNING.HATTY_PIGGY_TFC.RUNSPEED = 10
TUNING.HATTY_PIGGY_TFC.TARGET_DIST = 25
TUNING.HATTY_PIGGY_TFC.KEEPDIST = 30
TUNING.HATTY_PIGGY_TFC.SHARE_DIST = 25
--melee
TUNING.HATTY_PIGGY_TFC.DAMAGE = 45
TUNING.HATTY_PIGGY_TFC.RANGE = 2
TUNING.HATTY_PIGGY_TFC.ATTACK_PERIOD = 1.5
--charge
TUNING.HATTY_PIGGY_TFC.CHARGE_RECHARGE = 5
TUNING.HATTY_PIGGY_TFC.DAMAGE = 45

--elemental-------------------------
------------------------------------
TUNING.FLAME_ELEMENTAL_TFC = {}
TUNING.FLAME_ELEMENTAL_TFC.HEALTH = 400
--attack
TUNING.FLAME_ELEMENTAL_TFC.DAMAGE = 7
TUNING.FLAME_ELEMENTAL_TFC.RANGE = 15
TUNING.FLAME_ELEMENTAL_TFC.ATTACK_PERIOD = 0.7
--blast
TUNING.FLAME_ELEMENTAL_TFC.BLAST_DAMAGE = 250
TUNING.FLAME_ELEMENTAL_TFC.BLAST_RADIUS = 5

--lizardmen-------------------------
------------------------------------
TUNING.LIZARDMAN_TFC = {}
TUNING.LIZARDMAN_TFC.TARGET_DIST = 12
TUNING.LIZARDMAN_TFC.KEEP_TARGET_DIST = 20
TUNING.LIZARDMAN_TFC.DAMAGE = 25
TUNING.LIZARDMAN_TFC.ATTACK_PERIOD = 2.5
TUNING.LIZARDMAN_TFC.SPEED = 6
TUNING.LIZARDMAN_TFC.HEALTH = 680
TUNING.LIZARDMAN_TFC.SHARE_TARGET_DIST = 20
TUNING.LIZARDMAN_TFC.ATTACK_RANGE = 4
TUNING.LIZARDMAN_TFC.DIST_ATTACK_RANGE = 16
TUNING.LIZARDMAN_TFC.TORNS_DAMAGE = 5
TUNING.LIZARDMAN_TFC.BANNER_RECHARGE = 15

--boarilla--------------------------
------------------------------------
TUNING.SPIKY_MONKEY_TFC = {}
TUNING.SPIKY_MONKEY_TFC.SPEED = 7.5
TUNING.SPIKY_MONKEY_TFC.HEALTH = 1200
TUNING.SPIKY_MONKEY_TFC.TARGET_DIST = 12
TUNING.SPIKY_MONKEY_TFC.KEEP_TARGET_DIST = 20
--combat
TUNING.SPIKY_MONKEY_TFC.DAMAGE = 65
TUNING.SPIKY_MONKEY_TFC.ATTACK_PERIOD = 2.5
TUNING.SPIKY_MONKEY_TFC.ATTACK_RANGE = 4
--shield
TUNING.SPIKY_MONKEY_TFC.SHELL_REQ_DAMAGE = 350
TUNING.SPIKY_MONKEY_TFC.INSHELL_TIME = 5
TUNING.SPIKY_MONKEY_TFC.SHIELDED_DAMAGE_REDUCTION = 0.95
--slam
TUNING.SPIKY_MONKEY_TFC.SLAM_RECHARGE = 5
TUNING.SPIKY_MONKEY_TFC.SLAM_RADIUS = 5
TUNING.SPIKY_MONKEY_TFC.SLAM_DAMAGE = 100